### ISSUE TITLE
Zyn - Blank Instrument Bank

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1001]
(win 32xp)
Read this
http://linux-multimedia-studio-lmms.996328.n3.nabble.com/new-zasfx-how-is-the-quality-any-aspects-discuss-td9642.html
Toby has upgraded zasfz (zyn) so this strange zyn-bug may not be present, if it is, the wiki need something temporary
To reproduce you need to go to the main zyn ui
Then click to add a bank instrument
The bank overview opens

![image](https://cloud.githubusercontent.com/assets/6345473/6596449/00658050-c7cb-11e4-8896-39a7584b8437.png)

But this is empty!
You can see (red annotate) that is should show the plucked instruments. None is shown
However, if the blue annotated check-box is toggled, then the bank populate.
(PADsynth status is this completely irrelevant btw)
If the bank then is switched to a different bank, it do not populate before a new toggle of the blue-annotate.
A zyn-team bug, no doubt, but it will confuse lmms users, so
Could someone test master, and see if this behaviour also exists, after the newest update? 
Test all OS preferely

**Comment by falkTX** [comment]
FYI I've been toying a bit with LMMS zyn using NTK instead of FLTK and this issue is also present there.

One thing I noticed is that the initial choice of beginner vs advanced Zyn UI is not remembered, so there might be some config file conflicts.

**Comment by musikBear** [comment]
FYI in the vst version of zyn they have added a new button "Update Banks"
(This vst version btw also have fixed the crash when instruments based on AbSine (and one more i cant remember.. ) wave-shape is opend
I hoped i could use this feature, to manage *that* problem, but the VST-saved zyn-instruments, reverts to default when loaded in lmms)

**Comment by tresf** [comment]
> (This vst version btw also have fixed the crash when instruments based on AbSine (and one more i cant remember.. ) wave-shape is opend

Unlikely.  It's more likely that they use a different toolchain to build their binaries which is compatible with XP.  We aren't going to change our toolchain for this bug so please let this specific bug rest.

> the VST-saved zyn-instruments, reverts to default when loaded in lmms)

Why use the VST version of Zyn when we have it native already?  Upgrade your OS please.

> uh in case someone wonder - no connection between lmms-vst-gui and zyn-vst-dials exists, they are all unconnected, and unresponsive

Again, please use the built-in version.  Features, bugs or otherwise in the VST version do nothing to help this bug report.

**Comment by Sti2nd** [comment]
> One thing I noticed is that the initial choice of beginner vs advanced Zyn UI is not remembered

I have experienced this, one time... Can not reproduce, Zyn remembers in 1.1.0.

**Comment by Gps2010** [comment]
I just stumbled on this bug too, with my self compiled  lmms 1.1.2 on openSUSE 64 bit.

Unchecking, checking that box works a bit. Should I try to ask about this on soundforce, or am I the only one having this issue?

**Comment by Sti2nd** [comment]
You mean Zyn on Sourceforge???

**Comment by Gps2010** [comment]
Yes, the topic on Sourceforge, this one: http://sourceforge.net/p/zynaddsubfx/bugs/50/

I am having exactly what is described in the topic here, on the github, but lucky for me, clicking on the window does work, so I have a work around.

I found the topic here, when I googled for my zynaddsubfx problem, expecting to find a simple fix, but if I understand things right, there is not much I can do?

**Comment by tresf** [comment]
> there is not much I can do?

Correct.  The Zyn team's responses are in the upstream bug report (Sorry, sourceforge happens to be down at this exact moment).  That is the best place for this to be fixed unless someone from the LMMS team can hack in a quick fix.

-Tres

**Comment by fundamental** [comment]
As was stated in the closed bug report upstream and earlier in this thread, this issue is out-of-date as far as the upstream zynaddsubfx is concerned. This issue has not been replicated on the git head and the code responsible for this issue has been changed considerably. I'm shooting for the next upstream zynaddsubfx release around the time of LAC 2015, however the release could be considerably sped up by some testers.

**Comment by musikBear** [comment]
@fundamental -I have tested the stand-alone-vst version of zasfx. This vst does not have this bug. Is the current version used internally in lmms older or newer, than the stand-alone version.
As shown here
https://www.youtube.com/watch?v=foUqtb725JE
This bug is really 'only' serious for linux users, because the hack i found (by chance..) does not work in linux (afaik), only in win version of lmms

**Comment by fundamental** [comment]
@musikBear 
Unfortunately for this discussion, comparisons to the VST aren't really usable considering that it has been forked from the mainline code for quite a while (assuming you're talking about the VST available via the kvr forums).

The internal lmms version is based off of the 2.4.4 release of the mainline to my knowledge.

**Comment by tresf** [comment]
> The internal lmms version is based off of the 2.4.4 release of the mainline to my knowledge.

Correct. 

> I'm shooting for the next upstream zynaddsubfx release around the time of LAC 2015

:+1: Thanks.

**Comment by Gps2010** [comment]
@ fundamental 
I had read everything also on sound force, but I am confused.
The bug is closed but not solved  ? ( not in latest zybaddsubFX version ? )
But should be fixed in the release around LAC 2015 ?

If I can help testing, I am available, but never used ZybaddsubFX outside LMMS before.
And I am  a bit worried, that if I install it as stand alone, it might conflict with the one in lmms? 

@ musikbear, I am on Linux, but I don't have the extra problem reported by the Ubuntu users. For me clicking the window does work.

Maybe this can help you.
I am not gonna name all distro's, that would be a waist of time for everybody, but the most commonly used Linux distro's at home  are, Ubuntu, Mint, Arch, openSUSE and Fedora. 
Those names are also the most likely, to turn op on the lmms forums.

**Comment by fundamental** [comment]
@Gps2010 
The bug is closed and it is to my knowledge solved in the ZynAddSubFX developmental version which will be v2.5.0.
As long as zyn isn't built with ntk, there is no need to install anything in order to run the program.
Everything should run fine from the build directory.

**Comment by musikBear** [comment]
@fundamental Thanks for clearing this :+1: 
@Gps2010 -interesting! so Ubuntu is the version **with** the bug, (iirc you are on *Mint*?) - A list over the 'do work versions' would perhaps be useful..

**Comment by Gps2010** [comment]
@mucisbear, nope, I am on openSUSE.

Mint is made because some people were not happy with the way Ubuntu went, so they build their own distro.

To me as a simple user, this splitting up of things happens way to often with Linux.
One group of people invents a wheel, then another group does not like that wheel, and instead of helping to improve the first wheel, they start making their own. 

I am only human myself though, because I don't like Ubuntu. ;)  

Back to zynaddsubfx, I will one of these days prob test it.

**Comment by fundamental** [comment]
@tresf as a heads up, I managed to push the 2.5.0 release up some and I'm currently writing up the release announcement.

**Comment by tresf** [comment]
> @tresf as a heads up, I managed to push the 2.5.0 release up some and I'm currently writing up the release announcement.

@fundamental :+1:

@badosu @curlymorphic @Lukas-W @diizy @tobydox  FYI. :tada:

**Comment by badosu** [comment]
Nice! Maybe this can solve a weird problem I am having with ZASFX?

My X session crashes or hangs up the entire OS when clicking on "Show GUI".

**Comment by curlymorphic** [comment]
What are our plans with this. on #lad there was talk of 2.5.1 soon, to fix dssi and copy / paste. and the API has changed, think this might take some work to get in

**Comment by tresf** [comment]
Toby has historically integrated Zyn. That's why I tagged you guys.  If for some reason Toby's not available to integrate this, we'd need help from the core team to make it happen.

**Comment by curlymorphic** [comment]
Lets see what Toby wants to do, but im up for helping

**Comment by tobydox** [comment]
Feel free to do the update. If you look at the logs (https://github.com/LMMS/zynaddsubfx) you'll see that there are not many changes against upstream anymore so an update should be fairly easy to do.

**Comment by ryukusu** [comment]
I don't know maybe someone wrote that before me.
Looks like there is some kind of overlay for zynaddsubfx if you launch it from lmms.
I've compared standalone zynaddsubfx and zynaddsubfx launched from lmms.
It affects not only banks but also some another UI elements. I've also found that you can rebrush zynaddsubfx, but it doesn't help to deal with banks.
![2015-04-21-1429605644](https://cloud.githubusercontent.com/assets/6869742/7248627/d9d4a20a-e81c-11e4-89f8-82bc84bba8f6.png)
![2015-04-21-1429605767](https://cloud.githubusercontent.com/assets/6869742/7248635/ead1b57a-e81c-11e4-85e1-748003f1fdeb.png)

Also there is some kind workaround to see instruments by one. If you right-click on the instrument you will be able to rename it and thus you will see it's name. It is not convenient.
Is there some another hack to edit QT-applications located in RAM or I have to use fluid, edit sources and compile from sources?

**Comment by tresf** [comment]
> Looks like there is some kind of overlay for zynaddsubfx if you launch it from lmms.

What you are looking at is the NTK themed version of Zyn, LMMS is bundled with the FLTK themed version of Zyn.  This is a compile-time option.

That said, I'm glad to see the stand-alone has the same bug, but unless you are on version 2.5, it won't be addressed because the code base has undergone significant changes.

> Is there some another hack to edit QT-applications located in RAM or I have to use fluid, edit sources and compile from sources?

I don't know the answer to this, but historically I've edited the fluid sources for what you are describing.  I'm not entirely sure what that has to do with QT though if you are running the stand-alone version, AFAIK, the QT build isn't officially supported yet by the Zyn team (and would use QT rather than NTK, FLTK)

**Comment by tresf** [comment]
If you're looking to help fix/debug this on LMMS, time is probably better spent working with Dave on the 2.5 upgrade and seeing if it still exists there.

**Comment by curlymorphic** [comment]
@ryukusu I have taken some screen shots of the new zasf 2.5 imported into lmms. Are the issus mentioned addressed?

![image](https://cloud.githubusercontent.com/assets/7412852/7257417/73cf9cc2-e84d-11e4-8894-3852619f79a6.png)

**Comment by tresf** [comment]
... ah... a picture is worth 1,000 words. Thanks @curlymorphic Dave!

**Comment by ryukusu** [comment]
@tresf 
looks like you misunderstood. left is the stand alone zynaddsubfx. it has no such bug. I just mentioned that on the standalone it has no overlay while lmms version (right side) has some kind of overlay.

@curlymorphic should I downgrade then to previous lmms version, change sources and compile from sources or wait for next release?

**Comment by tresf** [comment]
> looks like you misunderstood.

> > some kind of overlay for zynaddsubfx if you launch it from lmms.

What is misunderstood?  You have a screenshot NTK Zyn and we don't use NTK.  If someone understand your point, please translate.

P.S.  The lime-green screenshots make your screenshots quite distracting to look at. ;)

**Comment by falkTX** [comment]
@tresf I think he's using the kxstudio packages, which uses NTK.

**Comment by tresf** [comment]
@falkTX, Do you have a custom build script?

**Comment by falkTX** [comment]
Yes, it's some changes to cmake and also some quick build-script to make things work.
I didn't manage to do everything via cmake yet, otherwise I'd have sent in a patch.

Anyway, yeah the zynaddsubfx in the lmms kxstudio packages uses ntk.
It has the same bug as the regular fltk build.

**Comment by tresf** [comment]
> Anyway, yeah the zynaddsubfx in the lmms kxstudio packages uses ntk.
It has the same bug as the regular fltk build.

Thanks and apologies to @ryukusu for the misunderstanding.

**Comment by ryukusu** [comment]
Thank you for clarifications. :+1: 
I knew that I shouldn't use KXStudio, but I was lazy to get the sources.
OK I will install lmms from sources and tell you if anything goes wrong. :)

**Comment by falkTX** [comment]
There's nothing wrong with the kxstudio packages.
In fact because it uses NTK zyn will look a bit nicer than usual.

**Comment by ryukusu** [comment]
I agree, that it looks more like flstudio. It's OK for me.
But when I decide to remove it and install fluidsynth-dev to compile from sources I've encountered dependency problem(with held packages). I will figure it out but looks like i'd better avoid using custom repos if I can compile from sources and it is not something critical for system.

**Comment by falkTX** [comment]
the kxstudio's lmms package purposefully conflicts with libfluidsynth-dev so it always uses fluidsynth-static instead.
the reason to use static libs is that kxstudio only builds once, and for the oldest available distro supported (debian 6) the libfluidsynth it has is too old.
(we could build against a new libfluidsynth version but then it wouldn't work on debian 6 or ubuntu 12.04)
take a look at debian/control and rules files to understand what it is doing.

anyway, this has nothing to do with lmms.
sorry for being off-topic, but I had to clear that little info.

**Comment by haakonn** [comment]
Still reproducible on LMMS 1.1.3 (KXStudio packages) on Ubuntu 15.4. Very annoying.

**Comment by tresf** [comment]
> Still reproducible on LMMS 1.1.3 (KXStudio packages) on Ubuntu 15.4. Very annoying.

Agreed, but this isn't our bug and upstream wants us to upgrade to 2.5 prior to it being fixed.  I'm closing this out as not-our-bug.  We can re-investigate if and when we move to 2.5.  Sorry, but for now, we'll just have to continue living with this one.

**Comment by etsnyman** [comment]
Almost a year later, and this is still a problem. Workaround does nothing.

**Comment by tresf** [comment]
> Almost a year later, and this is still a problem. Workaround does nothing.

> > Sorry, but for now, we'll just have to continue living with this one.

**Comment by musikBear** [comment]
> Workaround does nothing.

That depends! -IF (!) you can use VST then you can use the VST stand alone for everything related to editing, and your new presets will after import as zasfx presets, work perfectly in lmms. You can even work with the VST in VST-host side by side with lmms. OK that is NOT a fix, but it is a work-a-round that does work!
For reference:
https://www.youtube.com/watch?v=hrrl3OiiJvM

**Comment by echuber2** [comment]
Is this fixed in 1.2.0-RC2? Looks like I'm late to the party but this is still a pretty glaring issue with the KXStudio version.

**Comment by tresf** [comment]
> Is this fixed in 1.2.0-RC2?

No, and it won't be as the version we bundle is too old for upstream to maintain, sorry.

I've spent a considerable amount of time with FLTK and these UI problems and could never figure out what was causing it.  I expect Zyn 2.5 (or perhaps a future 3.0) to happen long before this bug is fixed.  If you want to hack at it, please feel free.   The best notes are documented here: https://github.com/LMMS/lmms/issues/1001#issuecomment-271260546

**Comment by echuber2** [comment]
@tresf Did you mean to link directly to this same thread? I might take a look at the code if time allows (I wish...)

**Comment by tresf** [comment]
@echuber2 yes, but the link was wrong.  Mean to link to the code comment.  Here it is: https://github.com/LMMS/lmms/issues/1001#issuecomment-66310329
