### ISSUE TITLE
Credit For The Samples Collected On The Internet From Other Producers Royalty Free Packs

### ISSUE THREAD

**Issue by HDDigitizerMusic** [LMMS/lmms#1018]
As most of you know, Stian Jørgenrud, StakeoutPunch, Unfa and I have been working on a new sample pack to replace the current one.

We've been synthesizing, recording, collecting samples and being cautious on the amount of samples in the pack once we're done.

Everything has been going smooth, though there is one difficult thing we need to get past. Samples on the internet, because of licensing and approval. We have to be 100% sure the samples has the licencing that gives our users complete freedom without having to mention any credit on their projects.

Though credit is something that the producers will want when they let us use their royalty free samples. (Most 100% royalty free samples don't let you put them in sample packs as is, unless you get their approval.) We definitely can't have people credit each artist, but we can put the credit here:

![untitled](https://cloud.githubusercontent.com/assets/6778944/3667728/2ced25ae-120b-11e4-95bc-3491a31000b4.png)

The reason I find this pretty important is because I doubt many producers will want their samples on here without some kind of credit in LMMS.
 
But anyway, things are going good and I think LMMS's new sample pack is going to be great.

**Comment by tresf** [comment]
@HDDigitizerMusic come back and finish this pack. :(  Closing.

**Comment by musikBear** [comment]
Has received several IM regarding a sample named 'raving_crowd01.ogg'
That sample should be from a sample-pack, that is not C0
The OP writes:

*I found a sample in LMMS's Native collection that is only licensed for personal use, (raving_crowd01.ogg, 65 Kb). It did not have a transferrable license either, so this may cause problems for distribution. Please consider.*

He has send me 3 IM on this now, with several sceneries.
Imo LMMS could just dump that particular file, and thats it
So remove it from the package?

**Comment by tresf** [comment]
Tell him to file a bug and point him directly to this post.  (Not the thread, but this `tresf commented 1 days ago` URL.

We need proof that the sample is part of a collection and we need to contact the author of the collection.

Why?  Well, CC0 means you, MusikBear Incorporated can freely and legally package up `raving_crowd01.ogg` and sell it under your own license.  CC0 allows samples to be re-released under restricted licenses, open licenses, whatever.  We don't pull samples because they're not being released CC0 elsewhere, but rather pull them if we never had permission to release them in the first place. :+1:

**Comment by tresf** [comment]
A good video about this problem is explained here: https://www.youtube.com/watch?v=5SaFTm2bcac

Pay close attention to the part about ownership.

**Comment by SirBothersome** [comment]
I'm the insufferable butthead who has been pestering musikbear. Unfortunately, the site where I found the content appears to be compromised. I got assaulted by soft-porn content last time I was there.
I'll be back on this

**Comment by SirBothersome** [comment]
> I do agree with you. Honestly, I've really never used LMMS's samples because I thought it would lead me into some lawsuit
Yup, same here. I think flushing the sample library of all third-party content is our best bet for new releases

**Comment by SirBothersome** [comment]
Hey Look! A relicensable, redistributable, royalty free collection of my made-from scratch samples!
WOW! How convenient,
[https://drive.google.com/open?id=0B3XfhZOnbJctcjlvelY4UWl0Tm8]

**Comment by tresf** [comment]
@SirBothersome please issue a PR against https://github.com/LMMS/samples.

**Comment by SirBothersome** [comment]
Heh, heh, sounds great. I'm new to GitHub though. I would like to say though: I think we should use ONLY, samples made/recorded by us. That way, there is no glimmer of doubt as to whether we are redistributing samples illegally, or if any attribution is required.

**Comment by SirBothersome** [comment]
I'll definitely taker over the repo, is there some administrative blessing I get, or do I just do it?

**Comment by tresf** [comment]
> I think we should use ONLY, samples made/recorded by us.

An electronic trail of authenticity back to the author is important, but by saying "us" you're potentially discriminating against otherwise compliant samples that may be of equal or greater usefulness -- that may be of equal or greater quality -- thus depriving them from the community at larger.  id est, we needn't the pride nor the paranoia associated with creation and self-ownership so as long as we do the diligence required for distribution. 

So yes, the burden of proving CC0 is on us, but that doesn't necessarily mean the burden of recording all samples is too.

>  That way, there is no glimmer of doubt as to whether we are redistributing samples illegally, or if any attribution is required.

You could make this same statement for [instrument presets](https://github.com/LMMS/lmms/tree/master/data/presets) and [code](https://github.com/LMMS/lmms/issues/2752) but we aren't going to take a nuclear bomb to that, now are we? :)

>  is there some administrative blessing I get, or do I just do it?

Sure.  We'll use the [pull request hack](http://felixge.de/2013/03/11/the-pull-request-hack.html) when the time comes.

**Comment by SirBothersome** [comment]
>You could make this same statement for instrument presets and code but we aren't going to take a nuclear bomb to that, now are we? :)

The difference here is that the only third-party presets we're using are for ZasFX as far as I understand. I'll double check, but they either have GPL or no license, and I doubt the ZasFX community would make non open-source content.
Now, as for the code, licensing is far more black and white, outright stealing is harder to do, and far more is available for Open-source use.
Any noob can download a sample pack though, and post it on SampleSwap.com or a similar website and call it "Creative Commons" or such. THAT is why I am concerned

**Comment by tresf** [comment]
> Any noob can download a sample pack though, and post it on SampleSwap.com or a similar website and call it "Creative Commons" or such. THAT is why I am concerned

Well, let's get somethings clear. 
 1. It's "we" that are concerned.  This isn't a new initiative.
 2. Code suffers the [same issue](https://github.com/LMMS/lmms/pull/2830).
 3. In regards to Zyn, non open-source content is different from CC0 content. This same problem applies to our existing presets.  https://www.linux.com/news/trouble-artwork-and-free-software-licenses

Last, no need to use two topics for the same discussion. https://github.com/LMMS/lmms/issues/2900

**Comment by SirBothersome** [comment]
> Last, no need to use two topics for the same discussion. 

Oh, well this one seemed to have gotten a bit crowded to the point of irrelevance. Context isn't so much a concern to me because I'll probably be starting from scratch on this. Hence, new guidelines, requests, administration (to me) = new issue.

**Comment by SirBothersome** [comment]
> Code suffers the same issue.

@tresf Unholy... have there been NO established coding conventions in this project? We could be knee deep in legal $#!+ here

**Comment by tresf** [comment]
> @tresf Unholy... have there been NO established coding conventions in this project? We could be knee deep in legal $#!+ here

Seriously, back off with comments like this.

**Comment by SirBothersome** [comment]
> Seriously, back off with comments like this.

Okey dokes

**Comment by SirBothersome** [comment]
>  CC0 allows samples to be re-released under restricted licenses, open licenses, whatever.

@tresf Though the "moral rights" clause of CC could complicate this. but I'm not sure if it applies to cc0.

**Comment by tresf** [comment]
CC0 is "No rights reserved", including moral rights.

https://creativecommons.org/publicdomain/zero/1.0/

https://creativecommons.org/share-your-work/public-domain/cc0/

> The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law.
> 
> You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. See Other Information below.

**Comment by SirBothersome** [comment]
> In regards to Zyn, open-source content is different from CC0 content. This same problem applies to our existing presets

I just googled the non-factory banks. They appear to have been made by LMMS' devel anyhow, so that may be a moot point.

**Comment by SirBothersome** [comment]
>If he can prove this to us or alternately point us to the entity that can prove this, we'll remove it. Otherwise, your'e both wasting people's time.

Let's talk turkey about that raving crowd sample, then. I'm not going to post the link for obvious reasons, but I'll email you the link if you need to see it for yourself. The sample that is.

**Comment by tresf** [comment]
> Let's talk turkey about that raving crowd sample

I provided a perfectly logical explanation of how `raving_crowd01.ogg` can make it into the wild in the link of a YouTube video called `Video explains the world's most important 6-sec drum loop` where the band that recorded a sample actually had less rights than the ones selling it due to improper re-licensing. So no, don't email me a link please.

**Comment by SirBothersome** [comment]
@tresf There is a substantial difference here. The Wilton's _could_ have acted all that time, but they didn't, and I've actually read elsewhere that they didn't mind that they weren't credited, AND there probably wasn't clear-cut laws on sampling as the technology was brand-new. In this instance, we have a possible host site with very clearly laid out terms and conditions that are at odds with their inclusion in the sample library. Just because we can do something doesn't mean that we should.
Just because we can get away with something doesn't mean we shouldn't exercise best practices

**Comment by tresf** [comment]
> You can't ask for proof, then decide to ignore the evidence.

If the site can't be linked publicly, I don't find it to be worthy of investigation.

If I'm wrong, reach out on behalf of us.  Get their copy and do a wave comparison against ours to prove it's identical.  Then find out who made it.  Don't stop until you know the original author and all licenses the original work was released under.  Don't take their word for it, take the author's word for it.  Once you have all of that information, come back on here and prove to us it was obtained and relicensed improperly.  If you can't find the original author, it is their word against ours.

And when you're done wasting all of this time, perhaps then you'll have time to get back to what you volunteered for: Getting new samples (rather than beating up the legitimacy of existing ones) which fixes the issue progressively (not regressively).

**Comment by SirBothersome** [comment]
> And when you're done wasting all of this time, perhaps then you'll have time to get back to what you volunteered for: Getting new samples

Making, technically. and processing. Before I do this though, I need more data. I'm still awaiting details on @StakeoutPunch's and @unfa's sample packs. AND there is yet to be consensus on the file type, variety, and quality of these samples. Which is why I opened #2900, the more contingencies I cover _before_ making this, the easier this will be to integrate. The previous sample threads are mostly irrelevant as the Digitizers third party sample fiasco does not appear to be resolved and several members appeared to have vanished.

**Comment by StakeoutPunch** [comment]
@SirBothersome I made one kick from scratch, then realized that I did not have the time to continue. Since then I have pretty much disappeared from the LMMS repository as I don't have the skill needed to contribute good code, which is the main thing that LMMS needs at the moment.

File type should be .flac as it is a lossless format, a supported file type in LMMS, and has a relatively small footprint. The new samples need to be as high production quality as possible, which is why third party samples were being discussed in the first place. To make this endeavor worth the effort the samples need to be top notch, like what can be found included with most other daws on the market.

**Comment by SirBothersome** [comment]
> The new samples need to be as high production quality as possible, which is why third party samples were being discussed in the first place.

This is really beginning to tick me off. Why is it assumed that we can't make good samples? This is a pack I made myself, in about three days, and I wasn't even trying hard
[https://soundcloud.com/mrlmmsguy/sample-pack-2-demo](url)

**Comment by SirBothersome** [comment]
> The new samples need to be as high production quality as possible, which is why third party samples were being discussed in the first place. To make this endeavor worth the effort the samples need to be top notch, like what can be found included with most other daws on the market.

This is really beginning to tick me off. Why is it assumed that we can't make good samples? This is a pack I made myself, in about three days, and I wasn't even trying too hard [https://soundcloud.com/mrlmmsguy/sample-pack-2-demo](url)

**Comment by SirBothersome** [comment]
And another demo for another pack I made, just to make it perfectly clear that I do know how to make samples. https://soundcloud.com/mrlmmsguy/sample-pack-announcement#t=0:20

**Comment by tresf** [comment]
> this is a pack I made myself, in about three days, and I wasn't even trying too hard

They aren't of the quality @StakeoutPunch is describing though.  I've now listened to all of them.

 * There are quite a few random snap sounds which would probably be better suited in an SF2 file for people who want lots of snap sounds
 * The Adlibs are mostly poor or very poor and most likely useless to the average person (unless they for some reason want your voice in their track).   I will never use these adlibs, and I'd fight hard to make sure they don't make it in.
 * The kicks sound quite muffled
 * The bongos are classified as "FX/Miscellaneous" for some reason?  It seems like these obscure "Glitch Claps" would fall better into that category.
 * The naming convention is a bit inconsistent.  Capitals where they shouldn't be, overuse of exclamation marks 

When comparing these to other drum packs they seem like they have a much more narrow application in regards to music styles. 

What I think may be worth cherry-picking is a few of the finger snaps because we don't have any as good as yours.  Full disclaimer, I've never needed or wanted to use a finger snap in a track before.

**Comment by Spekular** [comment]
@SirBothersome Personally I don't think the sample packs you've created are
as high quality as other DAWs.

**However**, disregarding this we also need to consider how we can get
better samples to our users as fast as possible. A lot of effort and time
goes into learning how to make and making samples. If we can find and
incorporate samples of the same quality in less time, that's better.

https://en.m.wikipedia.org/wiki/Not_invented_here

**Comment by SirBothersome** [comment]
> When comparing these to other drum packs they seem like they have a much more narrow application in regards to music styles. 

@tresf, @Spekular, the point is sirs, at the risk of boasting. If this is what I can do with five hours of work (the packs got picked up by FLstudioMusic.com, Noizefield, and ProducerSpot), Imagine what I can do in a month?

> The Adlibs are mostly poor or very poor and most likely useless to the average person (unless they for some reason want your voice in their track). I will never use these adlibs, and I'd fight hard to make sure they don't make it in.

I actually wasn't planning on integrating those. Again, I simply wished to demonstrate that I have experience in making samples. As for the naming conventions and organization... that was for a sample pack, not the native sample library for a DAW, If you want to split hairs, I'll gladly do that... After I've filed a pull reques.

**Comment by SirBothersome** [comment]
>  I've now listened to all of them.

And what you're not hearing is the effort I put into taking out predelay, background noise, eqing the sounds and adding/not adding appropriate amounts of reverb,

**Comment by SirBothersome** [comment]
> If we can find and incorporate samples of the same quality in less time, that's better.

@Spekular, yes, what could possibly go wrong? https://github.com/LMMS/samples/pull/5 (open in new tab for convenience's sake)

**Comment by Spekular** [comment]
@SirBothersome

The fact that some of our current samples might be iffy isn't really
relevant to my suggestion. It's easy to prevent this from happening in the
future by ensuring our samples are CC0.

You may be able to make a high quality sample pack in a month, but I'm
could most likely get someone else's samples approved in less than that
time.

**Comment by Umcaruje** [comment]
>You may be able to make a high quality sample pack in a month, but I'm
could most likely get someone else's samples approved in less than that
time.

^ This. If anyone wants to take on the task of contacting the artists, which would be really appreciated, can chime in on this thread: https://github.com/LMMS/samples/issues/15

**Comment by SirBothersome** [comment]
> You may be able to make a high quality sample pack in a month, but I'm
could most likely get someone else's samples approved in less than that
time.

@Spekular, well, if you have the time, patience, energy and chutzpah to do that _correctly_, then who am I to discourage you? You have my full moral support and endorsement for Volunteer of the Year.
If you need me, I'll be at my job at the supermarket... Making samples. :)
https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTxJ0Y6etW0gENyZIo_nHoWMDeZKMM3JAxH_MC40fCMlAXeF7o3vyZlVTkn

**Comment by SirBothersome** [comment]
I'm probably going to post the samples in a google drive link for peer review to keep the pull request from being a massacre. Does anyone want to volunteer for this? Or perhaps I should just crowdsource it in SoundCloud...

**Comment by tresf** [comment]
Wrong thread, wrong repo, and no.

**Comment by SirBothersome** [comment]
> Wrong thread, wrong repo, and no.

OOOH a rising tricolon! Nice rhetoric sir.
You may have noticed I opened this bugger here: [](https://github.com/LMMS/samples/issues/21)
And no _what_? No, you're not going to review the samples? No, you don't think they should be crowdsourced? No, no new samples period?
