### ISSUE TITLE
KILLER BUG: Inifinitely Loud Silence (ILS or rather NaN)

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1048]
**INTRODUCTION**
I'm fighting this beast for years now. With recent LMMS releases it has been worse than ever. Almost every project I start gets infected by this weird "virus" and I can't play the song or render it.

This is a very serious problem, as it makes the whole program unusable. No need to mention the frustration it causes.

I feel in need to lead an investigation to find the root of the problem and solve this once and for all. And I need your help.

**MY SETUP**
I am running KX Studio 14.04b 64-bit on a ASUS-K52J laptop with Core i5 processor and 8GB of RAM.
LMMS 1.0.3 from KX Studio repositories.

**WHAT IS IT?**
The bug makes L and/or R channel of LMMS master output mute with huge DC offset.
This "loud silence" has a very special property: it'll mute your whole computer, and no filters can remove it (AFAIK). The problem seems to attack projects that reach a certain level of development (small projects doesn't seem to be affected).

**How it looks like**
![osc](https://cloud.githubusercontent.com/assets/491704/3770781/bab757da-18ee-11e4-9fbe-e8a274369ed9.png)
The oscilloscope should show you a massive DC offset. But sometimes it just looks silent, regardless of the instruments playing and signal visible in the mixer strips.

Sometimes the ILS (Infintely Loud Silence) mutes all mixer channels, sometimes none, but master, sometimes just a few of them, as can be seen below:
![master](https://cloud.githubusercontent.com/assets/491704/3771085/d5aeae3c-18f1-11e4-9492-8bb855689666.png)
![mix](https://cloud.githubusercontent.com/assets/491704/3770990/b4996986-18f0-11e4-8deb-3f563fd0e310.png)

Here's a screenshot form Audacity, viewing a rendered project affected by ILS:
![auda1](https://cloud.githubusercontent.com/assets/491704/3771249/2e5f69ee-18f3-11e4-9e5b-016bc5edb751.png)

**How it sounds like**
Here's a sample from the rendered project seen on the screenshot above:
http://www.freesound.org/people/unfa/sounds/243833/

Here's a video I recorded to explain the problem (I sent it to the mailing list before):
http://youtu.be/YgXWC91DWVc

**FACTS**
1. The problems seems to start after the project is rendered for the first time. Before the first rendering it hardly ever occurs;
2. After rendering affected project to WAV I get an nearly empty file with huge empty space inside (checked with hexdump);
3. The problems is very random and hard to catch - sometimes projects that were not usable a while ago load and play fine, sometimes projects that loaded and played fine suddenly get affected and are unusable;
4. I believe ILS strikes less frequently on fresh systems, without ton of stuff installed (and without ton of updates installed). However I've installed a fresh system last week and now I've got the ILS mayhem again. However I let it update all the way, so maybe it won't happen if I don't upgrade the fresh system;
5. When you're running LMMS affected by ILS and other programs that have audio output too - the other programs will also have L and/or R channels mute. Looks like wherever Infinitely Loud Silence enters a signal chain - all other signals mixed there are removed and the sum of the equation is just ILS alone, a huge DC offset. I know, it's crazy;
6. In rendered projects - ILS frequently kicks in in the middle of the song (see the Audacity screenshot above), with the rest of it just ILS itself;
7. 16 or 24-bit sound files can store and restore some part of ILS, it's not actually ILS, it's more like a massive DC offset that leads to distortion of whatever is played through the same signal chain, but it's not muting other sources completely anymore;
8. The problem is removed when loading new project in LMMS - whatever is performed during that process - kills the bug (which can re-appear immediately after the loading window disappears but no earlier!);
9. One instance of LMMS can trigger this problem to another running in parrarel. I had two instanced open with different projects loaded, I started rendering with one instance, the second one showed the DC offset of one channel in the ossciloscope, and started pouring bad clicks in the left master channel. The DC offset didn't disappear after the rendering finished, but the clicks stopped. However when I switch between the two LMMS windows, a bunch of clicks sound in my left headphone. They also shot series at quasi-random - seems to be somehow related to CPU usage - when I scroll a webpage with mousewheel, the clicks appear.
10. JACK Bitmeter shows that the LMMS outputs NaN samples (Not a Number):
![nanny](https://cloud.githubusercontent.com/assets/491704/4190535/73f5f304-3786-11e4-83c2-ccfa17ac64dd.png)
The above image shows a screenshot of two Bitmeter's instances connected to Left and Right LMMS master JACK output ports.

**PROJECT FILES**
Here are some projects that are "infected" - the problem appeared in them at least a few times.
[Example projects.zip](https://github.com/LMMS/lmms/files/1911240/Example.projects.zip)

One project, two versions - version 10 is afected by the bug, while 08 is not. Maybe we can track down something that has changed in the project file? One thing is I used here suspected zita-rev LADSPA plugin (in both project versions). I didn't render the project, but it broke after a few hours of working on it.

That's all I know for now. Please let me know if you've ever had this issue, or if there's anything I can do to help hunting it down. You can contact me personally via e-mail:
unfa@unfamusic.com

-unfa

**Comment by TheSaucySoviet** [comment]
Yo I just got LMMS today, I am a complete newbie to this, and I was messing around with some drum sounds and I got this exact thing. But the worst part is that it is affecting my whole computer. Any audio that I play ends up doing this

**Comment by Wallacoloo** [comment]
What operating system are you using (and if you know, which sound driver
are you using)? Is this affecting audio output only while lmms is running,
or is audio still broken after you close lmms? If the second case, can you
confirm that lmms actually gets closed (if in Windows, open task manager
and click the *processes* tab)?

What are the exact steps it takes to reproduce the error? (I.e. include all
the instruments and effects you use - could be either a sound driver issue
or a misbehaving instrument/effect)

**Comment by Kitty-Dyson** [comment]
Try Choosing another Sound library. Edit -> Settings ->Audio settings. choose another sound library in the dropdown menu. the default should be sdl :)

**Comment by michaelgregorius** [comment]
#3408 might provide some code to hunt down the problem described in this issue.

**Comment by michaelgregorius** [comment]
@unfa, can you please provide one of the "infected" files? The ones that you have linked in the original description cannot be found anymore because your website forwards to Facebook which either does not have them or does not want to give them to me. :wink:

**Comment by PhysSong** [comment]
@unfa Could you fix the download link, as @michaelgregorius said? I'm currently working on some NaN issues so I'd like to investigate this issue.

**Comment by Sawuare** [comment]
This is most likely caused by the _crossover distortion_ effect.
**When you have the effect's parameters values like this:
_Crossover amplitude_ higher than `0` and _Smoothing_ not `0` or not `1`.
After playing a sound with the effect enabled, it generates a wave (it's the first half of a square wave, but it's continuous), the higher the _Crossover amplitude_ the louder it is (there's isn't a pattern to how _Smoothing_ affects its loudness), the sound never ends unless the wet/dry parameter is set to 0 or the parameters are set to the values above. Disabling the effect stops it temporarily, but when enabled it returns. Amplifying it is possible. Distorting it doesn't generate overtones.**

I got to these conclusions about the wave by generating a 1 Hz square wave for half a second in Audacity, this means that only the first half is generated, then inverted it so it's negative, and played it with a sample of a sound that has this effect, I got perfect destructive interference.

The tone generated by the _crossover distortion_ effect:
![image](https://user-images.githubusercontent.com/25503477/30241179-c7d3dcd2-9586-11e7-8c89-7a1532c0100a.png)

The tone generated by Audacity:
![image](https://user-images.githubusercontent.com/25503477/30241181-d5f4b14c-9586-11e7-93cb-07a379779f7e.png)

@unfa It can be filtered by a high-pass filter.
It isn't silence, it's something you can't hear.

**Comment by Sawuare** [comment]
To fix the problem, use the _DC offset remover_ effect after the _crossover distortion_ effect.

**Comment by unfa** [comment]
Here's the project files:
[Example projects.zip](https://github.com/LMMS/lmms/files/1911240/Example.projects.zip)

**Comment by tresf** [comment]
@unfa can you recall where the track would go silent?  Is that zita needed?  I don't have access to that and I'd rather not compile it.

**Comment by zonkmachine** [comment]
> Here's the project files:

There's too many external plugins in there for me to test at this moment. I've merged the fix now so it can be tested in rc6.

**Comment by tresf** [comment]
The team is in talks on Discord about reverting the INF/NAN sanitization checks.  In my investigation, removing the plugin `zita-reverb` is a workaround to this problem, however several distributions still seem to be shipping a buggy version of this plugin.

Quoting @LostRobotMusic:

> The plugin itself is broken on a fundamental level and it's solely the fault of whoever developed that plugin. 

This may be true, however the alternative would be to submit a patch to upstream or blacklist of these faulty plugins.  To do neither is being ignorant as to the impact on users.

**Comment by LostRobotMusic** [comment]
Here's the actual full quote of what I said, which was about plugins in general, not zita-reverb:

> I heavily doubt other DAWs are insane enough to sanitize anything, so if the plugin doesn't work here [in LMMS], it won't work anywhere else either.  If an external plugin generates invalid outputs, that's solely the plugin's fault and not something we should be expected to clean. [...] The plugin itself is broken on a fundamental level and it's solely the fault of whoever developed that plugin.  Our performance-ruining bandaid fix wouldn't even fix their plugin, it just makes its breakage slightly less obnoxious.  I don't think putting such heavy performance limitations onto the entirety of LMMS is a worthy tradeoff.

**Comment by tresf** [comment]
> I don't think putting such heavy performance limitations onto the entirety of LMMS is a worthy tradeoff.

This statement still needs to be quantified.

**Comment by AndiEcker** [comment]
What about integrating a new effect plug-in into LMMS, that can be placed
into the effect chain after any possibly faulty plug-in to filter out
NaN/ILS values.

This new pseudo-effect-plug-in could also display the accumulated number of
filtered-out values, and so be used to monitor, detect and debug possibly
faulty effect plug-ins.


Am Fr., 21. Juni 2024 um 01:08 Uhr schrieb Tres Finocchiaro <
***@***.***>:

**Comment by zonkmachine** [comment]
> What about integrating a new effect plug-in into LMMS, that can be placed into the effect chain after any possibly faulty plug-in to filter out NaN/ILS values.

Yes. This would be my first course of action. My first advice in alleviating large bursts of noise in the effect chain is to put an LMMS waveshaper effect in there and set it to clip the input. It can't do nothing about NaN, but it can be a good fix in some cases where you don't want to hit a beginner with the finer details of floating point values.

**Comment by musikBear** [comment]
How many _native_ effect-plugins -not counting zita-reverb, because it is not native, actually _has_ this issue?

**Comment by tresf** [comment]
> How many _native_ effect-plugins -not counting zita-reverb, because it is not native, actually _has_ this issue?

Based on some statements on Discord, I do not believe this to be common for most bundled LMMS plugins, except those still under development/integration.  Unfortunately this is not a measurable metric unless we run automated tests against each plugin.

**Comment by sakertooth** [comment]
> Based on some statements on Discord, I do not believe this to be common for most bundled LMMS plugins, except those still under development/integration. Unfortunately this is not a measurable metric unless we run automated tests against each plugin.

Our native EQ plugin was outputting NaNs very recently. Refer to #7131. The sanitation caused the problem (albeit a less serious problem). We had some uninitialized variables in our filters used by the EQ and initializing them fixed it.

The main issue I have with the mixer sanitation is that we are essentially trading real bad problems (like muting the whole computer) with simply bad problems (like the EQ muting output). In what way is the sanitation viewed as a solution? It's as if we are merely treating the problem to lessen its effects, rather than simply solving the problem.

If something on our side is producing NaNs, we debug and figure out why its doing so. It's almost always because of either undefined behavior or mathematical violations. If it's not on our side, like an external plugin, what would other DAWs do? Would they even do anything at all for these bad plugins that'll probably cause issues for any other host its used in?

Also, I don't think there's anywhere that says the expected behavior when a NaN is encountered is to just mute the buffer.

**Comment by musikBear** [comment]
> what would other DAWs do? Would they even do anything at all for these bad plugins that'll probably cause issues for any other host its used in?

Exactly.
Can this bug be reproduced in oscillations other than very low Hz?
Perhaps some limit of how low Hz processed could be a solution?
This
![image](https://github.com/LMMS/lmms/assets/6662066/3aa6e8f1-08e1-4cac-b1e3-45d2b71a1c07)

is 'only' an almost flat oscillation, with a very long cycle, right?

**Comment by tresf** [comment]
>  In what way is the sanitation viewed as a solution

You just said it... 

>  trading real bad problems with simply bad problems

The tracks mentioned in this bug report play just fine with sanitization.  They don't play without it.  If this is a super bad anti-pattern to sanitize NaNs and INFs, why not just add a toggle on the mixer?  We can even default it to OFF and if it really pisses people off, we can add a define that allows it to be removed from the UI entirely for those that really dislike it.

What I find particularly off-putting and minimizing to the problem is that with all of the advod, there's been almost no effort to track down the bug for `zita-reverb` to fix this at the source.  This suggests that "the plugin is broken [and should be fixed]" is just a "not my job/not my problem" and the users suffer.

> Would they even do anything at all for these bad plugins that'll probably cause issues for any other host its used in?

I tested a bad `.wav` file that @PhysSong made and attached higher in the bug report and Audacity does not play it properly.  I haven't tested other DAWs, but if we're to add a regression to the codebase, the onus of proof should be on those advocating for the regression, not those wanting to keep it.

> In what way is the sanitation viewed as a solution?

For the projects in this bug report, sanitization makes them playable.  I don't know the track well enough to know if the playback is ideal or desired, but they sounded just fine to my ear.  Without the patch, they play for less than one second and then go mute.  For the average user, software that makes sounds should make sounds, first and foremost.  If the software fails to do that, it's broken.  I'd rather not argue the definition of "solution" is in this context (we've clearly added a workaround, possible even a "hack") but it's usefulness to the user is indisputable.  If we can provide a better fix to this problem, that should be the proposal.  Defending broken -- as in can't play sounds -- software is never advantageous to a user, so any proposals that are essential "Remove it, ignore it, move on", are reckless disregard for the state of the software.

**Comment by sakertooth** [comment]
> You just said it...

I meant "solution" as in a proper solution. I should've clarified, apologies.

> For the projects in this bug report, sanitization makes them playable. I don't know the track well enough to know if the playback is ideal or desired, but they sounded just fine to my ear. Without the patch, they play for less than one second and then go mute.

I was able to play all three of the example projects sent here just fine in #7323 with `zita-reverb` active. Could you make a video of the project not being playable in that PR (or set `nanhandler=0` in your `.lmmsrc.xml`)?

I also exported the project. Heres unfa - Dancefloor:

![image](https://github.com/LMMS/lmms/assets/20197645/a900b20c-e63f-46bb-acec-b30edcdaf91b)

As you can see, the audio does not drop out like in the original bug report. I played this project after export and it played fine in its entirety as well. I can try and do the same for the others if you want. But it makes you wonder if this was really an issue with `zita-reverb`, or did we just suspect that it was the problem?

> What I find particularly off-putting and minimizing to the problem is that with all of the advocacy for the removal of sanitization, there's been absolutely no effort to track down the bug for zita-reverb to fix this at the source. This suggests that "the plugin is broken [and should be fixed]" is just a "not my job/not my problem" and the users suffer.

AFAICT, there is no bug here, but it might be system dependent. I might need to see what is happening from someone else's perspective.

> Defending broken -- as in can't play sounds -- software is never advantageous to a user, so any proposals that are essentially proposing "Remove it, ignore it, move on", are reckless disregard for the state of the software.

I agree, but I was not intending my complaint to be understood as a "move on" situation, but actually digging deep and fixing the problem at its core, not implementing a hack. I know sometimes workarounds are the only way, but we should put as much effort as possible in having a proper fix before we consider workarounds. Even when a workaround is required, we should make sure we come back and see if theres a real fix for it, simply because things change.

Since you claim that `zita-reverb` is the problem, we should have looked into contacting the developers of that plugin and figuring things out, not "implementing a workaround, move on". However, from my testing, I don't think there's an issue now anyways.

**Comment by sakertooth** [comment]
And since it was mentioned that after export this problem would appear, it would be nice to know what settings unfa used for his export at the time, if he remembers.

**Comment by zonkmachine** [comment]
> Since you claim that `zita-reverb` is the problem, we should have looked into contacting the developers of that plugin and figuring things out, not "implementing a workaround, move on". However, from my testing, I don't think there's an issue now anyways.

NB. zita revevb was definitely the problem in this issue but there was a bunch of different places where we generated bad data in lmms and the 3rd party plugins. Taken from memory the most issues I saw when testing was in calf and swh ladspa plugins.

So.
#1048 (this issue) is related to the zita reverb.
#3706 that closed this issue is not. It was a solution for the situation with bad data ahead of lmms-1.2. I don't think the situation has improved in any larger extent since that time but surely there has been fixes. The lmms team has sent bug fixes up-stream but most of the fixes we did for swh was against the ladspa branch and unfortunately the lv2 branch, even if they use the same files (duplicated), as I understand it, need to be fixed separately. Now that we have lv2 those bugs will resurface. I'll look into reapplying the fixes I did against swh-lv2.

> The main issue I have with the mixer sanitation is that we are essentially trading real bad problems (like muting the whole computer) with simply bad problems (like the EQ muting output). In what way is the sanitation viewed as a solution? It's as if we are merely treating the problem to lessen its effects, rather than simply solving the problem.

We obviously fix problems with bad data, even though the sanitizer catches it, and we send patches up-stream. It was a really big issue back when we released 1.2 even though we caught a lot of the related bugs. If you saw any of the related issues you definitely would see the difference after #3706. If you ever see the related issues rather depends on what plugins you use and how you use them, and also how you use lmms in general.

**Comment by sakertooth** [comment]
> NB. zita revevb was definitely the problem in this issue but there was a bunch of different places where we generated bad data in lmms and the 3rd party plugins. Taken from memory the most issues I saw when testing was in calf and swh ladspa plugins.

> So.
https://github.com/LMMS/lmms/issues/1048 (this issue) is related to the zita reverb.
https://github.com/LMMS/lmms/pull/3706 that closed this issue is not. It was a solution for the situation with bad data ahead of lmms-1.2. I don't think the situation has improved in any larger extent since that time but surely there has been fixes. The lmms team has sent bug fixes up-stream but most of the fixes we did for swh was against the ladspa branch and unfortunately the lv2 branch, even if they use the same files (duplicated), as I understand it, need to be fixed separately. Now that we have lv2 those bugs will resurface. I'll look into reapplying the fixes I did against swh-lv2.

> We obviously fix problems with bad data, even though the sanitizer catches it, and we send patches up-stream. It was a really big issue back when we released 1.2 even though we caught a lot of the related bugs. If you saw any of the related issues you definitely would see the difference after https://github.com/LMMS/lmms/pull/3706. If you ever see the related issues rather depends on what plugins you use and how you use them, and also how you use lmms in general.

Okay. I'll take into consideration that I rarely use most calf/swh/ladspa plugins and I wasn't here when this issue appeared, and also the fact that all of us really can't predict what plugin will be responsible for a NaN and when, but we definitely need a better way of pinpointing what plugin is consuming/generating the NaNs when it happens so it can make it easier for us to decide if we fix something in our native plugins or submit a patch upstream.

I think the route we need to go here is to:

1. Optimize and improve the design of the NaN checking functionality. We should have some visual indicator and a descriptive one of what plugin/effect chain is being muted and also make the thing faster. This is so that we know exactly what is happening from the get-go (i.e., instead of "The EQ is muting output", which is not that specific, we can say "EQ is generating NaNs for some reason", saving us time). Simply outputting to the console I feel is not always that apparent unless you are constantly checking it, and the majority of users wont start lmms from the console anyways.
2. Expose the `nanhandler` setting.
3. This should really be a troubleshooting feature and not always turned on IMO, since this is meant to cover the rare situations where NaNs do appear and we want to find out where exactly to make finding the problem and fixing it easier for developers. Users should feel free to enable it if the added safety outweighs any performance cost.

**Comment by tresf** [comment]
> Could you make a video of the project not being playable in that PR (or set nanhandler=0 in your .lmmsrc.xml)?
>
> I also exported the project. Heres unfa - Dancefloor

Could I?  Yes.  Will I?  No.  I'm not the one advocating for its removal.  BTW, I used Ubuntu 22.04 to reproduce, so if the bug has been patched up steam, that may explain the differences, but the onus is on those requesting it's removal to prove why, not the other way around.

**Comment by sakertooth** [comment]
> Could I? Yes. Will I? No. I'm not the one advocating for its removal. BTW, I used Ubuntu 22.04 to reproduce, so if the bug has been patched up steam, that may explain the differences, but the onus is on those requesting it's removal to prove why, not the other way around.

I've thought about this more deeply, and I'm kind of split/uncertain. In the case of other DAWs like FL, [it crashes when it encounters a NaN because any operation involving a NaN in Delphi crashes](https://stackoverflow.com/questions/43840657/delphi-64bit-nan-and-invalid-floating-point). As an example, [Soundgoodizer had audio input as a NaN, it crashed the program](https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/WhatsNew.htm).

In C++ however, the behavior is not exactly the same. It allows for these things (i.e., ILS) to happen unless you tell it in some way not to (setting FPE flags, `std::isinf`/`std::isnan` checks and muting the buffer, etc).

Because we work in C++, it doesn't crash by default unless you set FPE flags, so we are kind of in trouble if we don't handle the NaN in some way by default because the behavior of the audio hardware when it encounters one is basically undefined (it could be ILS, as it was here, but nothing else is telling me otherwise as of right now). Even worse is that AFAIK, when it crashes with the FPE flags, it doesn't exactly take you to where the violation happened.

So, if a NaN appears in a normal user build, it will propagate and then will reach all the way back to be played by the audio hardware, and I couldn't find any details as to what would happen in terms of the audio output specifically. For these reasons, I do think there is good reason to believe we are responsible for handling Infs and NaNs in *some* way when it comes to it appearing in our signal chain. In Delphi, it handles it by crashing, so we *could* do the same, but muting the buffer is also very viable really and is probably preferred since users have the choice of changing the plugins. But in either case, this does require us to at least check for Infs and NaNs.

The thought about removing the sanitation initially came to me when I profiled the code and found out that it was taking a bit of CPU time, so I wanted it gone for performance. I also wanted it gone in my effort to clean up the code and remove some things that aren't totally necessary. However, with the `nanhandler` option, it addresses my performance concern (and it can be optimized too), and the implementation can be cleaned up whenever.

Keeping it does not seem like a bad decision at all, assuming we implement the feature properly. It doesn't seem like we have much of a choice here, but to at least check for them when they pop up since we don't immediately crash like in Delphi by default. And in either case after we sanitize or check for Infs and NaNs, we obviously still always have the choice to work on a real fix.

**Comment by tresf** [comment]
@sakertooththnk you kindly for researching FL Studio on this issue.

Do you believe we could offer some type of visual feedback (e.g. fader code) when the issue occurs so that the audio engine can have its default , intended performance, but the user has some form of visual indication that there's an issue?  For example, if the federal could change to a solid color when the bad values arrive, we may also be able to add a tooltip when this occurs and ask the user to use sanitization.  This way we can lean into "performance first" while still offering some type of band-aid for those that need it.

**Comment by sakertooth** [comment]
> Do you believe we could offer some type of visual feedback (e.g. fader code) when the issue occurs so that the audio engine can have its default, intended performance, but the user has some form of visual indication that there's an issue? For example, if the fader could change to a solid color when the bad values arrive, we may also be able to add a tooltip when this occurs and ask the user to use sanitization. This way we can lean into "performance first" while still offering some type of band-aid for those that need it.

My idea was to simply color the mute checkbox for the mixer channel red, and maybe add a tooltip explaining that this means that the mixer channel was muted because it had invalid output. I'm in the processing of doing that now for #7323. And this will only happen when the option is checked in the setting to do so to save us performance for those who want it (even though I am optimizing this feature anyways).

**Comment by zonkmachine** [comment]
> My idea was to simply color the mute checkbox for the mixer channel red

Yes.

When a plugin is missing there is a shortage of information in general. For instance, the actual name isn't shown on the missing plugin. It's flashing by on the error report but it's not shown in the FX chain. If we had some way to see this information, that same interface could be used to provide a status report in the case of bad behaviour.
![missingplugin](https://github.com/LMMS/lmms/assets/6368949/ecdaf7c4-a33e-4bc6-9ed3-8458dcd2a66e)

**Comment by sakertooth** [comment]
The revamp is complete in #7323 for anyone who wants to take a look.

**Comment by tresf** [comment]
> The revamp is complete in #7323 for anyone who wants to take a look.

Thanks!  I left some comments there.  Notably how toggling this on/off should behave and the possibility of a config upgrade routine).  With the current proposal, I believe buggy plugins are either banned by proxy (they kill all sound, but unobviously) or they're killed explicitly (they're muted).  This may be exactly what the team wants, but it may not be what users want.

Regardless, I do see this as a helpful and useful feature, but it does have some rather unobvious side-effects, since plugins will get disabled/muted without any real corrective action to the end-user except removing the problematic plugin.  Again, this may be desired by many, but it is still a regression to an end-user that wants this plugin.  To use this bug report as an example, the reverb will just cease to work, causing a much more severe audible difference with the project.

**Comment by michaelgregorius** [comment]
Here are some thoughts that crossed my mind while reading the thread.

## Why can the audio of the whole machine be muted by the bug?
It would be interesting to know why LMMS can silence the whole audio chain of the machine. Is it because the operating system or audio system does not sanitize the buffers and the NaNs get mixed with the sound of the other applications or because the input is sanitized? If they sanitized the buffers I'd expect that the remaining applications could still be heard and that only LMMS was muted. If every application is muted then this seems to indicate that the NaNs are mixed with the other audio data and that even the "low level" code operates on the SISO principle.

## Proposal to not touch buffers and to auto-mute channels
IMO the best solution might be to not touch the generated buffers but to auto-mute channels with loud or problematic values. This is also what REAPER does. When a channel is auto-muted this is indicated very prominently and it is clear that this is not a normal or manual mute. LMMS could also inform users why an auto-mute happened and what steps they could take to investigate and mitigate the problem.

It would also be nice if the auto-mute threshold would be configurable. See [here](https://eu-browse.startpage.com/av/anon-image?piurl=http%3A%2F%2F2.bp.blogspot.com%2F-6QtiGe1rqu0%2FU2MQ-8uK7XI%2FAAAAAAAAAAs%2FuIlW6vSQFdY%2Fs1600%2FImagem1.png&sp=1719778025Tc8fd1036e4dea9cb7d52c762b91a758cc062aaf0a57993c4d282a68696963783) for the preference in REAPER.

## Plugin for testing other DAWs
For testing it would be interesting to write a VST or clap that intentionally creates NaNs and then to see how different DAWs behave with the plugin in the chain.

## Peak value indicators
How does the issue look with the peak value indicators that we now have? What values are shown?

**Comment by sakertooth** [comment]
>  Is it because the operating system or audio system does not sanitize the buffers and the NaNs get mixed with the sound of the other applications or because the input is sanitized? If they sanitized the buffers I'd expect that the remaining applications could still be heard and that only LMMS was muted.

I still find it odd how I cant find any details as to how operating systems handle NaNs when they are played back by the hardware.

> IMO the best solution might be to not touch the generated buffers but to auto-mute channels with loud or problematic values. This is also what REAPER does. When a channel is auto-muted this is indicated very prominently and it is clear that this is not a normal or manual mute. LMMS could also inform users why an auto-mute happened and what steps they could take to investigate and mitigate the problem.

When a Inf/NaN appears in the buffer, we can't skip over its processing and do a mute without touching the buffer. The buffer was already corrupted for that audio period. We can mute it for the next audio period if that is what you mean, but that NaN will be played back and reach the hardware, and these values propagate (at the very least for QNaNs in particular), so once they are in the signal chain, any operation involving them will be a NaN. For the next audio period, we can still mute and skip the channel, but if we don't touch the buffer, it might be permanently corrupted until a restart happens.

> How does the issue look with the peak value indicators that we now have? What values are shown?

Doesn't look like it affected much when I tested it, but if there were a few more NaNs in the buffer, something could be a problem there, not sure.
