### ISSUE TITLE
Choppy Notes when playing with computer keyboard

### ISSUE THREAD

**Issue by kuelomisli** [LMMS/lmms#110]
Hi, when I played notes in piano roll e.g. they started to play choppily really soon. I run LMMS 0.4.15 on Arch Linux 3.12.7-2 on a Dell Latitude D620, and I solved this problem for myself by turning off typematic delay. However, another user on the LMMS forum suggested I post this since he has heard about the problem from multiple sides and it works fine for him, even with typematic delay, on Linux Mint. Thanks for doing the great devel job!

**Comment by doyousketch2** [comment]
Ideally, you'd can fix this by changing your desktop shortcut to LMMS:

Set it to turn off keyboard repeat just before opening, 
then turn on keyboard repeat just after shutting down LMMS.

`xset r off ; env QT_X11_NO_NATIVE_MENUBAR=1 lmms ; xset r on`

Though for me, XFCE doesn't like it when you string together commands on shortcuts.
Not certain if that's intentional, or a bug.

Either way, the command works fine when you run it from a terminal.

**Comment by zonkmachine** [comment]
@doyousketch2 Works like a charm on Linuxmint-17.3 / Mate

**Comment by mechmind** [comment]
Unfortunately `xset -r` disables repeat for whole X session, so I had to write a simple hack that disables and reenables repeat when LMMS receives/loses focus.
