### ISSUE TITLE
B+B plays extra bar with note near the end

### ISSUE THREAD

**Issue by kmouse** [LMMS/lmms#1105]
I have a beat with a drum note very close to the end of the bar (although it doesn't touch).
![B+B](https://cloud.githubusercontent.com/assets/6356278/4054557/67213f5c-2d91-11e4-8583-4c1546c6fe9f.png)
As you can see, the arrow showing what is playing is in the next bar.
What I found more interesting is that If I add normal note to any point in the bar, it loops normally.
![B+B](https://cloud.githubusercontent.com/assets/6356278/4054586/d60b09ac-2d91-11e4-8157-c2ef20337c03.png)
Thanks

**Comment by Umcaruje** [comment]
Reproduced on Ubuntu 15.04 x64, lmms 1.1.3

**Comment by zonkmachine** [comment]
Here's an odd thing from the 'off by one' family and possibly related.

If you change to a 5/4 beat and add something to the 5  ...
![bbtrack541](https://cloud.githubusercontent.com/assets/6368949/13908484/766620ba-ef03-11e5-92ab-b3572f8d911d.png)

... and then change back to 4/4 you now have 17 boxes to tick. The last counts as position one in a subsequent 4/4 beat.
![bbtrack44ghost](https://cloud.githubusercontent.com/assets/6368949/13908578/a16fb97c-ef05-11e5-90b2-4a5a1e9cd613.png)

Hit the 'Add steps' button and there will be an extra empty step 33 that you can use.
![bbtrackmore](https://cloud.githubusercontent.com/assets/6368949/13908649/cbd05cc4-ef07-11e5-9f28-4751b1cc8ee6.png)


If instead any of the final positions in the 5/4 beat are taken...
![bbtrack542](https://cloud.githubusercontent.com/assets/6368949/13908534/7937be42-ef04-11e5-96cc-d329c1dd5bd4.png)

a change back to 4/4 will give you 2 full beats instead which is more expected behaviour but if you otherwise remove steps from a beat notes are just dropped so that could be an option here.
![bbtrack244](https://cloud.githubusercontent.com/assets/6368949/13908554/2ad812be-ef05-11e5-8b82-134ae0be895e.png)

**Comment by zonkmachine** [comment]
@kmouse @Umcaruje @musikBear 
Could any of you please see if #2491 affected this anyhow?

**Comment by musikBear** [comment]
@zonkmachine 
kmouse / Umcaruje can properly do that, but i need a binary for win32 to do it.

**Comment by zonkmachine** [comment]
OK. We'll soon have a new RC build for you to test.

**Comment by zonkmachine** [comment]
> Could any of you please see if #2491 affected this anyhow?

It didn't...
