### ISSUE TITLE
Instruments are very loud by default

### ISSUE THREAD

**Issue by grejppi** [LMMS/lmms#113]
Every instrument's volume is at 100% by default.

Some instruments, such as Kicker and BitInvader, output their sound at 100%. Any overlapping sounds, such as two notes playing at the same time, will cause clipping.

[Example project with Kicker, TripleOscillator, and BitInvader at their default settings.](http://ubuntuone.com/7Zr8grUZbMFMGFQWW41C7B)

This potentially leaves the user with a bad impression about the quality of LMMS' sound engine. It did for me initially.

**Comment by unfa** [comment]
I personally would not want any DAW I use to perform some hidden "sound enhancements" because I want total manual control over my sounds and this would be more of a problem than a feature. I don't like what FL Studio does to it's output, it confuses me.

**Comment by Wallacoloo** [comment]
One option I haven't heard is to make the default volume of placed notes something like 50% instead of 100%. This doesn't introduce any compatibility issues.

Personally, I am in favor of just adding a limiter to the default template, as suggested previously. I think this would do more good than harm. I don't know anyone who exports final songs without a limiter, so it saves time for everyone out there who is happy with the built-in limiter (and newbies), though the users who know what they're doing will obviously tweak it to their needs. Those who use more advanced limiters need only save over the default template and it's no more trouble for them ever again.

I'll be honest here. If my daw hadn't provided me with a default limiter on the master channel when I began writing music, I wouldn't have learned that it was normal practice to do that for at least 3-4 months, and my first few tracks would have inevitably had some clipping. Even most "smart" users typically start out as "stupid" users.

**Comment by musikBear** [comment]
ehh.. limiter on master is commonly used by most?
(?)
I have read the exact opposite. (and have never used limiters on anything, except a specific preset)  Is compressing perhaps what was in mind? 
Compressing on master is considered good, limiter is not
-im confused now :confounded:
(btw im with Vesa too, leave master sound /output/ raw, with no trickeries)

**Comment by darkscrap** [comment]
Wow. I didn't realize this conversation has been going on for over a year.

I mentioned it on the IRC, but my vote is to not do anything to the instruments themselves. I like @Wallacoloo idea of changing default note volume. I also think having a limiter (or a compressor, since @musikBear likes that idea better) on the main FX channel is a good option to prevent those loud noises on some instruments/voices.

Please don't hard-code anything into the master channel like FL Studio. One of the reasons LMMS is so great is because you can change almost anything.

**Comment by tresf** [comment]
I agree that they all need to be quieter by default.  I'd even go as far to say that presets should never be over a certain DB level -- since presets are often the entry point into an instrument, they would need to adhere to the same quality standards.

I think the major task here is someone with a good sense of sane defaults sitting down and sanitizing things.   First run should be the instruments themselves.  Second run should be the presets IMO (presets could take weeks to go through properly).

**Comment by musikBear** [comment]
I would suggest a spreadsheet 
default factory 3oc could be base value
All instruments & all presets tested on same system, and all measured up against base-value.
Then note how many dB each differ from base-value, in the spread-sheet.
This would ensure that any specific settings on anyones specific pc, would be transparent.
But there is a serious cravat:
*Are the sounds loudness equally comparable if they are created by different sound-devices ??* 
Eg, Will SDL output be significantly different from ALSA or JACK -what about ASIO ??
If Thats an issue, it would need one responsible for each devise choice..

**Comment by unfa** [comment]
I think we should not drop this all on one person who has the feel of sane defaults, but work to create a standards that can be measured and evened out even automatically. Like a function to normalize plugin/preset/sample volume for use in library.

I think ebur128 can be a nice tool for the measuring purpose:

ebur128 When_You_Fly,_Frostbyte.flac 
Integrated loudness:      8.5 LU
Loudness range:           7.7 LU

This means that the signal should be attenuated by 8.5 dB to be normalized according to EBU R128. I think it's a nice idea to follow this standard. It
ll ensure ours sounds are not too loud by default, and they are consistent.

It uses the EBU R128 recommendation to measure loudness. This is more accurate than RMS or peak dB.

Now we could render 60 second second samples of all presets, analyze the loudness, and add a compensation loundess tweak (an amplifier plugin?).

This way every preset gets normalized to the standard automatically. We jst need to find the sane offset (or should we go for -23 LUFS)?

I guess it's not that hard to generate an MMP file that'll play a middle C note for a plugin.

**Comment by ashafq** [comment]
My vote is to pull the instruments volume down to 25% of the full scale by default. Here's my reason: 

Typically the user would load up a project, pull down an instrument, and play a chord. Music rarely consists of one note at a time. A chord is typically 3 notes and the user will probably overlay a melody on top of a chord (one more note). So, the idea is to let that initial experience sound good, instead of clipped. The user will probably not notice clipping until he starts playing 5 notes with this setting.

**Comment by tresf** [comment]
Agreed (that it should be lowered) but this isn't a small task... I'll quote myself:

> I agree that they all need to be quieter by default. I'd even go as far to say that presets should never be over a certain DB level -- since presets are often the entry point into an instrument, they would need to adhere to the same quality standards.

> I think the major task here is someone with a good sense of sane defaults sitting down and sanitizing things. First run should be the instruments themselves. Second run should be the presets IMO (presets could take weeks to go through properly).

**Comment by disconnect5852** [comment]
Some instruments are loud indeed, but my problem is, the 70% of them are barely audible. Even if i set the volume to 200%, those few normal volume instruments fade them.

I think a normalization would be nice.

**Comment by BloodyRain2k** [comment]
> Now I'm thinking about a UI tool. What if a red "clip warning" turned on in each mixer channel whenever clipping occurred in that channel.
This is actually something that's very nicely done in ZynAdd's UI.
If there's a clipping it shows not only that the sample clipped at some point but also how far above 0db it went.
Something like that should be added for LMMS' channels too, but it should auto reset on play start so you can easier figure out where it happens. ZynAdd's must be manually reset by clicking it.
Currently there's only that tiny shortlived peak bar which lasts a second or so.

As far as the default volume goes, the argument that the volume needs to be less for chords is true, but so is that some presets are barely audible already.
I got that problem with mosy ZynAdd presets for example, a few make my ears bleed but most are at the same volume barely hearable.

Maybe auto tweak the volume to a base level, like -10db by adjusting the volume knob of the instrument when it's added? That way you can see and change it if it interferes with your intention.
A hidden auto tweaking is indeed undesireable because that can easily get away leaving you wondering wth is going wrong.

Alternatively (additionally?) offer a setting for the base level of added instruments? Like 70% so they get all added with 70% volume or -10db so they get set to that in whatever way the volume knob needs to be turned to do that.
The auto leveling to -10db or so should definitely be done for previewing samples in the left panel though, because they can be all over the place with their volume and even if you need to tune it down afterwards so a chord won't blast full out would it still help in hearing *what* you're about to add as sample.

**Comment by musikBear** [comment]
in RC3 win32 TripleOscillator (default) does barely react to base-velocity setting
Recreate:
Drag a default TripleOscillator in SE and play notes as  base-velocity is manipulated.
![velocity](https://user-images.githubusercontent.com/6662066/28996498-f59a0218-7a01-11e7-908d-5037e088f31f.gif)

zasfx has correct behaviour

**Comment by grejppi** [comment]
That's because TripleOscillator is not a MIDI-based instrument and therefore can use the velocity value directly. This control is only used by MIDI-based instruments to convert it to the scale they can understand.

**Comment by musikBear** [comment]
> That's because TripleOscillator is not a MIDI-based instrument

@grejppi ah.. ok, but should the option then be available? I feel they need to be either greyed-out or removed on the instruments that does not allow changing base-velocity, just as PITCH has been removed on Vibed, f.i.

**Comment by MIntrovrt** [comment]
I'd recommend normalizing since it would make precise mixing much easier.
Further than that, adding a little more headroom would be awesome.
I'd say lowering the track volume by 3 or even 6db would help a lot.
This new normalized value at -n db should be 100%

**Comment by tresf** [comment]
We should really make a unit test against new presets that sanitizes this.  Afaik we have no way of scripting this, it would be a newly written unit test.

**Comment by tresf** [comment]
Also, we bundle some 3rd party presets like ZynAddSubFX.  Not sure how to handle those since any changes would diverge from upstream.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
