### ISSUE TITLE
Rename "Beat+Bassline Editor" to "Pattern Editor"

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#120]
The titles says it all.
Let's have shorter and more universal names,

**Comment by tresf** [comment]
I'd like to resurrect this thread too. Most were in favor of changing it back in January 2014 but we got stuck on picking a good title.

**Comment by StakeoutPunch** [comment]
I still believe that what I suggested in [this comment](https://github.com/LMMS/lmms/issues/120#issuecomment-50108726) would be a good fit.

**Comment by Wallacoloo** [comment]
Let's get quantitative. Can we create a poll, "What should the editors be renamed to in LMMS 1.3?" with the various suggestions from this thread & then get actual numbers on what the users & devs want? Facebook provides a platform for this. Maybe our forum software does as well?

**Comment by eagles051387** [comment]
Colin there is also google survey and survey monkey these can be done on as
well. If you use facebook you are leaving out users who do not have a
facebook account.

On Sat, Aug 29, 2015 at 3:43 AM, Colin Wallace <notifications@github.com>
wrote:

> Let's get quantitative. Can we create a poll, "What should the editors be
> renamed to in LMMS 1.3?" with the various suggestions from this thread &
> then get actual numbers on what the users & devs want? Facebook provides a
> platform for this. Maybe our forum software does as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/120#issuecomment-135926299>.
>



-- 
Jonathan Aquilina

**Comment by musikBear** [comment]
...and once again NO should be an selectable option in any poll
NO is my vote -The amount of 'noise' confusion and pure nonsense **any** renaming will create, will be so so tiresome.
You should not rename important parts of anything as old and well known as lmms - my bend molded cent is spend now :p

**Comment by tresf** [comment]
> ...and once again NO should be an selectable option in any poll
NO is my vote -The amount of 'noise' confusion and pure nonsense any renaming will create, will be so so tiresome.
You should not rename important parts of anything as old and well known as lmms - my bend molded cent is spend now :p

Says the person who refuses to upgrade from Windows XP.

My vote stays the same, "Pattern Editor" is better than "Beat / Bassline Editor" but I'm open to better suggestions.

I'm against a Facebook poll on this, I think facebook is better left polling for features rather than barely noticeable cosmetic items, but if someone wants access, just ping myself or @Umcaruje privately and we can grant access.

-Tres

**Comment by cubician** [comment]
Lemme know when the poll is up. If there is a poll.

**Comment by tresf** [comment]
@cubician where have you been?  :)

Are you interested in running it for us?

**Comment by idtownie** [comment]
I know this thread is super old, but, as a newcomer to LMMS, I think this very much still needs to happen because I was at first completely unaware of the fact that you can put melodies and stuff in the BB editor via the piano roll, not just beat patterns. This was in part due to the UI not making it obvious that you can access the piano roll, but also due to the name. I second "pattern editor".

**Comment by filostrato** [comment]
Another vote for calling it "Pattern editor" from me; way more universal than the current name.

**Comment by lukeoftheaura** [comment]
another vote from me.

**Comment by tresf** [comment]
Some technical problems with this... 

* The word "Pattern" is ambiguous in the codebase.  e.g. It can refer to a PianoRoll Segment, it can refer to an Automation Segment.
    * For example, the enum type `PlayModes -> Mode_PlayPattern` already exists.  We need to give this a better name, such as `PlayModes -> Mode_PlaySegment` or more accurately `PlayModes -> Mode_PlayPianoRoll`.  Note that not all `Patterns` are piano rolls, however this enum seems to only control the playback of piano rolls, so perhaps it's name was just poorly picked.  Case-and-point, you can't playback an automation pattern without the Song Editor, so there's no "Play Mode" for an Automation Pattern.  Confusing?  Yeah.
    * `Pattern.h` would otherwise have nothing to do with `PatternEditor.h`, so this is another namespace problem/confusing unless we continue to rename.  We can namespace it `Segment.h` but that might be more confusing.  Sharing thoughts is important here.
    * To that point, most editors are now `PatternEditors` because they edit what we've historically called a `Pattern`.  Does this make the `PianoRollEditor` a `PianoSegmentEditor` and the `AutomationEditor` an `AutomationSegmentEditor`?

If you're nodding your head saying "Yeah, a `Pattern` should be renamed `Segment`", then Step 1 is renaming `Pattern` to `Segment` and must come before the "BB" renames or else we'll get lost.

**Comment by tresf** [comment]
@lukas-w made an important observation and that's that the ambiguous use of Pattern is even more confusing because `AutomationPattern` is not a subclass of `Pattern`, but rather they're siblings that are subclasses of TrackContentObject.  Refactoring TCO is now the first step.

**Comment by Spekular** [comment]
It might make sense then to call automation/instrument/bb patterns in the
song editor something else. "Clip" is used in some DAWs I think? Perhaps
this (or whatever other new name is decided on) could be used in the
codebase as well.

**Comment by tresf** [comment]
@Spekular `Clip` seems to be the winner.

So.... `Clip.h` gives birth to `NoteClip.h`, `AutomationClip.h`, `PatternClip.h`, `SampleClip.h`.  This will touch most of the source files, making syncing from `stable-1.2` harder.  Will see if an IDE can help with the refactoring and go from there.

**Comment by tresf** [comment]
Alternate proposals are **`MidiClip.h`**, `AutomationClip.h`, `PatternClip.h`, **`AudioClip.h`**

**Comment by vlad1777d** [comment]
Totally agree to rename it to "Pattern Editor" =)

**Comment by claell** [comment]
> The word "Pattern" is ambiguous in the codebase. e.g. It can refer to a PianoRoll Segment, it can refer to an Automation Segment. 

Will this be an issue, when only using Pattern Editor?

> Refactoring TCO is now the first step.

Is there an issue for that that can be linked? Also I suggest to add a label stating that this is awaiting another issue to be fixed first.

**Comment by russiankumar** [comment]
Sorry to be dropping on this dead issue, but I feel like even now this is a nice change to have, and it would be much more friendly for newcomers to LMMS (as Pattern Editor is a more standard name, and Beat+Bassline may seem to some as if only drums and basslines can be edited here). Judging by this conversation there's a lot of changes to be made which definitely can't happen in one PR. Can we break down this into a step-by-step rename (one PR per step), maybe like so:

1. Rename AutomationPattern -> AutomationClip
2. Rename Pattern -> Clip (or whatever else may be decided)
3. Rename BBPattern -> Pattern
4. Rename editors

List needs refinement, and this one is probably bs, but something like this so that this change can actually be executed finally.

Or if this change is not going to happen, maybe close the issue along with an explanation why it won't be?

**Comment by tresf** [comment]
> Or if this change is not going to happen

It'll happen and we welcome the change.  Previous attempts were mostly superficial making the code a bit harder to read, but you breakdown of it is what we'd really like to tackle.  Feel free to open a brand new bug report and have this one closed if needed.  If you're going to refactor many components, it will probably serve as a better bug report than simply "The titles says it all." 🤣 

Furthemore, thanks for offering.  The project can't survive without the hard work from people like you.  👏

**Comment by russiankumar** [comment]
> Feel free to open a brand new bug report and have this one closed if needed.

Nah, I think I'll stick to this one. There's a satisfying feeling closing a six year old issue when it's already solved rather than just renewing it. Don't know, just my preference honestly xD. Though if you prefer convenience, I can open a new bug report.

> it has the tendency to break other PRs

Oh I can see the wave of disappointed developers coming my way for this :D
I think active PRs need to be finalised and merged before this, and we need to warn developers that a major change is coming. Or we can make a new branch and rename everything there. That seems like a nice way to do it, although the merge conflict mess will be a headache.

Anyways, glad to be helping!

**Comment by Veratil** [comment]
If we're going to rename files, let's please organize them better, too.

**Comment by tresf** [comment]
> I think active PRs need to be finalised and merged before this, and we need to warn developers that a major change is coming. Or we can make a new branch and rename everything there.

There's a style one that @JohannesLorenz was waiting to merge.  That's the first that comes to mind.  Also, your very nice color PR (thanks!).  Anything stale gets punished for going stale.  At some point, people have to rebase and rewrite stuff.  To quote my mother cleaning a room... 

> "it's going to get worse before it gets better" 

To reference a time when a large sweeping change occurred: https://github.com/LMMS/lmms/pull/1353

The conversations that occurred then will occur again for eternity. ❤️

**Comment by russiankumar** [comment]
@Veratil, any suggestions? I’ve got no idea on how to go about reorganising myself.

@tresf,
> Anything stale gets punished for going stale.

Well said. Cuts off some nice features (like that Toolbar PR) but then again not like they were going to merge soon.

I guess we’ll let my color PRs and Johannes’ PR merge (and any other non-stale ones), and then start working on this. I suppose that nobody will be able to make a stable PR at this time, as everything will be moving around and getting renamed.

Also, rough plan which we can elaborate on:
1. Reorganise everything to better places
2. Rename files themselves and update everything that broke (#include, cmake etc)
3. Rename classes and variables and etc one by one
4. Rename the editors

**Comment by tresf** [comment]
> Cuts off some nice features

Exactly.  Most PRs are great btw, some just aren't as obviously great.  I'm an offender of stale PRs as are many other devs.  It's just part of the job and most devs are sympathetic to this.

**Comment by Veratil** [comment]
> @Veratil, any suggestions? I’ve got no idea on how to go about reorganising myself.

I'll have a look around and come back with one. 👍

**Comment by russiankumar** [comment]
You know what, I think a new issue would be better for this. Not exactly easy navigating through this huge discussion. In case somebody has something to say later on, we could point them back here I guess. Will create a new issue soon for better organisation.

**Comment by russiankumar** [comment]
Closing this in favor of #5592.
