### ISSUE TITLE
Mixer peak indicators.

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#1271]
![screenshot from 2014-11-07 07 47 18](https://cloud.githubusercontent.com/assets/335217/4950252/7a157970-6658-11e4-97c5-fc0e16690ea8.png)

Mockup of how this could look on the Fx mixer....

To improve the mixing functionality, useful for for both song construction and final mixdown we should implement a GUI element which will indicate the highest peak of every cahnnel.

this will work in the following way.....

(1) Optional switch for on/off in the config settings
(1a) Optional switch on the GUI element itself ( code can be taken from the master waveview on the main toolbar )

(2) The indicator will hold and display the highest peak reached by its channel until a higher value is received on that channel.

(3) Left click will reset the indicator to wait until it receives another highest db reading. This is the main benefit of having this functionality as we can see that we are above our threshold or too high in a separate channel, which is forcing the total of all channels to cause Master fx channel to rise above 0bd ( aka clipping ).
So we can now lower the volume slider in an FX channel and see what the new db value is easily.

(4) If the peak indicators value is >= 0.0db it will be highlighted ( red in my example.)

This behaviour is consistent with Ardour and Hydrogen drum machine

---

_note that i have done a keyword search in our git repo and cannot find this as a feature request, so if it is a replica i will merge this comment into it thanks MIkobuntu_

---

**Comment by RebeccaDeField** [comment]
@mikobuntu  Has this issue been fixed by #3056 ?

**Comment by musikBear** [comment]
@RebeccaDeField imo no. @mikobuntu idea was a real readout of the value. I love that idea, but it clashed with the area available.
I still think that miko's idea is so sexy, that it really deserve a 2. consideration.
The sc. 'realestate' area is imho quite an eye-sore, and on top of that, its function is also suboptimal. I feel we could exploit the **caption**-bar better, and then make a 6 char rule for the 'realestate' area. This rule should ensure that only 6 letters of a preset name was displayed in the mixer, but when a channel was highlighted, the *whole* preset-name would be shown in the caption (just as my mockup-picture above ( https://github.com/LMMS/lmms/issues/1271#issuecomment-62256282 ). It is also difficult read whole vertical names, so a display of the name in proper writing in fi. caption-bar, is in need. And **that** would leave room in the 'realestate' area for not only miko's sexy meeter, but even more functions.

( Current 'tooltip' is not too good. Often this happens
![fxmix_dodgyhint](https://cloud.githubusercontent.com/assets/6662066/19766127/722d8d84-9c4c-11e6-8c87-425e3ae21d47.PNG)
I have NO idea why. Since its not reproducible, i cant file a ticket

OBS! *Names* on the channels are **extremely** important, im **not** saying they arent! but 6 ..or 8? chars would be sufficient for *identifying* the channel, and the whole name would then appear at mouse-over in caption-bar, or similar, fi. there are a lot of space for a *general purpose info-area* in **Main** to the right of the CPU-meter

**Comment by Rossmaxx** [comment]
Done via #7045

**Comment by DomClark** [comment]
> Done via #7045

It doesn't look like it to me - that PR improved the existing features, but didn't add this one.

**Comment by michaelgregorius** [comment]
I have a first implementation of peak indicators which adds the new class `PeakIndicator`. It inherits from `QLabel` and has a slot to set/update the current peak value if it represents a new peak. It connects to a new signal of the `Fader` class. Here's the current implementation in action:

[Screencast_20240520_203622.webm](https://github.com/LMMS/lmms/assets/9293269/52f47a35-76af-483c-baaa-0509f8511a36)

## Peak indicator reset
For some strange reasons resetting the value via click does not work because the click event does not reach the peak indicator widget although I have overridden `mousePressEvent`. Does anybody have an idea what might be causing this? Some event filters somewhere or something similar?

Resetting the indicators when a new project is loaded also would have to be implemented due to the fact that the mixer strips are reused and keep their old state.

## Warning colors
Also no warning colors of any kind are implemented. Don't know if that is wanted in the first place?

## Noisy Lb302
What's interesting is that in the video the master channel already starts at "-147 dbFS" instead of "-inf dbFS" because the Lb302 instance directly seems to inject a weak signal. Test file is "Greippi - Krem Kaakkuja (Second Flight Remix).mmpz".

**Comment by michaelgregorius** [comment]
Pull request https://github.com/LMMS/lmms/pull/7295 adds peak indicators. They do not light up in warning colors if a threshold is crossed but already add some nice value.

I guess warning colors would need something more than just inheriting from `QLabel` so that the background colors can be set accordingly. So that's something for later or someone else.
