### ISSUE TITLE
Refreshing the Cool Songs

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1273]
I've noticed that many songs shipped with LMMS have a few things missing:

· Making use of FX-mixer
· A decent escription
· WOW factor
· polished feel

I'd say there's a lot of old stuff there that... well... doesn't get me too excited when I play it. And they don't look like they were made by LMMS masters - the project's don't use all LMMS potential (FX-mixer, automation, controllers, now availabile mixer sends and awesome new synths).

We've got so much talented and skilled artist in the community, I think we could filter the existing demo projects and take some action to attract new demo projects from the community.

I'd suggest making a competition for a demo song.
As a requirement I'd give a few points:
- you have to use the FX-mixer
- you have to write an aesthetic, comprehensive description
- make a track that's between 2 and 5 minutes long
- use only LMMS-shipped effect plugins so the projects are portable
- use only LMMS-shipped samples so the project is portable
- release it under a CC license and include this information in the project description

Additional points for:
- using mixer sends
- using automation
- using controllers
- using coloured song clips
- creating innovative sounds
- using a wide selection of instrument plugins

I think there should be a jury of skilled people who can judge the projects in both technical and musical ways. We could add the existing projects into the pool letting them compete with the new submissions - those who don't pass will be removed and replaced with the top tracks submitted.

As a bonus we could render the submitted tracks and master them making another LMMS community album available on Bandcamp.

What say thou?

**Comment by rubiefawn** [comment]
I would love to contribute to this. I'd be glad to whip something up from native LMMS.

**Comment by SecondFlight** [comment]
There has been quite a bit of work towards this goal since late 2014 when this issue was opened. I personally don't see a reason to keep this issue open.

In the spirit of pruning, here are my arguments for closing this issue:
1. This can't be solved by any single person.
2. New songs have been added, but no specific push has happened in the last 5 years towards actually moving this issue to a closed state, and it's not likely anything's going to happen now.
3. Closing this issue is not likely to have any significant impact on whether or not someone will request to have their song in LMMS.

I'll leave this open for a bit in case there are any objections.
