### ISSUE TITLE
Navigating and inserting notes in piano roll using keyboard only

### ISSUE THREAD

**Issue by grzesiek-galezowski** [LMMS/lmms#1421]
Hi!

Just wanted to ask for a small feature that is in Jeskola Buzz and that I am very used to. It would be very nice to be able to put specific notes on specific positions using only keyboard in piano roll.

In buzz, there is a feature that lets me "navigate" my position on the track using keyboard arrows and when I press a key on my keyboard, like 'z', it would automatically leave corresponsing note on this position. In lmms, when I want to leave a note on a specific position, it seems I either have to use the mouse (and point each place) in draw mode or recording (forces me to get timing right or fix things later).

**Comment by Sti2nd** [comment]
Information: There are no shortcuts reserved for this feature, as it probably will use a lot of them, and thus should be a mode.

**Comment by sorath72** [comment]
I've been working with tracking starting with fast tracker 2 then mad tracker, then currently using psycle tracker and sunvox for music composition. I just wish the LMMS would turn more into a fully functional and usable DAW for everyone. Not just FL Studio or other DAWs interfaces PROs out there.

**Comment by tresf** [comment]
> I've been working with tracking starting with fast tracker 2 then mad tracker, then currently using psycle tracker and sunvox for music composition. I just wish the LMMS would turn more into a fully functional and usable DAW for everyone.

We all do, which is why we're learning the code and fixing it.  This stuff is a lot of work and we need help! :beer:

**Comment by Redsandro** [comment]
I've been ~~looking into~~ _thinking about_ this a couple of times ever since in 2010 someone on `#lmms` told me how to recompile parts of the software. I wanted to break the LMMS piano roll dialog and turn it into a tracker. For personal use, and because it would attract the entire population that was born in the 80s to LMMS.

This keyboard-based step recording sounds like the next best thing. Having to use the mouse what made me step away from 'modern' music apps.

On an unrelated note; I do think that mouse events make it easier to port to Android though. On a touch screen, click (touch) events become fun again! FL Studio for Android managed to make me create some tunes again. :smile:

**Comment by Sti2nd** [comment]
> I'm gonna subscribe to notifications

Hey, no need to subscribe to notifcations if you code it :-D !! hint, hint

**Comment by zonkmachine** [comment]
Implemented in https://github.com/LMMS/lmms/pull/4544. Closing.
