### ISSUE TITLE
Export in LMMS (> 1.0.0) is not working with active ru.qm locale

### ISSUE THREAD

**Issue by megakott** [LMMS/lmms#1496]
Export in LMMS is not working with active ru.qm locale, i.e. for almost all installations in russian.

Affected versions: 1.0.1, 1.0.2, 1.0.3, ..., 1.1.0 (true for Windows, not sure for Linux)

Steps to reproduce:
1.) Take russian installation or emulate it. To emulate, replace file LMMS/data/locale/en.qm with file ru.qm from the same folder
2.) Try to export any LMMS project. Eternal 0%, LMMS hangs and may be shutdown only through task manager.

Possible workarounds for exporting from russian installations:
* Either take data/locale/ru.qm from 1.0.0 LMMS distrubution
* Or copy data/locale/en.qm into ru.qm

__________________________
Aleksandr Kotov,
            invisible member of Russian LMMS community :)

**Comment by ryukusu** [comment]
Yes, it affects linux version. At least 1.1.0 compiled from sources.
There is an error in the terminal: 
___
Mode initialization failed: invalid parameters for bitrate
___
If you replace ru.qm to en.qm project exported.
I think it's related with localization, because if you have russian language, you first letters in English for the menu items then russian localization.
Also I replace ru.qm from the previous version(for example 1.0.0) everything works again. :)

**Comment by badosu** [comment]
I traced the bug is going as far back as 2da7804c8230fb04d1963c63b12581c4a7255501...

**Comment by tresf** [comment]
@DanWin great find!

**Comment by tresf** [comment]
:+1:
