### ISSUE TITLE
Organic glitches

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#1499]
While trying some presets, I came to organic ones and I saw a little problem with all of them.

At the start and at the end of a note there is a glitch, a little click.
What's worse is that you can't avoid it because even if you play with the envelope you will still hear it when playing a note just after or during another one.

I exported some score with a 1osc preset, so without actually doing additive synthesis, let's say, and I opened it with Audacity.

Well, here is the problem
![screenshot_9](https://cloud.githubusercontent.com/assets/6437521/5554972/2fd76ac6-8c87-11e4-8616-f729739f78ea.png)

The two channels have different phases, and in orther to achieve this feature, they start with random initial phase.

I'm not really into synthesis yet, but I do know that starting a sound with an initial phase other than 0 will lead to a click, or glitch.

So, do we need different phases for the two channels?
If yes, what about having it by letting one of the two channels start a bit after the first? Like this:

![screenshot_10](https://cloud.githubusercontent.com/assets/6437521/5554978/e3a9cf9e-8c87-11e4-9669-0e7254af2fce.png)

Not sure if this is a bug, but it's not like I've heard this problem before now...

**Comment by tresf** [comment]
@diizy is this a long-standing bug?

Shall we push it out to 1.2 (or further) milestone?

-Tres

**Comment by zonkmachine** [comment]
> ...is this a long-standing bug?

Probably. It's not a bug as much as just how the oscillators work so it's not only Organic. Try a 3xOsc with only one sinewave and turn the SPD knob. When you offset one of the waves the oscillator will simply make it start right there in the middle of the wave. Biggest leap is at SPD settings 90 and 270. This isn't a problem with saw or squarewave as much as sine which is only the fundamental.


> So, do we need different phases for the two channels?

Yes. Even though it'll get you into trouble from time to time it's like a super duper cool thing to have.



> If yes, what about having it by letting one of the two channels start a bit after the first? Like this:

That'll work. If it's possible to tell the oscillator that it's the first or last cycle we could have it blank out everything before the start of the phase shifted tone on the first cycle or after on the last. Or we could make the stereo phase shift by actually using a delay but that would probably be more heavy on computation.

This is probably to complex to deal with this close to a release. Push to 1.3 ?

**Comment by DeRobyJ** [comment]
About issues for 1.2, I agree we can push some to 1.3
This is one of those which doesn't need to be fixed right now, it has no right of stopping the new incoming features.

(in my opinion, we should only focus on stability, at this point)

**Comment by michaelgregorius** [comment]
I have checked with the file http://www.mediafire.com/download/s5gnx3wod15z3m3/strageorganicproblem.rar which was provided a few comments above and it seems like Organic has a problem with polyphony.

Everything is ok as long as single notes with pauses in between are played (like for example at the beginning of the file). As soon as several notes are played at the same time the clicks occur at the start of each new note. An inspection of a render of the example file reveals sudden jumps like this one:
![organic-problem](https://cloud.githubusercontent.com/assets/9293269/10080218/b4519680-62ee-11e5-8291-32b6884055dc.png)

As was already mentioned by @DeRobyJ this also happens if you have the amp envelope active. It also seems that the problem becomes more pronounced the louder the first note is. You can try this as follows:
* Add and open an Organic instance.
* Set the attack of the amp envelope to 1.8.
* Play a note and keep it held the whole time.
* While holding the first note play another note repeatedly.

You will notice that at the start there is no click and that the click starts to appear as the first note becomes louder and louder.

TripleOSC does not show this behavior.

**Comment by DeRobyJ** [comment]
Do you think this problem is connected to the other one (explained  with the pictures in the first post)?

My point is that every note played with organic has a "sudden jumps" problem due to the fact that the two channels have different initial phase.
If you change the phase of an oscillator in 3OSC to something around 90° or 270°, you will have the same behaviour. That's the problem to me: having an initial phase different to 0° or 180°.

If we still want to have a random different phase for the two channels, we can have it by making them start something after the note is played (second pic in my post), avoiding the "jump" issue, and having a sudden and very brief silence when subsequent notes are played (instead of the jump you described)


About the amp evelope, it's curious that it is active for the first note only!

**Comment by DeRobyJ** [comment]
mmm, now that I try it a bit better, I think the problem is Organic changing the currently played note phase while it's playing, because it changes it for the new note.

Analyzing one channel only
- First note phase is A
- Second note phase is B
- First note phase becomes B when second note is played

Organic has a single value of phase (actually two, since both channels are different, causing the problem described in my first post), so it can't store the phase of multiple note.

**Comment by softrabbit** [comment]
Every time a note is played, the phase offsets are randomized and stored in the shared array ```m_osc```. The 8 Oscillators created for the note store a reference to ```m_osc[i]->m_phaseOffsetXXX``` instead of just a plain float, so they keep up with the changes for subsequent notes. https://github.com/LMMS/lmms/blob/master/plugins/organic/organic.cpp#L241

Ideas on how to solve this:
* The phase offsets could be stored separately for each note, probably in ```_n->m_pluginData```. 
* The ```Oscillator``` class could be amended to make the connection to the phase offset disconnectable.
* The randomization could happen only in the constructor of the plugin, but would that make the sound too static? It's a 1-minute fix, though.

**Comment by DeRobyJ** [comment]
I vote for first idea. It's how it should be, imo.

**Comment by michaelgregorius** [comment]
I vote for implementing the first idea as well.

**Comment by zonkmachine** [comment]
I don't see any difference with or without https://github.com/LMMS/lmms/pull/2458.
There are two reasons for glitch sound in these waveforms.
 * The transient in the beginning of a shifted note.
 * The frequent segments that are just drawn wrong.

These are both present with or without the fix.

`LMMS:master`
![screenshot at 2016-02-24 06 56 06](https://cloud.githubusercontent.com/assets/6368949/13294145/ffe31aa4-db22-11e5-9b25-cc80f2d30d9f.png)

`softrabbit:issue1499`
![withfix](https://cloud.githubusercontent.com/assets/6368949/13294151/04a28c3c-db23-11e5-8dc9-1b6bf2f38753.png)

**Comment by zonkmachine** [comment]
This is the transient in 3osc with one channel shifted 90 degrees.
![3osc](https://cloud.githubusercontent.com/assets/6368949/13295226/27284d3c-db28-11e5-8bf5-3cbc463e0508.png)

**Comment by softrabbit** [comment]
> I don't see any difference with or without #2458.

Right. Looks like I had a bit of tunnel vision in reading the comments when I jumped in ([around here] (https://github.com/LMMS/lmms/issues/1499#issuecomment-142992580) ), as there seems to be more than one kind of glitch.

#2458 only fixes the glitches that come from polyphony. Here's a test case for that:
[organic_phase_test.mmp.zip](https://github.com/LMMS/lmms/files/145249/organic_phase_test.mmp.zip)

Edited the PR to reflect that it's only a partial fix.

**Comment by zonkmachine** [comment]
Right. I didn't read that well after about the place where you jumped in...

:+1:  Fix confirmed.

The issue should stay open though. I think what @DeRobyJ reported on was the phase offset transient.

**Comment by DeRobyJ** [comment]
Yep, I originally wrote about the one that comes from polyphonic use. The attack phase offset can be fixed either using longer attack time or by changing how phase is offset (see first posts)

**Comment by zonkmachine** [comment]
I still don't feel like I quite grasp this but I've found a mathematical relationship with the parts that are drawn wrong. They're all 0.6 or 3/5ths of the waveform. Well, they could be the part drawn right and the rest is wrong off course...
Here is the same parts with the glitches stretched in Gimp to 167%

![glitches scaled](https://cloud.githubusercontent.com/assets/6368949/13335337/e513bd70-dc10-11e5-9c6e-52075848c97a.png)

**Comment by zonkmachine** [comment]
> They're all 0.6 or 3/5ths of the waveform.

Nope. They're: Amplitude / 'Bottom Volume Knob' for a short period. This is the volume knob to the right of the 'Dist' knob. Set it at 100% and all it's clean at least from this glitch. I don't know if there is any connection to the other Organic glitches though. The number of oscillators doesn't seem to affect this. I had a quick glance and didn't spot anything.
@softrabbit Maybe this is something you can have a look at since you've just visited this code?

**Comment by softrabbit** [comment]
Most of my visiting the code happened in November, but I can try. 

It looks like to me like the level is shifting, i.e. the envelope is discontinuous, but setting the AMT knob to 0 didn't change anything. The jumps are smaller when the signal is closer to 0, which would implicate multiplication.

The glitch seems to always start 96 samples after note start, and it's 80 samples between the level shifts, very consistently. Related to some buffer size (16)?

The fact that the glitch pops up from the second note onwards would IMO point at some artefact of the previous note being present, or shared state that shouldn't be. The search continues...

**Comment by zonkmachine** [comment]
At 1 percent I get just a metronome of glitches and a hint of organ in the background so our setups differ here. I also counted 80 samples first but then I've played with buffer size and at 2048 the shift start 192 samples in and are 160 long.

**Comment by softrabbit** [comment]
One step closer: https://github.com/LMMS/lmms/blob/master/plugins/organic/organic.cpp#L313 

In the plot there's only volume on the left, and everything but volume on the right.
```c++
		_working_buffer[i][0] = m_volModel.value() / 100.0f;
		_working_buffer[i][1] = waveshape( _working_buffer[i][1], t ) * 1.0f;
```
![1499-volume_vs_waveshape](https://cloud.githubusercontent.com/assets/6411463/13365180/259b96d0-dcdc-11e5-8bd3-01bc53bde070.png)

**Comment by zonkmachine** [comment]
I went back in time and this seem to be an issue that may originate some 2 years back. I will try and do a full bisect later today.

**Comment by zonkmachine** [comment]
270af579b8572ebef22ecc3c10a36d019ca005fe

```
270af579b8572ebef22ecc3c10a36d019ca005fe is the first bad commit
commit 270af579b8572ebef22ecc3c10a36d019ca005fe
Author: Vesa <contact.diizy@nbl.fi>
Date:   Sun Jun 29 23:13:00 2014 +0300

    Revision of handling of frameoffset for NPH, SPH
    Change in handling of frameoffset for multistreamed instruments and sampletracks.
    - Instead of holding the offset for the lifetime of the playhandle, negate the offset in the first period
    - Multistream-instruments require some small changes: they have to now check for the offset and accordingly leave empty space in the start of the period (already done in this commit)
    - There are possibly optimizations that can be done later
    - This change is necessary so that we can have sample-exact models, and sample-exact vol/pan knobs for all instruments. Earlier multistream instruments were always rendering some frames ahead-of-time, so applying sample-exact data for them would have been impossible, since we don't have the future-values yet...
```

The last wave in the graph below happened when I deleted `+ offset` , as one does, from [this line](https://github.com/LMMS/lmms/blob/270af579b8572ebef22ecc3c10a36d019ca005fe/plugins/organic/organic.cpp#L321
) in `270af57`. Also, all older waves start one cycle in (top wave, left) but that's fixed in master.

![waves](https://cloud.githubusercontent.com/assets/6368949/13375577/d0188a88-dda3-11e5-875f-580095116cd7.png)

**Comment by zonkmachine** [comment]
> One step closer: https://github.com/LMMS/lmms/blob/master/plugins/organic/organic.cpp#L313
> 
> In the plot there's only volume on the left, and everything but volume on the right.
> 
>        ` _working_buffer[i][0] = m_volModel.value() / 100.0f;`
>        ` _working_buffer[i][1] = waveshape( _working_buffer[i][1], t ) * 1.0f;`

@softrabbit I tried this and when I ad some envelope... it affects the volume. I'm a bit surprised as I thought the instrument would handle this separately after the plugin.

![envelopevolume2](https://cloud.githubusercontent.com/assets/6368949/13408911/8d0ad74e-df30-11e5-82d3-1af87b10a0a6.png)





> Edit: This is as far as my trouble shooting...

Well. Now I'm done... This bug is just weird.

**Comment by softrabbit** [comment]
> @softrabbit I tried this and when I ad some envelope... it affects the volume. I'm a bit surprised as I thought the instrument would handle this separately after the plugin.

What happens is that the level of the organic volume knob becomes the signal, after which the signal goes through the usual processing just as you thought. So it's really not that surprising when you think about it.

**Comment by Umcaruje** [comment]
@softrabbit @DeRobyJ is this issue fixed by #2458?

**Comment by DeRobyJ** [comment]
Yes, now you just need to add some attack time in the amplitude envelope and you will never get a click, even on a pure sinewave.

Closing as fixed

**Comment by teeberg** [comment]
Kind of related to this issue, has an option like Ableton's "Created Fades on Clip Edges" been discussed before to add this attack time automatically when needed?

**Comment by teeberg** [comment]
Kind of related to this issue, has an option like Ableton's "Created Fades on Clip Edges" been discussed before to add this attack time automatically when needed?

**Comment by tresf** [comment]
@teeberg, never discussed AFAIK, but I like the idea and so many of our instruments and samples could benefit.
