### ISSUE TITLE
Vestige dont work in linux mint 17

### ISSUE THREAD

**Issue by Khomkovm** [LMMS/lmms#1567]
![2015-01-07 15 17 14](https://cloud.githubusercontent.com/assets/10434650/5645499/043706b6-9681-11e4-8e35-e22da8a760cc.png)

Vestige dont work in linux mint 17, 17.1, etc.
Wine has been installed before.
Why?

**Comment by tresf** [comment]
> What platform then it is better to use?

Sorry, perhaps I was unclear.... Your platform of choice is terrific to use, we just don't package LMMS ourselves for it.  Someone else does that.  This is most common in the Linux world.  We do package the Windows and Mac versions because they can be run on nearly any Windows/Mac versions.  Linux packaging is usually specific to the Linux version you run.  For now, we don't package our Ubuntu/Debian/KXStudio installers or any other Linux installers for that matter.

> KXStudio repositories for Ubuntu, Debian.

Ok, thanks.  That is maintained by the KXStudio team so they are the best people to contact in regards to problems.

I'll ping a project maintainer for you out of courtesy.  @falkTX, how best to escalate this problem?

**Comment by falkTX** [comment]
If you're using the KXStudio repositories, make sure "lmms-vst-full" package is installed.
And also that you have a working Wine.

Not much that I can say, lmms + vestige still working fine here.

**Comment by Khomkovm** [comment]
Thanks falkTX, tresf, everything is working fine now.
The problem was in lack of "lmms-vst-full".
That is great, thank you! I truly appreciate all your help.

**Comment by badosu** [comment]
The same happens on Arch, you have to get `lmms-vst` or `lmms-git` from AUR to get lmms with VST support.

**Comment by tresf** [comment]
@badosu can you confirm this command so that we can add it to our downloads page.

```
sudo pacman -S lmms-vst
```

**Comment by badosu** [comment]
@tresf AUR is user repositories for Arch, so it's not available via `pacman` by default.

The user must install a pacman wrapper, see [this list](https://wiki.archlinux.org/index.php/AUR_helpers), or enable the `community` repo for pacman.

In my case I use [yaourt](https://wiki.archlinux.org/index.php/Yaourt) so my command is `yaourt -S pacman-vst`.

**Comment by tresf** [comment]
```
yaourt -S pacman-vst
```

Is this a typo for:

```
yaourt -S lmms-vst
```

**Comment by badosu** [comment]
It is, sorry : ).

This should be fixed in the future, see: https://bugs.archlinux.org/task/41302

**Comment by badosu** [comment]
Anyway, I guess we can close this one, right?

**Comment by badosu** [comment]
@tresf Instead of changing the pacman command, just point the user to https://wiki.archlinux.org/index.php/LMMS where the issues are described.

**Comment by tresf** [comment]
@badosu, thank you kindly.  Done via https://github.com/LMMS/lmms.io/commit/84c47bcd7011942a164bf9ca70fb37ac8251d2d7

Direct links to the page content:
http://lmms.io/download/#linux-arch
http://lmms.io/download/#linux-debian

Please let me know if you find any errors.

**Comment by badosu** [comment]
@tresf Great! Thanks!

Just be aware that you used a `h3` probably where it would be better to use a `h4` as the VST support section is related to the Arch instructions..

**Comment by tresf** [comment]
@badosu yeah, I went back and forth between `<h3>` and `<h4>`.  `<h4>` didn't look right either... :confused:

**Comment by badosu** [comment]
@tresf It's cool
