### ISSUE TITLE
SF2 player per-note bending

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#1607]
I believe the SF2 player could get per-note bending with a little tweaking. Looking at the available settings at http://fluidsynth.sourceforge.net/api/index.html#CreatingSettings hints that the number of MIDI channels can be increased to 256 (`synth.midi-channels`).

If then the same program is selected for all channels and each note sent to Fluidsynth on its own channel (ATM they all simply go on channel 1),  independent bending should be possible.

**Comment by diizy** [comment]
On 01/12/2015 03:07 PM, Raine M. Ekman wrote:
>
> I believe the SF2 player could get per-note bending with a little
> tweaking. Looking at the available settings at
> http://fluidsynth.sourceforge.net/api/index.html#CreatingSettings
> hints that the number of MIDI channels can be increased to 256
> (|synth.midi-channels|).
>
> If then the same program is selected for all channels and each note
> sent to Fluidsynth on its own channel (ATM they all simply go on
> channel 1), independent bending should be possible.
>

Possibly, if it can be done without affecting performance too much (and
without adding any more locks...)

**Comment by derula** [comment]
I recently discovered note detune (which I think this is about? correct me if I'm wrong), and was disappointed to find it doesn't work with SF2. 

First, am I correct to assume that the core problem is that MIDI pitch changes are applied per-channel, not per-instrument? I.e., note detune would with perfectly fine for monophonic tracks, and the suggestion in this issue is to automatically subdivide polyphonic tracks into separate MIDI channels using `magic()`?

Now, 4 years have passed since this issue was filed, and a new major version of FluidSynth has been released along the way. I am wondering if FluidSynth has introduced any new features in the meantime that would make this easier to implement. Or whether it's even sensible / possible to upgrade the bundled FluidSynth.

Finally, would it make sense to start work on this issue now? Or is there any recent development or other non-apparent information that would make it a silly idea to tackle this issue at this time? Asking because I'm semi-considering to see if I can make that change, since it would be very nice for me to have.

**Comment by ToruTheRedFox** [comment]
could probably help with vst per note bending too, at least with compatible vsts that support per channel pitch bending (such as Roland Sound Canvas VA which supports the entirety of General MIDI afaik)

**Comment by RiedleroD** [comment]
I'd wait for #6217 to go somewhere because it might be hard to merge back with whatever they come up with.

**Comment by Rossmaxx** [comment]
i think #6602 is related

**Comment by zonkmachine** [comment]
Fixed in https://github.com/LMMS/lmms/pull/6602
