### ISSUE TITLE
Faster loading in LMMS

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1741]
This bug is a list of places that could use faster loading.
1 vst and vst fxs loading
2 AFP sample loading
3 project files and templates files loading

**Comment by Sti2nd** [comment]
Your suggestions is of course desired, but this seems more like your opinions on what in LMMS one need to focus on than tangible information to work on. A developer of LMMS would better manage to make an issue or three for the proposals, issues that actually could be closed because they would include either what needs to be done or an estimation on how much faster loading could happen.

**Comment by tresf** [comment]
Unless you have something specific that helps the software, this bug report has no value and is invalid.
