### ISSUE TITLE
Enhancement Focus-points / bookmark-feature

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1746]
Current vers has 3 options for play-head-posistions
(those 'names' are btw horrible..)
i think an extra view-option-feature - *focus-point* , *bookmark* or *index-point*, can be a great addition.
This would be like 'book-mark(s)' on a project, and a mock-up could look something like this:

![pastenot](https://cloud.githubusercontent.com/assets/6662066/6091940/f41286a0-aec4-11e4-933d-53d728260e47.PNG)

1 is controller for the feature
2 is a focus-point

In piano-roll it would work as a series of 'jump-to-posistion' points
In song-editor, it could also work as project structure points

UI
1 The controller
left mouse: insert a point at playhead-pos
left-arrow+left mouse: browse through point from playhead-pos to the left
right-arrow+left mouse: browse through point from playhead-pos to the right
right-mouse: open list of points (default just numbered) -A click moves view to that point.

2 The points
left-mouse: Name point
right-mouse: remove point

**Comment by Sti2nd** [comment]
You could easily see this in relationship with https://github.com/LMMS/lmms/issues/156 .

**Comment by tresf** [comment]
Agreed this is really functionality on top of an enhancement that hasn't even been created.  Please post your thoughts there in #156 @musikBear.  We could consider a placeholder for all of these, but I really think we should organize and focus the feature ideas rather than scattering them around the bug tracker.
