### ISSUE TITLE
bug LMMS dirty sound of the converted files in wav or mp3 finished projects

### ISSUE THREAD

**Issue by Mark0001** [LMMS/lmms#1788]
Hi I wanted to point out a further program bug LMMS. and that is when you use the effect or codec "HugeGrittyBass XPF" and using writing notes both serious high then when the file is converted to wav files just released from the production of LMMS or even worse, especially when converting to MP3 because when listen to part with this effect and samples of LMMS hear audio type frying or popping sounds the same audio and data errors are not known to be poorly written or remotely incorrect but are audio noise from the sound of the file conversion or projects ready by Linux same (LMMS) I am reporting this because sometimes the production is good but annoying because dirty as sound and disturbatada interference and audio frying of LMMS itself, let me know thanks.

**Comment by musikBear** [comment]
Mark, could i ask you to take these bugs through the forum, in the 'troubleshooting' section:
http://lmms.io/forum/viewforum.php?f=7
Then if some real bug apears, it can go into the hub tracker, I ot others will answer all your Qs in the forum :)
Because, this is not a bug.
What you expirience is called **clipping**
http://lmms.io/forum/viewtopic.php?f=7&t=279
This could be a good start -
Its either a. o. caused by volume, resoance or bandwidth
(btw -Codecs are significantly different from presets, and things can get quite confusing..

**Comment by Mark0001** [comment]
ok thanks for answer
