### ISSUE TITLE
Piano Roll select and move bug [ latest stable build on Linux ]

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#1818]
To reproduce:-

(1) Drag ZASF into BB_Editor ( haven't tested with other instruments yet ).
(2) Open Piano_Roll press record.
(3) Create melody any time after the 1st bar ( let record roll past the 1st bar before pressing keys ).
(4) Stop recording.
(5) Use CTRL + A to select all notes. 
(6) Use Shift + Left Arrow key to pull all of the already selected notes so that the 1st note is at the start of the 1st bar.
(7) Play back melody

The result is there is no audio for the notes in the 1st bar. 

To regain audio of this 1st bar again, just click on a note as though you were going to manually drag all of the selected notes ( no need to even drag ) and audio will be resumed.

This leads me to believe the Shift select could be broken perhaps?

**Comment by Sti2nd** [comment]
> This leads me to believe the Shift select could be broken perhaps?

Or do you mean the Shift + left/right arrow shortcut

**Comment by mikobuntu** [comment]
@Sti2nd  yeah it could be that too or a combination of both, i will need to do further testing, but something is definitely broken , that's for sure ;)

**Comment by M374LX** [comment]
The problem does not happen only if notes are created by recording. The same happens if the one are created using the mouse.

Even if, after moving, only some of the notes are left in the first bar, this bar is silent while all others can be heard. The problem persists when the timeline reaches the end of the loop and comes back to the beginning.

**Comment by tresf** [comment]
Closed via #1855
