### ISSUE TITLE
Settings dialog resizable but widgets do not adjust to its new size

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#1849]
The settings dialog is resizable, but the widgets inside it do not adjust to the new size. 

One possibility is to get the widgets to adjust to the new size. Other is to simply make the dialog unresizable.

**Comment by badosu** [comment]
This settings UI needs a serious rewrite, but this also requires some decisions on packaging assets and discovering plugins. If I am not mistaken @curlymorphic made some work on this area, thoughts?

**Comment by curlymorphic** [comment]
> simply make the dialog unresizable.

this would be my choice. The content of the dialog was not designed to be resized. Let me know if this is required.

There is currently some redesigning going on in #1807

**Comment by tresf** [comment]
I vote we make it a fixed size since we don't benefit much from a resizing of this particular dialog.

That doesn't mean I love it the way it is, I just think if we are going to rethink our dialogs, we should rethink them from a global UI consistency, functionality and cosmetic perspective.

**Comment by tresf** [comment]
I believe the major difference with this dialog versus others is that it is not an internal MDI window, it is a floating modal dialog.  All of our floating modal dialogs seem to be resizable.

**Comment by tresf** [comment]
QDialogs affected by this bug:
 * `SetupDialog`
 * `RenameDialog`

QDialogs **NOT** affected by this bug:
 * `ExportProjectDialog`
 * `EffectSelectDialog`
 * `ControllerConnectionDialog`
 * `AboutDialog`
 * `plugins/sf2/PatchSelectionDialog`
 * `plugins/GigPlayer/PatchesDialog`

A reoccurring pattern seems to be files created with XML UI files don't suffer this bug, likely because they were created with a tool such as QT Creator.

**Comment by tresf** [comment]
I found [some solutions to this](http://stackoverflow.com/questions/575294/how-can-i-get-rid-of-the-resize-handle-in-a-qdialog), but in testing, I ran across a crash in master when the `~/.lmmsrc.xml` file is missing so I'm taking a break... :)

-Tres
