### ISSUE TITLE
Proportionally changed notes bug

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1905]
win32 1.1.3
Reproduce
Insert two chords of 2 bar note-length
Mark all
use combo sh+LMB in order to change note-lenght and note-position simultaneous. (proportional) 
Change length to 1 bar
At that moment the 2. chord get into its correct length, and position, the notes abruptly snaps into the first chord.
Obs!
This bug *only* occur when the first chord is in first bar! 
The first chord will in addition to this, *sometimes* be muted (looks like the note-start-pos could be outside first bars left limit?)

**Comment by Wallacoloo** [comment]
Interesting glitch! Here's a gif of it (using a build of the latest git commit: 77c6f5a2bf, even though the title bar says otherwise):

![musikBear #1905](https://cloud.githubusercontent.com/assets/1210751/6956019/a190bb2c-d8d6-11e4-9a96-88a0bdf1138d.gif)

As you can see, it happens even if the notes are not in the first bar for me. At the end 

when I very *slightly* drag one of the notes, you can see that it was located behind t=0, which does explain why the first note is occasionally muted.

I did a bit more fiddling with the shift+click stretching:
![musikBear #1905 - 2](https://cloud.githubusercontent.com/assets/1210751/6956355/5edf98ec-d8dc-11e4-8fb5-a55ea1724960.gif)

After the third note would have passed the second note in the above gif, it instead jumps an entire bar forward. It seems like there might be some logic error in whatever function handles pattern stretching.

**Comment by tresf** [comment]
@Wallacoloo thanks for taking the time to document this!

**Comment by Wallacoloo** [comment]
It looks like all of the relevant logic for this is confined to lines [2471](https://github.com/LMMS/lmms/blob/d61075972dd55c9833fdfbeaf6a8bcd2c86f3ded/src/gui/editors/PianoRoll.cpp#L2471) through 2476 and lines [2498](https://github.com/LMMS/lmms/blob/d61075972dd55c9833fdfbeaf6a8bcd2c86f3ded/src/gui/editors/PianoRoll.cpp#L2498) through 2516 of gui/editors/PianoRoll.cpp.

**Comment by Wallacoloo** [comment]
In fact, it looks like the logic error is on line 2510: `shift_offset += off_ticks;`. If the cursor is dragged 3 ticks to the left, then this causes the first note to be shifted 0 ticks, the second -3 ticks, the third -6 ticks, and so on. The result is that if your pattern is 5 ticks long and contains three notes, the third note can be shifted up to -10 ticks (i.e. behind the start of the pattern).

**Comment by Wallacoloo** [comment]
#2010 should fix this issue. I'd greatly appreciate it if you can test it out when you have some time @musikBear, since you seem to use this functionality more than I.

**Comment by musikBear** [comment]
@Wallacoloo would be most obliged, but i can only run x32 win binaries. No linux installation, sorry.
