### ISSUE TITLE
Instrument switcher (less clicks and window clutter)

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1937]
![instrument switcher mockup](https://cloud.githubusercontent.com/assets/6345473/7026976/f5b39d76-dd1a-11e4-8a84-1662fb40e1c6.png)

Instead of closing one window and opening another, a pair of buttons might reduce amounts of clicks required by users, as well as amount of windows present on the screen.

It's also a psychological shift towards single-window UI ;)

Hotkeys would also be great for those.

What do you think?

**Comment by tresf** [comment]
Yeah this would be nice. :)

**Comment by unfa** [comment]
I think it should be consistent with B+B editor. However there's no way to edit the name of a pattern inside B+B editor, and we need that in Instrument window. Maybe a right click/double click would make the combo-box editable? The previous/next buttons could be binned and replaced by mouse-wheel action in the combo-box.

**Comment by Umcaruje** [comment]
+1 sounds like a really useful feature.

**Comment by curlymorphic** [comment]
I really like the sound of this,

@unfa

 Are you suggesting we have just 1 instrument on screen?
How should instrument child windows (external plugin windows, effect windows) be handled?

**Comment by Sti2nd** [comment]
> Are you suggesting we have just 1 instrument on screen?

Like only one instrument window open at a time?
![image](https://cloud.githubusercontent.com/assets/6373430/7031691/b009c662-dd6d-11e4-95ff-aad8be0f8d05.png)
I didn't think that was what he was suggesting, I thought he just wanted to be able to select next instrument in some internal Zyn instrument list.

**Comment by tresf** [comment]
@Sti2nd nice call.

**Comment by Wallacoloo** [comment]
I like this idea. Did a quick search and the Vestige plugin already has a similar set of buttons that are used for changing presets. So we already have the icons for it, if we want, as well as some code to reference.

**Comment by Wallacoloo** [comment]
The biggest problem that arises with this is what happens when you have (in your example) one window open for `Brass Crescendo`, another open for `Timpani Drum`, and in the first window you hit the right arrow. Now you should have two windows both editing `Timpani Drum`. First of all, from me familiarizing myself with the UI code, it looks like it would take some significant refactoring just to make that possible. And secondly, synchronizing changes between the two windows would also require some more effort.

I think things will work fine in "one instrument track window mode" though.

**Comment by musikBear** [comment]
i kind of understand, but theres a substantial difference between the *internal* presets in a VST, and *external* versions of zasfx or 3oc instances 
Quite often the sequence of presets in a vst are 'related' -eg 1-12 are basses, 13-25 are pads, aso
Here it make sense to 'try the next one' in the 1-12 sequence *if you are trying to find a suitable bass!!!*
The sequence of zasfx or 3oc *instruments* in their folders, are however totally unpredictable, and only depends on which name the user gave the preset. so here there is no logical reason to 'try the next one', because it could be a FX or pad or whatever. *Only* if the user has subdivided everything in subfolders, so all basses are in a bass subfolder aso, the 'next-one' will logically make sense.
But is that common? 
(I use a prefix system, btw)

**Comment by Wallacoloo** [comment]
@musikBear I may have misunderstood the original feature request, but I don't think this has anything to do with presets. The left and right arrows are used to switch between different instruments that you've already dragged into the song editor (instrument tracks? I don't know the terminology). So for in the example, clicking the right arrow would switch the window currently titled "Brass Crescendo" into an editor for the pattern directly following it in the song editor: "Timpani Drum". Clicking right again would take you to "String Ensamble High", and so forth.

Functionally, the arrows do almost exactly the same thing as if you were to click on the currently selected instrument, thereby closing its editor, and then click on the following or previous instrument, thereby opening its editor.

**Comment by tresf** [comment]
For those not automatically notified of Pull Requests, please take a look over at #1987. :+1:

**Comment by musikBear** [comment]
1987 makes it much clearer :p :blush:
(those ani giffs are nice! What proggy do you use to make them?)

**Comment by tresf** [comment]
> it looks like it would take some significant refactoring just to make that possible

Good point.

The underlying models should actually support this pretty seamlessly (no different than an automation event, right?)  Although it could certainly be confusing to have two identical instrument dialogs open, it may not have the hard limitations one would initially expect.

**Comment by curlymorphic** [comment]
I have had 2 ui for the same effect hacked up ok before, I have not looked into the instruments, to see how they stand on separation of concerns.

**Comment by Wallacoloo** [comment]
@musikBear 
> (those ani giffs are nice! What proggy do you use to make them?)

They sure are :-) They're really useful to get more input from people who don't have the time to pull the changes, build & test. I use [byzanz](https://github.com/GNOME/byzanz) (specifically the command-line tool `byzanz-record`, since I don't use Gnome & didn't want to figure out the applet stuff). It's available in some PPA somewhere too, not sure where.

**Comment by musikBear** [comment]
> I use byzanz 

ahhh linux magic the win-user silently *sighed*  :droplet:

**Comment by mikezn** [comment]
I like this idea.
1. I think the dropdown option to select an instrument from is a great idea, easier and quicker to use than buttons. Flicking through instruments with the scroll wheel whilst mouse over the dropdown would add so much value to it too (mind you that could work if you designated a scroll region over the arrows if they were added).

2. To me LMMS is sequencer driven, it would be so beneficial for the selected instrument to have its track / lane highlighted or emphasized the whole way across the sequencer.

**Comment by Umcaruje** [comment]
Should this be closed? #1987 was merged.

**Comment by tresf** [comment]
:+1:

**Comment by Umcaruje** [comment]
Closed via #1987
