### ISSUE TITLE
difficulty finding the option of the speed of the notes on the piano roll of LMMS Software.

### ISSUE THREAD

**Issue by Mark0001** [LMMS/lmms#1940]
Hi I wanted to give information, I can not find the option or setting for the execution speed of the notes on the piano roll of the program LMMS, look through your answers.

**Comment by Spekular** [comment]
Are you looking to set different patterns to different tempo? I don't think
that's supported right now but IIRC more individual tempo control is
planned for some time in the future. Otherwise, you set BPM in the toolbar.
If this is a suggestion, could you clarify? If you just have a question
about using the software it's probably better suited for the forums.

**Comment by tresf** [comment]
> execution speed of the notes 

 1. If you mean tempo, please change the global tempo via [Getting Started](https://lmms.io/documentation/Getting_Started)

 1. If you mean repeating notes quickly such as an arpeggio, please see the [Instrument Editor's Arpeggio Section](https://lmms.io/documentation/Working_with_Instruments#Arpeggios).

 1. If you mean how long the note is held, please see the [Instrument Editor's Envelope Section](https://lmms.io/documentation/Working_with_Instruments#Envelope_basics).



Next time, please don't be so vague.  Furthermore, this is the wrong place to ask for basic help, we have [forums](https://lmms.io/forum/) for that.
