### ISSUE TITLE
Automatable/Assignable Controller Rack On/Off

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1997]
The controller rack LFOs needs a on/off button on them. This way you assign the on/off button on to the LFO a on/ off button to a button on your midi keyboard.

**Comment by tresf** [comment]
Well, it has one, it's just impossible to drag to an automation editor.

![image](https://cloud.githubusercontent.com/assets/6345473/7257743/c9d65160-e825-11e4-98b0-ffd9cae6c636.png)

**Comment by Reaper10** [comment]
what  about adding  on/off button on to the LFO so you can Assign it to a button on midi keyboard?

**Comment by tresf** [comment]
> The controller rack LFOs needs a on/off button on them. This way you assign the on/off button on to the LFO a on/ off button to a button on your midi keyboard.

Thanks that is tremendously useful over your previous statement. :)

**Comment by Sti2nd** [comment]
So basically he wants to be able to turn the controller on and off with automation?

**Comment by tresf** [comment]
Yeah, which a perfectly valid request.  We use a `Modal` dialog now, which blocks users from automating the LED since they can't drag the automatable LED.

His point is to just add an ON/OFF switch on the controller rack itself, which would be the most consistent with the rest of our software.  Either could get the job done. :+1:

**Comment by SecondFlight** [comment]
Closing in favor of #3686. I know they're *technically* different, but #3686 presents more sensible behavior and it would not be reasonable to have both IMO.
