### ISSUE TITLE
Better workflow with adding B&B-lines

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2014]
already the workflow for presets & mixer #355 #2011 is on tracker, a similar issue exists for adding new B&B to a project. Current workflow is not intuitive.
**Current workflow:**
User need to
- open B&B-editor
- click _add beat&bassline_ button
- compose
- open song-editor and find _Beat/basslineNm_ in the bottom of the project
- right-click the new BB
- Name it

**Proposed workflow:**
- open B&B-editor
- click _add beat&bassline_ button
- new popup for naming the new BB
- insert name
- compose

Both the BB in BB-editor, and the BB-track in Song-editor has now the inserted name.

All was done in one window (BB-editor).

**Comment by Wallacoloo** [comment]
If we do this, we should enforce some level of consistency across the board. That is, the "+" button in the Mixer should also raise a popup for the name of the new channel.

**Comment by musikBear** [comment]
agree :+1: , but i hope you can see the difference:
In adding fx-channels, the whole operation are made in one window
In adding BBs you need to open 2 windows, and scroll one

**Comment by Sti2nd** [comment]
> the "+" button in the Mixer should also raise a popup for the name of the new channel

Never :exclamation: I would rather want a random string name I can edit later.

Also I hate musikBears proposal, pop-ups are evil.

**Comment by musikBear** [comment]
> Also I hate musikBears proposal, pop-ups are evil.

How can a naming field option be evil?!
It just let you name the new fx-channel! So seen**once** in connection with the creation event. That is **exactly** as most OOP editors does, as you add a new object. Did you understand the proposal?

**Comment by grejppi** [comment]
It distracts the user from the actual goal which is to simply create a new track. The user shouldn't be forced to come up with a name first in order for LMMS to do it.

**Comment by tresf** [comment]
@Sti2nd and @grejppi are correct in terms of blocking dialogs, they quickly become evil.

Perhaps a quicker solution to this problem is to stop using blocking dialogs for renames and instead do something like this:

![image](https://cloud.githubusercontent.com/assets/6345473/7347417/82418190-ecb6-11e4-9e59-050e6aa05ae6.png)

The idea would be that the rename becomes immediately possible, but clicking off of it doesn't interrupt flow.

**Comment by curlymorphic** [comment]
> Perhaps a quicker solution to this problem is to stop using blocking dialogs for renames and instead do something like this:

I like this solution. Same improvements as @musikBear proposal, but less intrusive.

**Comment by Umcaruje** [comment]
I agree with @Sti2nd and @grejppi, modal dialogs are just evil. @tresf's proposal seems much nicer, but since your issue is about easy renaming the B&B editor without going to the SE, how about that right clicking the title of your pattern inside the BB editor allows you to rename it?
![bbeditor](https://cloud.githubusercontent.com/assets/6282045/7347742/dbbd5d90-eceb-11e4-9c55-2f750077dc73.png)

**Comment by tresf** [comment]
@Umcaruje or to be as consistent as possible, we switch to something like @Wallacoloo's instrument bar, making the BB title directly editable, just like an instrument... 

![image](https://cloud.githubusercontent.com/assets/6345473/7347837/54b938d6-ecba-11e4-892b-1e24a75c0980.png)

**Comment by musikBear** [comment]
@Umcaruje got it! 
That would be the best solution.
Remember: This is all about being able to create a new BB-track, in only the window where it is intuitive -Eg BB-editor!
> (re)Naming the B&B editor **without** going to the SE, how about that right clicking the title of your pattern inside the BB editor allows you to rename it?

:+1:

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
