### ISSUE TITLE
purpose of folders in 'disk':\Documents and Settings\'usename'\lmms

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2036]
Cant remember if this been up before -searching was negative
In fore mentioned folder l, lmms has the infamous .lmmsrc.xml + 4 other folders 

samples
preset
plugins
projects
-Mine are empty
* Why at all have *anything* outside the user-known installation? I cant see reasons for that..?
* what are the folders meant for?
* why use a 'dot' file for configuration (creates mishaps, if the user fumbles with it..

**Comment by tresf** [comment]
> why use a 'dot' file for configuration (creates mishaps, if the user fumbles with it..

This is standard for many config files as it hides the file on most unix or linux platforms.

> Why at all have anything outside the user-known installation? I cant see reasons for that..?

This **IS** the user-known installation.  If you're asking about why a user would want items being stored outside of these folders -- that should be obvious -- but it is because some items, such as VST plugins, LADSPA plugins may already be installed to the system.

> what are the folders meant for?

That what users should use for projects and project samples, etc (or change the path in your preferences).  It makes your LMMS installation somewhat portable as all you need to backup is a single folder to contain all of your work and the sample paths are stored as relative in the mmpz meaning they can be put on another computer without fuss.

But this is all LMMS basics and doesn't warrant a bug report.

**Comment by tresf** [comment]
Also... 
 *  `Documents and Settings` hasn't been used since Windows XP.
 * `%USERNAME%` is the wildcard on Windows which will work for representing a home folder for Windows NT 4.0 and higher.
 * All other platform simply refer to the user directory as `$HOME` or sometimes referred to as `~`, which the devs would be using when reproducing a bug report.
