### ISSUE TITLE
Song editor overview window

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2054]
The Song editer could use a song overview window at top or bottom.
IE  Ardour 
 
![overview](https://cloud.githubusercontent.com/assets/8137561/7667605/a6c2bca6-fbd3-11e4-8fd4-24028a02fe9b.png)

**Comment by Umcaruje** [comment]
What does 'Song editer' mean?

**Comment by Reaper10** [comment]
Song editor sorry about that.

**Comment by tresf** [comment]
Yes, it could.

**Comment by Wallacoloo** [comment]
I think this does have merit. It's something that a lot of code editors do, for example, which I find mildly useful. Being able to drag around that semi-opaque white box in the overview of Reaper10's screenshot would make navigating songs slightly easier.

Did you close this due to a lack of resources?

**Comment by tresf** [comment]
No, strictly out of [punitive measures](https://github.com/LMMS/lmms/issues?q=is%3Aissue+author%3AReaper10+is%3Aclosed).  If someone finds the feature useful, they can open a well written bug report.

**Comment by tresf** [comment]
Well, resources too I suppose.  Keeping up with the OP's requests is a full time job. :rocket:
