### ISSUE TITLE
Piano roll volume of selected notes

### ISSUE THREAD

**Issue by diizy** [LMMS/lmms#2070]
Ok so someone has apparently made some changes to the piano roll's vol/pan bars...

So now it seems that there's no way to adjust the volume of a note that is at the same time as another note... before you could select one of the notes and adjust only it but now that feature seems to be broken... who is responsible for this? How are we supposed to change the vol. of a single note in a chord now?

**Comment by tresf** [comment]
Thanks for the report, we'll find and link the commit which introduced this behavior.

Please note, finger pointing is not well received.  We're all in this together.

**Comment by eagles051387** [comment]
Would you like me to look into git bisect?
http://git-scm.com/docs/git-bisect

this will find the change with introduced a bug.

On Sun, May 24, 2015 at 7:48 AM, Tres Finocchiaro <notifications@github.com>
wrote:

> Thanks for the report, we'll find and link the commit which introduced
> this behavior.
>
> Please note, finger pointing is not well received. We're all in this
> together.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/2070#issuecomment-104983005>.
>



-- 
Jonathan Aquilina

**Comment by tresf** [comment]
Based on the titles, I'm looking into the following PRs...

#1963, #1874, #1855, #1716, #1674

**Comment by tresf** [comment]
So, the symptom is that despite the note selected, the one closest to the mouse is still adjusted.

This means that the problem is less related to the old functionality being remove, but more related to a bug with a commit which now adjusts notes on proximity regardless of whether or not they are highlighted.

In other words, whatever notes your mouse are closest to get adjusted as well as the ones selected.  If you raise and lower your mouse in an area without notes, you can temporarily work-around this issue until we locate the cause.

If I were to wager a bet, I would guess the refactoring in #1874 accidentally did this, but more testing will be needed confirm that.

**Comment by tresf** [comment]
I see some potential changes in #1804 (per bug report #322).  Investigating...

**Comment by tresf** [comment]
I think I found it, [`PianoRoll.cpp#L2101`](https://github.com/LMMS/lmms/blob/master/src/gui/editors/PianoRoll.cpp#L2101)


```cpp
if ( isUnderPosition || ( n->selected() && !altPressed ) )
```

should be:

```cpp
if ( ( isUnderPosition && !isSelection() ) || ( n->selected() && !altPressed ) )
```

The problem is that `isUnderPosition` should only be valid when there are zero notes selected.  This seems to fix it.

**Comment by Wallacoloo** [comment]
Nice troubleshooting!
