### ISSUE TITLE
Refreshing the File Browser should not collapse all folders

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#2121]
Currently, clicking the refresh icon in the lower right of a file browser in the left pane of LMMS will cause all of its folders to be collapsed.

Ideal behavior, in my mind, is to preserve the collapsed/expanded state of all folders that existed before the refresh and have only the newly created folders default to being collapsed. Similarly, if a file/folder was selected before the refresh, it should also be selected after the refresh, if it still exists, though that's a minor difference.

**Comment by musikBear** [comment]
I have already once made a topic around this, but it was dismissed. I have to chime in on this one, because the current behavior is a real anointment (imo)
Considder why the *refresh* is used:
The user open a folder, where he expect to find a particular preset
User enters s search-token
The search gives no usable result
The reason must be that the token was wrong OR the folder was wrong
so:
1 Token is wrong
If the user now press *refresh* the token remains, but the browser is empty -eg no further search possible
Current behavior is useless

2 Folder is wrong
If the user now press *refresh*  the browser is empty. There is no folder-tree to access -eg no further search possible
Current behavior is useless -again

In which circumstance is the *current behavior* useful /make sense?

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
