### ISSUE TITLE
is the message 'Your project is now saved' shown to soon?

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2128]
Some eledgely have lost project, because they have turned the pc off, just after saving. The 'saved' mmpz has no data.
Personally i have always said that the user must wait until the message *disappear*! -But that is not intuitive in respect to the words in the message
Perhaps the **logic** is ok, but then the message could be something like 
**'Please wait Your project is now being saved'**
That would make the user understand that there was an ongoing process, untill the message again disappear.

**Comment by Wallacoloo** [comment]
If this is true, it's likely that we just aren't flushing the file before
showing the message, unless we actually are showing that message in the
wrong order.

**Comment by Umcaruje** [comment]
Could /you/ offer some steps to *reproduce*? I 'never' encountered this __issue__!?

**Comment by michaelgregorius** [comment]
I have just checked the code. The saving is done in `Song::guiSaveProject` and the message is shown after the file was written. In `DataFile::writeFile` there is also another coarse check whether anything was written at all (checks if the file size is greater than 0).

Don't know if it really makes sense to explicitly flush the file (or whether `QFile` really supports what would be needed in the first place) because after some time the operating system should flush the data to the disk anyway. It should also do this when the computer is shut down which seems to imply that the original reporter of this problem has "turned off" his computer by ripping out the power cord of the computer or something similar. :wink:

**Comment by musikBear** [comment]
@Umcaruje No neither have i, but after what @michaelgregorius has deducted from the code-base, it is literally *impossible* that this could happen, in the way the orr opp describe it, in the forum post.
So the backend of this, is that i twice has tried to aid 2 different peeps that has lost mmpz-projects after they *-allegedly-* turned off their pc, just after they saw that message. But that train of events are simply de-railed. This issue cant happen in that way..
So left with a different Q
What did then happen? 
But -It is not the timing of the message. I will close this.

**Comment by Wallacoloo** [comment]
I wouldn't be so quick to discredit their reported experiences. In file
i/o, there is often both an operating system buffer and an
application-operated buffer. This means that if you write to a file and
don't call flush, the data may still be residing inside the application's
buffer and not the operating system's.

However, closing the file or destroying the C++ object that represents the
file handle might cause the data to be flushed - I don't know the specs.
I'll have to do some research.
