### ISSUE TITLE
Impact Zone plug-in

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2134]
*Edited 9/12/2015 by @tresf, fix formatting*

**Impact Zone plug-in**
 * A pad-based drum machine (similar to MPC hardware pad)
 * This is not for replacing the B&B editor.
 * 1 to 17 outputs
 * 16 drum pads
    ![impactzone](https://cloud.githubusercontent.com/assets/6345473/9832482/2cca2252-594a-11e5-85a9-cc9274904b37.png)

**The Master Section**
 * In #1987 adds a switcher buttons to the instrument track window in the master section of the Impact Zone plug-in you have a  switcher to change what pad mod Module you see in the Moduler window  when the show Modules is on. The Module window is next to pads when the Modules window is hidden all you see is the pads. The Impact Zone  instrument track panning and volume is all so found in the Master Section. The  Multi Output Button is all so found in the Master Section. A user can save a Impact Zone plug-in preset by the save preset  button in the Master Section. The FX button switchs the pad window from pads to the master FX window. 
 * The instrument track FX box  selector can act as a Master FX channel or  it can act as the normal FX box  selector. To make the Impact Zone plug-in change from a single output  plug-in to a multi output plug-in click on the  multi output button, click on the  multi output button again to change back to a single output plugin. When in  single output mode the FX box selectors for pads are locked to the master FX box selector, ie they are grayed out.
 * ![impact zone plugins master section](https://cloud.githubusercontent.com/assets/8137561/8389481/ccde43e6-1c36-11e5-8693-e7106eb8e0a0.png) ![fx change icon](https://cloud.githubusercontent.com/assets/8137561/8389489/e5435f70-1c36-11e5-9a44-bd505eb3a5ff.png)

**The Pads**
 * The pads has the Plug-in Modules pan, volume, FX Chanel selector box and the mute and solo buttons around the pads are the same as the ones in Plug-in Modules. The reason for this is so when the user has the Plug-in Modules window is closed the user can still use the pan, volume, FX channel instrument track box and the mute and solo buttons without needing to open the Plug-in Modules window. Every pad will have empty Moduler icon until the user loads a Module in the pad this way the user can see what pads are empty. The pad will all so say Empty Pad under the icon until the user loads a preset on to the pad, when the user dose load a preset on to the pad the icon changes to icon of the Plug-in and preset name. In the top left corner will all ways have the pad number on it.
 * ![screen shot 2015-09-12 at 12 25 58 pm](https://cloud.githubusercontent.com/assets/6345473/9832458/81c0a4f8-5949-11e5-848d-9141d77fc447.png)   ![screen shot 2015-09-12 at 12 26 06 pm](https://cloud.githubusercontent.com/assets/6345473/9832460/865a531a-5949-11e5-9314-cb701aa199ba.png)

**Presets**
 * Saving Presets the user can save all pad Modules with it's  pan, volume, FX Chanel setting as a  Impact Zone plug-in preset by the save preset button via the save preset  button that is found in the Master Section. Saving Presets the user can save from a Modules preset just like a normal presets via the save preset button in Plug-in Modules window.
To load a  Impact Zone plug-in preset just drag and drop, it's the same for Modules preset just drag and drop preset on to pad or just drag and drop preset on to Plug-in Modules window.

**Plug-in Modules**
 * The Plug-in Modules are the same Plug-in are basically plug-in as the ones that are in LMMS. The reason for this is so a user can save a preset and a user can use it in the normal Plug-ins and a use  normal Plug-ins preset.Sampling Plug-in**
 1. Audio File Processor (AFP) / Soundfont2 Player (SF2)
    ![afpsf2](https://cloud.githubusercontent.com/assets/6345473/9832484/359bd90c-594a-11e5-9dd5-ff55b595f47b.png)
In the future when SFZ support is add the SFZ plugin is a part of the Plug-in Modules list under the Sampling Plug-in type.

**Synth Plug-ins**
 * The parts that are added to the plugins to make them into the drum pad modules drum pad number plate, mute and solo buttons, pad trigger LED, gear menu.  There is no keyboard just a pad trigger readout box, pad trigger note, pad trigger note sector knob and the reset button, pitch and mod-wheel and range boxes. 
 * Watsyn, Kicker, etc
 
    ![watsynkicker](https://cloud.githubusercontent.com/assets/6345473/9832489/3b085910-594a-11e5-99be-6221d7b39cf3.png)
FYI, I forgot to add the ZynAddSubFX & VeSTige plugins to the Plug-in Modules list for theImpact Zone plug-in.

**The Gear Menu**
 (options found in the gear menu)
 1. Remove module
 2. Copy pad to 1-16
 3. All midi options
 4. Add default Modules  list
 5. After Add support for acidized samples #2154 is added a user can use one AFP / sample on all 16 pads.

**Comment by grejppi** [comment]
Is there anything this plugin can do that you couldn't already do with the Beat/Bassline editor?

From a technical view, the keyboard widget isn't something that you can't take away from an instrument, because it is not part of an instrument plugin in the first place. This proposal would either require a near-complete overhaul of the instrument API, or a completely new track type (not good). ~~Oval knobs are unlikely to happen either.~~

**Comment by Reaper10** [comment]
Feel free to chage what need just an idea

**Comment by grejppi** [comment]
When would you like to see this implemented?

**Comment by Reaper10** [comment]
when ever you can

**Comment by Reaper10** [comment]
can you keep the name?

**Comment by tresf** [comment]
The author of the plugin would have to decide that., but the name isn't bad.  It is catchy and very appropriate, so you may get your wish if it ever gets to fruition.

**Comment by grejppi** [comment]
In my opinion LMMS could benefit more from a general purpose layer plugin, or at least something along the lines of "note sends" analogous to audio sends in the mixer. But that'd be the subject for a different issue.

We already have a way to use our instrument plugins as drums, and it is called the Beat+Bassline Editor. In my opinion a new plugin for that would be completely redundant.

**Comment by Reaper10** [comment]
shoud I close this

**Comment by tresf** [comment]
I disagree strongly.  A drum pad as mentioned several times over and present in many DAWs is needed IMO.  Perhaps not so much from a functionality perspective.... as we can achieve the effect in several ways already as you've mentioned.... This would be more of a productivity improvement per  #1460

**Comment by softrabbit** [comment]
Edited the OP a bit to make a few spots more readable. 

First impression: why the 4x4 grid interface? What's wrong with a list that can be as long as it needs to be, like in the B&B-editor? Is it because some other software looks like this or is it to mimic some famous piece of hardware?

**Comment by Reaper10** [comment]
This is not for replacing the B&B editor it's a pad basted drum machine like the MPC.

**Comment by cubician** [comment]
So like Ableton's Drum Rack? This would be nice, especially since many MIDI files organize percussion in a single track. Not having to separate them would save hours of time when importing MIDI.

**Comment by tresf** [comment]
> So like Ableton's Drum Rack?

Yes.

**Comment by softrabbit** [comment]
I think this could be realized as a kind of a "view" on the B&B-editor, as the underlying idea is related, a container for instruments. And this could even become a more general purpose layer plugin with just one small modification: allow for note ranges instead of just one note per pad.

What functionality is missing along that line? Off the top of my head these are most obvious:
- The instrument note range idea (e.g. #1792) to limit which notes the instrument reacts to.
- Disjoint sets of instruments in the B&B editor (#453) 
- Saving B&B presets (one set at a time, obviously)

In broad terms it should then be mostly a matter of broadcasting the note data from the track onto all the instruments once those few points are solved.

And a few negative points:
- @Reaper10, I think most of us got the point from one instrument plugin mockup. You provide 9, all with the exact same modifications.
- How is changing the root note supposed to work if the piano is removed from the instrument UI? If e.g. a pad should react on an incoming C5 but you want to send A4 to the instrument...

**Comment by rubiefawn** [comment]
I think implementing it as a plugin would be more useful. Again, many MIDI files have all percussion in the same MIDI track, and if this is realized as a plugin there will be no need to separate the percussion tracks (which takes a very long time.)
But I can't code so whatever you devs decide on will be okay. I would just prefer a Drum Rack.

**Comment by tresf** [comment]
> many MIDI
files have all percussion in the same MIDI track, and if this is realized
as a plugin there will be no need to separate the percussion tracks (which
takes a very long time.)

:+1:

**Comment by softrabbit** [comment]
> if this is realized as a plugin there will be no need to separate the percussion tracks

That option wasn't really in my mind, as I said _"broadcasting the note data from the track onto all the instruments"_. Yes, it could be easier to get all the notes into a plugin which then hosts other plugins, but it shouldn't be impossible in some other solution either.

**Comment by Reaper10** [comment]
After Add support for acidized samples #2154 is added a user can use one AFP / sample on all 16 pads.

**Comment by tresf** [comment]
Please stop cross-post bumping.

**Comment by tresf** [comment]
@Reaper10 I'd like to reinforce a few things here... 

 1. This is probably the most comprehensive enhancement you've written (thanks).
 2. It is still a disaster and took about 15 minutes of cleanup because you are failing to exercise a standard level of readability to your bug reports.

I just cleaned up the original post and here are the results:

**Before**
 * 10 pages long

    ![screen shot 2015-09-12 at 12 33 22 pm](https://cloud.githubusercontent.com/assets/6345473/9832526/3f137692-594b-11e5-9fdf-872557a5ce4c.png)

**After**
 * 3 pages long (still too long, in my opinion)

    ![screen shot 2015-09-12 at 12 34 19 pm](https://cloud.githubusercontent.com/assets/6345473/9832528/5772fcb2-594b-11e5-9f79-0fa675100fcc.png)

This sets a bad example for our tracker and creates topics that are simply too long to read.  We have too many developers working toward progress and change to allow our tracker to become a garbage collector of @Reaper10's wishes.  We all have wishes, and if you want them to come true, you should show more appreciation to the tracker.

**Comment by Reaper10** [comment]
i'm sorry I just can't seem to get this right.:(

**Comment by Reaper10** [comment]
I forgot to add the ZynAddSubFX & VeSTige plugins to the Plug-in Modules list Plug-in Modules to Impact Zone plug-in.

**Comment by tresf** [comment]
Closing this as it is wishful thinking, but no plan exists to actually code and implement.  Please reference or re-open if status changes.
