### ISSUE TITLE
Jack audio support on windows

### ISSUE THREAD

**Issue by swellbastion** [LMMS/lmms#2136]
I don't know if this is the proper place for a feature request like this, but eventually it would be cool to have [jack](http://jackaudio.org/) support on windows. There are obviously much more pressing things to work on though.

**Comment by tresf** [comment]
Disclaimer: I'm not a Jack user, so I'll need some help from actual Jack users that feel comfortable enough with using it on Windows to explain how well it works.  Here's a [download link](https://github.com/tresf/lmms/releases/download/experimental/lmms-1.2.3-733+g2f7b60806-mingw-win64.exe) until the PR becomes available.

Jack's own website seems to be quite dated, the instructions reference -- what appear to be an older version of Jack -- asking users to call commands like `regsvr32` as post-install steps for `.dll`.  I didn't do any of these steps and I'm fairly comfortable starting that they're not needed.

Building Jack support into Windows hypothetically requires two steps: 1. Enabling it in CMake 2. Instructing mingw (or MSVC) to find the header.
* Assuming we target mingw, typically, we'd leverage an [mingw32 build of Jack](https://launchpad.net/~tobydox/+archive/ubuntu/mingw-w64) however one doesn't exist.  That's OK.
* Fortunately thanks to [weak-linking](https://github.com/LMMS/lmms/issues/3719#issuecomment-340498603) using the https://github.com/x42/weakjack project, we don't need to actually link against any libraries at build time.
* That said, since mingw is missing `jack/jack.h` as well, we need to copy the Linux version over.  Here's how I did that:
<details>
<summary>Show code</summary>

```bash
cp -R /usr/include/jack/ ~/lmms/build
```

```diff
 diff --git a/CMakeLists.txt b/CMakeLists.txt
index a3c83c1a4..411f7bad8 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -97,7 +97,6 @@ ENDIF(LMMS_BUILD_APPLE)

IF(LMMS_BUILD_WIN32)
        SET(WANT_ALSA OFF)
-       SET(WANT_JACK OFF)
        SET(WANT_PULSEAUDIO OFF)
        SET(WANT_SNDIO OFF)
        SET(WANT_SOUNDIO OFF)
@@ -105,7 +104,6 @@ IF(LMMS_BUILD_WIN32)
        SET(BUNDLE_QT_TRANSLATIONS ON)
        SET(LMMS_HAVE_WINMM TRUE)
        SET(STATUS_ALSA "<not supported on this platform>")
-       SET(STATUS_JACK "<not supported on this platform>")
        SET(STATUS_PULSEAUDIO "<not supported on this platform>")
        SET(STATUS_SOUNDIO "<disabled in this release>")
        SET(STATUS_WINMM "OK")
@@ -433,8 +431,10 @@ ENDIF(NOT LMMS_HAVE_ALSA)

# check for JACK
IF(WANT_JACK)
-       PKG_CHECK_MODULES(JACK jack>=0.77)
-       IF(JACK_FOUND)
+       
+       # PKG_CHECK_MODULES(JACK jack>=0.77)
+       IF(TRUE)
+               INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR})
                IF(WANT_WEAKJACK)
                        SET(LMMS_HAVE_WEAKJACK TRUE)
                        SET(WEAKJACK_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/src/3rdparty/weakjack/weakjack)
```
</details>

A more permanent approach is to use the jack source code as a submodule.  An example of a very similar technique (using a weak linked version of Carla) can be found [here](https://github.com/LMMS/lmms/pull/4813/files). 

Here's Jack working on Windows.  Any testing using the download link above is greatly appreciated.


![image](https://user-images.githubusercontent.com/6345473/96216191-afb97f00-0f4d-11eb-8490-f5654a035c8f.png)

Pining @falkTX since he asked about this in #4654.

**Comment by tresf** [comment]
Done via #5716.  Any builds from master here forward will have JACK support built-in.
