### ISSUE TITLE
Master branch can't find ladspa effects 

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms#2159]
In the master branch, LMMS does not seem to find any of the ladspa effects that come shipped with it. It finds all my external ladspa's from the hard-coded places fine (`/usr/lib/ladspa` and `~/ladspa`). 

I suspect that this has something to do with #1908, since that was the only major thing that has changed about the ladspa paths that I can think of. 

I also can't seem to change my ladspa paths in the settings dialog. They seem to reset to their default value whenever I restart LMMS.

**Comment by Wallacoloo** [comment]
I have similar issues. In my case, my ladspa path in the settings dialog looks like `/usr/local/bin/../lib//ladspa/,/home/colin/lmms/plugins/ladspa/`, and I cannot modify it. The double slash looks indicative of a possible error somewhere. Indeed, if I symlink `/usr/local/lib/ladspa` to `/usr/local/lib/lmms/ladspa`, then LMMS can properly find the effects.

I'm thinking [ConfigManager.cpp:380](https://github.com/LMMS/lmms/blob/31368699ec7d8d1bfb11db683203e78aea39f44e/src/core/ConfigManager.cpp#L380) is in part to blame for this incorrect default path. The line looks like:
```c++
m_ladDir = qApp->applicationDirPath() + '/' + LIB_DIR + "/ladspa/";
```
and is #if'd in order to only run on Linux. For apple, we have
```c++
m_ladDir = qApp->applicationDirPath() + "/../lib/lmms/ladspa/";
```

It's hard for me to trace back the definition of LIB_DIR completely, but it appears to be calculated on [DetectMachine.cmake:40](https://github.com/LMMS/lmms/blob/f40329946024b93c92bdd9c2c46b8390a027d393/cmake/modules/DetectMachine.cmake#L40) and then sent into the compiler on [CmakeLists.txt:41](https://github.com/LMMS/lmms/blob/31368699ec7d8d1bfb11db683203e78aea39f44e/src/CMakeLists.txt#L41)

**Comment by musikBear** [comment]
> LMMS does not seem to find any of the ladspa effects that come shipped with it.
On @Umcaruje your 1.1.3.01.07.15 binary Master, i have noticed that it takes ~ 3-5 times longer, to open the FX-collection (both on mixer fx-tab, and on preset-fx-tab) , compared to time on  the 1.1.3 -Could the prolonged time be related to this?
