### ISSUE TITLE
windows -Better crash info for vst

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2177]
im sitting with Master 01.07.15 and have some crashes, and i realize that those are not easy to 'locate'
Lmms throw a **RemoteVSTPlugIn had an issue and have to close** message, but *what* vst-plugin?
That is not possible to see, and then it is not easy to figure out where this problem came from.
If somehow the error could contain the name of the failing vst, then it would be much more useful to user.
I tagged 'windows' in topic, because i do not know how this error behave in other OS -Maybe this is general?

**Comment by tresf** [comment]
Yes, better overall windows debugging in general is what we need.

This is a two-step process...

 * First is making a separate debug installer downloadable for our users.
 * Second is finding a way to capture the debug symbols on Windows so that they can be provided in a bug report.

Another item that would help this is to get lmms compiling on Windows, which we've [started but never got working](https://github.com/tresf/lmms/wiki/Compiling-lmms-(on-Windows)).

-Tres

**Comment by tresf** [comment]
Closed per request of OP via: https://github.com/LMMS/lmms/issues/2400#issuecomment-147688479

> This is already fixed, as seen in the image (in fact i would close 2177 because of that?)
