### ISSUE TITLE
is it possible to re-include "Silva-Elves Call" to the coolsongs folder in a future LMMS release?

### ISSUE THREAD

**Issue by kLik-kLak** [LMMS/lmms#2239]
I just realized it wasn't included in 1.1.3 and it really broke my heart, that song was so mellow and chill and gave me some spacy vibes...

**Comment by grejppi** [comment]
The file [still exists](https://github.com/LMMS/lmms/blob/4a0c78387e2cb67605abe2314cf365b4fa546377/data/projects/OldStuff/Silva-ElvesCall.mmp) in the history of this repository, but it is unlikely to be added back in the distribution.

**Comment by tresf** [comment]
@grejppi is completely right, this was removed for a reason per #1074.  If you have objections, you'll have to find a way to resurrect it.

We have an initiative to move all of our default songs to a CC0 license.  We've touched base on this in #1273.

Feel free to continue commenting on this bug report, but we're going to close it as `won't-fix` since the removal was planned, agreed upon and justifiable.
