### ISSUE TITLE
New LMMS Toolbar

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2247]
The new toolbar is just like the LMMS side toolbar.
<img width="32" alt="capture" src="https://cloud.githubusercontent.com/assets/8137561/9156776/45d33efa-3eab-11e5-8c05-6f90ec83aee2.PNG">

It's found at the bottom of the LMMS window
<img width="512" alt="new toolbar gui" src="https://cloud.githubusercontent.com/assets/8137561/9156785/8167ea92-3eab-11e5-8f23-8851669fc99e.PNG">

<img width="246" alt="new toolbar" src="https://cloud.githubusercontent.com/assets/8137561/9156787/96cd7e38-3eab-11e5-8e8a-99e8537ebf34.PNG">

It's a hub for 
1. midi clip editor window
2. automaiot clip editor window
3. contoller rack window and lfo contoller windows
4. mix and plugin windows
5.audio editor for when LMMS Add support for acidized samples #2154  and when LMMS adds Change colors for SampleTrack #816  a user can use it to Change colors
When a user clicks on a clip the toolbar will auto open the right editor.

**Comment by grejppi** [comment]
What is wrong with the existing toolbar?

![toolbar](https://cloud.githubusercontent.com/assets/772336/9156852/fca7bd28-3ef0-11e5-9383-17816492c70c.png)

**Comment by Reaper10** [comment]
it's just an idea to help with New UI Concept - Single Window #1911

**Comment by Wallacoloo** [comment]
I'm with @grejppi.

We especially don't need a **third** toolbar. That's just laughing in the face of anyone with a small display.

Furthermore, pretty much all UI studies have found that the *least* effective place to put a menu is at the bottom of the screen, mainly because the primary content is usually concentrated in the upper portion of the display (often by choice, since we all read top-down) and this results in much longer mouse movements to and from the menus.

I see literally no motivation behind this suggestion.

**Comment by Umcaruje** [comment]
I agree with @grejppi and @Wallacoloo, this is a pretty pointless request since we already have a toolbar.

>it's just an idea to help with New UI Concept - Single Window #1911

Then write this idea there as a comment, stop cluttering up the issue tracker. Closing.
