### ISSUE TITLE
JUCE is a powerful, open-source C++ audio engine

### ISSUE THREAD

**Issue by mamarilmanson** [LMMS/lmms#2248]
Hello... I just stumbled across this... I don't know if this is of any help... :)

http://www.juce.com/

**Comment by tresf** [comment]
Thanks, yes we're aware of the JUCE project (and it is released under a compatible license).  We may decide to adopt this in the future, but that would be a larger initiative.  Closing as invalid for now.  I would recommend "feeler" posts are done on our forums or our mailing list so that it reaches a larger audience.

Furthermore if you or someone you know has experience with this library, C++ or coding in general or anything that you think you could help the LMMS project with please feel free to introduce yourself and get acquainted.  We're always in need of help! :+1:

**Comment by mamarilmanson** [comment]
what does "feeler" means?

:+1:

**Comment by tresf** [comment]
> what does "feeler" means?

http://www.urbandictionary.com/define.php?term=feeler
