### ISSUE TITLE
Settings revert to Dummy (no sound output) without allowing changes

### ISSUE THREAD

**Issue by Firsttimemusicproducer** [LMMS/lmms#2274]
Every time I open up the LMMS application, the sound output reverts to Dummy (no sound output). When I attempt to make changes, it tells me I may have to restart the program for the changes to take effect. Since the changes do not take effect, I assume I must restart the program, but upon returning it has reverted itself back to Dummy (no sound output) effectively preventing me from making any changes to my output settings. I have attempted every fix I can find, and each one works the very next time I open the application, however closing and re-entering the program results in the problem reoccurring.

**Comment by Firsttimemusicproducer** [comment]
I am experiencing this problem on Windows 8.1 Pro

**Comment by tresf** [comment]
@Firsttimemusicproducer can you try a few things:

1. First, try to use SDL

If SDL doesn't work, rename your settings file:

1. Open `cmd`
2. mv %USERPROFILE%\.lmmsrc.xml %USERPROFILE%\.lmmsrc.xml_bak

If you get a message "Access denied" can you browse to %USERPROFILE% and show hidden files and try to rename it manually?

**Comment by musikBear** [comment]
> and try to rename it manually?

@Firsttimemusicproducer You wont be able to rename, but you can just *move* it to any folder, and that will also work.
Firsttimemusicproducer, This is explained at least 5 times in LMMS forum already.
-please open an account on forum, and post ordinary help requests **there**, because this resource (gitHub) is meant for real acknowledged *bugs* that need developers to fix, and 'simple' help or troubleshooting questions just strangle the process, flood gitHub, and hamper the development 
Here is the correct place for help requests :+1: 
http://lmms.io/forum/viewforum.php?f=7

tyia.

suggest Closed.

**Comment by tresf** [comment]
Agreed with @musikBear.  Please continue to comment here for help, but support requests are best suited for the forums or mailing list.
