### ISSUE TITLE
Horizontal scrolling in Song Editor

### ISSUE THREAD

**Issue by kmouse** [LMMS/lmms#2275]
My trackpad allows me to horizontally scroll on some applications. Do you think LMMS should include this feature, or does this not have enough demand?

Edit: Apparently I can horizontally scroll in the piano roll, but not in the song editor. Should we make this consistent?

**Comment by tresf** [comment]
@kmouse I'm not sure we have any logic specific to prevent this.  Here's a similar article:

https://forum.qt.io/topic/7512/problem-with-horizontal-wheelevent/7

**Comment by unfa** [comment]
@kmouse I agree.

Also it'd be great of I could use the mousewheel tilting to pan the session and editors like piano roll, mixer, automation editor...

**Comment by Wallacoloo** [comment]
What is "mousewheel tilting"?

**Comment by tresf** [comment]
> What is "mousewheel tilting"?

Left/right scrolling.

**Comment by tresf** [comment]
I've tested this with a tilt wheel.

What doesn't work:
 * Song Editor

What does work
 * Everything else

This should be a relatively easy change, once we find out where the horizontal scroll events are getting consumed.

What is a bit unique about the Song Editor is that it encompasses a `TrackContainerView` which [tries to detect if a mouse event is `isAccepted()`](https://github.com/LMMS/lmms/blob/master/src/gui/TrackContainerView.cpp#L506) and if not, it passes its events up to the `QScrollView`.  My hunch is that the mouse event is not properly being detected rejected and being consumed by the child object.

Will experiment and post back.

**Comment by tresf** [comment]
The SongEditor doesn't seem to respond at all to WheelEvents, so they're all done manually.

First instinct was to use `TrackContainerView` but TrackContainerView is purposefully set to always hide the horizontal scroll bar.

After forcing horizontal scroll bar, two appeared and the TrackContainerView's would still be grayed out.

This is because left/right scrolling is exclusively done on the SongEditor.  Left/right scrolling is actually already enabled using the `Shift + Mouse Wheel` combo.  So I just added the Left/Right wheel to the same line of code.

Here's a visual of the scrollbar ownership.

![image](https://cloud.githubusercontent.com/assets/6345473/9421898/fa4f8f2e-484b-11e5-8ace-eba477f06fdd.png)
