### ISSUE TITLE
Cloning B+B pattern changes positions of all patterns after restart

### ISSUE THREAD

**Issue by Tomaqa** [LMMS/lmms#2277]
Hi,
I've experienced some troubles recently when I had to reorganize all patterns in my B+B editor.
I found out that bad things happen when I clone a B+B editor pattern in Song editor. Right after this, the order of patterns in Song editor does not match with the order in B+B, because the pattern which was after the cloned one is suddenly at the end of patterns' list in B+B. At this moment, when I save the project, restart LMMS and load again, now NAMES of patterns match, but pitch of patterns do not and Song editor plays completely different 'song'. Quite pity..
I tried this in a new project and it did the same.

LMMS: v1.1.3
kernel: v4.1.4-1
Running on Arch Linux.

**Comment by musikBear** [comment]
I have a little trouble understanding..
You have **instruments** in Beat&Baseline-editor?
These B&Binstruments plays a tune?
You *clone* one such BB**line** in song-editor (resulting in a new BB-line in BBeditor)
That will **change the tune** in song-editor-playback?
If so, That does not happen for me..

**Comment by musikBear** [comment]
mmm... one kind of valid question actually exists 
*Why at all have a feature for cloning BB-tracks in song-editor*
Where is it useful?

**Comment by Tomaqa** [comment]
Well, I don't know about a different way how to do that, e.g. in BB editor.
It's useful when I want to clone all 'boxes' in song editor and also (especially) the pitch from BB editor, then it's simple to use it almost the same - only a little modifying it.
It's two things together, but I dunno how to only clone a BB track outside of song editor.
I hope we understand one another ..

**Comment by tresf** [comment]
> mmm... one kind of valid question actually exists 
Why at all have a feature for cloning BB-tracks in song-editor
Where is it useful?

For cloning a pattern and modifying it. 

@Tomaqa you don't need to justify your use case. :+1:

**Comment by musikBear** [comment]
> For cloning a pattern and modifying it. 

ya.. but that could actually be achieved in a different workflow:
From BBeditor, create a new BBline
* Right click the pattern you need to work on
* choose copy
* open the line you just created, and point to the right preset
* right-click, and use insert
Now you have the same result, as if you have 'cloned' from within song-editor, and you can make any change you like in the new BBline.
I am not saying that this is a great method, because a user might have to copy/paste several times, but it is possible ..
..Bit if this strange thing wont die... -there actually is this option 

@Tomaqa I do not **at all** try to diminish your great bugfind -im only thinking 'around' the problem :)

**Comment by tresf** [comment]
> Right click the pattern you need to work on choose copy

That works for one pattern at a time.  What if you have 100?  

> because a user might have to copy/paste several times, but it is possible ..

Right.

**Comment by zonkmachine** [comment]
#2470 Is a duplicate but has slightly more info on the issue so I'm closing this one as duplicate instead.
