### ISSUE TITLE
Newbie mode for piano roll

### ISSUE THREAD

**Issue by liftarn** [LMMS/lmms#2280]
It would be nice to be able to have labels on all keys in the piano roll instead of just one.

**Comment by musikBear** [comment]
lmms **kind of** have it, but it is very confusing (imo)
Go into 
Settings | General settings
Find option & enable
"Enable note label in piano roll"
Restart lmms
You now have considerate more than you begged for / need, and you will develop a headache in ~an hour (imo) 
Subtle labels are missed, and 'imo' is not a shared point of view :p

**Comment by liftarn** [comment]
Yes, I see... Yes, I was thinking more like extra text on the keys, but this is something like it.
Thanks!

**Comment by michaelgregorius** [comment]
For anyone interested: this is how it currently looks like.

![2280 - current note display](https://cloud.githubusercontent.com/assets/9293269/9369736/8452c3b2-46cb-11e5-9a92-3a9c3691ff41.png)

The labels also stay in place when you move the scroll bar. Kudos if you only get a headache after one hour. :wink:

I have tried to paint labels for the other keys directly on the keyboard (like for the C keys) but it's more complicated than expected because the keys have different heights.

**Comment by musikBear** [comment]
![notelabels](https://cloud.githubusercontent.com/assets/6662066/9381889/f6095a3c-473b-11e5-8b26-13f403b14704.png)
*this* is all that was needed - the 'sharps' are (kind of) logical in respect to the whole-notes, but the last time i suggested this, someone demanded labels on sharps too, and then things gets seriously messy

**Comment by tresf** [comment]
Closing as invalid since we have a suitable feature.  We obviously have room for improvement here, as well as 1,000 other UX areas.  Feel free to create a mockup and start coding. :+1:

**Comment by michaelgregorius** [comment]
@tresf Coded. :)

**Comment by michaelgregorius** [comment]
Implemented with #2285.
