### ISSUE TITLE
Piano-roll: Volume represents Velocity

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2316]
lmms uses a wrong word for the bars in piano-roll (panning/volume) *volume* is in fact **velocity**
Because vol. can be changed *over the duration of a note*! 
velocity cant, that is *exclusively for the attack* !
in lmms volume changes over time, is implemented as a **envelope feature**, and that is 100% correct!

I propose that *volume* is changed to *velocity*

**Comment by Wallacoloo** [comment]
The relevant lines of code to changes are probably all in [PianoRoll.cpp](https://github.com/LMMS/lmms/blob/master/src/gui/editors/PianoRoll.cpp):

Line 186:
```c++
m_nemStr.push_back( tr( "Note Volume" ) );
```

Lines 2063-2065:
```c++
//! \todo display velocity for MIDI-based instruments
// possibly dBV values too? not sure if it makes sense for note volumes...
s_textFloat->setText( tr("Volume: %1%").arg( vol ) );
```

Line 3249:
```c++
s_textFloat->setText( tr("Volume: %1%").arg( nv[0]->getVolume() ) );
```

Line 3643:
```c++
new_val = QInputDialog::getInt(	this, "Piano roll: note volume",
					tr( "Please enter a new value between %1 and %2:" ).
						arg( MinVolume ).arg( MaxVolume ),
					(*nv)[0]->getVolume(),
					MinVolume, MaxVolume, 1, &ok );
```

(I may have missed some)

As can be seen, somebody left a comment about using velocity instead of volume, and the comment leads to the possibility of displaying "velocity" in normal cases, but instead displaying "volume" when we know that the velocity is actually just modulating the volume directly.

I'm not sure how easy that is - I think we could essentially do something like:
```c++
if (plugin->isBuiltin() && plugin->isVelocityMappedToVolume())
    // use "Volume" label
else
    // use "Velocity" label
```

The `plugin->isBuiltin()` conditional is required because I don't imagine there's any way to ask e.g. a VST plugin if it maps velocity to volume.

Is this a good idea? Or would it be better to just universally use "Velocity" even in the cases where we know velocity = volume?

**Comment by Spekular** [comment]
I'd say always use velocity, since it's entirely valid for velocity to only
affect volume. We can update documentation instead to specify that velocity
= volume on internal plugins, until/unless we add another use.

**Comment by musikBear** [comment]
@Wallacoloo 
holy cra.. ..nberries  ..i thought it was one single label :p 
Yes, i agree with @Spekular -velocity would be usable overall, but not all users would know what it mean. I will add a small explanation in wiki, at a suitable place.

**Comment by Wallacoloo** [comment]
Alright, so a more difficult problem to solve is that internally, the code conflates velocity with volume. That is, all the functions/types/variables are named things like `Note::getVolume()` of `volume_t vol = ...`. That's going to take some effort to revise.
