### ISSUE TITLE
LMMS Needs a SFZ file player plugin

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2369]
I'm asking for a simple SFZ file player plugin like your sd2 plugin. This is for those LMMS users who a lot of SFZ they want to use. There is all ready a free SFZ file maker soffware.  http://mildon.me/sfzdesigner

**Comment by tresf** [comment]
Closing as wontfix for now.  Please feel free to start discussion on the forums about the feasibility of this, gather some libraries and API docs to assist, or continue discussion here, but this bug will remain closed unless someone with the knowledge can step up and integrate.

**Comment by Reaper10** [comment]
This is all can find for now, I'll keep looking
http://www.sfzformat.com/index.php?title=Main_Page

**Comment by Reaper10** [comment]
did help at all?

**Comment by Reaper10** [comment]
http://api.256file.com/sfzmaker.0.9.1409.exe/en-download-55308.html
https://github.com/search?utf8=%E2%9C%93&q=synthclone+
https://code.google.com/p/synthclone/
You may be able to use the libraries and API from here_^

**Comment by Reaper10** [comment]
http://svn.linuxsampler.org/cgi-bin/viewvc.cgi/linuxsampler/trunk/src/engines/sfz/

**Comment by tresf** [comment]
@Reaper10:  the last link helps.  The synthclone links seem to be for SFZ creation, not playback.  The linuxsampler code will likely help, thanks.

http://svn.linuxsampler.org/cgi-bin/viewvc.cgi/linuxsampler/trunk/src/engines/sfz/sfz.cpp?view=markup

Here's a good KVR conversation about SF2 vs. SFZ.

Please cleanup your posts (delete most of them please), and adjust the original bug report to better describe the feature.  Also fix the title because `LMMS NEEDS ICECREAM` is a lie.  `REAPER10 WANTS ICECREAM` is the truth and the truth is irrelevant to the bug report.  `SFZ Plugin Support` would probably be a good title.

**Comment by Reaper10** [comment]
@tresf  hope that's better I'm tiring.

**Comment by tresf** [comment]
Getting there... Cleanup the bogus links please.  The ones I linked are a good starting point we can add more as needed.

**Comment by Reaper10** [comment]
I have an idea for the name for the SFZ plungin it's Doppelgänger https://en.wikipedia.org/wiki/Doppelg%C3%A4nger.
After all FSZ files are a sample copies of a instrument.
FYI i

**Comment by tresf** [comment]
Stop bumping closed threads and stop naming plugins you haven't (and won't) create.  Also, stop working on GUI ideas.  SFZ, Giga, SF2 are patch instruments and if we build the software properly, we can introduce them all as a single instrument patch plugin rather than having a different name and a different GUI for each.
