### ISSUE TITLE
choir synth LMMS instrument

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2372]
I just want choir synth instrument built in into LMMS that the reason for SID & Monstro pulse width speed, pulse width modulation & amount knob #2301 & LMMS qustion #2305. This is for those who don't have a choir synth vsti and they don't know where to find one. Or those who are like me who try to just use rhe LMMS Instrument Plugins to speed up my work flow being that vsts are slow to load up. Besides that my pc with all of my vsts crashed and I can't remember I got them from. This will all so help new LMMS users.

**Comment by tresf** [comment]
Stop opening a new bug a day.

**Comment by Reaper10** [comment]
Ok I will, will you consider reopening this one?

**Comment by Umcaruje** [comment]
>Ok I will, will you consider reopening this one?

No.

ZynAddSubFX has some good choir presets and its well suited for that purpose.

**Comment by tresf** [comment]
> Ok I will, will you consider reopening this one?

The opening line "I JUST WANT A CHOIR SYNTH" is a bad opening line and this is a warning that further spamming of our issue tracker will get you banned.  We read and process every single bug report and you are misusing it.

We welcome new feature enhancement requests, but you have singlehandedly requested 85 in one year, most of which are general ideas and have no resolution in sight.  We have over 400 valid bug reports and we cannot tolerate the frequency and lack of quality that you bring to our tracker.

If you want new features, jump in and help.  Do more to help us instead of asking more from us.

The next time we close a bad issue request from you or have to warn to stop bumping your own request, we will issue a final warning.  The final offense will be a permanent ban from our GitHub issue tracker.

**Comment by StakeoutPunch** [comment]
I will add to what Tres said by saying again that this is an ISSUE tracker, not a forum. We do have a forum though! Feel free to post ideas there as most of the people on this tracker are also on the forum.
http://lmms.io/forum
