### ISSUE TITLE
Can't load any VST in specific laptop

### ISSUE THREAD

**Issue by DeathSuperMario** [LMMS/lmms#2374]
On my computer with windows 8 I can do that without any problems.
Also on my mothers laptop with windows 7. On My Fujitsu siemens amilo with win7 ultimate I Can't load vst's in LMMS.
I think that problem is in RemoteVstPlugin. I added missing dll's in system folder. No error message when I start RemoteVSTPlugin.exe
I still can't load any vst with vistage in LMMS. Help :(

I can't load any vst. Name one and I cant load that. LMMS shows that error message ....under linux...contact developer. 
Maybe I need to start using Linux? I tried 32-bit cheapotone.dll and comboV.dll and comboF.dll and some other VST's. I can get 1gb more ram thats it. So that I have 2 gb ram. I have right now only 1GB ram. I'm using 32-bit LMMS 1.1.3
.
Also on https://lmms.io/forum/viewtopic.php?f=7&t=3631&p=12076#p12076

**Comment by tresf** [comment]
Please perform the following steps:

 * Remove all DLLs and EXEs that you have manually copied.  Do not copy any more to System32, they should never be copied there for use of our software.
 * Rename `%USERPROFILE%\.lmmsrc.xml`.  This is your settings file and is a good troubleshooting measure.
 * Uninstall LMMS from Add/Remove Programs
 * Delete the LMMS folder from `%PROGRAMFILES%\LMMS`.  If it does not delete, reboot and try again.  If your PC is 64-bit, this can change.  Just let us know.
 * Reinstall 1.1.3 and report your findings.

**Note**  We do not normally take support tickets in our tracker (we advise to use forums for that), so this will be closed out as a support request however please feel free to continue conversation here until this issue is resolved.
