### ISSUE TITLE
Logos for effect plugins

### ISSUE THREAD

**Issue by BaraMGB** [LMMS/lmms#2388]
Our native effect plug ins can have their own logo. This logo is shown in the plugin browser:

![effektbrowser](https://cloud.githubusercontent.com/assets/6502580/10162290/8fdf76b8-66aa-11e5-9dc3-0ed4913dc843.png)

The file name is "logo.png" and is stored in the plug in source file folder. Almost all of our plug ins got's this little penguin as logo. IMO we need new logos for every plug in.

**Comment by Reaper10** [comment]
The logo could be a screenshot of the plugin.

**Comment by IvanMaldonado** [comment]
Is anyone working on this ? I'd like to make some designs for these plugins

**Comment by tresf** [comment]
No one is working on this.

**Comment by SimoneIervasi** [comment]
Sincerely, i don't like the Tux image (it appears also when i use VSTs), it's a bit unprofessional, obviously it's only my opinion

**Comment by jackokring** [comment]
@Reaper10 the screen shots of some of the plugins look very boring. A very standard control set is generated. I think it is possible to make a custom UI, but none that I've opened can be called good lookers. (nice sounds though). At that resolution it looks like Donald Duck and a grey alien had an abduction love child, and sent it to earth in a black space (s)hip suit. Yes but :+1: for some variety.

Perhaps some indication (visually) of stereo/mono, and keyword to icon layer such as 'delay' to clone faded copies of the icon in the background ...

**Comment by tresf** [comment]
@Reaper10 is no longer allowed to post on our message board, please refrain from tagging him.

> Sincerely, i don't like the Tux image (it appears also when i use VSTs), it's a bit unprofessional, obviously it's only my opinion

Then change it. We're open source. :+1:

**Comment by JackHack96** [comment]
What do you think of this?
![schermata del 2015-11-29 20 09 03](https://cloud.githubusercontent.com/assets/3611330/11459368/82187164-96d5-11e5-8eac-a47e98535aa3.png)

**Comment by Umcaruje** [comment]
@JackHack96 That's a pretty neat icon you got there!

Though I'm not so sure it fits into the current gradient-full theme. It'd fit a lot better into the 'modern' theme though (#880) .

**Comment by tresf** [comment]
> What do you think of this?

It is fine, but remember that each plugin supports its own graphic, so we should consider personalizing the plugins as well, which is what the original post aims to accomplish.

**Comment by JackHack96** [comment]
Yes, I've seen.. Well that's a general icon... I'm not good at graphics so I can't design icons by myself :/

**Comment by RebeccaDeField** [comment]
Nice work @JackHack96. What if we design a standard plugin icon and then add all of the other icons as they are designed?

I don't have time to design all of the other plugin icons right now, but I was already going to make one to replace the tux so if someone wants to use that SVG to create a version that fits for the default theme that might save some time.

**Comment by JackHack96** [comment]
Ehm, I'm sorry but I'm not the author of that icon :(
I only substituded it with every tux image I found in the plugins folder, and then I compiled LMMS with that resources, for seeing how it was looking :)
Here is the link to the icon https://www.iconfinder.com/icons/376363/audio_control_equalizer_mixer_slider_volume_icon
Maybe in the future I could try to contribute to LMMS by developing something, because I'm now studying IT at university (not now, I don't know anything about Qt..)

**Comment by RebeccaDeField** [comment]
@JackHack96 Still, thanks for putting it together. ;)

**Comment by tresf** [comment]
> Ehm, I'm sorry but I'm not the author of that icon :(

Neither is anyone here, I'm not sure how this is relevant.

> I only substituded it with every tux image I found in the plugins folder, and then I compiled LMMS with that resources, for seeing how it was looking :)

Right, because we hate the penguin, I get it.  Issue a pull request and abolish the penguin if it bothers you, but this isn't very helpful at all, it just replaces an non-descriptive icon with a new non-descriptive one.

>  I'm now studying IT at university (not now, I don't know anything about Qt..)

You knew enough to mention it.  Most here are self-taught.  Help where you can. :+1: 


> I don't have time to design all of the other plugin icons right now, but I was already going to make one to replace the tux so if someone wants to use that SVG to create a version that fits for the default theme that might save some time.

Perhaps we do something like `SWH` and `Calf` for now, or perhaps an LADSPA logo.  Many of the 100s of plugins we list are LADSPA plugins.  Some are native, some are VST.  Changing this icon can be incremental.  Most of the LADSPA plugins have some meta data that we might be able to use for getting a proper icon down the road (i.e. we have a few EQs, we have a few Compressors, we have a few High Pass and Low Pass plugins).  We might be able to sketch some generic but relevant artwork down the road (if so, I believe this will require a rewrite of the LadspaEffect class since it [only has a single icon for all plugins](https://github.com/LMMS/lmms/blob/master/plugins/LadspaEffect/logo.png)).
