### ISSUE TITLE
FileBrowser adds samples/presets to BB editor

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#2396]
Double-clicking an item (sample or preset) on the file browser previously added it to the song editor, rather than the beat+bassline editor. This situation has recently changed, however.

Is this new behavior intended or a bug?

**Comment by IvanMaldonado** [comment]
:kissing_heart:

**Comment by softrabbit** [comment]
It's the documented behavior in the user wiki, and that's for 0.4.12 and out of date. 

https://lmms.io/documentation/Side_Bar#Samples says:
> Double-click the sample to add it to the Beat+Bassline-Editor as a new track.

And it says the same under "Presets".

I'd claim this is where the adding to the BB editor happens: https://github.com/LMMS/lmms/blob/master/src/gui/FileBrowser.cpp#L607
Could be that the behavior has changed and then changed back to the old way. Let's see: 
```git log --follow -S getBBTrackContainer gui/FileBrowser.cpp```: One potentially relevant commit, but it's a rename without changes.
```git log --follow -S getBBTrackContainer gui/FileBrowser.cpp```: Two commits in 2008 that might be relevant, but that's not "recently" in my books.

**Comment by musikBear** [comment]
This actually a bad feature in it self. 
The problem comes if the user tries to do this with a VST-preset.
Lmms will load 2 orphan (not track-related) VST-GUIs, and some times these wont have a 'close-X', and i am not even sure the memory is freed, it they are closed.
(A one-shot test (1.1.3) with the *large* VST etheral-pads, even crashed lmms.)
I vote that this double-clicking simply is removed. We already has a really nice rigth-click-context-menu, where the user can allocate to either song, or BB-editor.
Double-click behavior is not necessary (imo)
(wiki need to updated as well,then)

**Comment by tresf** [comment]
This bug doesn't state whether or not it should be changed, it just asks whether or not it is intentional.  Yes it is.

BBEditor has been default for a very long time.  If you use the context menu, you can add to song-editor.  If you disagree with this, please issue a pull request modifying the behavior.

Closing as there is nothing to fix from the bug description.
