### ISSUE TITLE
AFP Multiple samples

### ISSUE THREAD

**Issue by thore00** [LMMS/lmms#2402]
I just thought it would be a nice feature to be able to have multiple samples in the Audio File Processor, and choose different files for different notes.

This way you can get samples from a real piano, and put them into one Audio File Processor instrument track. This means that the pitch won't bend and sound weird in the higher/lower notes.

I don't know how to do this, you can maybe allow for a maximum of 16 samples and have tabs in the top so you switch between them.

The way (that I know of) is that you'll have to create one track for each sample right now, making it hard to create a melody between all tracks.

Of course you should still be able to use only one sample and use pitch-bend.

Thanks for reading!

**Comment by tresf** [comment]
Thanks for the feedback.

@thore00 the piano example is done using the SoundFont capabilities already built-in.  Please look for a grand piano `SF2` file.  There are quite a few out there that will suit this need.  Unless you are on a Mac, SF2 support works just fine in our current stable version.

In regards to assigning a sample to each note, that is similar to a drum pad, which we have an open request for.  Marking this as invalid since we have SF2 support already and the concept of note-based samples/note-based instruments or midi-range limiting is already on the radar.
