### ISSUE TITLE
LADSPA plugins list in plugin browser only

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#2426]
@grejppi and @karmux have mentioned this but in master branch, LADSPA plugins list in the `LADSPA Plugin Browser`, but don't list in the `Add effect` dialog.

![image](https://cloud.githubusercontent.com/assets/6345473/10674658/2f479948-78ca-11e5-8ec3-e82f4e378ff2.png)

Furthermore, the default paths for these don't seem to be getting setup properly like the rest of the [`ConfigManager.cpp#L67`](https://github.com/LMMS/lmms/blob/master/src/core/ConfigManager.cpp#L67) config detection logic.  Pinging @Lukas-W as this may be related to some changes made to [data/plugins path enhancement which allows launching from the build directory (#1719)](https://github.com/LMMS/lmms/pull/1719).

To reproduce:

 * Build master branch
 * Launch LMMS from `build` directory
 * Observe all LADSPA plugins are missing from both the LADSPA Plugin Browser dialog as well as the Add effect dialog.

 * Edit LADSPA path preferences, add `build/plugins/ladspa/` to the LADSPA path
 * Launch LMMS from `build` directory
 * LADSPA plugins list in the Plugin Browser only.  The Add effect dialog is missing LADSPA plugins.

**Comment by michaelgregorius** [comment]
I think I have found the cause of the problem. After the build the LADSPA plugin `libladspaeffect.so` can be found under `${builddir}/plugins/ladspa/` instead of in `${builddir}/plugins/` where all the other plugins are. If I manually copy the file to the parent directory at least my system wide installed LADSPA plugins are displayed. I assume that if you do a `make install` the file is also copied to the correct directory. That's why it's working in installed builds but not in development builds that start the application directly from the build directory.

So, I guess the fix has to go somewhere in the CMake files.

**Comment by karmux** [comment]
I compiled LMMS on [7be47230e33e381991001f6f28b7468e877d581a](https://github.com/LMMS/lmms/commit/7be47230e33e381991001f6f28b7468e877d581a) that was suspected by @tresf and all is good there. All installed plugins were usable.

PR #2428 fixes most of the LADSPA plugins for me exept CALF & CAPS plugins (see my comment #2270).

**Comment by tresf** [comment]
@karmux yes, it seems like #2428 doesn't completely fix the issue as explained here:  https://github.com/LMMS/lmms/pull/2428#issuecomment-152291738.

Since they list properly in the plugin browser but not in the add effect dialog, we should explore another option than deploying them to a non-ladspa subfolder.

**Comment by michaelgregorius** [comment]
Seem like the only thing missing in the pull request is a configuration issue. Please see [my comment here](https://github.com/LMMS/lmms/pull/2428#issuecomment-152586876).

**Comment by tresf** [comment]
@michaelgregorius agreed. Calf, Tap and Swh LADSPA plugins list properly for me with this patch.  The configuration issue should be tracked as a separate issue.

**Comment by michaelgregorius** [comment]
Should be finally fixed when #2430 and #2432 are merged.
