### ISSUE TITLE
Plugin Dev, Looks Simple Enough, Sound Ideas

### ISSUE THREAD

**Issue by jackokring** [LMMS/lmms#2452]
I'm interested in developing a synth idea, although an effects plugin maybe easier as a first go. The amplifier plugin looks very easy, and I'm sure I know enough DSP to bend it up in spacetime. I have enough experience with Qt, and C/C++ is OK. A few questions, assuming that's a go on development (as hobby).
1. Is there any memory limits expected to be constrained to? I do enjoy small and fast code, but is there for example a shared delay buffer?
2. Is it possible for effects to receive the frequency being played through them (approx.)?
3. What sort of controls are supplied as standard, and is there a UI design guide?

**Comment by tresf** [comment]
Since Amplifier is an FX plugin and what you are describing sounds like an instrument plugin, I'd recommend cloning something like [`plugins/bit_invader`](https://github.com/LMMS/lmms/tree/master/plugins/bit_invader) and going from there.
 * Remember to add your plugin folder to [`plugins/CMakeList.txt`](https://github.com/LMMS/lmms/blob/master/plugins/CMakeLists.txt).
 * The plugin itself will have its own standard `CMakeLists.txt` which will need the appropriate directives.  We have a [`cmake` module which helps with this](https://github.com/LMMS/lmms/blob/master/cmake/modules/BuildPlugin.cmake).

From a UI perspective, there's no strict guidelines so as long as it fits in our instrument plugin window. 

From a memory/resources perspective, the plugins aren't loaded unless they are used, so as long as you free what you consume, there's some flexibility.  We have some [delay code already which you may be able to borrow from](https://github.com/LMMS/lmms/blob/master/plugins/Delay/DelayEffect.h).  We don't have an official policy on cross-linking against our built-in-code, but you can [read this recent work](https://github.com/LMMS/lmms/pull/1443) on an EQ plugin for some good question/answer.

**Comment by jackokring** [comment]
I've read more of the docs, and used the program some. A few more questions.

1. As the filter and envelope is applied to an instrument, an instrument can be considered to be an oscillator followed by an effects unit. (simplified but kind of true). Is it possible to put FX pre the LFO and filter? Or create an effects aux send to an instrument as an input to an instrument for modulation?

A lot of that seems possible with peak effects. Although peak detect algorithm low passing removes some modulation possibilities. A lot of what I'd like to develop is in this sense an effect as there are enough oscillator possibilities. I could develop a simple oscillator front for the post oscillation 'effect' to make it pre LFO/'VCA', but that would limit use in other chains of effects.

2. Which file should I look at to get a list of the control types I can use such as POT, digital UP/DOWN, LED switch, etc?

**Comment by jackokring** [comment]
As an example, I've written an instrument specification, which it is my intention to eventually write. 
[Synth.pdf](https://github.com/LMMS/lmms/files/40884/Synth.pdf) and I'd like to know if it sounds like the kind of thing the project needs.

**Comment by softrabbit** [comment]
> Is it possible to put FX pre the LFO and filter? 

At that point, every note is rendered in a separate buffer, they are mixed into one stream after the envelope and filter section. So any FX there would need to be instantiated per note. Not saying it's impossible, but I'd probably shoot for a small selection of effects tweaked just for that synth instead of the full LADSPA plugin chain treatment.

> Or create an effects aux send to an instrument as an input to an instrument for modulation?

Could be possible already, IIRC there's been a lot of improvement in the area of sample exact contollers. Could be as simple as removing the low pass filtering from the peak controller to feed any audio output to any knob. 

> As an example, I've written an instrument specification, which it is my intention to eventually write. 
Synth.pdf and I'd like to know if it sounds like the kind of thing the project needs.

Doesn't look like anything already in LMMS, so why not.

**Comment by jackokring** [comment]
> At that point, every note is rendered in a separate buffer, they are mixed into one stream after the envelope and filter section. So any FX there would need to be instantiated per note. Not saying it's impossible, but I'd probably shoot for a small selection of effects tweaked just for that synth instead of the full LADSPA plugin chain treatment.

Well I better add more dials to the spec ... :+1: 

> Could be possible already, IIRC there's been a lot of improvement in the area of sample exact contollers. Could be as simple as removing the low pass filtering from the peak controller to feed any audio output to any knob.

I looked over the source of peak controller, seems ok, I do wonder why the wet dry mix doesn't do a classic sustain peddle output mix though as RMS already calculated. (I hate non functional knobs)

> Doesn't look like anything already in LMMS, so why not.

Okie dokie.

**Comment by jackokring** [comment]
Just another few questions.

I had an idea to also develop later a peak controller style effect, but wonder if it is both possible to have settings on both the effect and the rack buttons (different sets due to context)?

What's Carla? Is it a default, or does it need extra libs? Giving some of the source a once over.

**Comment by Umcaruje** [comment]
>What's Carla? Is it a default, or does it need extra libs?

Carla is a versatile plugin host (http://kxstudio.linuxaudio.org/Applications:Carla), and for it to get built you'd need either to build it from github yourself, or install it using the [KXStudio repos](http://kxstudio.linuxaudio.org/Repositories).

**Comment by jackokring** [comment]
Carla is a bit like Buzz then.

I just discover the "missing" stk source :dancers: ... Umm, a whole C++ library. How nice of Stanford. Could come in useful further down the line, but not now.

**Comment by lukas-w** [comment]
Closing because this was a discussion back in 2015 and doesn't appear to track any specific issue or enhancement request.
