### ISSUE TITLE
OpenCL rendering

### ISSUE THREAD

**Issue by jackokring** [LMMS/lmms#2460]
Good for intense DSP.

**Comment by tresf** [comment]
Since many of the people here don't necessarily know what OpenCL is or why a music library would consider leveraging a graphics processing library to do audio rendering, perhaps you could spruce up this bug report a bit to briefly explain this idea, the work involved, the library dependencies and the benefits the project would receive.

Your bug titles shouldn't have a question them.  The title should simply be "OpenCL rendering".  All features are "future features", so that part is irrelevant.  In regards to mile-stoning a feature, feel free to put that into the description along with any other questions you may have.

Lastly, we have tags and milestones for organization so please use the title and bug description properly or the bug reports will be closed out.  We don't like spamming of our bug tracker and although I don't feel that is your intent, you've created 5 bug reports in 3 days.

 * MIDI routing - likely duplicate
 * Plugin Dev - cross posting screenshot in the wrong topics
 * Mallets bug - valid bug, thank you
 * Organic tooltips - valid bug, but needs cleanup
 * OpenCL rendering - valid enhancement request, poorly written.

Please take this feedback as constructive.  Your interest in the project is greatly appreciated, but we try to keep our bug tracker as clean as possible.

**Comment by jackokring** [comment]
Okie dokie I really must not have two bug reports on browser tabs at once. My bad.

There are some FFT libraries (for the Raspberry Pi I think) which use OpenGL (I think), and rendering sound could be seen as rendering to a 1 line graphic. The z axis in the 3D could be a frequency change of a wave supplied in a sound texture. Plus excellent pixel/sample interpolation.

**Comment by tresf** [comment]
> There are some FFT libraries (for the Raspberry Pi I think) which use OpenGL (I think), and rendering sound could be seen as rendering to a 1 line graphic.

Perhaps this?  http://www.bealto.com/gpu-fft.html

Here's a good stackoverflow discussion on the topic.... 
http://stackoverflow.com/questions/8158632/is-it-worth-offloading-fft-computation-to-an-embedded-gpu

The discussion has good points about CPU vs. I/O trade-off and what use-cases benefit more from the GPU FFTs.

**Comment by jackokring** [comment]
Excellent as calculation of FFTs is needed to calculate the coefficients of IIR and FIR digital filters, I think the figures also include shifting the data on and off GPU, so the overheads reduce with larger process chains on the GPU.

**Comment by Wallacoloo** [comment]
In order for GPU rendering to be worthwhile, we need to do a lot of batch rendering. i.e. group entire FX chains together, send the data to the gpu & do the processing just once before returning to the CPU codepath. This is opposed to rendering an EQ on the GPU, followed by a CPU implementation of a delay effect, and then switching context back to the GPU to apply reverb, for example. The problem with that is that you have a whole bunch of latency and also overhead just from transferring the memory.

What this means is that GPU rendering can't *really* be effective until we have all our rendering take place in just one or two locations (in code). Because of the current plugin architecture, where each plugin is responsible for managing its *own* rendering, it's impossible to do any sort of batch rendering.

Maybe in the future we can port all the plugins we ship with LMMS in a more descriptive format (e.g. as transfer functions), rather than just code that directly manipulates sample values, to faciliate this effort. But until then, I think the possibility of using gpu rendering is so far off that this isue should be closed until it's more relevant.

Don't get me wrong, I'd *love* to see gpu rendering someday. But this project just isn't designed to accomodate that possibility in its current state. Feel free to reopen for discussion if you disagree with the points I've made above.

**Comment by softrabbit** [comment]
> This is opposed to rendering an EQ on the GPU, followed by a CPU implementation of a delay effect, and then switching context back to the GPU to apply reverb, for example. The problem with that is that you have a whole bunch of latency and also overhead just from transferring the memory.

If the chain contained only OpenCL plugins, I assume it should be possible to transfer data only at the start and end of processing and run the plugins in succession?

> Maybe in the future we can port all the plugins we ship with LMMS in a more descriptive format (e.g. as transfer functions), rather than just code that directly manipulates sample values, to faciliate this effort. 

What I'm pondering is, _what should the data and code look like for OpenCL to shine_? I haven't yet grasped enough of OpenCL, but I imagine it to have some limitations. Like SSE and AVX are great at performing one operation on a bunch of data in parallel, i.e. something like lots of audio channels being run through the same filter or a buffer having a simple volume change applied, but a lot less useful for something involving branching or only 2 channels being processed.

**Comment by Wallacoloo** [comment]
> If the chain contained only OpenCL plugins, I assume it should be possible to transfer data only at the start and end of processing and run the plugins in succession?

Yes. If your implementation supports heterogeneous addressing, then plugins won't even care whether their input is arriving from the cpu's address space or the gpu's address space (I *think*). Otherwise, you would have two slightly different code paths for when a plugin is receiving input from cpu address space vs gpu address space (essentially, a conditional memcpy to move the memory into the gpu's address space). I've only ever used CUDA, not opencl.

> What I'm pondering is, what should the data and code look like for OpenCL to shine?

Minimize the number of interdependencies among your calculations. That is to say, if you're filling a buffer, `y` with 500 samples, `y[100]` should not depend on `y[99]` or any other output. This allows you to easily compute all 500 samples completely in parallel. Despite most gpus only having 50~200 execution units, you actually have to spawn 4-5 times this number of gpu threads in practice in order to fully saturate the gpu. This is because gpu schedulers rapidly swap out a thread for a fresh one whenever execution would instead be waiting for data that has to be fetched from main memory while they fetch that data in the background.

A common predicament is, given N inputs and M outputs, should you allocate N threads that each calculate one portion of *all* M outputs, or should you allocate M threads that each draw upon *all* N inputs? For example, I have an additive synthesizer that needs to add 500 sine waves and place the result into a buffer of length 1000. I can either allocate one thread per sine wave, or one thread per output sample.

Generally speaking, the latter is preferred (it's better to allocate one thread per output in this case). The reason being that if I have N threads that will potentially try to add a value to the *same* output, I either have to use atomic operations, or use a reduction algorithm. On the other hand, if I have M threads that will potentially try to *read* the same input, this is perfectly fine.

In general, if you can write your algorithm as `y[i] = f(x, i)`, where the time complexity of f is uniform in regards to i, and f is not stateful, it should be pretty straightforward to implement an efficient OpenCL equivalent.

You'll notice then that it's generally easier to port FIR filters and effects to an OpenCL environment than it is IIR filters, as in an IIR filter, `y[i]` is usually coded as a function of `y[i] = f(y[i-1], x[i])` (i.e. each successive output depends on the previous output), but a FIR filter is usually coded as `y[i] = f(x[i], x[i-1], x[i-2], ...)` (outputs depend only on inputs).

**Comment by Wallacoloo** [comment]
On a gpu, branching isn't *that* evil, but "divergence" is. Again, my experience is in cuda. But when you spawn 500 identical threads, the gpu actually runs 16 of these simultaneously in each execution unit. It's essentially doing a bunch of vector operations. As long as all 16 threads take the *same* branch, then there's not that much of a performance degradation. But if 4 threads take one branch and 12 take the other, then the EU is only issuing 4 FLOPS each cycle while the first branch path is being taken (the other 12 threads are idling), and then only issuing 12 FLOPS during the second code path.

You generally have some amount of control over which threads are grouped together, so you can arrange for divergence to be minimized.
