### ISSUE TITLE
New from template doesn't display all the template files

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2525]
The "New from template" menu entry doesn't display all the template files.
The templates from share/lmms/projects/Templates/ are not included in the list.
Tested on current lmms master repo.

**Comment by Umcaruje** [comment]
Could you care to send a screenshot? I just freshly compiled the master branch and all the default template files seem to be there: 
![screenshot from 2016-01-28 23 45 22](https://cloud.githubusercontent.com/assets/6282045/12661342/63011934-c619-11e5-829c-71361d590544.png)

**Comment by zonkmachine** [comment]
The default projects are there but not the ones you "Save as default template".

**Comment by zonkmachine** [comment]
It's all blank here too so I'm going to look into it. With one eye at least.

**Comment by zonkmachine** [comment]
@Umcaruje Git bisect has spoken! ff93b34dca06d0450007ec647f0744a6e8d918b0
```
:~/builds/lmmsBisect/lmms$ git bisect bad
ff93b34dca06d0450007ec647f0744a6e8d918b0 is the first bad commit
commit ff93b34dca06d0450007ec647f0744a6e8d918b0
Author: Umcaruje <uros.maravic@gmail.com>
Date:   Tue Nov 24 23:37:26 2015 +0100

    Merge Demos and CoolSongs. Also fix the case on other project folders
```

**Comment by Umcaruje** [comment]
Ok, so I changed the case to Sentence case on all the folders, but the rest of the folders in LMMS are lowercase. Sorry about that. At the time of the PR it made sense to make the remaining folders Sentence case, since the majority of the folders in the `projects` folder were like that.

**Comment by ycollet** [comment]
Here is a fix:

diff --git a/src/gui/MainWindow.cpp b/src/gui/MainWindow.cpp
index 41cf211..25c5ec0 100644
--- a/src/gui/MainWindow.cpp
+++ b/src/gui/MainWindow.cpp
@@ -1461,7 +1461,7 @@ void MainWindow::fillTemplatesMenu()
                                        ( *it ).left( ( *it ).length() - 4 ) );
        }
 
-       QDir d( ConfigManager::inst()->factoryProjectsDir() + "templates" );
+       QDir d( ConfigManager::inst()->factoryProjectsDir() + "Templates" );
        templates = d.entryList( QStringList( "*.mpt" ),
                                                QDir::Files | QDir::Readable );

**Comment by Umcaruje** [comment]
Ok, there are 3 solutions for this problem, and all of them are easy to implement, but I'm not sure which one to pick.

As you are aware of, all of the folders in the `data` folder are lowercase, and now that's inconsistent with the projects folder.

__Solution 1:__ Don't change the case of the folders, and just change the hardcoded path in `MainWindow.cpp`

__Solution 2:__ Change the case of the templates folder only, since its a special folder, and as such it should differ from the others

__Solution 3:__ Change the case of all the folders to lowercase.

I vote for option 2 or 3, so we become consistent with the user folder, where everything is lowercase.

**Comment by ycollet** [comment]
Or leave the template folder with the capital letter and change the line 
of code in src/gui/MainWindow.cpp.

**Comment by Umcaruje** [comment]
>Or leave the template folder with the capital letter and change the line
>of code in src/gui/MainWindow.cpp. 

That was solution 1...
