### ISSUE TITLE
Controller Rack forgets controller names

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2560]
When I name Peak Controller in Controller Rack as **Kick Peak** then after reloading project this Peak Controller is named as **Controller 1**. When controller is connected to somewhere then connection has correct name and also Connection Settings dialog has correct controller name. So this bug only is about Controller Rack dialog. I'm on latest master.

**Comment by michaelgregorius** [comment]
@karmux I can reproduce the problem with the Peak Controller but not with the LFO Controller. If you can also reproduce the problem with an LFO controller please provide the exact steps.

I think the problem is the following. Once the tag `controllers` is encountered during the loading of a song each controller found in that section is instantiated and then added to the song after it has been fully initialized (including their names). This is done in `Song::restoreControllerStates`. Adding a controller to the song leads to a `ControllerView` being instantiated for that controller which initialized the name label according to the name of the controller.

The problem with the Peak Controller is that it adds itself to the song in the constructor of `PeakControllerEffect`. At this point the instance is only instantiated but not initialized with the data from the file. This is done later in `EffectChain::loadSettings`:
```C++
// Loading of the controller
Effect* e = Effect::instantiate( name.toUtf8(), this, &key );

// Restoring the state of the controller
if( e != NULL && e->isOkay() && e->nodeName() == node.nodeName() )
{
	e->restoreState( effectData );
}
```
This means that the `ControllerView` is initialized with an uninitialized controller thus showing the default name. By the way after the peak controller is restored in `e->restoreState( effectData )` it has the correct name which means that it's stored correctly. You can check this by double clicking on the name of the controller. The rename dialog will show the name that you have previously entered.

I think there are some other issues due to the non standard behavior of the Peak Controller.

**Comment by karmux** [comment]
@michaelgregorius , fixed first comment. It's only with Peak Controller not LFO Controller.

**Comment by Umcaruje** [comment]
`<offtopic>` @michaelgregorius (and others) It would be useful if you add a `bug` label to issues that you successfully reproduced. If the issue is not complete, it should have the `needs clarification` label. For info on what other labels mean you can read: https://github.com/LMMS/lmms/wiki/Labels-Information `</offtopic>`

**Comment by michaelgregorius** [comment]
@Umcaruje Thanks for the pointer! I have just added the label.

**Comment by Umcaruje** [comment]
:+1:

**Comment by zonkmachine** [comment]
This is a duplicate of https://github.com/LMMS/lmms/issues/193 Maybe close that one since we've got more useful info on the bug here?

**Comment by IvanMaldonado** [comment]
Not sure if relevant, but I was using 2 LFO controllers and a peak controller, closing and opening the project again produced this:

![captura de pantalla_2016-02-29_21-13-55](https://cloud.githubusercontent.com/assets/12549082/13416559/60b79d82-df29-11e5-80a3-8019378f73c7.png)

The fader controlled by the Peak controller was now connected to the LFO controller and the other LFO got disconnected.

**Comment by IvanMaldonado** [comment]
And sometimes this also happens (I just removed the Peak controller)

![captura de pantalla_2016-02-29_21-41-58](https://cloud.githubusercontent.com/assets/12549082/13417017/5de6e2da-df2d-11e5-9153-cf8217507052.png)

I also can't delete the controller by clicking on "Remove this plugin"

**Comment by karmux** [comment]
I just noticed that this bug doesn't exist on master anymore. Somebody has secretly fixed it :)
