### ISSUE TITLE
Clean build with the latest git stable-1.1 has GUI glitches on 1st run

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#2615]
Hi guys great to see so much activity here lately :)
To reproduce....

1 Backup your old lmms directory.
2 Clone and build stable1.1 branch.
3 lmmsrc file is still intact from a previous build.
4 Open lmms
5 note that I am always using the default theme and am not installing lmms system wide, but to ~/lmms/target

Result:

1 Song Editor steps are not showing correctly with multiple coloured pixels everywhere.
2 icons for instruments , sample-track etc are the wrong size with the icons in an incorrect position.

This only happens on the 1st run. After this everything runs perfectly graphicically .

I believe this may not be a big issue as the rc file could be at fault with having a previous master branch build or some kind of cache issue to blame?
Anyway I thought I would just point this out.

**Comment by tresf** [comment]
Related #1187

Our logic does a version compare to reset the themes directory and one downside to the RC versioning is `1.1.90` has the same major/minor version as `1.1.3`.

Furthermore, part of the `1.2` branch is to allow LMMS to be run from a build directory, so the classic missing /incorrect theme problem continues to be a problem for those that run dev builds from non-standard locations.

**Comment by Lukas-W** [comment]
A bit off-topic: Why are we using `1.1.90` in favour of e.g. `1.2.0-beta`?

**Comment by mikobuntu** [comment]
@tresf Thanks for the detailed explaination and it's good to know that 1.2 will fix this issue , albeit a minor issue.

**Comment by tresf** [comment]
> @tresf Thanks for the detailed explaination and it's good to know that 1.2 will fix this issue , albeit a minor issue.

To know for sure, you can edit your `~/.lmmsrc.xml` and change:

```diff
- <lmms version="1.1.90">
+ <lmms version="1.2.0">
```

> A bit off-topic: Why are we using 1.1.90 in favour of e.g. 1.2.0-beta?

Well, according to a decision made [here](https://sourceforge.net/p/lmms/mailman/lmms-devel/thread/52DD9BF7.6090506@nbl.fi/) we'd be rolling up on `3.0.0` this release. :smiling_imp: 

But to answer your question, this was just [tradition](https://sourceforge.net/p/lmms/mailman/message/31938507/).  We can easily change it so as long as we're ok with calculations of `ProjectVersion("1.2.0-RC1") > ProjectVersion("1.2.0")` or change the comparator logic to know that `RC* < 0`. :+1:

**Comment by Lukas-W** [comment]
> as long as we're ok with calculations of `ProjectVersion("1.2.0-RC1") > ProjectVersion("1.2.0")`

We should fix that in case we do the change. It's probably best to use an existing library such as [zmarko/semver](https://github.com/zmarko/semver) or [euskadi31/semver-cpp](https://github.com/euskadi31/semver-cpp) instead of reinventing the wheel ourselves.

I'm in favour of doing this. It's less confusing for both humans and computers apparently. What would be left to discuss is whether or not we use a library and how to include in the project (opening the can of worms, aka dependency management / submodule / etc discussion).

**Comment by oeai** [comment]
i'd propose to add new section in .xml/.rc file for each new version
in my case i had different versions in different paths, 
so if some configs can be imported then to make it clean there can be a 
"reset config" button and\or
"import config"
having just import config can be more tweaky, because if we have few versions, then we can switch between them at any time, and "default" config for each version can be saved as well as few current configs, so users will be able to switch between many cards + latencies etc
 i'd also set "restart lmms" button there.

**Comment by tresf** [comment]
> i'd propose to add new section in .xml/.rc file for each new version

So you want to blow away all old versions each time, or prompt when the version has changed?  What about patch versions (1.1.2 -> 1.1.3)?

**Comment by lukas-w** [comment]
If I understand correctly, this should not be an issue anymore with our current versioning scheme.
