### ISSUE TITLE
Consider using a localization platform?

### ISSUE THREAD

**Issue by liushuyu** [LMMS/lmms#2676]
AFAIK, LMMS is very difficult to translate, for it contains many technical lingos. And thus a co-operative translation team should be established to care for the translations. So I suggest you to use a sort of localization platform like Crowdin and Transifex. **They are totally FREE for FOSS projects.** (I personally recommend Transifex https://www.transifex.com 😃)

I hope this can help you a bit. Thanks!

**Comment by liushuyu** [comment]
Ah, I consider this can be tagged as 'enhancement'

**Comment by tresf** [comment]
@liushuyu can you help us understand what's needed to integrate with a service like this?  I assume you've worked with a translations service like this in the past?

**Comment by liushuyu** [comment]
@tresf Yes, I introduced someone to explain how this works for you. @JeffBai

**Comment by MingcongBai** [comment]
> @liushuyu can you help us understand what's needed to integrate with a service like this? I assume you've worked with a translations service like this in the past?

For instance, the usage of Transifex.

We have been using Transifex (yes, with @liushuyu) in our community to host some large scale translation projects (LMMS is among one of the largest that we've been putting our hands on. Services like Transifex can provide:

- An easier way to manage involvement, each language has a team, with a coordinator and (multiple) a reviewer, and translators that involves in translating the respective language;
- An easier way to update language translation catalog, admit it, Qt .ts files are just a pain in the arse to work with when updating;
- An easier way for upstream developers (like you) to keep track of translation progress:
    - You can use an auto-import mechanism for Transifex;

Just my two cents. But I do agree with @liushuyu (as you could probably tell) on using a 3rd party translation hosting service. Just imagine developing LMMS without the help of Git...

I am willing to answer further questions.

Best Regards,
Mingcong (Jeff) Bai

**Comment by tresf** [comment]
@liushuyu @MingcongBai we may have a great candidate now with the back-and-forth with our Spanish translations, but I don't know the pain points currently.

#2359

@DiegoAccorinti @IvanMaldonado @GNUMariano, since you're working on a collab translation now, do you have time to see if this could help us?

**Comment by IvanMaldonado** [comment]
This reminds me on how Gnome manages its translations, using a system like this so the current translations could be improved and things that aren't translated are easier to find and easier to get translated since there is more than one person reviewing it.

When @DiegoAccorinti pull-requested the translation, I was half the way doing it so I just focused on what was missing or what could be improved. Then @GNUMariano appeared and made a work far better I could have ever done, so we move forward to talk about how difficult words could be translated. 

Notice how 3 people were working on the exact same language at more or less the same time. It's a yes for me.

**Comment by DiegoAccorinti** [comment]
ok, l'm in :+1:   @tresf @IvanMaldonado @GNUMariano @liushuyu @MingcongBai

**Comment by MingcongBai** [comment]
Awesome. One more vote to go.

**Comment by eagles051387** [comment]
Good Afternoon,

I would like to propose a different platform.

http://pootle.translatehouse.org/

What I like about pootle is that most of the translations are done online,
and even have the option for translations to be done offline.  We would
need people to take charge of the Loco teams to ensure that the
translations are accurate. One massive projects that uses pootle is
Libreoffice. I am willing to help and work on getting this setup and
integrated into our workflow.

Jonathan Aquilina

**Comment by liushuyu** [comment]
It seems that we have stuck here... But, as the LMMS will roll up to 1.2 soon, from my perspective, we can not put off the topic for another week.

**Comment by MingcongBai** [comment]
+1 to @liushuyu. But at the same time... I don't know, the sooner the change, the less the pain.

**Comment by tresf** [comment]
@liushuyu what are the next steps?  I don't think anyone is intentionally holding this up. :+1:

**Comment by liushuyu** [comment]
>@liushuyu what are the next steps? I don't think >anyone is intentionally holding this up.

Okay, next we need to decide which platform we are going to use. In fact, each platform comes with its unique advantage and disadvantage, and many of them have similar functions like translation memory, offline transition, and terminology lists. 

From my perspective, if I were you, I will choose Transifex, as this one has good support for Qt translation files, and it is famous for having many talented translation volunteers online.
The Poolte is also good but I am afraid this platform mainly focus on po translation files.

**Comment by tresf** [comment]
> we need to decide which platform we are going to us [...] I will choose Transifex

This is up to the translators, so decision has been made as far as I'm concerned. :smile:

**Comment by liushuyu** [comment]
>This is up to the translators, so decision has been made as far as I'm concerned. 

Hmm, no. For **you** need to upload the translation files to the platform , assign language team, and keep translation files up-to-date.
We will need to arrange the translations before you collect the translations and merge back to git here.

If you choose to use Poolte, you'll need a server to host it, and if you choose to use Transifex or Crowdin, I and @MingcongBai can help you with that.

**Comment by tresf** [comment]
> For you need to upload the translation files to the platform , assign language team, and keep translation files up-to-date.

Let's not point any fingers here. If someone needs elevated access, email an admin, please.  I'm not the one that proposed this technology, so respectfully, no.

**Comment by liushuyu** [comment]
>Let's not point any fingers here. If someone needs elevated access, email an admin, please. I'm not the one that proposed this technology, so respectfully, no.

Sorry about that. But my point here is that we need a general localization manager, who has the direct write access to LMMS repo and has strong sense of responsibility. This person will take care of the things I mentioned before.... (Sorry, once I thought your were responsible for everything 😃  )

**Comment by tresf** [comment]
> Sorry, once I thought your were responsible for everything

When a bruise gets poked over and over, it starts to get sore after a while.

This codebase is 500,000 lines long, and in addition to that, we maintain builds for dozens of operating systems (and many iterations of each OS) as well as release cycles, a website, an annual competition, social media, etc.

We're downloaded thousands of times per day, [just for Windows and Mac alone](https://api.github.com/repos/lmms/lmms/releases).

So, yes, some of us are responsible for everything, but I'm not sure how that matters.  This isn't a corporation, this is a free piece of software that you decided to open a bug report on.

> we need a general localization manager, who has the direct write access to LMMS repo and has strong sense of responsibility

We NEED:
 * a core rewrite
 * VST support fixed
 * release our own Linux binaries, 5 years ago
 * support more than VST/LADSPA plugins
 * better performance, less crashing

But somehow we're doing alright, so unless you're volunteering, I recommend you stop making claims like:

> LMMS will roll up to 1.2 soon, from my perspective, we can not put off the topic for another week

as this can come off as quite insulting to the people who are already responsible for everything. :wink:

**Comment by IvanMaldonado** [comment]
@tresf, I think he is just talking about what it's needed to implement the idea here presented, and not what lmms needs in general. 

If someone is needed to make this happen, count with me, I have seen how platforms like this work before and since we are just going to work with the translation files, those are the only things from the repo that we will need. 

Everybody have access to the repo. 👍

**Comment by liushuyu** [comment]
Okay, @tresf maybe we have some misunderstanding,  I thought you'll in charge of this. Now, I have set up the project on Transifex here : https://www.transifex.com/lmms/lmms/

Thanks for your patience!

**Comment by liushuyu** [comment]
Just wait a few minutes while I am importing existing translations

**Comment by tresf** [comment]
@IvanMaldonado :+1: @liushuyu :+1: 

Please speak up if access rights need to be changed.

**Comment by IvanMaldonado** [comment]
Maybe there could be another branch or repo exclusive for lmms translations (lmms-translations) so the changes in the translation files (done online) could be updated there to be then merged to the master branch.

**Comment by tresf** [comment]
> Maybe there could be another branch or repo exclusive for lmms translations (lmms-translations) so the changes in the translation files (done online) could be updated there to be then merged to the master branch.

We always can, but translations aren't something that get a whole lot of scrutiny today, because the admin approving it quite often doesn't speak the language being translated, so if the service you are using has the workflow, I'm pretty sure the admins will be happy with that.

On that note, if you're uncomfortable with turning on pushes to our live repo right away, you can always point it at your own personal forks until the kinks are worked out. :+1:

**Comment by liushuyu** [comment]
Progress update: All existing translations have been successfully imported.
Cheers!
Next, I need the existing translators to register an account on Transifex:
https://www.transifex.com/signup

**Comment by tresf** [comment]
@liushuyu thanks for setting this up.  Very nice.

A good way to ping some translators is to [browse through the changes made to our locale directory](https://github.com/LMMS/lmms/commits/master/data/locale) and check for GitHub IDs which were use for translation commits.

![image](https://cloud.githubusercontent.com/assets/6345473/14006996/f34e24c8-f148-11e5-9a22-ce875e29afc8.png)

**Comment by liushuyu** [comment]
Further more, I have set up serveral interesting tags to attract more
volunteers on Transifex to join our project. And so far, I witnessed
serveral strangers have joined already! 😃

**Comment by liushuyu** [comment]
>A good way to ping some translators is to browse through the changes made to our locale directory and check for GitHub IDs which were use for translation commits.

Okay, I have invited as many people as I can, so far we've got 7 people here, more to come!

**Comment by IvanMaldonado** [comment]
@liushuyu You must be aware that LMMS use a lot of technic words and there should be just people who know about music production in general, for real, the last translation for spanish lmms had, had some bad interpretations about the controls, because we in spanish use words to define different things when english usually uses just one and you have to find the most coherent context.

I imagine that other languages have this issue too, just saying.

**Comment by liushuyu** [comment]
So, what do you suggest me to do about it?

**Comment by IvanMaldonado** [comment]
@liushuyu Do not let any person to join, they have to know what they are working with first.

**Comment by liushuyu** [comment]
I am aware of that, thanks! Actually, when someone want to join, they will
wait until @Tresf or I to accept the request. So I will take care of that.
Thank again! 😃

**Comment by Umcaruje** [comment]
Hey, so @liushuyu is this a paid service? 

Also how do we update the translations with new strings? IIRC translators used to `lupdate` to manually update the translations with new/changed strings ( I recall @midi-pascal talking about that ).

How does transifex handle this? Also, how will you commit the new changes to the repo?

**Comment by liushuyu** [comment]
Well, it's free for open source projects. And I am setting up automatic
updating bot for you to update translations simultaneously. And when
translations reached certain progress, the bot will merge the translations
back....

**Comment by Umcaruje** [comment]
Closed by #2706

**Comment by GNUMariano** [comment]
Hi @liushuyu ! I've missed this issue because of mail problems (I've received the mails from the last 20 days just today! Maybe I must change my mail account this delay causes me a lot of trouble...)
I want to say it's a great idea to coordinate efforts this way. I've already joined Transifex 'bout 2 hours ago and [almost] completed the Spanish translation. I hope @IvanMaldonado can help me reviewing it! 
Good luck everyone :+1:

**Comment by liushuyu** [comment]
Well, you are also a coordinator, so you can 'review' some by yourself😃.
If you encounter any problem leave me an email.

**Comment by GNUMariano** [comment]
Thanks! I'll keep in touch :smile:
