### ISSUE TITLE
LMMS scans entire home directory on first launch

### ISSUE THREAD

**Issue by kamnxt** [LMMS/lmms#2698]
On my system, LMMS seems to hang on launching. After further examination using strace, I found out it tries to scan the entire home directory, which in my case contains a lot of files, causing LMMS to be unresponsive for several minutes.

**Comment by tresf** [comment]
Sounds like it's doing a recursive scan of files.  If you move `~/.lmmsrc.xml` out of the way, does it still occur?  I ask because by default, the working directory for the application is `~/lmms`, which unless there's a bunch of strange symlinking going on, shouldn't be deep enough to exhibit what your'e describing.

**Comment by kamnxt** [comment]
Still happens with .lmmsrc.xml removed. 

The thing it hangs on is this:

    access("/home/<my user>/<directory>/<subdirectory>", R_OK) = 0

It seems like it's only being done 2 directories deep though. I've got a directory with around 72k directories in it, which seems to be the problem. If the directory is directly in my ~, it's being scanned (and hangs LMMS for quite a while), but if it's in a directory inside ~, it isn't.

I think that the launch window should at least show something more informative than "Preparing UI".

**Comment by michaelgregorius** [comment]
I investigated a bit on this one and I think that it's caused by the file browser which shows the user's home directory. I have used the following command for `strace`:
```
strace -o strace_result.txt -e trace=open ~/lmms-dev-mg/lmms-build/lmms
```
This will trace all `open` system calls and log them into the file `strace_result.txt`. Doing so gives me several entries of the following form:
```
open("/home/michael/<subdir>", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 22
```
If I comment out the following line in `MainWindow.cpp` these lines are gone:
```C++
sideBar->appendTab( new FileBrowser( QDir::homePath(), "*",
							tr( "My Home" ),
					embed::getIconPixmap( "home" ).transformed( QTransform().rotate( 90 ) ),
							splitter, false, true ) );
```
@kamnxt Can you please check if LMMS starts faster for you if you comment out this line of code as well? If that's the case then we have found the cause and can try to improve it. Thanks!

**Comment by kamnxt** [comment]
@tresf Yep, this causes it to start pretty much instantly.

**Comment by michaelgregorius** [comment]
@kamnxt Can you please try how your system behaves if you change the last parameter that's set to `true` in the code above to `false` so that it becomes the following:
```C++
sideBar->appendTab( new FileBrowser( QDir::homePath(), "*",
                            tr( "My Home" ),
                    embed::getIconPixmap( "home" ).transformed( QTransform().rotate( 90 ) ),
                            splitter, false, false ) );
```
The last parameter in `FileBrowser`'s constructor is called `recurse` and seems to control whether the content of the top level directories is loaded on initialization. Setting it to `false` should change the behavior so that the directories are only loaded when they are opened by the user.

So in your case LMMS should start quickly after the change and it should only take a while if you decide to open the directory with the 72k entries in the Home directory browser.

**Comment by kamnxt** [comment]
Ok, sorry for suuper late reply, but setting it to false prevents the problem from happening.

**Comment by michaelgregorius** [comment]
@kamnxt Seems like I am five minutes too late. I will close my pull request. :smile:

**Comment by kamnxt** [comment]
Should have probably made the commit first I guess :P
