### ISSUE TITLE
High pitched sound is played faster in Piano Roll Editor 

### ISSUE THREAD

**Issue by RoiEXLab** [LMMS/lmms#2702]
This is Issue #2696 reopened...
I'm using Windows 8.1 x64 and LMMS 1.1.3.
When using Bassdrum01 in the piano Roll editor the sample plays faster the higher you pitch it.
You'll recognize it easier if you are creating a scale in the editor.
You will notice that at some point the sample won't sound perfectly aligned.

**Comment by Spekular** [comment]
I'm fairly certain this is intended. Playing a sound faster will increase
the pitch, and vice versa.

**Comment by tresf** [comment]
> When using Bassdrum01 in the piano Roll editor the sample plays faster the higher you pitch it.

If that's not desired, use the soundfont.  Sound waves shrink as their pitched.  This is default.  Try it in Audacity.  This isn't a bug.

**Comment by zonkmachine** [comment]
> You will notice that at some point the sample won't sound perfectly aligned.

This is because the frequencies are calculated as ratios of the sample mathematically. This bug was, kid you not, earliest described by Euclid and is called the [Pythagorean Comma](https://en.wikipedia.org/wiki/Pythagorean_comma). It's why piano tuners has to train for years to get it right with the 'tempered tuning'.
Samples that can be pitched up/down correctly use a more advanced file format and multiple samples where you use a couple or so samples per octave. Check out the [Maestro Concert Grand v2](https://www.linuxsampler.org/instruments.html) It use five samples per key to also get the volume right. For most uses it's not worth the hassle and you just do one sample and within a small note span where it works for you.
If you have more questions on this, bring it up on the lmms forum. https://lmms.io/forum/
