### ISSUE TITLE
CPU load on internal windows when buttons are hidden (Windows only)

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#2767]
When a window size is changed (on Song Editor, Piano-roll, automation editor and project notes), buttons that don't fit it are hidden and accessible via an arrow button.

If that happens, the cpu goes to max for the LMMS process (25%)
(I'm on a quad core, and one of the cores goes to around 70%, while the others are normal)

I'm on Windows 7 64bit, and I'm using the third RC from Tres' fork (1.1.90-g33d8c44), which is in qt5
Seems fine on linux

**Comment by tresf** [comment]
@DeRobyJ confirmed on Windows at least.  This seems to happen with any collapsible toolbar.

This may be a Qt5 + Windows bug.  If you get the Song-Editor and drag it smaller so that the dropdown-toolbar menu appears, it also utilizes an unreasonably high amount of CPU.

![image](https://cloud.githubusercontent.com/assets/6345473/15113329/8bb73258-15c1-11e6-9f0c-9981803bb9cf.png)

Tagging @michaelgregorius since this new toolbar feature was added in #2287.

**Comment by DeRobyJ** [comment]
Yup, seems Windows only.
Tested in KXStudio 14.04, lmms 1.1.90-g268ddb2

Re-writing issue~

**Comment by michaelgregorius** [comment]
Does the high CPU load persist as long as the toolbar is collapsed or is it "only" a spike?

@tresf Do we have a recent Windows release build with debug information (RelWithDebInfo) that we can send through a profiler like [Very Sleepy](http://www.codersnotes.com/sleepy/) to check where the time is consumed?

**Comment by tresf** [comment]
> @tresf Do we have a recent Windows release build with debug information (RelWithDebInfo) that we can send through a profiler like Very Sleepy to check where the time is consumed?

Negative.  We've never done well in this regard.  It think we attempted to enable debug symbols when built from Linux, but never succeeded with Msys2 (I can try to hunt down the build flag changes if needed).

**Comment by tresf** [comment]
> Does the high CPU load persist as long as the toolbar is collapsed or is it "only" a spike?

From my quick testing, it remains until it's no longer collapsed. It's persistent so as long as it is collapsed.

**Comment by michaelgregorius** [comment]
@tresf I think for g++ you only need to pass `-g` when compiling the release version.

**Comment by tresf** [comment]
@michaelgregorius If your comment is in regards to a debug build... I'd be happy to add debug instructions to our build process, but when I had originally tried this it was under the assumption we had a version of `gdb` running directly inside Windows (for that particular bug, `winegdb` wasn't a candidate) but the msys2 build process is extremely unorthodox.  It fetches Toby's mingwppa for the `dll` files but needs to use native msys2 version of the `exe` files, so we do a bunch of clobbering of build tools at compile time.

If we can document a build flag to `mingw` on Linux, that would be better than what we have now.  AFAIK Dave and I improved this in https://github.com/LMMS/lmms/pull/2205 but I haven't extensively tested it yet.

**Comment by michaelgregorius** [comment]
@tresf My intention is to use a release build with debug information to let it run in Very Sleepy to find out where the time is spent and whether it's really spent in Qt's code. The debug information would be needed so that the symbols can be resolved. However, come to think of it, if it in fact spends most of the time in Qt a release with debug info build won't help anyway because Qt would also need to be built as a release with debug information as well. So perhaps a normal release build will do as long as it tells us that most of the time is spent in symbols from Qt's DLLs.

Can you provide me with a Windows release build (preferably one that can simply be unzipped and does not need to be installed) so I can give it a spin with Very Sleepy?

An alternative might be to try to reproduce the problem in a minimal Qt application under Windows.

**Comment by tresf** [comment]
> An alternative might be to try to reproduce the problem in a minimal Qt application under Windows.

Yeah that might be quicker through QtCreator.  I'd be happy to make a debug build of LMMS however I'd rather not spend the time of compile an uploading unless we know it will work.

>  I think for `g++` you only need to pass `-g` when compiling the release version.

Can you be more specific from a `cmake` perspective?  For example, is this just a `CXX` flag?  Can it be provided on command line?

**Comment by tresf** [comment]
So I installed QtCreator and now apparently I need a compatible MSVC compiler to match.  This is gross. Ugh.. 

http://stackoverflow.com/questions/31897847/can-not-configure-compiler-and-build-kit-for-qt-5-5

**Comment by liushuyu** [comment]
@tresf You could download a community version of Visual Studio to get the compilers and other necessary tools. It might take around 10 GB of disk space.

**Comment by tresf** [comment]
@liushuyu yeah thanks.  I had it installed but was missing some stuff.  Posted the steps here: http://stackoverflow.com/q/32413617/3196753.

Next step, getting a toolbar added. :+1:

**Comment by liushuyu** [comment]
>I had it installed but was missing some stuff

So what went wrong with your installation?

**Comment by tresf** [comment]
> So what went wrong with your installation?

It's explained in the stack overflow article, but MSVC 2015 wasn't bundled with MSVS 2015.  I opened it up (30 day trial had expired, signed in with a hotmail account), tried creating a C++ project and Visual Studio prompted to install MSVC 2015.  Once that was done, QtCreator was fine.

**Comment by liushuyu** [comment]
>Once that was done, QtCreator was fine.

So you are good to go now?

>I opened it up (30 day trial had expired, signed in with a hotmail account), 

BTW, there's a community version available, which is free to use with open source projects. And it bundles everything from Windows development to Android deployment.

**Comment by tresf** [comment]
> BTW, there's a community version available, which is free to use with open source projects. And it bundles everything from Windows development to Android deployment.

Yes, that's what I was on (well, the non-bundled version apparently), but it forces you to sign into a Microsoft account after 30 days. 😈

**Comment by liushuyu** [comment]
And I've noticed that some projects that compiles well with gcc just fails when compiling with M$VC's `cl`compiler, but since Visual Studio 2015, you can choose `clang` as preferred compiler. And I suggest to do that.

**Comment by tresf** [comment]
@michaelgregorius,

I cannot reproduce on QtCreator/Qt5 but I don't think it's a 1:1 comparison... 

 * We use the `QToolBar` in the `QMdiSubWindow` container, which QtCreator doesn't seem to have direct support for in the GUI designer.
 * By default QtCreator places `QToolBar` directly in the `QMainWindow` instance.

Also, I tried to reproduce this bug using the new `QToolBar` but on Windows + Qt4 and it is not present.  This is a pretty specific bug.

Another item worth noting/investigating is that we have custom buttons/widgets added to the `QToolBar` which may have inefficiencies in the `paint()` methods that this bug is bringing to light.



Off topic, but I also noticed the `.ui` file references the subwindow as just a standard `QWidget` object.

**Comment by tresf** [comment]
On a side note, I did force the `Fusion` theme to be safe, since [we do that in LMMS](https://github.com/LMMS/lmms/issues/2611#issuecomment-193817867).

![image](https://cloud.githubusercontent.com/assets/6345473/15204475/b93aaf2c-17db-11e6-92c1-546c8c0e549f.png)

**Comment by liushuyu** [comment]
>Another item worth noting/investigating is that we have custom buttons/widgets added to the QToolBar which may have inefficiencies in the paint() methods that this bug is bringing to light.

So, to really figure out the problem, a timing debugging should be done. I'd like to test this out, but I don't know if we could fire a complete debug build on Windows.

**Comment by liushuyu** [comment]
Hi, guys, I've done a quick Very Sleepy timing profile (with release build unfortunately), and found something interesting. I've done the test under Windows 10, however I captured the screenshot under Linux (via Wine).

![screenshot_20160512_214952](https://cloud.githubusercontent.com/assets/6829345/15217106/a891ae66-181f-11e6-9856-ac402337c24e.png)

And I also attach the sample Very Sleepy timing capture here, in case you are curious to see the whole complete report (which I've profiled for only 60 seconds)

[lmms.sleepy.zip](https://github.com/LMMS/lmms/files/261459/lmms.sleepy.zip)

Just rename `lmms.sleepy.zip` to `lmms.sleepy` (because the file itself is a zip file, and GitHub only allow me to upload the file with `zip` extension)

**Comment by musikBear** [comment]
can this issue be recreated on win32?
I cant.
CPU is 100% stable no matter how any widget-window is sized, minimized, top-placed, in or out of focus.
Same CPU load on all situations.
(1.1.90-g33d8c44 on xp)
![accesablebuttonshide](https://cloud.githubusercontent.com/assets/6662066/15219913/d392afa2-1865-11e6-81d3-f9142f976ff9.png)

maby x64 specific? maby im just wrong, again.

**Comment by liushuyu** [comment]
>maybe x64 specific? maybe im just wrong, again.

Emm, maybe this issue is tied to higher version of Windows?

**Comment by tresf** [comment]
> CPU is 100% stable

WTF is 100% stable?

**Comment by liushuyu** [comment]
>WTF is 100% stable?

He meant to say CPU was in normal state

**Comment by tresf** [comment]
> He meant to say CPU was in normal state

I cannot confirm
 * :large_blue_circle: Ubuntu 12.04: Normal CPU utilization
 * :red_circle: Windows 10 x64: High CPU utilization
 * :red_circle: Windows 7 x64: High CPU utilization
 * :red_circle: Windows XP x32: High CPU utilization

![image](https://cloud.githubusercontent.com/assets/6345473/15220782/be2c63c6-1836-11e6-8e30-8c11c74f0aea.png)

**Comment by liushuyu** [comment]
My Arch Linux x64 seems to be fine as well...
So it seems to be a Windows specific problem

**Comment by liushuyu** [comment]
@tresf I've done a timing above, hoping we can figure out some potential causes

**Comment by liushuyu** [comment]
oh @musikBear , can you show us your Task Manager when running LMMS ? And if Task Manager shows that LMMS takes no or low CPU resources, can you run `systeminfo` in your command prompt and paste the output? Thanks!

**Comment by tresf** [comment]
> (1.1.90-g33d8c44 on xp)

@musikBear this is a Qt4 build, it won't experience the bug.  This isn't immediately obvious when you fire up LMMS, but if you're using a build from my branch, I've explicitly tagged releases for Qt5 in the file name.  The way to know with these older builds is the QMdiSubWindow decorations are black.  Modern builds won't be as easily distinguishable and you'll have to go to About, LMMS to know for sure.

Original bug report:

> I'm on Windows 7 64bit, and I'm using the third RC from Tres' fork (1.1.90-g33d8c44), **which is in qt5**

Next post:

> This may be a **Qt5 + Windows** bug.

**Comment by liushuyu** [comment]
@musikBear Download here: https://github.com/tresf/lmms/releases/download/v1.2.0-RC1.3/lmms-1.1.90-g33d8c44-win32.exe

**Comment by tresf** [comment]
@liushuyu that's the one he's using.  My mistake it is Qt5 after-all.   Not sure why it affects my VM but it won't affect @musikBear.

**Comment by liushuyu** [comment]
@tresf No, I've edited comment...

**Comment by DeRobyJ** [comment]
@musikBear on my system, one of the cores was around 70%, while the others were normal.
It might be possibile that on a 32bit system the bugged process takes over the whole cpu.
How many logical cores do you have?

**Comment by tresf** [comment]
> It might be possibile that on a 32bit system the bugged process takes over the whole cpu.

Single-core system, yes.  The VMs I'm testing in deadlock when this bug happens.  32-bit is behaving the same as 64-bit in my tests.

**Comment by musikBear** [comment]
No its my mistake. If i use a cpu monitor, there is a rise, it is just not big enough to make a change on lmms' cpu-monitor, but it increases to ~40, and it does indeed drop to ~2 if the window is maximized. Sorry for confusing the issue, should have used cpu-monitor, not just relied on the lmms cpu-monitor.

**Comment by tresf** [comment]
@DeRobyJ can you please re-test with [this build](https://github.com/tresf/lmms/releases/download/v1.2.0-RC2/lmms-1.1.90-8c2f98a-win64.exe)?  No changes have been made specifically but I'm having a hard time reproducing the problem now and want reconfirmation.

**Comment by tresf** [comment]
We've had multiple reports that [this build](https://github.com/tresf/lmms/releases/download/v1.2.0-RC2/lmms-1.1.90-8c2f98a-win64.exe) no longer suffers the problem.  Closing.

**Comment by DeRobyJ** [comment]
Yup, I confirm it's fixed

**Comment by musikBear** [comment]
Confirming for 1.2.0-rc2 on XP
Good job! 👍
