### ISSUE TITLE
Switching Helm presets crashes LMMS

### ISSUE THREAD

**Issue by mestaritonttu** [LMMS/lmms#2784]
[Helm](http://tytel.org/helm/) is open source. I used the 64-bit Windows version and reproduced on two different machines.
1. Load Helm to VeSTige
2. Drop some notes in the piano roll and hit play
3. Click Browse in Helm and switch presets

It might crash the first time or after a couple of preset changes.
LMMS 1.1.90.
Helm 0.6.0.

**Comment by tresf** [comment]
Possibly related #1183, #1389, #2157, #493

In short, we desperately need someone to help with the state of VST in this DAW.  Not only are several VST plugins in bad shape, but our Linux support is having problems loading VSTs at all per #1875 (#2739, #2728, #2724, #2628, #2488, #2448, #2196, #2390, #2304).  Sigh... :disappointed:

**Comment by mestaritonttu** [comment]
I am ready to throw 100 euros at someone willing to fix this issue and the Grace one.

**Comment by tresf** [comment]
> I am ready to throw 100 euros at someone willing to fix this issue and the Grace one.

Understood.  You can create a bounty on the bug report and see if someone bites (but speaking personally, I've had no luck in this regard).

**Comment by jasp00** [comment]
Helm is built on the JUCE library. It would be nice if JUCE's license (GPL-2+) included an exception to combine with Steinberg's SDK. Otherwise, binary VST hosts cannot be distributed. I wonder if Helm can really be distributed in binary form, since that would be a violation of GPL, but not of Steinberg's license (I think), which is the one of my concern.

The 32-bit version loads on Linux. Following the steps [above](https://github.com/LMMS/lmms/issues/2784#issue-154980945), LMMS gets locked and Helm still runs. I would like to have a look, but #2739 should be merged first. This is the first open-source VST plug-in that I see, although it is not the [only](https://github.com/tmwoz/binaural-vst) [one](https://github.com/bsutherland/JuceOPLVSTi).

**Comment by jasp00** [comment]
I have solved some concurrency issues. Switching presets makes Helm crash with Wine sometimes, but LMMS does not get locked.

**Comment by mestaritonttu** [comment]
@jasp00 Let me know how I can give you 100 euros after you crack the case. I decided not to lump the bounty together with the Grace loading problem.

**Comment by jasp00** [comment]
@mestaritonttu, thanks, but do not worry about me. If you are satisfied, you might [donate to the project](https://lmms.io/get-involved/) (look for _Donate_).

**Comment by osamaar** [comment]
A temporary workaround is to use LMMS' VeSTige instrument window switch preset function in instrument window instead. This indeed changes presets (right/left arrows) and the little down arrow lists all of Helm's presets (albeit without the nice filtering and categories available in Helm GUI), although the GUI seems to not reflect some of the changes when the preset changes.

![VeSTige instrument window](https://lmms.io/wiki/images/8/8d/Plugins_VeSTige1.0.0.png)

I suppose VeSTige save/load preset can also be used although I haven't tested them myself. This makes it possible to bypass the whole preset section in Helm GUI until a proper fix is available.

**Comment by zonkmachine** [comment]
> LMMS 1.1.90.

Can you please test the latest development release for lmms 1.2.0 and confirm if this is fixed?
https://lmms.io/download/#windows

**Comment by mestaritonttu** [comment]
I confirmed it does not crash anymore with LMMS 1.2.0 RC4 and Helm 0.9! Thanks a lot.

**Comment by zonkmachine** [comment]
Great news, thanks for the feedback!
