### ISSUE TITLE
Add a download manager to download audio / presets ressources from the web

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2794]
Add a download manager to download audio / presets ressources from the web.
Something like the download manager from the hydrogen drum sequencer which download drum sound fonts from sourceforge.

**Comment by tresf** [comment]
@ycollet we discussed this for quite a while here: #661

The decision was made to shelve this for a while due to money, complexity and lack of help of the solution.  I'll leave this open for a while incase people want to discuss, but unless someone decides to run with it, it'll be marked as a duplicate of #661, which is closed.

**Comment by lukas-w** [comment]
Closing as duplicate of #661.
