### ISSUE TITLE
Frequently crashes because of Microsoft Management Console crashing

### ISSUE THREAD

**Issue by william1835** [LMMS/lmms#2810]
I open my project file (.mmpz or .mmp) and the splash screen appears. Shortly after, the familiar not responding dialog appears. Now you think it should have LMMS on the dialog, but instead it has Microsoft Management Console. I can usually solve the problem by reinstalling LMMS, however it may take 1, 2 or even 3 reinstalls to solve the problem. The issue comes back after every session in LMMS.

**Comment by DeRobyJ** [comment]
Doing a little search online, it seems this error appears from time to time in different cases on Windows.
If that does happen with LMMS only, it might be a problem with LMMS, but I strongly feel it isn't and we can't do much about it.

Just to be sure, are you using the correct version of lmms 1.1.3 (32-bit or 64 according to you system)

**Comment by william1835** [comment]
@DeRobyJ Well, it has only happened in LMMS to me, I am using the correct version as you have mentioned above. I do wonder, however, what use the Microsoft Management Console would have in LMMS, it seems unusual.

**Comment by DeRobyJ** [comment]
Maybe you can see if there's some process that you can get rid off, even some bloatware from the manufacturer

**Comment by musikBear** [comment]
just one thing. Do you have skype, icq or similar in your *start* list. I have heard that this can make problem with  msmsgs, also think teamspeak or xfire was a culprit

**Comment by tresf** [comment]
MMC is not used at all by lmms.  MMC is used by windows for many (many) things such as starting and stopping services (services.msc), managing hardware (devmgmt.msc) hardware, security policy (secpol.msc).

The fact that this opens may be more attributed to the tools you have installed on this particular workstation rather than LMMS.

In the off-chance LMMS has a DLL namespace conflict, it should be observable using a resource monitoring tool such as the free DependencyWalker application.

**Comment by william1835** [comment]
@tresf Thanks, I'll try and do a full trace of the error
