### ISSUE TITLE
New theme don't show velocity of steps 

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2863]
In B+B view all steps have same very bright color even when their velocity is very different e.g. 1% vs 100%. Only when totally muted then step color is a bit darker. Introduced after new theme was merged.

**Comment by michaelgregorius** [comment]
This problem is caused by the brightness/transparency level of the images [step_btn_on_100.png](https://github.com/LMMS/lmms/blob/master/data/themes/default/step_btn_on_100.png) and [step_btn_on_yellow.png](https://github.com/LMMS/lmms/blob/master/data/themes/default/step_btn_on_yellow.png) in the new default theme. Painting the steps at different levels of brightness is implemented by repeatedly painting these image according to the level of the note. This is the relevant code for painting an active step from `PatternView::paintEvent`:
```C++
p.drawPixmap( x, y, stepoff );
for( int i = 0; i < vol / 5 + 1; ++i )
{
    p.drawPixmap( x, y, stepon );
}
for( int i = 0; i < ( 25 + ( vol - 75 ) ) / 5; ++i )
{
    p.drawPixmap( x, y, stepoverlay );
}
```
So if a note has a volume of 100 the "step on" image is painted 21 times each time taking a bit more of transparency. Then the "step overlay" image is painted 10 times. The maximum value for volume is 200, so the "step on" image will be painted at most (200 / 5) + 1 = 41 times and the "step overlay" image will be painted at most (25 + (200 - 75)) / 5 = 30 times. Having at most 71 paint calls for a single note does not seem to be very efficient anyway.

@RebeccaDeField: If we decide to fix this without changing the code the images [step_btn_on_100.png](https://github.com/LMMS/lmms/blob/master/data/themes/default/step_btn_on_100.png) and [step_btn_on_yellow.png](https://github.com/LMMS/lmms/blob/master/data/themes/default/step_btn_on_yellow.png) will need more transparency. In case the alpha values add up linearly an alpha value of 2 for the area that lightens or darkens in both images should hopefully do the job ((255 / 71) / 2 = 3.59 / 2 ~ 2).

**Comment by RebeccaDeField** [comment]
I really appreciate detailed feedback like this.

You can access and edit the source files [here](https://github.com/LMMS/artwork). If you don't have time I'll see if I can get to it when I have the time :+1: 

@michaelgregorius @karmux

**Comment by michaelgregorius** [comment]
@RebeccaDeField I'd prefer if you do it. Thanks! :)

**Comment by RebeccaDeField** [comment]
@michaelgregorius I don't have time to do all of the design related tasks, but I was already planning on doing this one. :+1:

Just making sure I understand correctly, you want the transparency lowered to 2 for both of the step graphics?

**Comment by michaelgregorius** [comment]
@RebeccaDeField I have experimented a bit and it looks like setting the transparency to 2 / 255 will likely not do the job. What I've done was to replace [step_btn_on_100.png](https://github.com/LMMS/lmms/blob/master/data/themes/default/step_btn_on_100.png) with a fully red square with a transparency of 2 / 100 and [step_btn_on_yellow.png](https://github.com/LMMS/lmms/blob/master/data/themes/default/step_btn_on_yellow.png) with a fully green square also with a transparency of 2 / 100. Even with these relatively lower transparencies I don't get the expected result:
![2863-transparency-experiments](https://cloud.githubusercontent.com/assets/9293269/16567061/e197b1f4-421a-11e6-8a85-4152bc4dbf41.png)
There is a note on every beat: the first one at a velocity around 25%, the second at 50%, the third one at 75% and the fourth one at 100%. The last two notes are at 150% and 200%. As you can see none of them is fully active.

I think we should consider to implement the painting of the notes differently as the current implementation is not very transparent (no pun intended) to designers.

**Comment by RebeccaDeField** [comment]
@michaelgregorius Thank you for looking into this. It looks like we will need to come up with some different solutions for the way the notes are painted.
