### ISSUE TITLE
Version hash isn't updated properly

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#2966]
I just switched branches and the `About` version info reads:
`Version 1.1.90-0c62b7a (Linux/x86_64, Qt 4.8.6, GCC 4.8.4)`

The hash `0c62b7a` is old. I'm now on commit `54a9aa6`

**Comment by tresf** [comment]
> The hash 0c62b7a is old. I'm now on commit 54a9aa6

It's probably an issue with your branch and how it's reading the latest commit.

 * The `(Linux/x86_64...` stuff is completely irrelevant, it doesn't come from cmake, so it just adds confusion to the bug report.
 * To troubleshoot this issue, you should run `git describe --tags --match v[0-9].[0-9].[0-9]*` and see if it gives the correct hash.  If it doesn't, just fix that command, or see if perhaps the header [file isn't getting cleared properly](https://github.com/LMMS/lmms/blob/master/src/lmmsversion.h.in#L5)

**Comment by jasp00** [comment]
IMHO, the only hash that matters is the last one committed to master. I would add a dependency for `lmmsversion.h` on `.git/refs/heads/master`.

**Comment by tresf** [comment]
> IMHO, the only hash that matters is the last one committed to master. I would add a dependency for lmmsversion.h on .git/refs/heads/master.

Can you elaborate a bit?  We generally don't keep the hashes around for official releases, and official releases are the ones that really should be most concerned with permanent, in-code upgrade steps.

**Comment by jasp00** [comment]
Non-stable versions are useful when users report bugs; these versions come from master. Other case is when users make projects with unofficial releases, because there is VST support or a fix for a segfault; versions come from master too. It is nice to support upgrades from unofficial releases if possible.

The version is not so important when a developer switches branches, which is the reason to open this issue. Users are unlikely to file bug reports or to make projects with these developer versions.

**Comment by zonkmachine** [comment]
This issue was obsoleted by 5eb0ae2d7576a12e7a2cd16e4bae7baeeee41c83
