### ISSUE TITLE
Enable/Disable window minimization Setting

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#2976]
Right now, you can minimize some of the windows inside LMMS.
You can do it for the windows that are already accessible from the function keys or from the top bar of the program, and for instrument track windows.
If a window is minimized and then closed, it will stay in minimized state even if you call it again.
This, in my experience, leads to confusion.

That particular problem would be fixed by just resetting the window state to normal, not minimized, when a window is closed. So when it gets called again, it will show up on screen right away.
But there is an inconsistency with effect windows, which can't be minimized: I propose to remove the minimazation alltogether.

**Comment by jasp00** [comment]
The minimization of LADSPA Plugin Browser is buggy. Removing minimization would take care of this.

**Comment by tresf** [comment]
> Disable minimization on all subwindows #2983

Are we really doing this?  I don't use minimize all that often, but this seems quite drastic.

**Comment by Umcaruje** [comment]
>Are we really doing this? I don't use minimize all that often, but this seems quite drastic.

Why? I find the minimize function to be quite pointless. Minimized windows are really easy to get lost under other windows, and I found it was always a pain to find them.

Furthermore, when you close a window, and open it again, it restores itself to its previous position, just like it was minimized. 

Also as  @jasp00 pointed out the minimization can be buggy for some windows, so removing it also helps on that field too.

**Comment by midi-pascal** [comment]
When you right-click on the window title bar do you still see the "Minimize" option?
This remembers me an other case I solved for the "Resize" option for fixed size windows...
My 2 cents.

**Comment by Umcaruje** [comment]
@midi-pascal nope: 
![image](https://cloud.githubusercontent.com/assets/6282045/17825693/770b9bce-666a-11e6-9b65-e4b03b52e0d9.png)

though the non-maximizable windows have the maximize option, but that should be a separate issue.

**Comment by midi-pascal** [comment]
:+1:

**Comment by tresf** [comment]
> I find the minimize function to be quite pointless.

That's obvious by the proposal to remove.

> Why [drastic]?

Because it is a core window management function in every MDI windowing interface ever.

As stated before, I don't use this feature, but I want to know the majority of our users don't either.

Albeit quite different context, [here](https://tech.slashdot.org/story/11/03/05/1619223/gnome-to-lose-minimize-maximize-buttons).  Comments are a good read. 👍

**Comment by Umcaruje** [comment]
http://lmms.io/forum/viewtopic.php?f=4&t=5554

Made a poll on the forums

**Comment by BaraMGB** [comment]
@Umcaruje I agree with you in all points, but is this something we want do for 1.2?

**Comment by Umcaruje** [comment]
>but is this something we want do for 1.2?

This change can't really break stuff, so I don't see why not.

**Comment by Umcaruje** [comment]
> but I want to know the majority of our users don't either.

Ok, so the results of the poll so far are like this: 
![screenshot from 2016-08-21 20 04 27](https://cloud.githubusercontent.com/assets/6282045/17839382/501e5fe2-67e6-11e6-8aed-d68ca428ac84.png)

As we can see, 71% of the users never, rarely, or just accidentally minimize their windows. The other 29% do it sometimes, and none of the users said they minimize their windows all the time.

Also the users that replied to the thread, either supported the removal, or said they wouldn't mind it.

**Comment by tresf** [comment]
This isn't a good poll.  The question is about the minimize button specifically, which the question doesn't specify.  There are two underlying questions:. Do you use it and should we remove it.  Answers like "yes, but accidentally" are bad as they don't illustrate any measurement for comparison.

Even a disclaimer "LMMS is considering removal of ...." following by a "how strongly do you feel.... " would be better.

Last, your summary of the very low 14 results focuses only on the statistic that benefits the removal.  If you are to properly extrapolate the 29% (now enough data IMO, but to do it properly) would illustrate that of our 500,000+ user base,  145,000 people use this feature occasionally.

How easy can this be configured to be re-enabled?  A configuration option would reduce the severity if those impacted.

**Comment by Umcaruje** [comment]
>How easy can this be configured to be re-enabled? A configuration option would reduce the severity of those impacted.

A configuration option that could get checked in the subwindow to set the appropriate flags should probably work.

What I'm more worried about is how this feature is broken. I tested this in 1.1.3 so I would be sure we didn't break the minimizing behavior with the subwindow enhancements:
![screenshot from 2016-08-21 22 21 51](https://cloud.githubusercontent.com/assets/6282045/17839633/f6d0966e-67ed-11e6-9cd4-e9efa32c6e07.png)

I managed to create a havoc by minimising and restoring a lot of windows. Not to mention that when you minimise the LADSPA Browser and the sample track effect window, you can't restore them, because their width becomes 8px rather than 120px

**Comment by DeRobyJ** [comment]
I agree the poll got too few votes.

We may create a setting about it.
By default, minization will be there, but you can open the settings menu and disable it.

I propose not to remove it completely, and if this setting solution is harder to code, I'd rather postpone the change.

**Comment by tresf** [comment]
> By default, minization will be there, but you can open the settings menu and disable it.

I think @Umcaruje's points are contrary to this statement and are about how important the removal of it is, as without removing this button, we have some rather severe bugs (albeit rare) to sort out.  i.e. Disable by default.

I like this forum response:

> I do minimise windows, probably just because it's traditional in Windows and it feels wrong to close a window when you just want it out of the way for a minute or two. But since minimised windows don't dock anywhere where you can easily find them again I don't think I'd miss the function too much if it went away.

> > > caLRo wrote:
> > I voted never. If LMMS is going to have a dock for minimized subwindows in a future update, I would consider using it.

> > Though with the function keys (f5,f6,f7 f9 etc..) pulling up the editors a la FL Studio, what's the point of minimize? It's way easier to just call them up and you can switch at will, with minimal clicking around

> It's called workflow....and everyone has their own preferred one. Personally I hate F-keys. On my laptop they're tiny and a pain to find in a hurry. Mouse clicks are much easier (for me).

> We're all different. That's why any decent DAW has options and choices ;).

So the consensus from these forums responses seems to be "No, but maybe if it worked properly".

It is true that the idea of closing and minimizing is blended in our UI and that is likely part of the confusion.

I still feel all points about the bugs are spot-on and we should disable it by default, I just can't speak on behalf of the users as I don't have data to represent the usage of this particular feature, so I think the option of re-enabling via preference/configuration option would eliminate most backlash that may occur from this change.

**Comment by DeRobyJ** [comment]
Should I change the title and description of the issue?

**Comment by tresf** [comment]
> Should I change the title and description of the issue?

I think it's just fine. :+1:

**Comment by jasp00** [comment]
IMHO, this should be "Remove or fix window minimization". If minimization is to keep, fixing the most annoying bug (open window in minimized state) is better than adding a new setting that allows broken behavior.

**Comment by grejppi** [comment]
> open window in minimized state

If this is fixed, wouldn't it make minimization then essentially the same as closing the window?

**Comment by jasp00** [comment]
If there was a window list widget, closing the window would remove it from the list, minimizing would not. A window list allows quick access for windows without keyboard shortcut, and helps with drag and drop. However, minimization is not necessary if there is a window list. Since the LMMS background is inactive (no context menu, no drag and drop to the background), there is little point in having minimization. Hiding animated widgets to reduce CPU usage would be a reason to keep it.

**Comment by SirBothersome** [comment]
> Last, your summary of the very low 14 results focuses only on the statistic that benefits the removal. If you are to properly extrapolate the 29% (not enough data IMO, but to do it properly) would illustrate that of our 500,000+ user base, 145,000 people use this feature occasionally.

@tresf , this is the second time now I've heard you bring up the half a million figure. I'm not trying to be cynical, but how did you come by this figure? Because judging by the size of our community, it would seem a lot smaller. We maybe have one hundred active SoundCloud users, the most people we've had on our forum is 61, and most of the conversation on the forum comes from some twenty odd users, (including @musikbear and me). I think it is important to look at the poll, because while it may not cover our entire user base, it does give some insight to our _active_ user base. And these are the people who are going to be using the bleeding edge.

**Comment by tresf** [comment]
> @tresf [...] but how did you come by this [half a million] figure?

Off-topic.  Download metrics [here](https://api.github.com/repos/lmms/lmms/releases) and unique site visits [here](https://cloud.githubusercontent.com/assets/6345473/17897470/57b808ce-6922-11e6-9d5f-e190c4367f5e.png).  How many people actually open up and use the software?  Who knows, but 0.5 million is a pretty good estimate, IMO.

> most of the conversation on the forum comes from some twenty odd users

Because they'd [rather use Facebook](https://cloud.githubusercontent.com/assets/6345473/17897661/f57f9d2e-6922-11e6-8c49-4137f7c4360b.png).

**Comment by tresf** [comment]
Let's go ahead and remove this Minimize button in the RC2 and see if people complain.  Sometimes it's better to ask for forgiveness than it is to ask permission.

**Comment by DeRobyJ** [comment]
Like the idea.
We may expressly say in the changelog that we're testing the UX without minimize, and we're open to discussion on it.
(in a better English than mine tho)
