### ISSUE TITLE
Previewing presets that contain effects doesn't work properly

### ISSUE THREAD

**Issue by TomoAlien** [LMMS/lmms#3053]
In 1.2.0-RC1, when previewing presets that contain effects, the preview crackles and with some effects (such as reverb or feedback) may cause the audio to get severely distorted. The easiest way to reproduce this bug is to preview the AudioFileProcessor preset Erazor, which quickly should clip to the point where no sound can be heard (I recommend lowering your speaker volume).

Changing buffer size doesn't help.
Changing the audio interface doesn't do anything either. I've set the device to dummy, and the oscilloscope displayed the same behavior.

This bug doesn't exist in 1.1.3.

I'm running Windows 7 64-bit, with a 64-bit build of LMMS 1.2.0-RC1.

**Comment by zonkmachine** [comment]
Hi!

Thanks for reporting this. I think it's issue #2434 that's been fixes for the next release.

**Comment by SirBothersome** [comment]
I just discovered in the current RC (not bleeding edge) that I'm getting a stuck note previewing a preset with a VST effect. Is this related at all?

**Comment by zonkmachine** [comment]
@TomoAlien 

I believe this is fixed in the latest release. Please reopen if you still can reproduce this. Latest release is 1.2.0-RC2 https://lmms.io/download/

> I just discovered in the current RC (not bleeding edge) that I'm getting a stuck note previewing a preset with a VST effect. Is this related at all?

I don't think so but there were more than one bug fixed with previewing over the last year. I just tested a preset with a VST effect under Linux/Wine and it worked just fine.
