### ISSUE TITLE
I can't hear any normal sound only weird noises...

### ISSUE THREAD

**Issue by KhABoooKIN** [LMMS/lmms#3061]
When i play any sounds i can only hear a weird 80's video game glitch like sounds or worse...  What can i do with this?

**Comment by Spekular** [comment]
We're gonna need more info.

What version are you on?
What sounds are you playing? (Samples? Plugins?)
Have you set up you audio backend in the settings?

**Comment by KhABoooKIN** [comment]
1. I'm using version 1.1.3 win64 .
2. All type of sounds... It can't play any sound normally.
3. I guess no?....

**Comment by Spekular** [comment]
Here's a screenshot of  the page I was referring to in question 3:

![image](https://cloud.githubusercontent.com/assets/8918426/19115764/72edad02-8b13-11e6-90e2-b459391d9183.png)

It should be under Edit > Settings and then the fourth button from the top. I remember having some trouble with this the first time I installed LMMS, and iirc the process I followed to get it working was:

1. Select your audio interface (SDL in my case)
2. Press ok
3. A popup will warn you that settings might not take effect until you restart LMMS
4. Save the default project. You can name it whatever
5. Close LMMS
6. Relaunch LMMS
7. Test to make sure sound works

If you don't know what audio interface to use, you'll have to repeat the process until you find the one that works. I'm sure there's another way to find out but I don't know what it is. SDL might work for you as well though, since I'm also on windows.

**Comment by tresf** [comment]
> When i play any sounds i can only hear a weird 80's video game glitch like sounds or worse... What can i do with this?

After making sure SDL is selected, reboot.  When all else fails with LMMS on Widows this usually fixes things.

**Comment by KhABoooKIN** [comment]
It works! Thank you so much! I really appreciate all the help i got! ^^

**Comment by BaraMGB** [comment]
Okay. I think, that one can be closed.
