### ISSUE TITLE
Error building  lmms  with clang

### ISSUE THREAD

**Issue by slacka** [LMMS/lmms#3073]
Building with clang results in:
`AutomatableModel.h:310:8: error: private field 'm_oldValue' is not used`

Full log:
http://clang.debian.net/logs/2016-08-30/lmms_1.1.3-3_unstable_clang.log

**Comment by tresf** [comment]
We no longer support the 1.1.3 branch, but I can confirm, [`m_oldValue` doesn't seem to be used](https://github.com/LMMS/lmms/blob/stable-1.1/include/AutomatableModel.h#L310).  It appears it was [replaced with a funtion-scope `oldValue`](https://github.com/LMMS/lmms/blob/stable-1.1/src/core/AutomatableModel.cpp#L302) yet never removed from the source header which seems to have been [reverted in master](https://github.com/LMMS/lmms/blob/master/src/core/AutomatableModel.cpp#L220), which is why no one else is seeing it.

Feel free to submit a patch if you wish. 👍

**Comment by jasp00** [comment]
Do you use the Debian version? Then why do you not fill the bug in the Debian BTS? Another bug in my task list.

**Comment by tresf** [comment]
Closing. @slacka please reopen if you're able to reproduce this problem on master branch.

**Comment by jasp00** [comment]
Reproduced with Clang 3.8.1. I have fixed LMMS 1.1.3 for Debian, so I believe I can handle this issue. Should we add to Travis a Clang build on Linux?

**Comment by tresf** [comment]
>  Should we add to Travis a Clang build on Linux?

Yes, please.  [OpenBSD packages our software against Clang](https://github.com/LMMS/lmms/pull/2690); It'll help discover bugs earlier.

**Comment by zonkmachine** [comment]
I believe this was fixed for 1.2 in 44f1d3df85afba439706ec01cc2b4b877a368001.
