### ISSUE TITLE
freezes when loading or saving large files

### ISSUE THREAD

**Issue by gryffn** [LMMS/lmms#3123]
please fix this lmms team i lost 3 days of hard work because it crashed when i saved

**Comment by gryffn** [comment]
also could you add an auto save feature

**Comment by liushuyu** [comment]
What operating system are you using and which version of LMMS are you using?

What LMMS instruments you have used?

**Comment by liushuyu** [comment]
We do have auto save feature, but not enabled by default. In addition, this feature has some known defects and we would like to implement a new one sooner or later.

We are sincerely sorry for the loss.

**Comment by musikBear** [comment]
> i lost 3 days of hard work because it crashed when i saved
..surely you mean 3 hours? If you use software 3 days and do not save for ..3 days, i would strongly suggest a different way to work.
However, you may like to read lmms' fail and rescue guide, because if you infact DO have a saved file, but that file simply wont load, then it is very possible that the notes can be saved, with one of the tricks in that guide. Furthermore, if you fail, and still DOES have a file, you are welcome to IM me on the forum, and i will try to rescue your data, if any exists.
Fail-guide: https://lmms.io/wiki/index.php?title=Working_with_VSTs#VST_related_problems
Forum: http://lmms.io/forum/index.php

**Comment by BaraMGB** [comment]
I close this because of not answering within 2 months. If you can provide more information about this issue feel free to reopen it.
