### ISSUE TITLE
MIXER - Rename Channel With F2 Hotkey Or Maybe The Enter Key

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3157]
Hello Everyone,

I was wondering what everyone thought about assigning the F2 button as a hotkey when MIXER is selected to rename the channel label?  Following the Windows standard of using F2 to rename things.
Or maybe even using the "Enter" key (which I would prefer over F2) might work nice because you can use the Enter key to close the "Rename FX Channel" dialog box already as well so it might be a smooth use of it hitting ENTER to enter the rename and then ENTER again to close it.

Just a thought

**Comment by tresf** [comment]
I really like both shortcut proposals for rename as they are widely adootrd.  Note... Enter Key.... I've only seen this rename shortcut in use on Mac.

**Comment by tresf** [comment]
In addition.... How they apply to LMMS depends largely on how intuitive it is to make something have focus and then a subsequent key press. In most cases a double click will do the trick which seems OK. I consider F2 an advanced user shortcut and not something the average user would even attempt, so this would really have to have multiple uses throughout the software -- not just mixer -- to make it a worthwhile addition.

**Comment by BaraMGB** [comment]
F2 👍

**Comment by SirBothersome** [comment]
>  I consider F2 an advanced user shortcut and not something the average user would even attempt,

I can't find the screenshot at the moment, but some people also have really tiny function keys, and do not like using them. I do believe that LMMS could use more keyboard shortcuts though

**Comment by tresf** [comment]
> some people also have really tiny function keys, and do not like using them

Many modern computers have [re-used the F1-F12 keys for other functions, requiring the pressing of an `Fn` key simultaneously](https://cloud.githubusercontent.com/assets/6345473/21267023/7c1fb4ce-c376-11e6-8705-ec67b6e65843.png).  Perhaps this is what you're describing.  This would be a vote in the direction of also supporting a secondary shortcut such as `Enter` however a full evaluation of the various input fields should be done.  

For example
 * It is difficult to apply this concept to a track label, since clicking the track name opens a new dialog (would then this new dialog respond to rename?).  
 * We support the renaming of patterns (such as a single piano roll segment), which have to be right-clicked.  How would F2 be applied?
 * The left file browser -- The files can be dragged into the editor.  Should we add more shortcuts to that area and if so, should we allow preset renaming directly through the DAW like that? 

Note, the Open dialog currently DOES allows renames based on the current OS shortcut (`F2` on Windows, `Enter` on Mac, etc).

![screen shot 2016-12-16 at 10 06 29 am](https://cloud.githubusercontent.com/assets/6345473/21267225/75771670-c377-11e6-9bf9-475d6d31f8c3.png)

**Comment by SecondFlight** [comment]
Closed via https://github.com/LMMS/lmms/pull/4348
