### ISSUE TITLE
Windows RC2 - Mallets won't load - Stk installation missing 

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms#3227]
![image](https://cloud.githubusercontent.com/assets/6282045/21772041/fdd0dc52-d689-11e6-964a-76c2559c27d1.png)

I got the same message on my linux computer, but fixed it by installing the `stk` package which was not installed. This is probably related to our build system.

**Comment by SirBothersome** [comment]
@Umcaruje what build? Windows 10 x64 loads just fine
![mallets](https://cloud.githubusercontent.com/assets/20342439/21773341/a5bb6ba4-d65c-11e6-8337-f05da66080f1.PNG)

**Comment by Umcaruje** [comment]
It won't load on windows 10 x64 rc2 for me. Weird. Maybe there is something leftover from the previous installation.

**Comment by tresf** [comment]
@SirBothersome please do a full uninstall before filing bugs.  @Umcaruje this may be a bug with the windows packager.  If the RAWWAVES aren't there, it throws this message.

Generally when default directories are screwed up, it's because the user failed to uninstall the previous version.   We really need to do a better cleanup job prior to a fresh install on all platforms.  Removing `%userprofile%/.lmmsrc.xml` generally fixes these things.

If the RAWWAVES are missing, it's a bug with the Windows packager.  If they're there, you need to get in the habit of uninstalling prior to reinstalling (and we should track all of these cleanup efforts for the various platforms).

Indirectly related #638, #2933, #1656, https://github.com/LMMS/lmms/issues/1649#issuecomment-70505400

**Comment by Umcaruje** [comment]
Actually, I just realised I didn't even have LMMS installed on this windows system, as I've recently reset it. 

Aaand the stk folder is missing from the data folder in RC2:
![image](https://cloud.githubusercontent.com/assets/6282045/21780790/35bd9ad8-d6ad-11e6-912c-92907b1c0863.png)


It probably works for Leche because he has the rawwaves dir set to some older version. I just checked RC1 and it has the stk folder.

**Comment by tresf** [comment]
> If the RAWWAVES are missing, it's a bug with the Windows packager. 

It is. I'm not sure how this was [ever working in 1.1](https://github.com/LMMS/lmms/blob/stable-1.1/data/CMakeLists.txt#L18) actually.  There must have been a task to copy the `.raw` files to the install (`../target` AKA `CMAKE_INSTALL_PREFIX`) folder, but I can't find any evidence of it and it doesn't make any order of operation sense.

A better permanent home for this logic would be to write this into the `plugins/stk` CMakeLists.txt file and handle [Apple](https://github.com/LMMS/lmms/blob/master/cmake/apple/install_apple.sh.in#L48), Windows and Linux bundled installers in one fellow swoop.

```diff
-FILE(GLOB RAWWAVES "${CMAKE_INSTALL_PREFIX}/share/stk/rawwaves/*.raw")
-LIST(SORT RAWWAVES)
-INSTALL(FILES ${RAWWAVES} DESTINATION "${DATA_DIR}/stk/rawwaves")
+IF(LMMS_HAVE_STK)
+	FILE(GLOB RAWWAVES "${MINGW_PREFIX}/share/stk/rawwaves/*.raw")
+	LIST(SORT RAWWAVES)
+	INSTALL(FILES ${RAWWAVES} DESTINATION "${DATA_DIR}/stk/rawwaves")
+ENDIF()
```

**Comment by miketurn** [comment]
I apologize, but I am quite confused.
I am experiencing the same issue on Windows 7 (64Bit) with LMMS 1.2.0 RC2 (32Bit).
(I did a complete uninstall and I deleted the lmmsrc.xml)
From what I understand, this issue is closed because it has been fixed in the sense that it will be in a future release.  I am a little unclear, is there a way that it can be manually fixed, that copy something from the 1.1.3 or 1.2.0 RC1?
Thank You

**Comment by tresf** [comment]
@miketurn a temporary workaround until RC3 is released is to install LMMS 1.2-RC1 and then install LMMS 1.2-RC2 over the top.

**Comment by Rossmaxx** [comment]
i experienced the same issue on the latest master and wrote an issue for it #6464. was searching for stk installation and found this closed issue instead.

**Comment by tresf** [comment]
> i experienced the same issue on the latest master and wrote an issue for it https://github.com/LMMS/lmms/issues/6464. was searching for stk installation and found this closed issue instead.

A long time ago, `MINGW_PREFIX` was the only way to know where files existed when targeting Windows.  Fortunately, MSVC has improved upon this, but the old prefixes need to be updated to use either an MSVC conditional or a MINGW conditional.

In the case of STK, it [has a formula ready on vcpkg, so I'd look there first](https://github.com/microsoft/vcpkg/blob/66045de4dcc5da3d1029c02b606307f5951dcb22/ports/libstk/portfile.cmake#L31), quoting:

```cmake
file(GLOB RAWFILES ${SOURCE_PATH}/rawwaves/*.raw)
file(COPY ${RAWFILES} DESTINATION ${CURRENT_PACKAGES_DIR}/share/libstk/rawwaves)
```

@DomClark or @PhysSong should have experience with how MSVC environment prefixes.  Otherwise, it will look something like this:

```cmake
 IF(LMMS_HAVE_STK) 
    IF(MSVC)
        # MSVC uses "share/libstk"
 	FILE(GLOB RAWWAVES "${<<FIXME_CURRENT_PACKAGES_DIR>>}/share/libstk/rawwaves/*.raw") 
    ELSE()
         # MINGW uses "share/stk"
         FILE(GLOB RAWWAVES "${MINGW_PREFIX}/share/stk/rawwaves/*.raw") 
    ENDIF()
 	LIST(SORT RAWWAVES) 
 	INSTALL(FILES ${RAWWAVES} DESTINATION "${DATA_DIR}/stk/rawwaves") 
 ENDIF() 
```

**Comment by anytizer** [comment]
[Reference](https://filipe-teixeira.com/2017/10/missing-files-from-stk-on-lmms/)

Folder [data]/stk/rawaves is missing. Replace it and it works.

Other findings:

- Rename .lmmsrc.xml file.
- Close LMMS and reopen it.
- In the configuration window, you do NOT see options to enter stk path.

In the newly created .xml file, the xml appears.
`<paths stkdir="data:/stk/rawwaves/"/>`
