### ISSUE TITLE
Use tittlebar for showing FX channel name information

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3239]
The problem around labels in FX-Mixer could be solved, if the tittle-bar was used : 

![fxmixer-preset-area](https://cloud.githubusercontent.com/assets/6662066/21814564/fa049c96-d759-11e6-8464-9de90fc2dc4a.PNG)
Alternatively, but with more complexity 
![mainwinfo](https://cloud.githubusercontent.com/assets/6662066/21851619/30d3d67c-d810-11e6-83e9-9b7c8d1650ba.PNG)
That field should be used for all kind of info (as in Fls)

**Comment by mikobuntu** [comment]
Other methods :- 

(1) There is plenty of space below the Mixer strips to show longer text. 

(2) Use Continuous scrolling of the text in the FX strips. I imagine the scrolling only to be needed if the text exceeds a certain number of characters to save on CPU cycles.

**Comment by Umcaruje** [comment]
>(1) There is plenty of space below the Mixer strips to show longer text.

The padding was removed

>(2) Use Continuous scrolling of the text in the FX strips. I imagine the scrolling only to be needed if the text exceeds a certain number of characters to save on CPU cycles.

I find constant scrolling hard to grasp, and I think there will be readability issues since the text is vertical

I quite like this idea, to be quite honest, it uses the current real estate, and it is kind of consistent with the Piano Roll, where we show the name of the currently edited pattern.

**Comment by tresf** [comment]
To be consistent, it will be `FX-Mixer - Master` (dash, not colon).  Also, unrelated, but we don't need dashes in our window titles.  We need to make that consistent too.

**Comment by tresf** [comment]
Here's a mockup from 2017:

![screen shot 2017-01-11 at 6 51 41 pm](https://cloud.githubusercontent.com/assets/6345473/21871283/309273a2-d82f-11e6-976d-1b41d26a56f4.png)

**Comment by mikobuntu** [comment]
@musikBear 's proposal does make good use of otherwise wasted real-estate . 
* Just noticed that in the latest master branch, that the text string no longer exceeds beyond the FX channel LED, like in @musikBear 's image. :+1:

**Comment by miketurn** [comment]
**PLEASE CONSIDER THIS**

Hopefully this opinion will be considered, especially since this very idea was birthed on my own turf! :)
MIXER - Length Of Channel Labels #3156

As I mentioned in the thread above I personally don't like how that looks, to me it looks like it doesn't belong there, because it makes the text off center and would kind of clutter up the clean new look implemented in 1.2.0 RC2.

I do however like the idea of making use of that space and I think I have a good idea/compromise.
You put an on/off option in the LMMS Settings called something like......
"Replace FX Mixer Title with Selected FX Mixer Channel Name"

This way you don't have an odd amount of text items in the title bar.
I would probably LEFT justify the text as shown here 
(the two white vertical lines are an idea of what to align the text to)
![mixer title bar channel name edit](https://cloud.githubusercontent.com/assets/24556082/21909887/caa1ec62-d8e7-11e6-9c64-3f7ac299c2a0.JPG)

This actually might go great with another idea I was thinking about (which I will reference when I post it) concerning the label lengths.

**Comment by tresf** [comment]
> You put an on/off option in the LMMS Settings called something like......

I'm never a fan of burying GUI preferences in the settings dialog (they should be a right-click menu, if any).

> This way you don't have an odd amount of text items in the title bar.

What?  I don't know what you're saying, but we do that in other areas.

**Comment by miketurn** [comment]
If this title bar channel name gets approved, I personally would eliminate the hovering tag, that shows the select mixer channels name.
This name tag can get a little distracting, it also shows up even for channels that don't get cutoff with "..." at the end.  

If others want this name tag to stay, then maybe the code can be changed so that this tag only shows up when you hover over labels that cutoff with the "..." at the end?  If such coding is possible and desired.
Just an idea.

Here is a picture of the tag that I am speaking of......
![mixer channel name dropdown tag](https://cloud.githubusercontent.com/assets/24556082/21910377/b9411770-d8e9-11e6-94a1-f43a25677144.jpg)

**Comment by miketurn** [comment]
@tresf    
> I'm never a fan of burying GUI preferences in the settings dialog (they should be a right-click menu, if any).

Even better, I agree with having options specific to a window, be in that windows specific context menu.


> This way you don't have an odd amount of text items in the title bar.

> What? I don't know what you're saying, but we do that in other areas.

(First off, I am in no way trying to argue with you, hard to convey that with typing, I think the work you do is amazing)
I don't think I have seen any of the title bars contain any other info other their that windows title, especially in the main components (mixer/songeditor/b&b editor)
Is there an example where this is done in other windows I can take a look at for reference?

The "odd amount of text" I was referring to is that in my own opinion, it might be weird because
(based on the image provided by musikBear at the top of this thread) 
(note it is hard to tell the justification of that text from that picture)

1.) If the "FX-Mixer" label remains centered and the proposed channel name goes after that it would be off centered if the "FX-Mixer" label remains static at the center of the title bar and the channel name is shown after it.
2.) If the entire label gets centered "FX-Mixer - <Channel Name Here> then it seems like you would see a lot of movement in the title bar when selecting channels.
3.) Even if the text is left justified, if a user is looking for the channel name in the title bar, it might be a little confusing/unnecessary to always have to see the "FX-Mixer - " prefix when trying to read it.
4.) Also may be a little confusing if someone labels channel names for example "Drums - Snare" then you would see "FX-Mixer - Drums - Snare".

Again, just my opinion I am not trying in any way to step on anyones toes.

**Comment by tresf** [comment]
@miketurn please re-read https://github.com/LMMS/lmms/issues/3239#issuecomment-272032491

**Comment by Umcaruje** [comment]
>This way you don't have an odd amount of text items in the title bar.
I would probably LEFT justify the text as shown here

No. It won't be consistent at all with other windows, and a seperate settings option is an overkill

>1.) If the "FX-Mixer" label remains centered and the proposed channel name goes after that it would be off centered if the "FX-Mixer" label remains static at the center of the title bar and the channel name is shown after it.

Look at @tresf's mockup please, as it is more close to how this feature would look coded up, and the text is perfectly centered

>2.) If the entire label gets centered "FX-Mixer - then it seems like you would see a lot of movement in the title bar when selecting channels.

That's a valid concern but I don't know how it might affect my workflow until I code it and test it.

>4.) Also may be a little confusing if someone labels channel names for example "Drums - Snare" then you would see "FX-Mixer - Drums - Snare".

Maybe we could implement something like `FX Mixer [Master]` and do it in the piano roll too. 

I also think we should drop the FX from the Mixer, it's completely unnecessary in my opinion.

**Comment by tresf** [comment]
> think we should drop the FX from the Mixer

👍 

> > If the entire label gets centered "FX-Mixer - then it seems like you would see a lot of movement in the title bar when selecting channel
> That's a valid concern but I don't know how it might affect my workflow until I code it and test it.


![untitled](https://cloud.githubusercontent.com/assets/6345473/21913964/168752d2-d8fe-11e6-853c-ff158127a086.gif)

**Comment by miketurn** [comment]
@tresf 
I agree with the removing of the "-" from titles such as Song-Editor and Piano-Roll
and I was going to mention removing the "FX-" from the FX-Mixer title as well.
(You mentioned it was alright for me to edit text items I found, but am I right in saying that these are not items I can edit like the others without approval?)

To Anyone,
All the other windows can have multiple instances, so for example the piano roll showing "Piano Roll - Bitboy" will make more sense.

There can be only one Mixer so having "Mixer - " in front of each channel name wouldn't really be necessary.  The only reason I mentioned making a "setting" for it was to keep the consistancy, so that each window has the same centered title, but for those who are know it is a mixer :) can check off that option and get functionality out of that title bar space.

The only reason I mention to Left Justify it was because you will scroll through mixer channels a lot more than you would piano rolls, so looking in just one place where the text is left justified the beginning of the label will always be in the same place which would be easier in my opinion to look at and read.

If I knew I was going to be typing so much regarding this issue above, I would have spent more time creating a graphic and posting an idea that will make this above topic regarding label length obsolete :)
It is a relatively simple idea and it is going to rock all your worlds!  I will be back tomorrow!
(I am just messing around, but I do have an idea which hopefully others will agree with)

**Comment by tresf** [comment]
> All the other windows can have multiple instances, so for example the piano roll showing "Piano Roll - Bitboy" will make more sense.

Not true.   GIF above.

**Comment by miketurn** [comment]
@tresf 
Ahhh, I forgot that it is just one instance, but in this case the piano roll gets the titlebar name of the instrument because that entire window at that moment belongs that specific instrument.  In the case of the mixer, all the channels share that title bar.

Not only did I forget about the piano roll only having one instance, but on top of that I combined BitInvader and Freeboy in my brain and called it "Bitboy" :)

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
