### ISSUE TITLE
Idea - Generic Touch Device Support

### ISSUE THREAD

**Issue by felixkah** [LMMS/lmms#3267]
Hey, i have some ideas about features and would like to know if these are already present or if any developers are interested in joining me in creating the idea. I am a programmer myself, but I have no knowledge of the projects code;-) I would love to help by developing or leading development

One Idea would be to use VNC or X11 Forwarding to connect from the phone to the hosting computer via local wireless connection and programming a touch interface to use with the synthesizer interface. this would be set up like midi or be preconfigured. Early versions don't require an app, just a set up of the vnc viewer connection on the phone. Set up of the server (pc where lmms runs) can be done via script. Well and the coding of the Feature would be fun;)

Anybody interested? And if this is not a new idea, how is it done?

sincerely,
efkah

**Comment by tresf** [comment]
> One Idea would be to use VNC or X11 Forwarding to connect from the phone to the hosting computer via local wireless connection and programming a touch interface to use with the synthesizer interface. 

Can't you just do this now? BTW, X11 forwarding will eventually be harder to use on PCs once Wayland and Mir start shipping.

**Comment by tresf** [comment]
> i'm not only not familiar with the code i am also not familiar with the command line.

And you know what X11 forwarding is?  Bollocks. ;)

> I am thinking of having like a server with LMMS running and you can assign different lines in the song editor to different devices.

The closest you're going to get to that is a [network attached midi controller](https://lmms.io/forum/viewtopic.php?t=5051) which should be available for Android and iOS in various formats granted we get [better MIDI support](https://github.com/LMMS/lmms/issues/1472).

Regarding the display export, it won't work unless you export the whole app and it'll suffer latency and screen size issues.  We don't run the vast majority of instruments in a separate process and those that we do run in a separate process aren't setup for inter-process communication with 3rd party apps.  Besides, [X11 export can get very slow](http://unix.stackexchange.com/questions/187415/why-is-firefox-so-slow-over-ssh).

Since this is just a general question, I'm closing it out (too general, no work to be done).  Feel free to name a specific technology or design and reopen if needed. 👍

**Comment by felixkah** [comment]
Well then saying i'm not familiar with the AppStore and the MIDI Development is maybe more trueish.
Also thanks for the x11 firefox issue link, good thing to know;)
But my first intention was to open a vnc display with geometry of the touch client and xmove a  plugin-window to there at fullscreen. Or opening a Threaded server on an arbitrary port and start an external app to be forwarded or even be run directly. but i guess thats what ipMIDI does.
I hope to keep skipping by here though!

**Comment by tresf** [comment]
> But my first intention was to open a vnc display with geometry of the touch client and xmove a plugin-window to there at fullscreen

You should be able to do that today at least with the LMMS process.  If you have a spare Windows machine, xming + putty with X11 forwarding for windows is a good way to test it out, you just need to set the `DISPLAY` variable to the target machine, usually with the `export` command.

**Comment by felixkah** [comment]
i'm using linux only, i think i understand what you say, problem seems to be that lmms is a single window? there is no seperate process running for the synth as you said and i cannot just move the plugin out of the lmms window.

**Comment by tresf** [comment]
> there is no seperate process running for the synth as you said and i cannot just move the plugin out of the lmms window.

Correct and the chances of a desktop-UI instrument or plugin playing nicely with a touch-only mobile device are so slim that the request is only good conceptually.  It would be much better use of time to just get MIDI working better and have some tutorial on how to install and configure LMMS with the most common of touch devices as DAW remotes.
