### ISSUE TITLE
Kontakt VST (among others) crashes after reloading the project

### ISSUE THREAD

**Issue by Mark-Agent003** [LMMS/lmms#3274]
I have been using LMMS for a while now, and it's a very usefull program. The biggest problem I have is that there are a few vst's that will crash LMMS. At first they will load, but after I save the project and open it again, it crashes. And it usually pops up an error saying something about the Maize sampler player was unable to load this instrument. If more information is needed, let me know!

P.S. I use Windows 10

**Comment by tresf** [comment]
Thanks for the bug report.

Possible duplicates #109, #1008.
Possibly related: #1183, #493, #607

Since the other "Kontakt" bugs are all closed and this seems to be a popular plugin, we'll leave this one as open.

**Comment by projectpitchin** [comment]
Hello, @Mark-Agent003.

I'd love to get some more specific information if you'd be willing. It might shed some light on all of the issues that @tresf mentioned. First, I'd like to get a list of the plugins that you've had trouble with, broken down into three groups:
- "Crashes": When you try to load the saved project, LMMS vanishes and no longer appears in the "Apps" list in the Task Manager. (If you see RemoteVstPlugin somewhere in the Task Manager, kill it and let us know that too!)
- "Hangs/Freezes": The program gets stuck during some step of the loading process, and no further interaction with it is possible. There may or may not be a message telling you about the failure. You'll have to kill it from the application list in the Task Manager. I'm not super familiar with Windows 10, but you may have to kill the RemoteVstPlugin process separately.
- "Failures": The save file fails to load, and you receive a dialog box to that effect. After dismissing the message, you are able to interact with LMMS normally.

On top of helping us understand these issues better, we can use this information to update [the list of tested VSTs.](https://lmms.io/documentation/Tested_VSTs)

Thanks!

**Comment by Mark-Agent003** [comment]
It has always been it hanging up/freezing so far... Yes, I have noticed that RemoteVstPlugin.exe stays in Task Manager even after I close LMMS after it freezes. I always close it down though. Here's the list of plugins I have that work:

4Front_Bass
4Front_Piano
4Front_E_Piano
4Front_Rhodes
MT Power Drum Kit 2
DSK Brass
DSK_ElectriK_GuitarZ
DSK_Strings
fnequalizer
Kontakt_5_Player
MDA_Piano
Orchestral_Strings_One
Synth1

Here's the list of VST's that have frozen LMMS:

Kontakt 5 Player
DSK_Guitar_Acoustic
DSK_Saxaphones
DSK_AcoustiK_Keyz
Marimbaphonic

**Comment by tresf** [comment]
@Mark-Agent003 you've listed `Kontakt 5 Player` as both working and frozen sections. :)

**Comment by Mark-Agent003** [comment]
@tresf Oops. Fixed it. 😆

**Comment by projectpitchin** [comment]
Based on your lists and the lingering RemoteVstPlugin process, this looks like another manifestation of issue #1008. 

I'm excited by the fact that it looks like those DSK VSTs work with LMMS on Linux, and once worked on Windows! That's according to [the LMMS website](https://lmms.io/documentation/Tested_VSTs) and this old Youtube video: [Free VSTi Acoustic Guitar Work With LMMS Linux](https://www.youtube.com/watch?v=n-TzUcU1DxM)

Interestingly, neither source mentions the problem you're seeing. Unless the docs are incorrect, that rules out the possibility that the DSK plugins have never worked on Windows. (I'd love to know when these instruments were listed on the site, but I wasn't able to find that page on github. Am I missing something?)

If that holds, then some change happened in the code base that caused this issue to appear in Windows. On top of that, while the video shows DSK working on Linux on July 13, 2011, we don't have proof that it works _now_. 

Further supporting evidence for this issue being the side effect of a change is provided by the difference between issue #109 (reported Jan 23, 2014) and issue #1008 (reported July 18, 2014). While the report for #109 is vague, the program still appears to function, even though the GUI did not load completely. I will note that this is further than I ever got when observing #1008.

A good first step would be to try the DSK plugins out in Linux. My Linux partition is way out of date and I've been thinking of reinstalling for a while (feeling like Mint at the moment), so I'd rather not make a promise for this weekend. If someone else could try it out, that would be great, otherwise I'll be able to swing back around to it.

Thanks for your help, @Mark-Agent003!

**Comment by projectpitchin** [comment]
I just realized I could also try to grab an old version of LMMS to see if #109 can still be reproduced on an updated Windows 7. If I can make that happen, it would reduce the chance that a change to the OS itself is at the root of this. I'll also try to reproduce this issue on the master branch.

**Comment by tresf** [comment]
DSK Elektrik Keys [is working fine on Windows 10 x64, 1.2.0-rc2](https://cloud.githubusercontent.com/assets/6345473/22171399/346e6494-df5b-11e6-8b4a-40af27a2669f.png)

**Comment by tresf** [comment]
Sorry, my mistake... It was `AkoustiK KeyZ`.  Well that also [is working fine on Windows 10 x64, 1.2.0-rc2](https://cloud.githubusercontent.com/assets/6345473/22171436/1054167a-df5c-11e6-8ee1-d897867e95d0.png)

**Comment by projectpitchin** [comment]
I'm still seeing [Kontakt 5 Player hang on Windows 7 x64, 1.2.0-rc2.13.](https://cloud.githubusercontent.com/assets/22012635/22171642/d69121f2-df57-11e6-9197-7fadc96111ca.jpg)

**Comment by Mark-Agent003** [comment]
I haven't tried any of the ones on my list inside 1.2.0-rc2 yet except kontakt

**Comment by projectpitchin** [comment]
Hm, I'm still getting the following message in the terminal when I try to load the DSK instruments, after which I can interact with the rest of LMMS but have to kill the application to return control to the terminal:
"remote plugin died! invalidating now.
Remote plugin 'C:/msys64/home/Notroot/lmms/build/plugins/32/RemoteVstPlugin32.exe' not found."

Not sure why it's even looking for that file, really. @Mark-Agent003, I'd be curious to hear if you get the same results as @tresf for your DSK instruments on 1.2.0-rc2.

**Comment by tresf** [comment]
@projectpitchin please see here: https://github.com/LMMS/lmms/blob/master/plugins/vst_base/CMakeLists.txt#L19

**Comment by projectpitchin** [comment]
Ah, good to know! I should probably fix that. I can confirm that the DSK instruments loaded and reloaded on Windows 7 with the install from the website (cross-compiled, I presume?), while Kontakt 5 Player still failed in the way described before.

**Comment by tresf** [comment]
> cross-compiled, I presume

Correct.  All Windows installers have (always) been made with the Linux version of Mingw.  The msys2 environment is a very recent addition (and quite buggy).  Please improve this as you see fit. 👍

**Comment by musikBear** [comment]
I was writing an explanation of a  method i used to 'preserve' vst-settings, to zonkmachine here: 
http://lmms.io/forum/viewtopic.php?f=3&t=8361#p26858
-and it then struck me:
Why do lmms attempt to save vst settings? Why not save its *own* settings!
The problem with lost setting in vsts could perhaps be solved by using the *dial-array in lmms* instead of the dial-values in the vst *chunk*.
The fail happens typically when the chunk is bloated to *absurd* size #493, but that could be omitted :

If a save would make lmms read out all the VST dial setting and sets all of the dials in lmms dial array to those Values and then save the values of the lmms instead of the chunk from the VST then the values would be natively lmms values and the problem with the chunk could be omitted
So there wouldn't be any saving of the VST values, instead lmms would be saving the values from the lmms-dial-array
This method depends on a way to synchronize from vst to lmms-dial-array
Some vst's would most likely still be non-accessible, namely the ones that appears in lmms-dial-array as *blanc* -eg where the dials are with no legend (like zasfx-vst or Crystal)

**Comment by Mark-Agent003** [comment]
Any way I can help?

**Comment by tresf** [comment]
> Any way I can help?

Yes, debugging the chunk of VST data would be stellar.  I don't think this is a big bug, just a matter of troubleshooting the loading process.

**Comment by projectpitchin** [comment]
It sounds like the proposal is to avoid the chunk entirely where possible, but seeing the file format might still help. If you're interested in viewing the chunks produced by each VST, you can look at them using the uncompressed LMMS project format, .mmp (vs. .mmpz). [I've attached an example of a project that fails to load in the binary release of 1.2-rc2.](https://github.com/LMMS/lmms/files/721590/uncompressed_kontakt5p.txt)
 (Converted to .txt to load onto GitHub.)

In my experience, modifying the chunk didn't have a visible effect on the Kontakt 5 issue specifically, but it would be nice to have someone else make sure. I explored that in a bit of a mad science manner by removing the chunk or swapping it with the chunk of a file that loads to see the effects on both. I don't know how to interpret the value myself, but I'm sure someone here can point you in the right direction.

**Comment by Mark-Agent003** [comment]
I'll get right to debugging it... After someone tells me how to

**Comment by musikBear** [comment]
doubt anyone can read chunk content

**Comment by Umcaruje** [comment]
```

**Comment by Umcaruje** [comment]
```
~	hsinV4tbMM/ZDSINvHDSINjDSIN
bep000DSINuhsinAy9EqBK|DSINuJDSINsDSINhsinvDI,C1%DSIN4KINhsin[H]ryZF4KINkDSINe4DSINjDSIN	5.5.2.880DSINlhsinKBT|DSINlDSIN
New (default)Kontakt\@color0\@devicetypeflags1\@soundtype0\@tempo0\@verl1.7.7\@verm1.7.7\@visib0DSINyhhsin!2B2q8DSINyDSINDSINthsinj&YB-zj<fDSINtMDSINsDSIN.
.
` hsin@@PG]u0n@ DSIN@#@@m   @#SgQIyF'7@/g@#b7H 	s @*@?@
New (d 	fault) ;G # @@``!`w>$`A
 
  `    @     Ar @     @cAp s"."1"#B2P@0hCRxh@Xh2 BXh3 h@Xh4 fDIh7HDa;@@@@@B} z@G	/E/EE(F7EPEdExEEEEEEFFF,F@FTFhF|FE 
!"#$%&'()H+/,-./0123456789:;<=>*@
I'>D@ 
eEEEEEmEYEEE1EE	DCK`G
be4KIN:hsin,HRliO
4KINDSINc75noKXgwp	5.5.2.880
```

Not sure how helpful, but here's that chunk base64 to ASCII decoded. There is def some info about kontakt, but the rest is gibberish.

**Comment by tresf** [comment]
> Not sure how helpful, but here's that chunk base64 to ASCII decoded. There is def some info about kontakt, but the rest is gibberish.

Probably more valuable to post the base64 encoding bin or the bin file itself.  I'm not sure if all VST chunks are created the same or if the authors are allowed to read the binary back in anyway they wish.  Note if the actual saving/loading is causing the problem we may have something as simple as an encoding/decoding problem.

> If a save would make lmms read out all the VST dial setting and sets all of the dials in lmms dial array to those Values and then save the values of the lmms instead of the chunk from the VST

Don't be presumptuous.

**Comment by musikBear** [comment]
> Don't be presumptuous.

You forgot that i wrote:
> This method depends on a way to synchronize from vst to lmms-dial-array

I thats not possible, then my idea wont work
