### ISSUE TITLE
Rename "FX-Mixer" to "Mixer"

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3300]
Rename "FX-Mixer" to "Mixer"

With LMMS, windows titles come with heavy debate, not my decision to make, but I noticed that this was mentioned in a few other posts, so I figured I would give it its own platform for debate, as other possible window name changes have....

Rename "Beat+Bassline Editor" to "Pattern Editor"
Rename "Song Editor" to "Sequencer"

**Comment by BaraMGB** [comment]
I'm not happy with the renaming of editors in lmms. The names are historical grown. Lmms has it's own language and renaming at this point of developing makes things not easier.

**Comment by musikBear** [comment]
Not to mention all the edits that would be necessary in docs
The same discussion has been chewed for song-editor
No to renames imo

**Comment by miketurn** [comment]
Oh man so I will have to continue to say "Beat+Bassline Editor" for the foreseeable future....
:)

Not sure who makes the final decision, should I close this?

**Comment by jasp00** [comment]
>I will have to continue to say "Beat+Bassline Editor"

You may say BB editor.

>should I close this?

You may reopen if you find a good reason; e.g., convention about glossary among popular DAWs.

**Comment by BaraMGB** [comment]
Can we close this issue or are there more options on that?

**Comment by tresf** [comment]
It'll be Mixer.  The word "FX" provides absolutely no contextual significance unless the creator of it is named "Francis Xavier".  "FX" needs to be dropped in the DAW as do many other naming conventions including "Beat/Bassline" which is incorrect and misleading.  We can't decide to hang on to bad words out of convention alone.

**Comment by tresf** [comment]
I'll elaborate a bit...

**Mixer**
 * The main purpose of a mixer is to mix levels.  This is apparent visually in LMMS and all other DAWs because the mixer's largest UI component on first load is the up/down volume sliders as well as the DB visual.  When mixing a track, mixing is paramount. 
    * An additional feature of a mixer is to offer (currently missing) [panning capabilities](https://github.com/LMMS/lmms/issues/1974#issuecomment-275576502).  Vocoder [can't work without it](https://github.com/LMMS/lmms/issues/1202) due to FX+Midi limitations and panning is a feature every mixer has.  I strongly feel panning is NOT an effects plugin but rather a basic mixing feature.
   * Yet another additional feature of a mixer is to offer Effects.  Although Effects are already available on the instrument, organization places them on a channel to avoid redundancy.  Any channel or track should be allowed Effects.  Since we don't call instruments "FX Instruments", I see no argument to call the mixer "FX Mixer".  I strongly feel "FX" doesn't belong in the name.

**Beat/Bassline**
 * Historical or not, this is a throwback to the original purpose of BB Editor -- to play the beat while the rest of the song plays the notes.  History has shown, this isn't how people use it (nor should developers juristic this).  It needs improvement (#453, #454) but shouldn't be limited by its name.   A Beat/Bassline does suffer some limitations currently but long-terms should be an easy way to add variant patterns to the Song Editor regardless of whether home to an actual Beat or a Bassline.

**Comment by musikBear** [comment]
This has bearings to the recent talk about a whole new documentation, but it will be a mess, nomatter how it is done, because of so many different sources of info.
Mixer or FX-Mixer -thats almost transparent, and noone will be confused, but going from B&B to like 'pattern-editor', that will be confusing..
But lets say its done
Then!
**Everything** nomenclature wise **must** be straighten out *once and for all*
A complete nomenclature sheet **must** be made! -and **that** must be it! Everyone must confirm to **that** sheet.
It will be a complete 'polish-parliament' disaster, if it goes to a 'consensus debate'  (imo)
*Someone* simply need to go DonaldTrump on this, and do it as pr. Decretum (sorry:)

Im willing to make a html-page with every lmms component as a picture gallery, and a blanc field for the designated Master-of-nomenclature (yet to be appointed) to fill in.
That picture-collection can then be hosted online, and everyone can use the pictures.
It could also be available as dl for any user, as a component reference, perhaps in the form of a *.HLP 
IF that has interest, just let me know.

**Comment by tresf** [comment]
@musikBear please don't confuse tasks here.  Documentation is not more important than the end-user experience nor is the effort needed to document even remotely close to the effort needed to code this.

I've used Gimp for 15 years and when they change the UI I adapt.

Furthermore, most users don't use wiki's to learn software anymore, but instead use YouTube or just ask on Facebook.

**Comment by jasp00** [comment]
>The word "FX" provides absolutely no contextual significance unless the creator of it is named "Francis Xavier".

Not because of me. "FX" means "effects". Instruments had an "FX" tab and there was a mixer already. tobydox made a new mixer that worked like the "FX" tab. "FX mixer" was a sensible name and it is not that uncommon.

Current names are not useless. They have worked fine all these years. They may not be the prettiest, but I believe everyone knows what we are talking about when using these names.

I am not saying that names should not be changed. I only say there should be a good reason, such as that newcomers have absolutely no clue about the meaning of the names, or being part of a marketing campaign. Changing nomenclature has consequences regarding existing documentation (issues, requests, logs, etc.). You should not ignore that `Mixer` has a historical meaning in the code.

If we rename GUI components, we should do it just once and for the best possible choices. I do not know how other DAWs call their components, but we should reach maximum consensus among projects and back our proposals with bibliography.

**Comment by tresf** [comment]
> tobydox made a new mixer that worked like the "FX" tab. "FX mixer" was a sensible name and it is not that uncommon.

That's fine, but eventually you have to stop calling the "New Car" 🆕 .  It eventually just becomes 🚗 .

> If we rename GUI components, we should do it just once and for the best possible choices.

We are.

> but we should reach maximum consensus among projects and back our proposals with bibliography.

We do our best, but this isn't a democracy.  If it were, nothing would get done.  Naming and artwork conversation are subject to far too much opinion and drain projects.  Furthermore, whenever the opinion is "Let's keep it that way because it's not that bad now", it's too weak of an argument.  This is a small change, we're taking the word `FX` out.  There's no name clash, it's shorter, more standardized across DAWs, easier to translate across languages and less "Effects Centric" by name.

If the `cpp` naming convention is the major concern, let's work that into the issue, but let's not throw the 👶  out with the bath 🚰 , so to speak. :)

**Comment by jasp00** [comment]
>"Let's keep it that way because it's not that bad now"

It is actually "It is not broken, we can wait for the best solution".

>this isn't a democracy.

I am rather calling for technocracy. The more brains we get from other audio projects, the better. References would be appreciated too. I am not arguing that "mixer" is not better than "FX mixer", but why "[mixing console](https://en.wikipedia.org/wiki/Mixing_console)", "audio mixer", "audio console", "mixing desk", "sound mixer", "sound board", or simply "board" are not better options?

>If the `cpp` naming convention is the major concern

This is secondary to GUI naming. I only say that we should rename just once and for the best.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.

**Comment by claell** [comment]
@tresf If I am correct this is just about renaming all occurring instances of `Fx-Mixer` to `Mixer` in the code? If yes this looks like an easy starter issue and I am willing to create a PR for that.

**Comment by SecondFlight** [comment]
I believe you have the right idea - it's easy to break things with find and replace, so as long as you double-check the replacements you're making then you should be good.

I think this would be a fantastic starter issue.

**Comment by claell** [comment]
@SecondFlight see the PR. I hopefully have done nothing wrong, will check again!

**Comment by SecondFlight** [comment]
Based on what you said I was expecting variable name changes, which are more likely to cause issue. I did a quick check and it looks good, assuming you didn't miss anything.

**Comment by russiankumar** [comment]
Seems to be stagnating, maybe I can take over the PR?

**Comment by tresf** [comment]
> Seems to be stagnating, maybe I can take over the PR?

I think this comment was somehow deleted?  @russiankumar feel free to take this over!  Feel free to discuss in the closed bug reports.  We can even reopen them if needed.  They're all closed for consolidation purposes because it's hard to track what's actually being worked on.

**Comment by russiankumar** [comment]
@tresf, yeah, I did delete it because I thought that's a lot of issues I wanna take over for one day xD. But yeah, this will be a part of the renaming project (discussed in #120 towards the bottom) so I suppose sooner or later someone will have to take over the PR, fix it and merge it. May be me, may not be me, let's see :)

**Comment by claell** [comment]
@russiankumar Since I did not finish my PR until now since I did not really have time to do it, feel free to take over :+1: 

Just let me know when you start. I might have some time in the near future, so that would avoid double effort :smiley:

**Comment by russiankumar** [comment]
Thanks a lot @claell! I expect to start as soon as all non-stale PRs merge (1-2 weeks hopefully). If you happen to be free at that time, I could leave it to you (since there’s a lot to work on and sharing this work makes it easier). You can ping here if you are ready, and then you can rebase your current PR probably and merge it accordingly.

**Comment by claell** [comment]
Alright. I will have a look on the progress of the overall refactoring and might help with this specific issue when everything is ready for these changes if I have the time.

**Comment by tresf** [comment]
Closed via https://github.com/LMMS/lmms/pull/6239
