### ISSUE TITLE
Adjustable grids in the song editor

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#3395]
Hello!. This time I come to suggest another idea. And is that; Currently the editor of lmms does not have a grid system as in the piano roll, but has a kind of mesh like this
![rejilla del editor actual](https://cloud.githubusercontent.com/assets/26127693/23491174/011f098a-fed3-11e6-87e5-1c08874e1cdd.png)
This mesh causes the fragments or tracks in them to magnetize and conform to the meshes, creating fragments in an empty space, causing the rhythm to be lost, currently the song editor has a free but accurate scrolling option. At the time of recording the tracks are created empty spaces even though there is only one note in the fragment, causing the rhythm to be lost (you can check).

![rejilla en el editor de cancion](https://cloud.githubusercontent.com/assets/26127693/23491451/c7ea6b3a-fed4-11e6-985f-8308169ba562.png)
So I suggest that you put an adjustable grid system, as the piano roll has, it would be very useful because the Maya are not adjustable, but if they are, they would give us more pressure at the time of recording and the space of the fragments Would be proportional to the number of notes, and there would be no empty spaces. I know it's a lot to ask for a free software and few who do, but the ideas are there, and the lmms project is stopped since 2015. have a good time

**Comment by musikBear** [comment]
Nee, you are using this wrong
I will recommend you to read the wiki:
https://lmms.io/wiki/index.php?title=Main_Page
And please do a search on this board, before you post :)

**Comment by BaraMGB** [comment]
>but the ideas are there, and the lmms project is stopped since 2015. 

Oh that's not true. We are working hard on lmms every day.

**Comment by Gabrielxd195** [comment]
Good afternoon. In the first place, thanks for explaining to me the position of the bars. But that was not what I wanted to say. Later I will edit an image with the problem. The problem is not the grid of the piano roll, but the one of the song editor, in the image I put as an example the grids of the piano roll in the song editor, but what I wanted to leave said is that the song editor needs a system Of grids similar to the piano roll, currently the problem is in the bars, for example: when you place a round note, it occupies all the space of the Maya well !!, but when you place a black note, it occupies a quarter of space Of the Maya, and however the bar adjusts to the Maya leaving an empty space and causing the rhythm to be lost. Currently there is a free option of bars, but this is true, there is also another option to resize the bars but only works with the bars of the editor of rhythm, when I try to resize the bars of the piano roll, this fails and does not Is resized like the beat editor. So I suggest a grid system for the bars to fit the grids that can also be edited. Later I will edit an image of the problem. and on the other hand. I value lmms and disinterested work of the developers lmms is a musical jewel of linux that has great potential and that is why I encourage you to give my ideas (I do not know if they are valid) because I like this application and the great work they have Done in it.

**Comment by vlad1777d** [comment]
Hello. 
As I understood, your problem appears in such case:
![2017-03-15 21-01-00](https://cloud.githubusercontent.com/assets/12682937/23966118/e1b643d8-09c2-11e7-8c96-5bc1be6fe19a.png)
Here 2 beats are 4\4 and fully filled, 3-rd beat is filled on half. You want such patterns go straight one after other, but cannot do so with current Song Editor's placing system.

You can do so:
![2017-03-15 21-01-39](https://cloud.githubusercontent.com/assets/12682937/23966887/aac6add8-09c5-11e7-98e0-6fd71e62a3ae.png)
You change size of bar from 4\4 (bar had 4 notes, each of them has size of 1\4 beat, so full bar had 1 beat size) to 5\4 (so one bar has 5 notes of 1\4 beat, so full bar has now 1.25 (1.1\4) size).
So all is good now.

But if you want to make next pattern with full 3 bars ? Than you cannot do so, that melody goes straight one after other, neither if you'll switch back to 4\4 size:
![2017-03-15 21-31-42](https://cloud.githubusercontent.com/assets/12682937/23967300/08cf21f2-09c7-11e7-8103-acdc15e7dc44.png)
, nor if you'll stay at 5\4 size:
![2017-03-15 21-34-01](https://cloud.githubusercontent.com/assets/12682937/23967336/2c89cf20-09c7-11e7-9ebf-9facb04215a4.png)
(now between pattern 3 and 4, which have full 3 bars of notes, there is a free space of size 3 beats).

I agree, the problem is present. And I agree, that making grid in Song Editor (which size user can change) will be the good decision.
User could make grid of 2 beats size in Song Editor and place this patterns just one after other, there will be no silent space between them.
This will give us great flexibility!
I agree with such @Gabrielxd195 's decision:
![2017-03-15 21-34-05](https://cloud.githubusercontent.com/assets/26127693/23491451/c7ea6b3a-fed4-11e6-985f-8308169ba562.png)

_There is not big underwater stone, we'll need to switch between 4\4 and 5\4 size when we will edit different patterns, but this is not a problem. It's one of the ways to do this. In future we could make that size (4\4, 5\4, etc) as default value for every pattern, and add to every pattern (into piano roll\beat editor) ability to override that value (in case, when we want to make unique patterns)._

**Comment by Gabrielxd195** [comment]
Wow !. Not only did you understand my idea, but you improved it, thank you! I put the grid of the piano roll as an example only (So that they understand me better), because the song editor needs to improve his grid to improve the accuracy, besides this improvement like the other one that mensione # 3394, can be of much help For future improvements, in case in the future the developers add the recording and audio editing to lmms. Lmms is great but with more improvements would be much more great.

**Comment by zonkmachine** [comment]
Related/Duplicate: https://github.com/LMMS/lmms/issues/874

**Comment by tresf** [comment]
> Related/Duplicate: #874

Yeah.  @Gabrielxd195 these duplicates are out of control.  Clean it up or you'll be blocked from creating bug reports.
