### ISSUE TITLE
Improvements to example tracks

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#3461]
Hello!. I have a small suggestion, I hope it is to your liking. Truly lmms is a great program to create music, but it lacks another detail. In the preview version 1.2.0 rc2 improved the audio reproduction from any position of the song in the sample tracks, I suggest that the small effect window of the example track becomes an audio style editor Audacity, it already has a wave detector, but it lacks little basic tools for the manipulation of audio like: copy, cut, paste, move, divide, join, add effects, automation, and above all but later, a recording button And the connected microphone menu (like audacity). Please analyze this suggestion, with this type of improvements lmms will grow a lot. What do you think?. Have a good time

**Comment by tresf** [comment]
@Gabrielxd195 thanks for the suggestion.  This feature is on our long-term radar (unless someone new can start it now of course!)

This feature has been requested several times over the years, most notably here: https://github.com/LMMS/lmms/issues/495.

Since our sample track is feature-incomplete, we decided to consolidate all Sample Track features into something we call a `META` issue, which is here: https://github.com/LMMS/lmms/issues/1471

Closing, marking as duplicate.
