### ISSUE TITLE
Effects to individual midi notes

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#3462]
Goodnight!. I would like to make a suggestion, I hope it will be to your liking. It has happened to me that I have a midi track, but I want to add effects to some notes, so I have to clone this track (when it's a vst sometimes hangs up) lmms for now only allows me to control the volume and paner of each note.
![anadir efectos a notas actual](https://cloud.githubusercontent.com/assets/26127693/24394239/358483ee-1369-11e7-8bd9-0cda2599a38f.png)

 But it would be an advance to be able to add a special effect to each note in such a way that I do not have to clone the track, but add an effect to any note. This characteristic I saw in tracktion 5, it would be more economical to have a single track with all the effects than having multiple tracks with their effects. The image says it all 
![anadir efectos a notas sugerido](https://cloud.githubusercontent.com/assets/26127693/24394267/51a994b0-1369-11e7-90af-e983440ee793.png)

First select the notes, then click the '' add fx '' button and suddenly the effects menu will appear, you will be assigned an effect, and ready, the selected notes will be the only ones with the effect, without needing Create new instances, saving us resources. What do you guys think? have a good night.

**Comment by tresf** [comment]
We don't have any place for this in the UI and we likely won't any time soon.  You really should use a separate piano roll pattern for this feature.

Slightly related:  https://github.com/LMMS/lmms/issues/3132
Bears some resemblance to https://github.com/LMMS/lmms/issues/1381, but mostly because it covers custom ranges.

I'm not sure this feature is warranted, but I'll let time be the test of that.

The problem with this feature is we simply have no place to hide away or organize the effects stack.  We could offer two effects stacks per instrument, but it's simply the wrong design as it adds unnecessary complexity to the most basic of tasks.

We do have some per-note enhancements (such as pitch #51, #39, #1466, #3190) so we could consider sneaking a FX channel into the per-note tuning, but it's really bad UX as it's just hiding a feature away.  Think of how confusing when FXs are added at the 1. Instrument 2. Mixer and then 3. Note level! :)

Thank for the write-up.  I'll leave this open for comments, but I will probably close as wont-fix if there's no clear execution and no clear demand.

**Comment by Mark-Agent003** [comment]
I don't think just adding an "Add FX" button is a good idea, what would the sliders control, the W/D? What about just being able to connect the per-note sliders to a knob, like how automation editors are connected by simply ctrl-dragging a knob into them. I think FL allows for this behavior, but I'll have to check on that. Adding a dropdown where the "Note Volume:" currently is may help make this feature (and per-note panning) be noticed more. Perhaps something similar to: "Volume, Pan, and Add new..." And if the sliders could be connected to any knob, it would also address #3132 .

**Comment by Spekular** [comment]
+1 for per note sliders that connect to anything.

**Comment by tresf** [comment]
Marking as `wontfix`.  There's really no place in the UI to do this per-note.  Perhaps per-key, such as in #4075.  If someone has time to work on this, please feel free to reopen (or request a reopen, etc) but having an FX stack for every single note is a UI nightmare and not something that is going to make it into 1.3.0, 1.4.0, etc.
