### ISSUE TITLE
2 "Beat+Bassline Editor" GUI bugs.

### ISSUE THREAD

**Issue by Hussam-Eddin-Alhomsi** [LMMS/lmms#3584]
There are 2 bugs with the "Beat+Bassline Editor".

(1) The first bug: the right side of the "B+B E" near the last 2 steps of the fourth beat gets cropped when the "B+B E" opens.

An example:
Opening LMMS then opening the "B+B E":
![beat bassline editor 1](https://cloud.githubusercontent.com/assets/25503477/26532646/01fd8332-440f-11e7-830f-5b8d1ab8fae2.png)

(2) The second bug: when the "B+B E" is moved, the first bug disappears, but the "B+B E" takes a piece of the windows that is behind it and put it in its window near the last 2 steps of the fourth beat.

The first example:
Opening LMMS with the "Song-Editor" in view (this happens by default) then opening the "B+B E" then moving the "B+B E":
![beat bassline editor 2](https://cloud.githubusercontent.com/assets/25503477/26532647/06a81500-440f-11e7-8162-a2ca88145378.png)

The second example:
Opening LMMS with the "Song-Editor" in view (this happens by default) then opening the "B+B E" then closing the "Song-Editor" (so the "B+B E" is over the "Automation Editor") then moving the "B+B E":
![beat bassline editor 3](https://cloud.githubusercontent.com/assets/25503477/26532648/0bbe9dde-440f-11e7-95b6-99636746625f.png)

The third example:
Opening LMMS with the "Song-Editor" in view (this happens by default) then opening the "B+B E" then closing the "Song-Editor" then closing the "Automation editor" (so the "B+B E" is over the blank background) then moving the "B+B E":
![beat bassline editor 4](https://cloud.githubusercontent.com/assets/25503477/26532649/0fc1f232-440f-11e7-84cf-ae95d2af9e3b.png)

* The second bug happens with instrument plug-ins, too.

**Comment by BaraMGB** [comment]
both bugs confirmed. They are related. I look into it.

**Comment by BaraMGB** [comment]
A quick workaround is to resize the bbEditor window. 

The problem here is, the size of the window is saved with the project. But our new theme uses more space in width for the B+B editor. So the right side is cropped.

**Comment by Hussam-Eddin-Alhomsi** [comment]
> A quick workaround is to resize the bbEditor window.

I'm aware of that.

> The problem here is, the size of the window is saved with the project. But our new theme uses more space in width for the B+B editor. So the right side is cropped.

Got it, 😉

**Comment by BaraMGB** [comment]
Okay, after a deeper dive into this problem I found it. If a project will be saved and a window is hidden a given size will be saved with the project. In case of the BB Editor this is 640 x 400 Pixel. 

@Wallacoloo Do you know why this is necessary? This leads to this bug.

**Comment by Wallacoloo** [comment]
@BaraMGB I vaguely remember changing that code. IIRC: Previously, the behavior was that all open windows have their positions/sizes saved so that the workspace remains identical when the project is reopened. But oftentimes people arrange the windows specifically (e.g. mixer on right, B+BE on left) and minimize/hide them when not in use. When they save the project & these windows aren't visible, the position/size wasn't reported correctly, so their location wouldn't be preserved when opening the project again - I think they were saved with a size of (0, 0) and would be tiny when reopened.

The fix was to add that `QSize sizeToStore = visible ? normalGeom.size() : sizeIfInvisible;` line, to have some sane default (as opposed to a 0x0 window). I thought it had been implemented in a way where we would save the window's size prior to being minimized, but I guess not.

If it's introducing problems, it should be safe to modify so long as you test the behavior of loading a project with minimized windows afterward.

**Comment by Umcaruje** [comment]
> loading a project with minimized windows afterward.

We removed minimization of windows, they can only get closed now.

**Comment by Wallacoloo** [comment]
It might have covered both minimized and closed windows - not sure (maybe
hunt down the commit message).

**Comment by BaraMGB** [comment]
If we'd fix that and save the actually size no matter the window is hidden or not the problem persist for older projects. It would be only fixed for projects which will be saved with this new program version.
