### ISSUE TITLE
Dragging and dropping tracks in the "Beat+Bassline Editor" GUI bug.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#3598]
When you move a track from the "Song-Editor" to the "BB E" OR from the "BB E" to itself by pressing <Ctrl> and clicking on "move-grip" then dragging and dropping, this is what happens to the track moved:
![bug 1](https://cloud.githubusercontent.com/assets/25503477/26595244/75368e92-4573-11e7-9aa5-dc8b1916ebef.png)
This bug can go away by playing the current beat/bassline.

**Comment by zonkmachine** [comment]
Behaviour introduced in commit 703a42e77cc5e14cf435adbc799feb7079a781fc

```
703a42e77cc5e14cf435adbc799feb7079a781fc is the first bad commit
commit 703a42e77cc5e14cf435adbc799feb7079a781fc
Author: Javier Serrano Polo <javier@jasp.net>
Date:   Fri Aug 19 04:12:16 2016 +0200

    Create BB-related TCOs along with BB-related tracks (#2981)
```

**Comment by PhysSong** [comment]
In `BBTrackContainerView::dropEvent()`, `Track::create( const QDomElement & element, TrackContainer * tc )`is called. It overwrites TCO information. After this call, `BBTrackContainerView::dropEvent()` also calls `Track::deleteTCOs()`.

Things which happen while the drop event is processed:
1. Correct TCOs for BB tracks are created.
2. They are replaced by previous TCOs.
3. They are deleted.

That's very weird process.

**Comment by PhysSong** [comment]
Currently, there's no way to determine where the dragged track from. There are some possible solutions.
One is to add source container information in `TrackOperationsWidget::mousePressEvent()`. It could be also done in `Track::saveSettings()`, but needs some extra checks because it won't allow distinguishing between tracks dragged from BB editor and presets saved from there, without workarounds.
