### ISSUE TITLE
Cancel track rename with Escape key

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#3675]
On 1.2.0-rc3, when the user tries to rename a track on the song editor, it is not possible to cancel the action by pressing the Escape key.

Allowing the user to do so would improve the usability.

**Comment by Hussam-Eddin-Alhomsi** [comment]
Right now it's only possible to cancel the re-name action by clicking away. I like your idea of cancelling with the "Esc" key.
Since we are going to implement the "Esc" key functionality and a track name can't have newlines, It would be nice if the user can execute the re-name action by pressing the "Enter" key while the track windows is open. Right now, the "Enter" key only does this when re-naming a track from the "Song-Editor", but not from the track window itself, which isn't consistent.
