### ISSUE TITLE
Transparent values for TCOs have glitched graphics

### ISSUE THREAD

**Issue by Mark-Agent003** [LMMS/lmms#3709]
When trying to edit a theme, I tried out making the patterns transparent. When testing it on an old project, I discovered this mess:

![image](https://user-images.githubusercontent.com/25230510/28398864-eb89a372-6cce-11e7-8d8b-852984df23d2.png)

The background color for the PatternView's were: rgba(33, 161, 79, 150). But not only the patterns, but all TCOs had this effect. If any more information is needed, I'm happy to supply it.
I'm using the latest release candidate of LMMS: 1.2.0 rc.3.

**Comment by Mark-Agent003** [comment]
![image](https://user-images.githubusercontent.com/25230510/28486326-998783fe-6e46-11e7-95e3-2add9a391e3d.png)
Also noticed this strange LMMS watermark showing up

**Comment by michaelgregorius** [comment]
The effect becomes even more pronounced if you set the property `background-color` of `PatternView` to something completely transparent, e.g. `rgba(255, 255, 255, 0)`.

I think what we see here is the uninitialized memory of the graphics buffer for the pattern. Because the code in `PatternView` just applies the background color found in the style sheet this leads to problems in case this background color is transparent because then these uninitialized values are still visible.

Several solutions come to mind:
1. Add code to `PatternView::paintEvent` which first fills the pattern's rectangle with black (or another color).
2. Do not take alpha values from the style sheet into account when painting the background.
3. Document that style sheets should not use transparent colors for backgrounds.
