### ISSUE TITLE
Time Signature in Song Editor

### ISSUE THREAD

**Issue by gi0e5b06** [LMMS/lmms#3734]
Time signature was not displayed in the song editor. Always assumed 4/4.
I fixed it for the numerator.
![song_editor_timesig](https://user-images.githubusercontent.com/30031949/28743776-8551f290-7452-11e7-86ad-8078b60b83ff.jpg)

**Comment by PhysSong** [comment]
Could you clarify what you mean?

**Comment by gi0e5b06** [comment]
The black and grey backgrounds.
Also the bar numbers were inappropriate.

**Comment by PhysSong** [comment]
I think something looks inconsistent in current LMMS, but I don't think it is wrong.
@Umcaruje Do you have any idea about this?

**Comment by zonkmachine** [comment]
I'm not sure what you're trying to achieve here. A bar is still one bar under a different time signature. Putting bars in groups of three, as in the example above, just because the time signature is 3/4 doesn't make much sense musically.

**Comment by PhysSong** [comment]
Background looks okay, but I think text positions are somewhere weird.
For 5/3 signature and 100% zoom, labels are: 1, 8, 15, 22, ...

**Comment by gi0e5b06** [comment]
@zonkmachine
Short answer: you're right and I reverted to 4. (one line of code)
Long answer: It's not uncommon to have the length of the hyperbars matching the time signature in some way, but it can not be generalized.
Goal: I would like a better representation of the hyperbars and/or the structure. If possible, automatically.

**Comment by zonkmachine** [comment]
> Long answer: It's not uncommon to have the length of the hyperbars matching the time signature in some way, but it can not be generalized.

Right. I actually only have deeper experience with lmms so I should maybe be a bit careful to express myself in absolutes. : )

**Comment by Umcaruje** [comment]
@gi0e5b06 please, open pull requests from different branches for each of your proposals, I can't see what's wrong with the current implementation, or what problem you're describing. Code would tremendously help.

 From a musical standpoint it makes sense to always use groups of 4 for bar shadings, because most usually musical sentences are either 4 or 8 bars long, and that's not dependent on the time signature. the time signature affects metering inside the bar, and that is a piano roll problem, not a song editor one.

**Comment by gi0e5b06** [comment]
`	const int tactsPerBar = 4; // most common case
	//const int tactsPerBar=Engine::getSong()->getTimeSigModel().getNumerator();`

@Umcaruje I already agreed that it is not possible to assume the length of the hyperbars using only the timesig. But I disagree with you on 4 being the best choice, however I don't have the data to prove it. I still think that, statiscally, the length of the phrases is loosely correlated to the timesig. Anyway, it doesn't matter, because it should be user-defined.

Thanks to this thread, I have refined a lot my idea (to show the structure of the song) and how to implement it.

**Comment by gi0e5b06** [comment]
Starting to look good. Default to 4.
Structure is: intro+ABABABB+outro (typical pop song)
![hyperbars1](https://user-images.githubusercontent.com/30031949/28771248-60719df4-75e2-11e7-92cd-00f96cdd77db.jpg)
![hyperbars2](https://user-images.githubusercontent.com/30031949/28771247-606def88-75e2-11e7-92a9-75255cffd3be.jpg)
WIP. Labels and Dialog are missing.

**Comment by musikBear** [comment]
im confused

**Comment by tresf** [comment]
@gi0e5b06 please use the default theme when possible and also, we would prefer if working from a pull request.

At a glance, it appears this bug report (Time Signature improvements) is being used to show mock-ups for custom loop points (right?).

**Comment by gi0e5b06** [comment]
@tresf You can not switch between themes easily and the default theme is beautiful but painful for the eyes.

Not custom loop points but the song structure (these are two different things). And not mock-ups but real code (it's not finished but it's working).

In this example:
green = intro
red = verse (16 bars)
blue = chorus (8 bars)
there is also a one-bar break and a two-bar outro.

PS: multi-loops is a different issue and it's only 10% done. It works but nothing is saved, there is no postponed jump like for Ableton, it's not yet midi-controlled (so no launchpad). But the main problematic point in LMMS is that each track doesn't have an independant play position (it will take 6-8 hours to implement that, maybe next week).

**Comment by tresf** [comment]
@gi0e5b06 please read your original bug report and then realize how off-topic this all is.

Using your own theme is fine for mock-ups, but the code must use our theme and the PR should illustrate that.

The contributions are welcome, but we expect the code to be in a reviewable fashion.  This means you should create a separate branch for each feature, a separate PR for discussion and use our built-in theme so that developers can approve this from a code quality, UI quality and UX quality perspective.  We can help with these, but we do expect the standard theme to be used for the proof of concept.

> @tresf You can not switch between themes easily and the default theme is beautiful but painful for the eyes.

Your development build should use a localized `lmmsrc.xml` file, so you should be able to switch at least the one you're building easily.

**Comment by musikBear** [comment]
> In this example:

@gi0e5b06  Oh, you are shading over spans of structure
My eyes simply could not catch that (they are rather lousy.. 🦇 
Coloured B&B segments in one B&B-track, can actually be used for that already now

**Comment by BaraMGB** [comment]
I close this because of not valid. I don't see what is the issue here.

**Comment by gi0e5b06** [comment]
Seriously?
