### ISSUE TITLE
1.2.0-RC3 download fails to launch on OS/X El Capitan "may be damaged or incomplete"

### ISSUE THREAD

**Issue by SundialServices** [LMMS/lmms#3760]
The LMMS application contained on the current 1.2.0-RC3 (for OS/X 10.11+ ... on the left) download on the web site failed to launch on OS/X El Capitan (10.11.6) because "the package may be damaged or incomplete."

The Console utility did not provide any additional messages of interest.

The ".dmg" file did successfully mount, however.

I noticed that the first attempt at download did not complete, leaving a ".download" file in the Downloads folder.  

... waitaminit ... it just DID launch from the ".dmg!"

- - - 
All right, I can confirm this:  it will run if launched directly from the DMG, but it will not run when copied to the hard drive.  If copied to my home directory, the icon has a "do not enter" graphic superimposed upon it.  I frankly have absolutely no idea why it is so ... but, it is so.  I am checking the other RC3 image now as well as the stable one.

The other RC3 image also failed in the same way, and I noticed that the "do not enter" image overlayed the icon -before- the file had finished being copied from the DMG.  I haven't seen this overlay on an icon before, and I couldn't coax OS/X into telling me more about what the trouble was. (So I guess you learn something new about your computer every day ... one would ask, what on earth could go wrong when copying an ".app" to the hard drive?)

The stable version (1.1.3), however, DID copy correctly from the hard drive, and DOES run.

(However, since it does not recognize Apple MIDI, and the RC3 promises to do so, I will wait with baited-breath for the RC3 issue to be fixed.)

**Comment by PhysSong** [comment]
Does this still happen for RC4?

**Comment by tresf** [comment]
> it will not run when copied to the hard drive.

I'm skeptical of this.  It generally means some files in `/Applications/LMMS` were locked for editing, which means the `lmms` process is hung up in some way.

The "DO NOT ENTER" sign is a sign that the copy failed which can be a sign of hard drive corruption or the launchd service may be running very very slow.

Anyway, this issue is `invalid`, closing.  Evidence:

![screen shot 2017-11-26 at 3 00 20 am](https://user-images.githubusercontent.com/6345473/33238196-3c86d032-d256-11e7-9a69-10b8b091d118.png)
