### ISSUE TITLE
Wrong overlays being displayed on instrument plugins

### ISSUE THREAD

**Issue by a2aaron** [LMMS/lmms#3908]
This bug occurs on `1.2.0-RC4` This bug does not occur on `1.2.0-RC3`.

OS: macOS 10.12.5
Kernel: Darwin 16.6.0
RAM: 8 GB, DDR3, 1600 MHz
CPU: Intel Core i5 @ 3.2 GHz
GPU: NVIDIA GeForce GTX 675MX

How to reproduce:

1. Open any project. 

2. Add any plugin that isn't TripleOscillator.

3. Click on the plugin in the track.

4. Notice that the plugin overlay has the TripleOscillator overlay.

Examples of incorrect overlays. Somehow, I was able to get FreeBoy to show the correct overlay, but then every plugin I added thereafter showed FreeBoy's overlay.

![Image showing the strange plugins](https://user-images.githubusercontent.com/15718048/31909981-f88d5470-b809-11e7-93a5-80ee52161e86.png)

Additionally, the sidebar of instrument plugins is missing their icons.

![Sidebar](https://user-images.githubusercontent.com/15718048/31910233-d41f63d4-b80a-11e7-996f-1b2001d78dd1.png)

**Comment by a2aaron** [comment]
It seems that occasionally, an added plugin will show the correct overlay, but then every plugin other plugin will show plugin's overlay. Sometimes, this seems to be the very first plugin that one adds after opening LMMS or will occur after wait a random amount of time. 

It appears that the Monstro plugin shows the correct overlay always, regardless of this previous effect.

**Comment by musikBear** [comment]
looks like lack of graphical update

**Comment by tresf** [comment]
Reproduced.

![ezgif-5-1273747bfe](https://user-images.githubusercontent.com/6345473/33406033-f78da5ba-d538-11e7-9318-c11f1ca7ae47.gif)

I'm not aware of any code changes in 1.2.0 that could have triggered this.  I suspect there's a bug with the build and this will go away with a fresh MacOS build.

Looking at the versioning, the build was created with 10.12 (I was using 10.11 for my environment), so I suspect this could have been caused by someone such as @lukas-w providing the builds this time around?  Just a guess.

**Comment by tresf** [comment]
@a2aaron can you see if a fresh build fixes this? https://github.com/LMMS/lmms/releases/download/v1.2.0-rc4/lmms-1.2.0-rc4-mac10.12.dmg

**Comment by tresf** [comment]
@lukas-w uploaded a new RC4 binary and this problem has gone away.  Please download and reinstall the RC4 beta from our download page.
![screen shot 2017-11-30 at 11 35 00 pm](https://user-images.githubusercontent.com/6345473/33468064-75fdab0e-d627-11e7-8698-67348fccacc5.png)
