### ISSUE TITLE
Automation Editor - draw line function selects last point drawn for a drag

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#4040]
A minor nuisance in the draw line function. When you draw a line the last automation point drawn is selected and ready to be dragged. This is a bit unintuitive and can lead to some unexpected results which is especially prone to happen if you work fast. The resulting drag action gives the illusion that it's the line draw action that is buggy with skipped points and/or nudged levels.

![drawlineagain](https://user-images.githubusercontent.com/6368949/33659245-c10958d0-da7f-11e7-993f-712aaae6d62f.png)

A - Expected result from a line draw.
B - Last point moved.
C - Last point level nudged.

To reproduce:
Method 1 - Draw a line and while keeping the left mouse button down, move the mouse around.
Method 2 - Press <Shift> and draw lines fast moving the mouse around. You will find gaps in the lines from where a point has been moved after the line was drawn.

**Comment by tecknixia** [comment]
I think I figured it out.  All that needs to be done is to disable the mouse button until it's clicked again.

There's already a boolean `m_mouseDownRight` variable.  Just need to:

- create a `m_mouseDownLeft`
- set it to `true` in `mousePressEvent` when it's pressed
- set it to `false` right under the `drawLine` call in `mousePressEvent`
- set it to `false` again when released in `mouseReleaseEvent`
- replace the first `mouseEvent->buttons() & Qt::LeftButton` with `m_mouseDownLeft` in `mouseMoveEvent` where it checks for condition of the left mouse button and `DRAW` mode (before the other drawLine call)

... and I think that's it! Unless I'm overlooking something.  Seemed to work well for me in the 10 seconds I spent checking it out.

**Comment by Spekular** [comment]
> * create a `m_mouseDownLeft`

There should be a way to query this instead. Perhaps [this function](https://doc.qt.io/archives/qt-4.8/qapplication.html#mouseButtons)

**Comment by Spekular** [comment]
It seems the function was moved in Qt5, now it's in [QGuiApplication](https://doc.qt.io/qt-5/qguiapplication.html#mouseButtons).

**Comment by tecknixia** [comment]
@Spekular 
By query, do you mean read the state?  The idea is to intentionally dismiss the state of the mouse, which is the opposite of reading it.

Since I'm new to this, I don't yet understand the documentation.  It seems to me it's all talking about reading the state.

> Returns the current state of the buttons on the mouse.

If there's a way to use `QGuiApplication` to change the state, independent of the actual state of the hardware, I'm unaware of how to do that.

**Comment by Spekular** [comment]
> By query, do you mean read the state? The idea is to intentionally dismiss the state of the mouse, which is the opposite of reading it.

From what I understand, m_mouseDownLeft checks if LMB has been pressed and not released. In other words, is LMB held down. You "set it to true in mousePressEvent when it's pressed" and "set it to false again when released in mouseReleaseEvent".

If I'm understanding this correctly and you care about whether the left mouse button is down (hence "mouseDownLeft"), then that Qt function should do the trick*. If it works like the keyboard modifiers do you'd probably write something like ``QGuiApplication::mouseButtons() && Qt::LeftButton``.

*With reservation for Qt being weird. It could very well be that this function doesn't work as one would expect...

**Comment by tecknixia** [comment]
> From what I understand, m_mouseDownLeft checks if LMB has been pressed and not released. In other words, is LMB held down.

> If I'm understanding this correctly and you care about whether the left mouse button is down (hence "mouseDownLeft"), then that Qt function should do the trick*.

I care about whether the left mouse button is down, except during a given situation.  What I'm doing is replacing a conditional boolean check with a boolean variable that works very much the same way, except it allows me to set the variable independently from the direct state of the mouse.

The problem with the mouse grabbing the last point after drawing a line is due to a condition check in mouse MOVE when the left mouse button is down.  I want it to function normally, except only when `drawLine` in mouse PRESS is called.  This is a way of preventing that condition from being true, even though the mouse button is down.

**Comment by zonkmachine** [comment]
Tested it briefly and it works as stated. Nice!

Another approach would be to let the whole line to be recomputed on drag.

**Comment by tecknixia** [comment]
Recalculating a line on a drag might feel odd while drawing quickly, with lines moving between the mouse button press and release.  The way it is now seems to be good for quick drawing.  Recalculating on a drag could be considered an enhancement feature for slower, more precise placement of a line... and perhaps could be activated by holding `ctrl` along with `shift`... and if so, would probably deserve it's own issue.  In this case, it may still be difficult to place lines perfectly with the mouse.

There's also the possibility of adding an alignment feature to select mode, so that all the points between the first and last points of a selection are made to form a straight line.  That way a line could be drawn, the first and last points adjusted to precision, and the points between could then be aligned to that precision.

**Comment by zonkmachine** [comment]
> Recalculating a line on a drag might feel odd while drawing quickly

The way it's been done now is just fine.
