### ISSUE TITLE
Rubber bands persist when clicking a mouse button other than the drawing one.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#4082]
Can happen in both the Song editor and the Piano Roll editor.
In the Piano Roll editor, only the below combination of mouse buttons works, and only one rubber band can exists at a time. In the Song editor, any combination of mouse buttons works, and multiple rubber bands can exist at a time.

To reproduce:
1. Enter the edit/select mode in any of the editors mentioned above.
2. Left-click and drag to draw a rubber band (selection rectangle).
3. Right-click before releasing the left mouse-button.
4. Release everything.

Multiple rubber bands in the Song editor:
![Song editor](https://user-images.githubusercontent.com/25503477/34452843-4240bda8-ed59-11e7-8da1-3a1902f51b59.png)

**Comment by Spekular** [comment]
Where is "rubber band" used to describe selection areas? "Selection
rectangle" makes more sense (IMO) and shows up with relevant search results
on google (although "rectangle selection" appears to be more common).
"Rubber band (software)" and "Rubber band (audio)" mostly return results
about a timestretch library. Personally the term makes me think of "rubber
banding" in online games, so the title made me think this might be an issue
with playback skipping backwards.

As for the actual bug (sorry about the long semi-off-topic bit above):

Unless I'm mistaken, the expected behavior is for these to disappear when
the mouse is released. This works as expected in draw mode ("the drawing
[mouse button]") but not in other editor modes ("mouse button other than
the drawing one").

Is this correct?

>

**Comment by Sawuare** [comment]
https://doc.qt.io/archives/qt-4.8/qrubberband.html

Yes, correct.

**Comment by Spekular** [comment]
"Rubber band selection" returns lots of relevant results, so it appears I
was out of the loop here. Sorry about that and thanks for the link.

**Comment by PhysSong** [comment]
I can reproduce with Windows(both `stable-1.2` and `master`, Qt 5.4.2), but not with Ubuntu 16.04 + Qt 5.5.1.

**Comment by BaraMGB** [comment]
I'll look into it.

**Comment by PhysSong** [comment]
I'm not sure if it's a bug of LMMS or Qt or something else, but I can't reproduce it with builds from `master` anymore.
Please feel free to reopen this if you still experience this with `master` builds.
