### ISSUE TITLE
Crash when using Edit mode during playback of a song containing a Sampletrack

### ISSUE THREAD

**Issue by Sauerstoffdioxid** [LMMS/lmms#4165]
When using the edit mode to move large parts of a song containing a Sampletrack, the square indicating what area is being selected seems quite frail. Eventually, after moving the selected parts a couple of seconds, LMMS may crash.

The selection:
![ezgif-4-e2d49f83b5](https://user-images.githubusercontent.com/35171164/36064417-0157e14c-0e8b-11e8-8f96-b9461e15da2e.gif)

And, after about 20 seconds of moving it around, the crash:
![ezgif-4-fa865f23cf](https://user-images.githubusercontent.com/35171164/36064455-963ace1e-0e8b-11e8-9682-35b914b04434.gif)
After that, LMMS closes. (Interestingly, apart from the stuttering audio, it's still fully responsive as long as the box is shown.)

I read somewhere there were issues with large Sampletracks of 100MB+. However, the sample I had loaded was an ~7MB FLAC, so this shouldn't be related.

Win10 64bit, LMMS-rc5 x64

**Comment by tresf** [comment]
@Sauerstoffdioxid thanks.  Yeah, there's a lot going on there that could trigger a crash, you have multiple events happening at once.

The fact that the audio keeps playing is suggestive that it's a bug in the UI, but we'll see if we can reproduce on a platform with a full backtrace and escalate as needed.

Note, for you or anyone interested in helping squash bugs like this, we have a stellar tutorial for building and debugging on Linux and Mac.  Linux runs great in a VM and we can help you get it all setup in #support on [Discord](https://lmms.io/chat).  I say this because we're 100% volunteer based and we need all of the help we can get, even if it's just reproducing and providing a backtrace. :)

**Comment by Sauerstoffdioxid** [comment]
I won't be able to install Linux anytime soon but I can test the bug a bit more on Windows.

Firstly, I wanted to clearify the statement about the sound still playing: it's a short (~1 second) loop which is kinda what I'd expect from a music programme crashing. However, as long as the text box isn't closed, the UI of LMMS is still responsive, i. e. I can still drag around/move note patterns.

Secondly, after some more testing, it turns out this are actually two different bugs which aren't related much to each other:
First, there's the bug of the resizing square becoming very frail. The effect is much worse when I load the WAVE version instead of the FLAC.
... and second, there's the crash. I recreated it with just a bunch of empty BB tracks (in this case 6 B+B lines with 32 patterns each). The less patterns are moved, the longer it will take for the crash to happen.

**Comment by PhysSong** [comment]
Reproduced. It looks like #3956 though I'm not sure. I'll post a test build with a potential fix in a couple of days.

**Comment by PhysSong** [comment]
@Sauerstoffdioxid Can you still reproduce this issue? If so, could you test this version?
https://github.com/PhysSong/lmms/releases/download/vdummy/lmms-1.2.0-rc5.61-win64.exe

**Comment by Sauerstoffdioxid** [comment]
@PhysSong Seems to be fixed.  👍

**Comment by PhysSong** [comment]
Then I'll open a pull request soon.
