### ISSUE TITLE
VST - Problem

### ISSUE THREAD

**Issue by TristexMusic** [LMMS/lmms#4177]
Dear LMMS - Team!

I have a problem with a VST - Plugin.
I tried to import the Bitsonic Piano via Vestige. It`s working fine. 
But when I save my LMMS - Project and try to reopen it, it crashes loading at says:
'unable to load this instruments.'
Problem fixes?
PS: It is already in my VST folder
PPS: other VSTs work
PPPS: If you need some more (detail) information pls contact me via email: 
tristexmusic@gmail.com

Thanks Tristex

**Comment by musikBear** [comment]
This error indicates, that this particular VST, does not work in that version of LMMS. You have 2 options:

**Comment by Umcaruje** [comment]
Hey @DomClark could you take a look at this one?

**Comment by DomClark** [comment]
Cannot reproduce on 1.2.0-RC5, Windows 10 x64. The VST appears to be created using the Maize Sampler, so this is most likely a duplicate of #3274 and fixed in #3776.

@TristexMusic Try downloading the latest beta version of LMMS, and please reopen this issue if you can still reproduce the crash there.

**Comment by TristexMusic** [comment]
It worked with the Beta. Thanks for your help. 👍
