### ISSUE TITLE
in FX Mixer channel, the SEND+arrow should be replaced with a more intuitive arrangement

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4187]
Currently, the internal connection is denoted by SEND and an up/down arrow.

This is not intuitive, because the word "send" itself means "outward signal". 
How can it be understood to mean "send in" and "send out"? 

There are several options (all discussed at devtalk channel of Discord), which I am summing up here.
1. Instead of showing  **SEND** in gray+green, change the button to IN and OUT.

2. Instead of text, show the "IN" and "OUT" graphically.
I am listing some examples for inspiration:

In this first example, the symbol toggles between "OFF", "IN" and "OUT".
The first set uses gray+white color-scheme. The second set uses gray+green color-scheme.

![image](https://user-images.githubusercontent.com/9047168/36629942-c55e846c-1983-11e8-85aa-7f825707a41b.png)

These are only for illustration. Many more variations are possible. 
For example, instead of the gray line, we can use a gray rectangle. 
![image](https://user-images.githubusercontent.com/9047168/36629944-ce17b7ea-1983-11e8-87e8-2e7ea70040cb.png)

In the following images, I have used a composite image, out of which some part "lights up".
Again, the example show the two color-schemes: gray+white and gray+green.

![image](https://user-images.githubusercontent.com/9047168/36629938-bd4dae60-1983-11e8-8e95-d333db573a11.png)

In the following examples, the arrow layout is left-to-right instead of top-to-bottom.
![image](https://user-images.githubusercontent.com/9047168/36629935-aef2e830-1983-11e8-8fa7-660100daf5a0.png)
![image](https://user-images.githubusercontent.com/9047168/36629925-80c9f282-1983-11e8-9765-78e9eeeda43f.png)

![image](https://user-images.githubusercontent.com/9047168/36629926-8a0a9892-1983-11e8-87ca-8f61effb70c7.png)

![image](https://user-images.githubusercontent.com/9047168/36629927-922c031c-1983-11e8-9c75-a87b1fd5cc3e.png)
![image](https://user-images.githubusercontent.com/9047168/36629928-99771b52-1983-11e8-9cc9-5a3f39b64251.png)
![image](https://user-images.githubusercontent.com/9047168/36629931-9f693d24-1983-11e8-966b-ff6cde203895.png)

**Comment by Spekular** [comment]
I don't quite understand what issue you see with the current design, and
your proposal doesn't seem more intuitive to me.

"SEND" only appears when a channel is selected (and the channel displays an
upwards/outwards arrow), so it's clear to me that it means "send the
selected channel here" (here being the channel where you press "SEND").

The current "SEND" button is also very compact. I believe you pointed out
the issues with left/right arrows on Discord (they could be confused with
sending to the right or left in the mixer), and up/down would surely
require more vertical real estate than "SEND". Considering the design of a
mixer, vertical space is at a premium.

On Feb 24, 2018 12:39, "Narayan" <notifications@github.com> wrote:

Currently, the internal connection is denoted by SEND and an up/down arrow.

This is not intuitive, because the word "send" itself means "outward
signal".
How can it be understood to mean "send in" and "send out"?

There are several options (all discussed at devtalk channel of Discord),
which I am summing up here.

   1.

   Instead of showing *SEND* in gray+green, change the button to IN and OUT.
   2.

   Instead of text, show the "IN" and "OUT" graphically.
   I am listing some examples for inspiration:

In this first example, the symbol toggles between "OFF", "IN" and "OUT".
The first set uses gray+white color-scheme. The second set uses gray+green
color-scheme.

[image: image]
<https://user-images.githubusercontent.com/9047168/36629942-c55e846c-1983-11e8-85aa-7f825707a41b.png>

These are only for illustration. Many more variations are possible.
For example, instead of the gray line, we can use a gray rectangle.
[image: image]
<https://user-images.githubusercontent.com/9047168/36629944-ce17b7ea-1983-11e8-87e8-2e7ea70040cb.png>

In the following images, I have used a composite image, out of which some
part "lights up".
Again, the example show the two color-schemes: gray+white and gray+green.

[image: image]
<https://user-images.githubusercontent.com/9047168/36629938-bd4dae60-1983-11e8-8e95-d333db573a11.png>

In the following examples, the arrow layout is left-to-right instead of
top-to-bottom.
[image: image]
<https://user-images.githubusercontent.com/9047168/36629935-aef2e830-1983-11e8-8fa7-660100daf5a0.png>
[image: image]
<https://user-images.githubusercontent.com/9047168/36629925-80c9f282-1983-11e8-9765-78e9eeeda43f.png>

[image: image]
<https://user-images.githubusercontent.com/9047168/36629926-8a0a9892-1983-11e8-87ca-8f61effb70c7.png>

[image: image]
<https://user-images.githubusercontent.com/9047168/36629927-922c031c-1983-11e8-9c75-a87b1fd5cc3e.png>
[image: image]
<https://user-images.githubusercontent.com/9047168/36629928-99771b52-1983-11e8-9cc9-5a3f39b64251.png>
[image: image]
<https://user-images.githubusercontent.com/9047168/36629931-9f693d24-1983-11e8-966b-ff6cde203895.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LMMS/lmms/issues/4187>, or mute the thread

**Comment by musikBear** [comment]
njea.. infact 'SEND' should read 'RECEIVE' or 'GET' or similar

**Comment by tresf** [comment]
> infact `SEND` should read `RECEIVE` or `GET` or similar

Well, if we [take a lesson from ImageLine](https://user-images.githubusercontent.com/6345473/36632736-54efaf88-1958-11e8-8b66-8545bbb294c2.png), the less text the better.  This also helps non-English users.

Related discussion is here: #4181

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
