### ISSUE TITLE
Add a button to enable a piano-roll TCO 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4209]
Enhancement:
We have **all** done this:
Dobble click a TCO pressed play, and had -no- replay..
Yes the track is muted..
So the 'fix' is to 
* close this piano-roll
* find the track in question in song-editor
* enable the track
* re-locate the TCO in question
* open that (by now free¤%%#) piano-roll

Because of *that* i suggest a diode inside piano-roll, that will enable replay-Something like
![piano-roll-enabler](https://user-images.githubusercontent.com/6662066/36911499-00918830-1e44-11e8-853d-2803d89730bf.JPG)

**Comment by Mark-Agent003** [comment]
This is a great idea, and it'd definitely find myself using it. I think a better title may be 'Add a button to *mute* a piano-roll TCO '.

**Comment by tresf** [comment]
Muted piano rolls shouldn't stay muted when played from the Piano Roll editor.  This is really a bug in my eyes.  Adding a "mute" LED as an indicator that song-playback won't occur is a good idea, but BB tracks would need to be enhanced with this as well, as they add an additional layer of potential muting.

But to take this further, most of this is a UI band-aid because we have a clunky MDI-style windowing system.  A single-window interface would guarantee that we have the potential for all components to be on-screen at the same time.

**Comment by musikBear** [comment]
>  A single-window interface

true 👍

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
