### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by Anonymouqs** [LMMS/lmms#4237]
The ability to update without redownloading would be interesting, like how Starcraft II doesn't require the user to download every new version from scratch. This would also reduce bandwidth usage on new releases since existing users only need to download a small portion.

An optional Time-Warp feature in order to use previous versions to keep LMMS versions organized would be possibly useful IDK about the demand but just a random idea (This could possibly consume a lot of memory, so during the installation process, it would not be added by default.)

**Comment by Umcaruje** [comment]
I’m tempted to close this. This isn’t an achieveable or a needed idea for a very long time. An average lmms installation is 30 Megabytes, which is so small there really wouldn’t be any benefits of the system you propose. Starcraft is a large game which is probably a couple of gigabytes and it’s not comparable to lmms.

**Comment by tresf** [comment]
Automatic updates and what you call "time warp" are completely unrelated and shouldn't be bundled.  I agree this is `wontfix` for now but should be doable.

LMMS is very fortunate due to the fact that it can run 100% in user-space.  Not all applications have this luxury, many applications need to install things (such as drivers) in system-space and require elevated permissions, LMMS does not.  Running in user-space has it's caveats, but if this is the direction we go in, it would greatly simplify the ability to auto-update.

Running in user-space varies between platforms.  On Mac, it's almost unheard of.   Generally, apps are dragged to `/Applications` and run from there.

On Linux, it's hit-and miss.  AppImages are user-space as are compiled versions, so this is becoming more widely accepted as time goes on.

Windows has mixed deployments.  It's probably the most common for user-space installs, but most projects decide at design-time if they're user-centric or system-centric.  This decision affects upgrades, so they should be done gracefully.

**Why can't we just do it like Chrome does?**

Some apps like Firefox and Google Chrome have this ability to auto-update, but it's a very complex mechanism that does this and only a few applications do it properly.

* First, a service process needs to be installed and running at all times with write-access the to root filesystem and ability to kill the parent process.  This access can be a security risk.

* Next a validation mechanism must occur which periodically checks for, validates the origin and authenticity of the content and fetches it to the local computer.

* Finally, once the updated application has been fetched and verified, it is installed, generally on next launch.  Some desktops like Apple don't actually close an application when the "x" is clicked, so a "restart now" option is usually presented to the user.

Requesting auto-update for a small-dev team like LMMS has is a stretch.  Asking for a way-back machine is borderline insulting.  We're here to make music-software, not to make software-software.  ❤️
