### ISSUE TITLE
Segmentation Fault when running appimage.

### ISSUE THREAD

**Issue by DarkLinkXXXX** [LMMS/lmms#4286]
Version: lmms-1.2.0-rc5.43-linux-x86_64.AppImage
Run on Debian Testing (buster). 
Core dump attached. 
[core_lmms.real.12003.gz](https://github.com/LMMS/lmms/files/1886707/core_lmms.real.12003.gz)

**Comment by tresf** [comment]
Unless I'm doing something wrong, this core dump is useless unless you have a near identical system to run `gdb` from.  Can you upload the backtrace instead?

**Comment by PhysSong** [comment]
It isn't easy to debug AppImage directly using `gdb`. @DarkLinkXXXX Could you try following instruction? Since you have a core dump, this may help.
1. Go to the directory which contains the AppImage
2. Run `./lmms-1.2.0-rc5.43-linux-x86_64.AppImage --appimage-extract`
3. Run `gdb squashfs-root/usr/bin/lmms.real (path to your core dump)`
4. Type `set sysroot ./squasfs-root` and then `set solib-search-path ./squashfs-root/usr/lib`
5. Type `thread apply all bt full` to get full backtrace of all threads.
6. Post the output

If you can't follow this instruction, please run the AppImage on terminal and post output.

**Comment by DarkLinkXXXX** [comment]
I did as you have asked (output is attached), but I'm afraid there's no debugging symbols. http://ix.io/17hn

**Comment by tresf** [comment]
I just downloaded the Live CD for Debian Buster and LMMS launches fine.

![image](https://user-images.githubusercontent.com/6345473/38565606-c5b557ca-3caf-11e8-8782-593670aeb72b.png)

**Comment by lukas-w** [comment]
@DarkLinkXXXX Your `gdb.txt` suggests you have some 3rdparty libraries that are being loaded from `$HOME/Downloads`, amongst others `libxul.so`:

```
Thread 1 (Thread 0x7fb14d852780 (LWP 12279)):
+bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00007fb10e705de3 in ?? () from /home/john/Downloads/libxul.so
No symbol table info available.
#2  0x00007fb10e6faf4d in ?? () from /home/john/Downloads/libxul.so
```

This may be the cause of your crash. Can you remove them and try again?
