### ISSUE TITLE
Effect groups/sub-chains

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#4402]
It would be nice if effects in a chain could be grouped, and these groups could be:
* Named
* Collapsed/Expanded
* Muted/Unmuted

This could help organization with larger chains. Muting several effects would be particularly useful for A/B-ing.

**Comment by SecondFlight** [comment]
As an alternative, could we have a way to enable/disable effects for a channel? Then the same functionality could be accomplished via channel sends without the need for a complicated new UI feature.

I think part of the issue is that our widget for effects is so large, so trying to find an effect when you have as little as 5 requires scrolling.

**Comment by Spekular** [comment]
Effects can already be disabled both in the instrument and mixer channel chains, but that's not the same functionality.

**Comment by SecondFlight** [comment]
No, I mean disable all effects on a channel. I think your new issue pretty much sums up the functionality I had in mind.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
