### ISSUE TITLE
SDL deadlock on exit

### ISSUE THREAD

**Issue by DomClark** [LMMS/lmms#4406]
Occasionally, when exiting LMMS, the process remains hanging. I don't have a backtrace unfortunately, because gdb takes ages to launch LMMS on my machine, and I can't reliably trigger the issue, but here's what I gleaned from Process Hacker on the 1.2.0-RC6 release:

Main thread is blocked on `SDL_LockAudio()` in `AudioSdl::stopProcessing`:
https://github.com/LMMS/lmms/blob/3bf3fab0e33b7bb199b2c4b32b1ccd0e1da096ca/src/core/audio/AudioSdl.cpp#L106-L115
`AudioSdl::stopProcessing` is called from `Mixer::stopProcessing` is called from `LmmsCore::destroy`.

The SDL audio lock is held by SDL which is in the audio callback, which is blocked on `m_reader_sem.acquire()` in `fifoBuffer::read`:
https://github.com/LMMS/lmms/blob/32f07ac317b42dda42a1d00b0a3b1fa1feef0655/include/fifo_buffer.h#L60-L67
`fifoBuffer::read` is called from `Mixer::nextBuffer` is called from `AudioDevice::getNextBuffer` is called from `AudioSdl::sdlAudioCallback`.

Related: #4032.

**Comment by PhysSong** [comment]
I've seen this a few time. I think https://github.com/LMMS/lmms/pull/4083#issuecomment-368321330 may be related, too.
I'll look into this.

**Comment by PhysSong** [comment]
LMMS uses two sort of audio backends:
- Thread-based: ALSA, OSS, sndio
- Callback-based: JACK, PortAudio, PulseAudio, SDL, soundio

FIFO buffer writes a null buffer to notify processing is stopped. It works fine for thread-based backends because `stopProcessing` waits for audio thread until it receives the null buffer.
However, the mechanism may fail for callback-based backends for some reason. It may either suffer from deadlock or quit processing in unexpected way.

I think the best way is to check whether audio backend read the null buffer sent from `Mixer::fifoWriter::run`. Also, all callback should stop processing when receiving null buffer.
