### ISSUE TITLE
seperate FX sends

### ISSUE THREAD

**Issue by noahb01** [LMMS/lmms#4423]
It would be very useful if you could send the pure wet signal from an effect to a separate FX channel, i.e. a Reverb effect should be able to send just the reverb signal to FX2 while sending the pure, original signal to FX1. This would allow for further manipulation of the effect output without compromising the original signal. For example, I've always wanted to sidechain the reverb without sidechaining the original signal.

**Comment by SecondFlight** [comment]
Try this:
Send your instrument to FX1. Send FX1 to FX2 and FX3, and send FX2 and FX3 to FX4.
Put your reverb on FX2 with the signal set to 100% wet.

Now you have a completely wet signal in FX2 and a completely dry signal in FX3, and you can add effects to them separately on FX2/FX3 or together on FX4.

This is pretty much what @karmux is saying, but this will also let you put effects on the input/dry/output signals in addition to the wet signal.

**Comment by noahb01** [comment]
@SecondFlight @karmux I didn't think of that, good idea! However, it would still be easier to allow the effect to send wet/dry signals to different channels, and it would only use 2 fx channels instead of 4

**Comment by Spekular** [comment]
You can still achieve this with two, SecondFlight's method just adds some
flexibility. The simpler method, as mentioned is:

 * Instrument to Channel 1
 * Channel 1 to Master & Channel 2
 * Reverb on Channel 2

I use this kind of setup all the time to sidechain my reverb.

Your proposal seems like it might be interesting in other usecases though,
although I can't think of any off the top of my head.

On Jun 12, 2018 22:34, "Noah Brecht" <notifications@github.com> wrote:

@SecondFlight <https://github.com/SecondFlight> @karmux
<https://github.com/karmux> I didn't think of that, good idea! However, it
would still be easier to allow the effect to send wet/dry signals to
different channels, and it would only use 2 fx channels instead of 4

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LMMS/lmms/issues/4423#issuecomment-396724319>, or mute
the thread

**Comment by SecondFlight** [comment]
I personally don't see enough use cases to merit this kind of extra complexity. If this truly did allow you to do something new that you couldn't do before then I could see the case for it, but as far as I can tell it doesn't.

**Comment by tresf** [comment]
> send the pure wet signal from an effect to a separate FX channel

You can send an instrument.  You can send a channel.  You **cannot** send an effect.  If you want an effect to have a "send" option, you're using the software wrong.  This is a workflow issue as @SecondFlight has described unless we're all missing something.  Feel free to correct me. :)

**Comment by noahb01** [comment]
In that case, I'll close this issue.
