### ISSUE TITLE
Discussion: Adding Machine Learning features to improve LMMS

### ISSUE THREAD

**Issue by darkmastermindz** [LMMS/lmms#4587]
I was thinking of training the sounds and then manipulating them towards the producer's workflow, Because sound is just values, modeling won't be too terribly difficult (however, it may take multiple models to create the desired result). 

More so for like mixing and generating new sounds and giving good suggestions (will help with UX a lot too).  Mixes it in a way that assists the producer. A very general analogy example would be kinda like autocomplete / autosuggestion with assistance on fine-tuning things but for LMMS.

The obvious issue here is that I'd have to use Python and the project is in C/C++ and the data-collection of features would be required to make this work. 

Help in this is appreciated!

**Comment by tresf** [comment]
> The obvious issue here is that I'd have to use Python and the project is in C/C++ and the data-collection of features would be required to make this work.

Python works well with C++ but as far as I understand things need to be externally exposed which is where it would get tricky.  Perhaps hooking into the signals and slots would be a good first step, but you may need to bundle PyQt and likely dealing with IPC.

@falkTX has some experience in this area both with Python, PyQt as well as IPC since he's the author of Carla (https://github.com/LMMS/lmms/pull/1155).

I'd recommend starting with a proof of concept.  Also, providing an example machine learning plugin or example for another C++ app would be a good baseline for yourself or others looking to expand on this feature.

**Comment by DeRobyJ** [comment]
I think we should define what are the values to edit and what is the user input.
Multi-layer perceptrons can easily be developed in C++, however since our goal is not to classify things, but to help the user in some tasks, we should find an appropriate mathematical tool for "error correction".

Let's make a quick example on a basic utility for a plugin than implements randomness: sfxr.
When you want to make an 8-bit game-like sound, you now have to listen to various randomly generated examples.
The user could rate the current sound as "great, good, bad, trash", and this would be saved in the current instance of sfxr.
By doing that, that instance will now generate sounds based on the user opinion and taste.


Another completely different example of machine learning would be score writing.
That is, completing a score initiated by the user, or giving a brief inspiration.
Although this would require tons of data by the same user, ready to be analyzed to suit their tastes.

A more general kind of approach would be a "what did I do in similar situation"-kind-of-assistant.
It would record the user actions in certain situations (that is, the data in the currently edited view), and then it would put suggestions deliberately (constant resource usage) or by user request.
The user may even want to use it reversely: doing what they never did but not following suggestions.
This requires a lot of data to be userful, but not as much as the previous one.

I'd be glad to help in this kind of project 👍

**Comment by DouglasDGI** [comment]
Slightly off-topic, but I actually just happen to be programming the same thing for ZynAddSubFX right now, except it's an external program written in Python.  When it's finished, I wonder how possible it would be to convert that into C++ and implement it into LMMS.

**Comment by tresf** [comment]
@DouglasDGI it's not off-topic at all.  

> The obvious issue here is that I'd have to use Python and the project is in C/C++ and the data-collection of features would be required to make this work.

**Comment by darkmastermindz** [comment]
@DouglasDGI My thoughts would be it would be easier to implement something that interfaces with the python code since the ML community doesn't use C++ for a lot of reasons (such as it's easier to adjust hyper parameters in python and focus on the data). Would still need someone knowledgeable to help me implement ways to gather that relevant data for LMMS though before anything can be done on my part @tresf.

**Comment by darkmastermindz** [comment]
> 
> 
> Slightly off-topic, but I actually just happen to be programming the same thing for ZynAddSubFX right now, except it's an external program written in Python. When it's finished, I wonder how possible it would be to convert that into C++ and implement it into LMMS.

@DouglasDGI My thoughts would be it would be easier to implement something that interfaces with the python code since the ML community doesn't use C++ for a lot of reasons (such as it's easier to adjust hyper parameters in python and focus on the data). Would still need someone knowledgeable to help me implement ways to gather that relevant data for LMMS though before anything can be done on my part @tresf.

**Comment by lukas-w** [comment]
This may be interesting research idea but it's extremely unlikely to happen as a part of this project. Closing because it doesn't make sense to track it here.
