### ISSUE TITLE
LMMS just broke my project.

### ISSUE THREAD

**Issue by igggo123** [LMMS/lmms#4729]
I'm on Windows. Is there a wat to repair/recover it?

**Comment by DouglasDGI** [comment]
@igggo123  I'm unsure if Github is the right place to be asking this, especially since no details of any sort have been given concerning the circumstances causing it to break, what about it is broken, your LMMS version (bugs should not be reported for older versions of LMMS, as far as I'm aware), or whether it's even a bug or just user error.

But to answer your question, you should find a .mmpz.bak file where you saved your LMMS project.  Just rename the file from "project.mmpz.bak" to "project.mmpz", and your file should be recovered.  "BAK" means "backup".

**Comment by zonkmachine** [comment]
> I'm on Windows. Is there a wat to repair/recover it?

Maybe but there is too little information here.
Which version of LMMS are you are using?
Can you describe what happened when things went wrong?
Were you saving/playing?
Can you upload the file somewhere?
