### ISSUE TITLE
Improve plugin preset browser and effect browser (for LV2)

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#4733]
This is more a meta issue/discussion.

When LV2 will be implemented, tons of new instruments and effects will likely be available. The downside of this is that users will have to search and scroll to find the plugin/preset they like.

In Discord, we (@DomClark, @SecondFlight, @t0nit0rmx, @tresf and me) had some initial discussion. The ideas were, at least for the instruments, that
* Everything should be doable via the **presets**: LMMS will add a default preset to the tree for every instrument, and drag-dropping this will add the desired instrument, but won't load any file.
* The presets widget should be structured **tree-wise** (already true).
* There should be a **search bar**, like in the `EffectSelectDialog`.

Some open questions:
* How does this apply to the EffectSelectDialog? Effects can, in theory, also have presets (though it's not the case in LMMS currently).
  1. One way would be to add **a new effect file browser** (like for the instruments) and let users drag-and-drop the effects into effect chains etc.
  2. Or the **EffectSelectDialog will contain a file browser** (no drag-and-drop).
  3. Or a **different idea** to let EffectSelectDialog also select presets?
* How to group the presets tree widget?
  1. By **instrument**? (Currently true)
  2. By **folder**? If you look for a new suited bass, do you care from which instrument it is? Or do you prefer to have a folder "basses", where you can quickly get the bass you want? (Note: Can still be changed later)
  3. Note that there will probably be **more than 1 levels**, e.g. X42 plugins -> equalizer -> equalizer 1, equalizer 2, ...

Feature requests resulting from this (in progress, all independent from LV2 implementation):
* Add search bar to plugin window (good first issue)
* Add default pseudo preset to each preset (good first issue)

A final note: We've discussed [the project aurora gui](https://github.com/SecondFlight/aurora-borealis/tree/slider). It's currently not ready yet and due to time pressure, I wouldn't want to wait with LV2 for it.

**Comment by tresf** [comment]
I'm not married to any specific solution, but... 

* Drag-and-dropping of effects as well as effects presets have my vote
* Searching (naturally) has my vote.

It may be sensible to isolate the built-in plugins visually from the 3rd party ones as it affects portability.  
* We already do this -- rather accidentally -- with the VST instruments because they're dragged in using the same file browser used for dragging in samples and patches (sf2, gig).  Perhaps we move this to a "Plugin" file browser.  I'm not sure if SF2 and Gig would fall into that category or of they stay in samples.
* We don't currently do this well for the Effects browser.  VSTs are lumped in with the rest but there's a table that can be used to sort.

In regards to the tree -- vs. -- table listing, I'm not sure.  I use the effects browser a lot and I really like being able to type and search for a plugin.  We don't offer much metadata about each plugin (and nothing besides the type is searchable) so classification can be a conversation on its own (e.g. Guitar ~= Bass ~= Synth).  I'd be interested to know how other DAWs do it.

Currently, I categorize my soundfonts based on classification but they're generally recorded instruments.  I'm not sure how software instruments should be classified and I'd hate for that type of conversation to spam this bug report. :)

**Comment by JohannesLorenz** [comment]
I think what @tresf suggested can mostly be realized. The mockup suggested by @budislav suggests to use a tree widget for the plugins, where you can expand LV2 and native. That, together with a search bar, should be what you (and budislav and I) are thinking of.

Grouping differently, i.e. by bass/guitar/piano etc, should still be doable later.

If no one else has an opinion on it, I'll open a beginner feature request now, which groups the plugins in a tree widget of buttons (instead of a vbox of buttons) now and adds a search bar on top. The tree view will only have 2 top level items now: LMMS (all must be put there now) and LV2 (empty right now):

```
<filter search bar>
LMMS
|- bit invader
|- triple oscillator
|- zynaddsubfx
|- ...
LV2
```

**Comment by Spekular** [comment]
It seems a bit odd to have VeSTige under the LMMS category while LV2 gets
it's own heading.

**Comment by noahb01** [comment]
Presets for effects would be great, especially for compressors/eq with lots of settings that need to be tweaked.

**Comment by JohannesLorenz** [comment]
As this is done in the corresponding PR #4759 already, I'll close it.
