### ISSUE TITLE
LadspaEffect : free ptr pointer

### ISSUE THREAD

**Issue by shlyakpavel** [LMMS/lmms#4753]
https://github.com/LMMS/lmms/blob/7f0593c601a7f48fda193139f2d6bb3d76f10384/plugins/LadspaEffect/tap/tap_dynamics_st.c#L255-L262
I guess it would be nice to free allocated memory for ptr pointer before returning from the function :)

**Comment by michaelgregorius** [comment]
The does not seem like problematic code to me because `as` is assigned to `ptr` [a few lines later](https://github.com/LMMS/lmms/blob/7f0593c601a7f48fda193139f2d6bb3d76f10384/plugins/LadspaEffect/tap/tap_dynamics_st.c#L268). This buffer is then later free'd in the function `cleanup_Dynamics` ([here](https://github.com/LMMS/lmms/blob/7f0593c601a7f48fda193139f2d6bb3d76f10384/plugins/LadspaEffect/tap/tap_dynamics_st.c#L689)).

**Comment by michaelgregorius** [comment]
Ok, now I understand. You mean that the `malloc` for `ptr` which is done [here](https://github.com/LMMS/lmms/blob/7f0593c601a7f48fda193139f2d6bb3d76f10384/plugins/LadspaEffect/tap/tap_dynamics_st.c#L249) is not free'd in the cases where we return `NULL` prematurely. You are right, this should result in a memory leak.

However, this is rather a problem in the upstream code of the LADSPA project. I don't know if the copy inside LMMS' code is really maintained or updated from the upstream code.

**Comment by tresf** [comment]
@shlyakpavel please submit a PR to the author.  We use his submodule in `master`.

https://github.com/tomszilagyi/tap-plugins/blob/master/tap_dynamics_st.c#L253-L259

In the meantime if you feel this worthy of backporting to `stable-1.2` branch, we'd happily accept it once merged upstream.
