### ISSUE TITLE
RmsHelper.h : strange code

### ISSUE THREAD

**Issue by shlyakpavel** [LMMS/lmms#4754]
https://github.com/LMMS/lmms/blob/7f0593c601a7f48fda193139f2d6bb3d76f10384/include/RmsHelper.h#L79-L80
The modification of the 'm_pos' variable is unsequenced relative to another operation on the same variable. This may lead to undefined behavior.
This is pretty strange. Can one explain it?

**Comment by michaelgregorius** [comment]
I think this code is OK because the assignment operators are executed from right to left and therefore the order of the operations should be predictable ([source](https://en.cppreference.com/w/cpp/language/operator_precedence)). There also isn't any modification of `m_pos`.

So the intention is the following:
1. The current value of the buffer at `m_pos` is subtracted from `m_sum`.
2. The value in the buffer is replaced with the square of `in`.
3. The new value is then added to the current value of `m_sum`. So it's the same as `m_sum = in * in`.

**Comment by shlyakpavel** [comment]
> are executed from right to left

Why?

>new value is then added to the current value of m_sum

It can be either the old value or the new one

**Comment by tresf** [comment]
> > are executed from right to left

> Why?

I'll quote [stackoverflow](https://stackoverflow.com/a/19353704/3196753):

> Remember that assignment is done right to left, and that they are normal expressions. So from the compilers perspective the line
> 
> ```cpp
> sample1 = sample2 = 0;
> ```
> is the same as
> ```cpp
> sample1 = (sample2 = 0);
> ```
> which is the same as
> ```cpp
> sample2 = 0;
> sample1 = sample2;
> ```
> That is, `sample2` is assigned `zero`, then `sample1` is assigned the value of `sample2`. In practice the same as assigning both to zero as you guessed.
