### ISSUE TITLE
Double-listing of plugins and instruments

### ISSUE THREAD

**Issue by binaryblob01** [LMMS/lmms#4791]
Operating system: openSuSE Tumbleweed x64 (Tumbleweed is rolling release, Qt libs have not been updated or changed since compiling LMMS)
Qt version: 5.12.1 (source cloned from Qt git repo and compiled, placed into /opt)
LMMS version: 1.2.0-rc7 (source cloned from LMMS git repo and compiled, using Qt 5.12.1 libs, placed into /opt)

LMMS displays instruments and plugins twice when loading with Qt 5.12.1, although both listings do work correctly. When forced to load with Qt 5.12.0 provided by system, plugins are not displayed twice (but Vestige is missing and the drag'n'drop bug comes back).

I have verified that LMMS is using the correct libraries via LD_DEBUG

Attached screenshot of listing issue. It also affects plugins/effects list and LADSPA plugins list as well.

![screenshot_20190120_113925](https://user-images.githubusercontent.com/25039459/51717751-c09ec000-2007-11e9-8b5c-00ef48a477c6.png)

On a side note (and it may or may not be related), even when using LMMS compiled against Qt 5.12.1, it still gives the following error:

`15283:     /opt/qt5.12.1/lib/libQt5Widgets.so.5: error: version lookup error: version Qt_5.12.0_PRIVATE_API' not found (required by /opt/lmms/lib/lmms/libvstbase.so) (fatal)
Cannot load library /opt/lmms/lib/lmms/libvstbase.so: (/opt/qt5.12.1/lib/libQt5Widgets.so.5: versionQt_5.12.0_PRIVATE_API' not found (required by /opt/lmms/lib/lmms/libvstbase.so))`

Vestige still works, despite the error.

**Comment by tresf** [comment]
* Updated the [build tutorial for openSUSE](https://github.com/LMMS/lmms/wiki/Dependencies-OpenSUSE#qt5) to include Tumbleweed packages.
* Reproduced "drag'n'drop bug" in Qt 5.12.0 that is provided with openSUSE Tumbleweed.
* Downloaded [Qt 5.12.1](https://drive.google.com/file/d/1bw9qHYR-uwuGbf-R8d_aRqMjXpnefeX_/view?usp=sharing) that @binaryblob01 (`@abjumpr` on Discord) made.

I can't reproduce the double-plugins issue.

![image](https://user-images.githubusercontent.com/6345473/51766967-044a0600-20aa-11e9-91ff-85d574bca4f4.png)

![image](https://user-images.githubusercontent.com/6345473/51767017-280d4c00-20aa-11e9-835c-79196e2176e9.png)

![image](https://user-images.githubusercontent.com/6345473/51767111-686cca00-20aa-11e9-80c1-8ccb8ba726ce.png)

Vestige loads and appears to work, but the plugin I'm testing with deadlocks the software if any embedding is used, so I had to turn off embedding.
![image](https://user-images.githubusercontent.com/6345473/51767778-5c820780-20ac-11e9-9701-441f1d6d158e.png)

**Comment by binaryblob01** [comment]
Unable to reproduce again on a fresh install.

**Comment by Jacalz** [comment]
I am having almost the same issue on Solus when I built the latest 1.2.0 version of lmms. All plugins appear twice and seem to both work. I would be very happy to help out diagnosing this issue with you, because this is a problem and it needs to be fixed. We are building with Qt version 5.12.3. I am currently working on updating the package on Solus and would like to get this fixed before it goes out to stable.

![image](https://user-images.githubusercontent.com/25466657/59961276-d55b8300-94d5-11e9-8dc4-1919c86c5214.png)

Not doubled:
![image](https://user-images.githubusercontent.com/25466657/59961290-09cf3f00-94d6-11e9-91ff-40b914db94d9.png)

![image](https://user-images.githubusercontent.com/25466657/59961297-1f446900-94d6-11e9-82cc-5ba25a789211.png)

Link to package.yml file of lmms (if how it is built would be interesting): https://dev.getsol.us/D6546
Link to Qt build file: https://dev.getsol.us/source/qt5-base/browse/master/package.yml

If there is any special way you need to debug or anything to test, please ask me to do so.

**Comment by Jacalz** [comment]
All effects and the LADSPA plugin browser entry under tools in the menu bar is double too:
![image](https://user-images.githubusercontent.com/25466657/59966311-10cc7080-951b-11e9-9037-344f2dd9ea72.png)

**Comment by Jacalz** [comment]
This is only reproducible when installing to lib64 not lib, managed to fix the issue :+1:
