### ISSUE TITLE
Record chords

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4807]
Edited by @tresf 

In the Piano Roll editor, the "chords" drop-down does not affect notes played through a keyboard, only those placed with a mouse, also impacting recording.

![image](https://user-images.githubusercontent.com/6345473/54231711-64bcc780-44df-11e9-867f-ce1ad2175950.png)

---

Original

When the piano-roll *chord-selector* has any other setting than *no-chords*, using  *record* ought to insert the selected* chord* in piano-roll. For now only the pressed note is inserted.

**Comment by tresf** [comment]
Agreed, this should record chords directly into the Piano Roll.  I consider this a bug.  It's also a good first issue for a newcomer to the project.

Quality issues with this bug report:
* The description needed improvement
* Please refrain from over-using italics, or drawing unnecessary emphasis to made up words.
* Please provide a small screenshot when possible.  It helps removes ambiguity caused by a bad report.
