### ISSUE TITLE
Embedded plugins hide UI by default

### ISSUE THREAD

**Issue by Pyrif** [LMMS/lmms#4834]
Upon starting the program, I thought my UIs weren't loading at all. I believe this to be a UX issue, and it made me hesitant to switch until I found out what the problem was.

RC8 Win10

**Comment by DomClark** [comment]
I guess you're referring to VST effects when loading projects. This seems to be because the saved visibility is taken from the plugin widget:
https://github.com/LMMS/lmms/blob/e7720cc8cb878fb33fa31b1339ad1ffcdd93f00c/plugins/vst_base/VstPlugin.cpp#L196
If the effect control dialog is closed, the widget is not visible and so is saved as being hidden. When the control dialog is opened, the plugin UI is hidden, and needs to be shown using the "Show/hide" button.
Since projects load with all effect control dialogs closed, any untouched plugin UIs will enter the hidden state over two save-load cycles.

**Comment by Spekular** [comment]
How often do people want to hide the UI of an effect they're opening? If it's hard to remember the state correctly it'd probably be better to default to having the UI expanded.

**Comment by tresf** [comment]
> How often do people want to hide the UI of an effect they're opening? If it's hard to remember the state correctly it'd probably be better to default to having the UI expanded.

* Initial Load: Never
* Project Open: Always

**Comment by Spekular** [comment]
Closing and consolidating into #5433
