### ISSUE TITLE
What are your thoughts on this UI update I might add?

### ISSUE THREAD

**Issue by InVaLiDEDM** [LMMS/lmms#4845]
If enough people seem to like this, I might start developing it.
My idea was to have these changes to patterns:

B/B Patterns show notes of what's inside them
Patterns become slightly transparent (handy for when you are overlaying patterns)
Patterns lose their border
Patterns become slightly rounded

Here's a quick photoshop for reference:
![untitled-1](https://user-images.githubusercontent.com/47680576/53279029-8558e500-36ca-11e9-81be-bbdd34320923.png)

(Accidentally set the border radius in photoshop too high on the drum patterns, if I was to do it for real I'd lower the radius)

**Comment by MeapMusic** [comment]
This would be really helpful!
It annoys me sometimes when I see a b/b track and I forgot what its purpose was, in which I have to click inside to see.
Just a personal preference, but I do not like many windows open at once :P 
It would also make the things in b/b seem like it's actually part of the music now, not just some opaque box that spits out stuff inside. It makes it seem more organised, like a group of notes to be repeated again and again, but then it can be seen yay

**Comment by musikBear** [comment]
> B/B Patterns show notes of what's inside them

Yes, that could be ok, however it should not obscure names, and if a pattern is empty (eg used for setting up a structure, then it should be no problem.
> Patterns become slightly transparent (handy for when you are overlaying patterns)

Well LMMS is meant to have real ghosted notes in 1.3, so note-blocks on to of note-blocks is not a normal usage, and would be confusing. Previously it has even been discussed, that it should impossible. I find this feature unneccesary 
> Patterns lose their border

Absolutely **not**. I want to stress this, because it is the only way you in song-editor, can see withch block you just have worked with. In fact i would favor a more prominemt border -Alternatively, a different 'mark-of-last-edited' could be substituting current border, but a way to spot the 'last-edited' is crucial!
> Patterns become slightly rounded

No! This would make it more difficult to see snapping between Pattern-blocks. It would be an unnecessary and even impractical feature.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
