### ISSUE TITLE
Carla plugin fails to build with 'develop' branch of Carla

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#4909]
As of https://github.com/falkTX/Carla/commit/d4a0292f37c2948d6e649bac1a6f218292566416, Carla plugin fails to build. The API-breaking commit changed the type of `inBuffer` parameter of `NativePluginDescriptor::process` from `float**` to `const float**`.

The conversion from `float**` to `const float**` [can't be done implicitly](https://en.cppreference.com/w/cpp/language/implicit_conversion#Qualification_conversions), while `float**`-to-`const float* const*` conversion can be implicit(in C++, not in C).
This means if we want to fix the build for newer versions of Carla, we must drop support for old versions(which Mac builds use) since the only way to convert pointers between `float**` and `const float**` in C++ is explicit `const_cast`s.

@falkTX

**Comment by falkTX** [comment]
There are some other changes actually, that make it ABI incompatible between 2.0 and future 2.1
I took the chance to cleanup the API since backwards compatibility was going to be broken anyway.
This is all happening on the develop branch, for which there might still be more changes.
I will send a PR-fix to LMMS when I get finalize tests and decisions.

This is not yet something that LMMS needs to be concerned about, I think.
Though if building packages for Linux still uses KXStudio repos for its `carla-git` (I guess this is how you noticed the breakage?) then simply change the package name to `carla`.
I am releasing v2.0 as stable in the next few days, the changes in the repos reflect that.

See also https://kx.studio/News/?action=view&url=changes-in-kxstudio-repos-regarding-carla-and-jack2

**Comment by PhysSong** [comment]
As of 032c324dbc592173f94d24f835f8a7fdc8f73879, Travis-CI builds use `carla`. Please let us know when you make a final decision.

**Comment by falkTX** [comment]
As of https://github.com/falkTX/Carla/commit/0514349938fd7cc1cdfc23e9aee34d8184cd0d04 Carla 2.1 plugin ABI is now backwards compatible with 2.0 again.
So both versions are fine, though I recommend to keep using the `carla` stable version without git/develop[ment] stuff.

Note there might be some minor compiler warnings building against 2.1 of carla, since new enum values got added. but they are all optional

**Comment by tresf** [comment]
> As of falkTX/Carla@0514349 Carla 2.1 plugin ABI is now backwards compatible with 2.0 again.

@falkTX working on #4813 I encountered the same exact issue mentioned above using the tip of the `develop` branch, so I believe this statement to be incorrect, no?

The temporary fix for #4813 was to checkout the submodule at revision `v2.0.0`, which is currently working just fine.

**Comment by falkTX** [comment]
ah I forgot this part. I will update Carla so that it matches old API.

**Comment by falkTX** [comment]
Should be fixed now, please confirm

**Comment by tresf** [comment]
> Should be fixed now, please confirm

Seems to work just fine, thanks!
