### ISSUE TITLE
Please use semantic versioning for the project

### ISSUE THREAD

**Issue by Praveen-Rai** [LMMS/lmms#4917]
> Yeah !! version 1.2.0 - RC8 is out, soon we'll be having our hands on v1.2.0. But !! Wait a second we release 1.2.0 - RC1 on Feb 17, 2016. Seriously ?? Waiting 3 years for a minor version upgrade ?

That's how it typically would be interpreted. I can see a huge list of improvements and bug/fixes in the release notes. The only thing is that our versioning system fails to highlight all the hard-work.

I would request to use use 2.0 instead of 1.2.0, that signifies the 3 years of development and the huge improvements ( and might have broken backward compatibility ). Also, looking at the trend, we usually release only twice in a year so may be we can keep bumping the minor version for all those releases.

**Comment by Gabrielxd195** [comment]
You're right, friend, and I'm worried. in another thread I had talked about the subject. In addition to the lack of developers and contributors, version control and the stability model are a big part of the problem.

In each release many errors are corrected, each mistake is important, but because there are many errors, each release takes too long to develop. I think they took the wrong way to adopt this release model, it would have been better to launch small and constant periodic updates to the stable version (1.1.3, 1.1.4, 1.1.5, etc) and try new features in the test ( RC), which focus only on making large corrections in the test version (RC). for the stability of a program is necessary constant maintenance, and that's why we see that the version '' Beta '' is more stable than '' Stable ''. perhaps you have not noticed this?

Currently there is a milestone 1.2.1, maybe this is a stable 1.2.0 update, if so, then they changed the versioning, only missing that the developers do not accumulate too many corrections for that release and for the next ones, to have updates more constant. regards

**Comment by zonkmachine** [comment]
The version of the next stable release is 1.2.0 from the stable-1.2 branch.
