### ISSUE TITLE
req. Refresh button

### ISSUE THREAD

**Issue by Davi-Danger** [LMMS/lmms#4947]
Lmms often has syncing issues which can be fixed by closing the program and re-opening it. Although these are fundamental issues which need to be patched eventually, one button or hotkey (preferably both) which would restart the software and load the old file would make song creation much easier.

**Comment by musikBear** [comment]
> Lmms often has syncing issues 

Sync with *what*?
If you mean external-files, like samples, then a 'sync-button' already exists, it is the circular arrow *next to the search-window*:
https://lmms.io/wiki/images/e/e3/Sidebar-search_1.1.0.png
If you refer to MIDI sync, we need more about the MIDI-peripheral you need to sync, and in what circumstances and on witch OS

**Comment by Gabrielxd195** [comment]
> > Lmms often has syncing issues
> 
> Sync with _what_?

I do not think he's talking entirely about synchronizing, but he mentions that LMMS has synchronization problems (although he does not say which). I think it refers to '' restarting '' the program and '' irrigating '' automatically the recently closed project.

This option if it is needed in LMMS, since whenever you make a configuration in options, it asks to restart the program, and also it would help in the problems of synchronization to which the user refers.

**Comment by T0NIT0RMX** [comment]
If OP is talking about sync problem like VST that sometimes are out of sync (happened a lot to me with the sidechain Vst bigkixdippa) I've never encountered this bug in RC8

@davi-danger what LMMS version do you use ?

**Comment by Davi-Danger** [comment]
When I wrote this issue I was using 1.1.3, and have since switched to RC8. With the beta I haven't had the syncing issues, which I realize I never explained. 
@musikBear @T0NIT0RMX  Often when I deleted a track, it appeared to have been deleted: can't click on the track or see it; however, upon hitting play, the track still plays as if I didn't delete the track at all. The only solution to this from what I can tell is to close the program entirely. Once it's reloaded, the "deleted" track is visible and can be deleted genuinely.

**Comment by SecondFlight** [comment]
@Davi-Danger Glad RC8 is working well for you! I'm going to close this issue, as you said you're not having the problem with RC8. Feel free to comment here if you see the issue again in the beta, and I'll reopen.

**Comment by Gabrielxd195** [comment]
> Feel free to comment here if you see the issue again in the beta, and I'll reopen.

I have not experienced any synchronization problems in the beta version. but I do not think it is necessary to close this thread, because they focused more on the synchronization problem than on the same suggestion about the '' reset '' button in LMMS that @Davi-Danger gives us. since LMMS does need it because whenever you configure it, it asks you to restart the program.

This had happened to me before but I never suggested it, and I dare not suggest this in another thread because then they would mark it as a duplicate. it is better to reopen this thread, change the title to: '' Add reset button '', and edit the report that only talks about this suggestion.

**Comment by tresf** [comment]
A nice workaround is to go into preferences and tell LMMS to open the last file.  Then, closing and restarting is much less clicks.  Could probably write a taskkill script to make it easier.  I used to have a High Priority script for a similar purpose (VSTs would lag) until I just reached in and patched the code. :)
