### ISSUE TITLE
Merge PRs targeting stable-1.2 right before the release?

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#4989]
As the 1.2.0 release seems close, I wonder if we can merge branches of medium or large size targeting stable-1.2. In my case, it was #4976 . The review was successful, but it's one of those fixes that could have side-effects.

If we merge now, there may not be enough time to test before the 1.2.0 release. If we wait, it will go into 1.2.1, right? What would be appropriate?

**Comment by BaraMGB** [comment]
In my opinion we should merge the fix and fix the side effects in 1.2.1. 😉

**Comment by tresf** [comment]
#4976 is an enhancement to current functionality and shouldn't have been targeted against `stable-1.2` in the first place.  That said, if you guys are willing to take on the risk, merge it before release. 👍

**Comment by Spekular** [comment]
At this point I think it's worth postponing even fixes, assuming they're not fixing severe regressions. We do have a known bugs section in the release notes.

If 4980 is fixed and no worse bugs are found in the meanwhile, I think it's time to release.
If 4980 isn't fixed by June 16th (a month since the issue was opened)... release anyway?

**Comment by Spekular** [comment]
Update: #4980 is fixed for 1.2, and no worse bugs have been found in the meantime.

**Comment by JohannesLorenz** [comment]
We might want to wait for #4996

**Comment by JohannesLorenz** [comment]
#4996 is now also solved

**Comment by JohannesLorenz** [comment]
As we are about to release, I'm closing this thread. Feel free to reopen.
