### ISSUE TITLE
Spectrum Analyzer: Default Y scale should have a greater range

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#5090]
The current default Y range of the Spectrum Analyzer is rather limited and hides information from the user. Here's a comparison between the current "Default" setting, the "Audible" setting and the "Extended" setting. They all show the same signal.

Default:
![SpectrumAnalyzer-ScaleDefault-Small](https://user-images.githubusercontent.com/9293269/61658286-566c8c80-acc5-11e9-9ae3-9104ad81c7b3.png)

Audible:
![SpectrumAnalyzer-ScaleAudible-Small](https://user-images.githubusercontent.com/9293269/61658299-5d939a80-acc5-11e9-952a-9d56eafef426.png)

Extended:
![SpectrumAnalyzer-ScaleExtended-Small](https://user-images.githubusercontent.com/9293269/61658312-64baa880-acc5-11e9-9671-e8f1553fb783.png)

The current "Default" scale makes it look like there's no signal above 3-4 kHz.

**Comment by he29-net** [comment]
The ranges are up for discussion, of course -- I chose them somewhat arbitrarily, based on some experiments and my judgement.

My thinking behind it was to, by default, limit the range to signals that can be easily heard -- anything hidden in the first view will be almost certainly masked by all the stronger low frequency components. This is not to _hide_ information from the user, but the opposite: is is meant to make the best possible use of the vertical space.

The Extended scale makes it look like the spectrum is rather uniform. The small "disturbance" at 200 Hz seems insignificant. But in the Default view, you can clearly and easily see it is about 2 dB, which can certainly make a difference.

But I'm not opposed to the idea of making Audible the default range, if that's what people want. (For Audible, I simply turned my speakers all the way up and slowly increased the volume of an instrument until it became audible, and that became the lower limit.) The current Default range could be then renamed to Loud or something. But using the Extended range would seem to me as an absolute overkill.

 - :tada: -- Audible by default, rename Default to Loud
 - :rocket: -- keep Default
 - :eyes: -- other (explained below)

**Comment by SecondFlight** [comment]
Personally, I expect metering tools to represent what's actually happening in the signal, not what I hear. I use metering tools because I don't trust my ears.

As a producer, having more visual information allows me to better read the visual footprint of my audio, and it helps me to make better and more informed decisions as I develop intuitions from the information I'm seeing.

I'm fully in support of 🎉 as I believe it will alleviate confusion for new producers.

Sidenote: Voxengo SPAN defaults to the equivalent of `extended` and allows you to set a vertical zoom window in the UI.

**Comment by michaelgregorius** [comment]
I have voted :tada: as it looks like a good compromise between potentially too much and not enough information.

**Comment by he29-net** [comment]
Audible also seems to better match the current waterfall "brightness" a bit better, so I tend to agree with making it the new default range.

I'm just not sure about the new name for current Default range. It goes from 0 dB down to -30 dB, having the role of focusing only on the "most interesting area" for properly mixed audio. But renaming it "Loud" does not really reflect that, since Audible goes up to +10 dB to cover the occasional occurrences of clipping signals, and Extended goes even higher to +20 dB, so Loud would be the second most "silent" range. And obviously, keeping "Default" would make no sense as well..

**Comment by michaelgregorius** [comment]
Good question. What do you think about renaming it to "Peaks"?

Now that I had another look at the screenshots I also wonder whether having vertical scales on the left and the right side is a bit redundant. If we only kept one Y scale we'd have some more space for the spectrum display.

**Comment by he29-net** [comment]
"Peaks" sounds like it may have something to do with Peak hold, making it potentially confusing, and it does not really describe a "range" or target sound intensity. I also thought about "Focused" range, but I'm not sure if that's descriptive enough (focused on what?). Or it could be a "Mixing" range, but during mixing you'll probably want to switch ranges anyway, based on current needs, so it does not make that much sense either. Or maybe sticking with "Loud" would be best after all? Hard to say..

As for left / right side labels, there are two main reasons: it is easier to read out values at the opposite side, and most of all, it is a convenient way to indicate which color means what channel in the stereo mode. Also, it makes the display symmetric, which looks a bit nicer in my opinion.

**Comment by SecondFlight** [comment]
Personally I thought "loud" made a lot of sense.

**Comment by he29-net** [comment]
OK, so let's keep Loud as the new name for current Default.

I just also realized there is a small problem with Audible as the new default range: it will make the default linear display even worse, because +10 dB translates to 10.0, so the linear range goes from 10.0 to 0, where values from 10 to 1.0 are used only when the signal is clipping. So the values will appear even smaller (#5089).

The current Default, on the other hand, goes only up to 0 dB (1.0), meaning that the linear range covers 1.0 to 0 and nothing else, making the linear peaks easier to see. So I'm thinking about changing Audible range upper bound from 10 to 0 dB to prevent making the other issue worse.

When you get clipping, you probably want to get rid of it, not to equalize or precisely measure it, so it should be not missed that much on default range. There is still the Extended range for those who need it. Also, having the signal go "outside of the graph" would be a clearer indication of clipping, given that other software (and the Eq plugin) may assign 0 dB to some arbitrary value, so having signal over 0 dB is sadly not a universal clipping indication. And it would also "support" the new "Loud" range name, so, really I see only positives.

**Comment by michaelgregorius** [comment]
The problem mentioned with the linear scale might be solved if my proposal to completely drop the option of the linear scale is accepted (see [this comment](https://github.com/LMMS/lmms/issues/5089#issuecomment-515131332) in #5089).

**Comment by he29-net** [comment]
This issue was fixed by #5160; the default range is now Audible, going from 0 dBFS to -50 dBFS.
