### ISSUE TITLE
Should Drag+Drop from Plugin to Host add Controls to host UI?

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5095]
If we have plugins with external UIs (Lv2, SPA, VST3 ...), when you drag-drop a control into an LMMS automation track/controller, this external control should be automated by LMMS. Now, I have been wondering about visualization of this connection, there are >=3 ways:

* :eyes:  **Maximal visualization.** After the drag-drop, the host UI (e.g. the counterpart of the plugin UI, see e.g. the Instrument "Plugin" window in the current zynaddsubfx) adds a knob, too.
**Advantage:** Maybe that you can see the controls moving without clicking through the external UI?
**Disadvantage:** Not trivial to implement. E.g.: we must take care of what happens if the user automates this visualized control (probably we must forbid that).
* :tada:  **Only listing.** After the drag drop, the host UI lists the controls as strings, also allowing to disconnect (e.g. right-click), but there are no controls (knobs) added.
**Advantage**: You see quickly what is connected,
**Disadvantage:** ?
* :rocket:  **Minimal visualization.** After the drag-drop, no knobs/strings/... are added. If you want to disconnect, you can drag-drop the plugin control on the controller rack in an area where no controller is, or, if it's connected to an automation track, via right-click on that.
**Advantage:** Easy to implement.
**Disadvantage:** You don't see directly what is connected to LMMS and what not.

Please vote, or propose another solution. Also, please name advantages/Disadvantage if you see any.

**Comment by DomClark** [comment]
I'm in favour of the "maximal visualisation" option. Presumably, when the user drags a control to some target (an automation track or controller), the target is connected to some internal `AutomatableModel` instance representing that control. The the host knob that is created for it can view the same model, in which case we don't need to worry about what the user does with the visualised control. (Or do you want to implement it differently?) An additional advantage of having knobs representing plugin controls is that the user can then interact with these in the same familiar way as the rest of LMMS.

**Comment by JohannesLorenz** [comment]
> the target is connected to some internal AutomatableModel

Indeed, using an AutomatableModel (one slightly modified, such that it sends to the plugin when changed) was what I planned for Lv2 (and already [use for SPA](https://github.com/JohannesLorenz/lmms/blob/osc-plugin/src/core/SpaOscModel.cpp)).

As you say, you can use that model and just add a UI control for it. I was thinking there might be some pitfalls or race conditions, but right now it seems logical to me.

Since we were already talking about group boxes of knobs ("LinkedModelGroups", #4964 )... If the plugin has both controls in host and plugin UI, and some plugin UI controls are automated, should those be put into a separate group box? I'd say yes, because it's getting easier to overview and only consumes a bit more space. I.e. 2 group boxes: "Fixed ports" and "Automated ports".

**Comment by Spekular** [comment]
As mentioned on Discord, I'm in favor of Maximal Visualization (along the lines of the current VST parameter list) whenever native behavior isn't available. Otherwise I prefer Minimal, i.e. behaving the same way that native knobs do when automated.

**Comment by musikBear** [comment]
I voted *listing*. I did so, because it resembles the current 'list of connections' known from automation-tracks, and controller-rack. eg, the implementation would not clash with current, so it would be intuitive for users. *Maximal* is neat, yes -but i can see confusion if some are lists, and some are not, witch in the end perhaps lead to 'needs' for a re-design of the listed ones, bringing *them* 'up' to the Maximal-std

**Comment by DomClark** [comment]
A couple more comments, which are mostly VST3-specific, sorry. Feel free to disregard them for LV2 if they don't seem appropriate.

Since it is optional for VST3 plugins to expose locations of controls in their UI to the host, and to implement host context menu integration, some plugins will need the "maximal visualisation" option anyway. Given this is the case, I think implementing it for all plugins would be more consistent. If a particular plugin offers more advanced integration, that's a bonus, but I don't think users should have to figure out how to do automation separately for each plugin.

> If the plugin has both controls in host and plugin UI, and some plugin UI controls are automated, should those be put into a separate group box?

VST3 provides a concept called [units](https://steinbergmedia.github.io/vst3_doc/vstinterfaces/vst3Units.html), which, among other things, the host can use to organise its internal representation of a plugin's parameters. If we take advantage of this for organising controls, putting automated controls in a separate group box as well may be difficult and/or messy. I was planning to use a similar technique to what we currently use for VST parameters, adding an option to show only automated controls. (Probably unrelated here, but there are a lot of requests to add an option to see recently changed plugin controls. Perhaps this could all be combined into one sorting option, e.g. "plugin-specified order", "alphabetical", "automated", "recently modified".)

**Comment by JohannesLorenz** [comment]
> Since it is optional for VST3 plugins to expose locations of controls in their UI to the host, and to implement host context menu integration, some plugins will need the "maximal visualisation" option anyway.

Yeah, that's a very good argument for maximal visualization. I think that already decides the whole discussion.

> Probably unrelated here, but there are a lot of requests to add an option to see recently changed plugin controls. Perhaps this could all be combined into one sorting option, e.g. "plugin-specified order", "alphabetical", "automated", "recently modified".

The ability to sort/filter indeed seems like an advantage for having one group box for all. :+1:

**Comment by JohannesLorenz** [comment]
Now I wonder *where* we should allow drag-drop actions to drop:

1. Only allow drag-dropping plugin-side controls directly on automation tracks/controllers. This will create mirroring models in the LMMS plugin window. (current solution)
2. Only allow drag-dropping plugin-side controls on the LMMS plugin window, which creates the mirroring models. If you want to automate them, you'll automate the mirroring models.
3. Allow 1 and 2.

The advantage of (1) is that it's just one drag-drop for a user to automate a plugin-side control. (2) looks more "clean" though (and maybe more easy to code). Any opinions?

**Comment by Spekular** [comment]
So essentially, 1 is a shortcut for 2 + automating the newly added knob?

My vote would be 3. Dragging to automation tracks should be consistent with existing knobs and as easy as possible. However, dragging onto the plugin window to create a mirror is nice if you want to connect that knob to another knob, for example.

**Comment by JohannesLorenz** [comment]
As I took the answer from @Spekular , I'll close the thread.
