### ISSUE TITLE
Add CMake switch to specify submodules

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5105]
Currently, there is no way to specify which submodules you really want to "fetch", cmake will just init and update all. There are currently `LMMS_MINIMAL` and `PLUGIN_LIST`, but those are only used for compiling, not for git.

I think `PLUGIN_LIST` should be used by the in `cmake/modules/CheckSubmodules.cmake`

Expected advantages of this are:
* reduction of compile time
* reduction of download time and bandwidth
* independence of broken submodules

**Comment by JohannesLorenz** [comment]
@tresf I can do this, but as `cmake/modules/CheckSubmodules.cmake` is your file, it might be better if you'd do it. In the latter case, I could offer a review.

**Comment by tresf** [comment]
> there is no way to specify which submodules you really want to "fetch"

This statement is not correct.  Submodules can be skipped by providing:

```bash
cmake -DSKIP_SUBMODULES=foo;bar
```

... as documented here: https://github.com/LMMS/lmms/blob/master/cmake/modules/CheckSubmodules.cmake#L13

> I think `PLUGIN_LIST` should be used by the in `cmake/modules/CheckSubmodules.cmake`

That script was written with the intention of being as generic as possible.  Although a human can "infer" which submodule pertains to a plugin, it's not a 1:1.

Plugin Name | Submodule Name
-------------|-------------------
Xpressive | exprtk
FreeBoy | game-music-emu 
tap | tap-plugins
swh | ladspa
caps | caps-lv2
calf | veal
OpulenZ | adplug

(please feel free to add any others that are missing)

To make one list influence the other, we'd need a cross-reference.

> it might be better if you'd do it. In the latter case, I could offer a review.

I'm not sure the best place to stash this meta info.  I guess we could look at the canonical folder name of the submodule we're about to clone and attempt to filter.  This could have scalability issues if we re-use a folder name although the plugin names are unique enough we might be ok.

**Comment by JohannesLorenz** [comment]
Ahhh `cmake -DSKIP_SUBMODULES=plugins/Xpressive/exprtk ..` worked.

Some things that could be improved:
* Fail if you asked to skip a module that the script did not recognize
* Allow slashes at the end of the folders (`-DSKIP_SUBMODULES=plugins/Xpressive/exprtk/`)

Using this, CMake errors because it still wants to build the plugin:
```
CMake Error at cmake/modules/BuildPlugin.cmake:57 (ADD_LIBRARY):
  Cannot find source file:

    exprtk/exprtk.hpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  plugins/Xpressive/CMakeLists.txt:19 (BUILD_PLUGIN)


CMake Error at cmake/modules/BuildPlugin.cmake:57 (ADD_LIBRARY):
  No SOURCES given to target: xpressive
Call Stack (most recent call first):
  plugins/Xpressive/CMakeLists.txt:19 (BUILD_PLUGIN)
```

Now, IIRC, if you just want to not build Xpressive, you have to use `-DPLUGIN_LIST=all plugins of lmms except Xpressive`? In this case, a `-DSKIP_PLUGIN=plugins to skip` would be a cool addition.

Then, maybe skipping submodules could even be coupled with skipping builds? I.e. using `SKIP_SUBMODULE` sets the respective `SKIP_PLUGIN`? Though I could live without that.

**Comment by tresf** [comment]
Done, `CheckSubmodules.cmake` now honors `PLUGIN_LIST`.  In order to accomplish this, I had to decouple the plugin listing code from the `plugins/CMakeLists.txt` and move it into a dedicated module (`cmake/modules/PluginList.cmake`) so that recursive inclusion doesn't happen too early in the build process.

This works by assuming `^plugin/` prefix in the submodule path (thus not impacting `src/3rdparty` submodules) by cycling through`PLUGIN_LIST` (after processing it, since it can have magic words like `MINIMAL`, which expand into `audio_file_processor;kicker;triple_oscillator`) and checking for a match on `^plugin/*<plugin_name>`.  I tested with `zynaddsubfx`, `FreeBoy`, and it seems to work rather organically.

The major downside that I see to this approach is it moves the plugin listing to a different subdirectory, which isn't intuitive, but I left a breadcrumb for programmers to find the new file.

@JohannesLorenz if you like it, feel free to merge.  If there's something that needs to be improved, please let me know. 😄
