### ISSUE TITLE
Instrument window's MIDI tab is wider than the rest

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#5129]
In master, the MIDI tab has grown in width. The remaining tabs have stayed the same, however, leading to an awkward margin on the right hand side.

![image](https://user-images.githubusercontent.com/8918426/63210962-768b4200-c0f1-11e9-9c07-0845f5f06d6c.png)

Tested on Win 10, 2560x1440 screen.

**Comment by artur-twardowski** [comment]
I have noticed the same issue on my setup on Ubuntu.

Seems that "ENABLE MIDI OUTPUT" groupbox is too wide. I had an impression that captions under LcdSpinBoxes could be shortened. The problem was even more visible when I switched to Polish language.

Maybe the captions could be shortened so that they are never wider than the spin-box? Let's say "CHAN", "VEL", "PROG", "NOTE" (the last one is actually narrow enough).
