### ISSUE TITLE
MIDI Program Change to change the patches in VeSTige

### ISSUE THREAD

**Issue by artur-twardowski** [LMMS/lmms#5138]
After loading a VST instrument into VeSTige we are able to walk through all the plugin's patches and try them out instantly. We can choose them using the mouse (clicking on [<], [>], [v] buttons) or the keyboard ([-] and [+] keys).

Many MIDI keyboards are able to send Program Change events (0xC_n_), so that we can change the patches directly from it. However, some VST instruments seem to ignore them while still working correctly with VeSTige's controls (examples are SQ8L and DVS Guitar). Additionally, changing patches from the MIDI keyboard does not update the patch name visible in VeSTige user interface.

My proposal is to embed the handling of Program Change directly into VeSTige. Additionally CCs 0 and 32 (Bank Select MSB & LSB) should be supported as well, so that we are able to access the patches beyond 128th one. To give the user a choice, a toggle button can be added to the VeSTige GUI, allowing to enable or disable the feature.

**Comment by DomClark** [comment]
Thanks for the enhancement suggestion! In order to keep our tracker clean and simple, I'm going to consolidate this issue into our MIDI placeholder issue #1472, which contains many other issues related to general MIDI improvement. If you'd like to have a go at implementing this yourself, we'd love the help.

**Comment by artur-twardowski** [comment]
Similar change to be implemented in Sf2 Player and GIG Player
