### ISSUE TITLE
Crackling

### ISSUE THREAD

**Issue by jinkinson** [LMMS/lmms#5314]
#### Steps to reproduce
Open the default interface for recording that comes up when you first download and open LMMS.
Among the several windows you can then see is the Triple Oscillator window, which you can open by clicking the button of that name in the Song Editor window. 
Then you can try to play a note on the piano by holding down the corresponding key on the computer, and then start holding down a different note.

#### Expected behavior
I expected that I would then just hear both notes playing simultaneously, with each of their sounds not being crackly or otherwise modified from what it would be by itself.

#### Actual behavior
Crackly and distorted version of sound starts once you start playing the second note, sounds kind of like the blades of a helicopter annoyingly superimposed on the sounds you actually want.
#### LMMS version used
Version 1.2.1 on MacBook Pro with Catalina (10.15.1)

**Comment by SecondFlight** [comment]
Hi! Thanks for the well-written bug report.

What you're experiencing is clipping. This happens when a sound gets too loud, and causes the waveform to be "clipped" at the 0db mark, creating the sound that you're hearing.

This problem can be fixed by simply turning down the volume of TripleOscillator. Arguably the volume should be lower by default, but that's covered in #113. There are a variety of plugins to help you control your dynamics like compressors, limiters and clippers, though I'd personally suggest looking up some tutorials before just trying to use them - they can seem cryptic at first. And remember, simpler is better! Don't use compression when you can just turn something down.

I'd also suggest turning on the oscilloscope. It will turn red if something is clipping:
![image](https://user-images.githubusercontent.com/6700184/68524035-5f429780-028f-11ea-83d5-83ebcbc428e4.png)

Best of luck with your production, and please let me know if you think this should be reopened. If you have any production questions, feel free to ask them in this thread or [on Discord](http://lmms.io/chat)!
