### ISSUE TITLE
Continued Support for Raspberry Pi.

### ISSUE THREAD

**Issue by lee-yunseok** [LMMS/lmms#5335]
### Enhancement Summary
Update LMMS for Raspberry Pi 4 Raspbian OS, and others if it possible.

#### Justification
Current LMMS version on Raspbian is 1.1.3. RPi can't run VST plugins but Soundfonts works well with Sf2 Player, and other features and plugins also works well.

I hope LMMS will keep updating on Raspberry Pi.

**Comment by he29-net** [comment]
LMMS 1.2.1 is already in Debian Bullseye (testing), so I believe it should be included in the next Raspbian release as well, as it is based on Debian. Unfortunately LMMS 1.2.0 came out just a little while after the latest Debian release (Buster) went into feature freeze, so for the lifetime of Debian Buster the version is unlikely to change. If Raspbian offers _testing_ repository, you may want to install it from there. Otherwise you'll have to wait for the next release (which usually takes around 2 years).

As for the VSTs, most of them are built for the x86 architecture, so I imagine there is almost no chance of running them on an ARM-based machine like the Raspberry Pi.

**Comment by lee-yunseok** [comment]
Thank you for answer. I will ask them to add testing repo.

However, LMMS does not provide an armhf build binary yet. I also tried build from source, there is no problem with cmake, but I failed compile with make -j4.

_And I agreed with VSTs, I don't execpt it._

**Comment by DragonEagle** [comment]
There have been some experiments with running x86 wine on the raspberry pi by channeling it through qemu-user-static, but you will have to recompile your kernel to get the right ram configuration and you will probably have to recompile qemu on buster because it's broken in the repository.  A quick google search will pop up a few video tutorials that will help.  You may not get real time processing because you're passing an emulator through an emulator, but you do have a quad core 1.5 gigahertz processor at your disposal so your mileage may verry.

**Comment by lee-yunseok** [comment]
@DragonEagle 1.13 works perfect without qemu so I think the newer version of LMMS can support RPi 4 Raspbian with armv7l(armhf flaged) AppImage.

**Comment by DragonEagle** [comment]
@lee-yunseok I was talking about vst usage

**Comment by lee-yunseok** [comment]
@DragonEagle Ah..., I understand but I think vsts is not suitable for RPi. Most high quility vsts need huge disk space. Soundfonts may be better.

**Comment by PhysSong** [comment]
@lee-yunseok What's your exact request? Is releasing AppImages for ARM sufficient?

**Comment by lee-yunseok** [comment]
@PhysSong Yes Appimage for RPi.

**Comment by zonkmachine** [comment]
@PhysSong Travis ARM builds is in alpha.
https://docs.travis-ci.com/user/multi-cpu-architectures
