### ISSUE TITLE
Decay and Gate knobs not working in effects chain for any VST

### ISSUE THREAD

**Issue by Shtarkbochur** [LMMS/lmms#5352]
When I try and edit the values for those knobs in any VST, for example TripleOscillator it won't change. The W/D knob is working but the rest aren't.

**Comment by DouglasDGI** [comment]
In Edit->Settings there's an option labeled "Keep effects running even without input".  Turn that off and those knobs will function.
That option being enabled is now default (not sure why, it seems like a waste of CPU).  Turning it off will make it so the effects don't do anything while silence is being sent through them.  The Decay and Gate knobs give you more control over that.  I think in the future, it'll be made more obvious when those knobs don't actually do anything.

**Comment by zonkmachine** [comment]
@Shtarkbochur The instructions above are correct. This has been reported before. I close this one as a duplicate and bump https://github.com/LMMS/lmms/issues/4749 to the next release and hopefully someone will fix it by then.

**Comment by DomClark** [comment]
> That option being enabled is now default (not sure why, it seems like a waste of CPU).

It's enabled by default because when it was off, effects such as delay were behaving incorrectly, shutting off before the signal came through. See #4378. It only uses a lot of CPU if there are enough (or intensive enough) effects in the first place, and even then only saves CPU if those effects are unused most of the time. The feature certainly isn't without merit (hence the option exists at all), but the consensus appeared to be that above all the software should appear to function correctly out of the box, and users can change the configuration as and when necessary if a particular situation becomes too demanding.
