### ISSUE TITLE
Buzzing between tracks in song-editor in lmms

### ISSUE THREAD

**Issue by DivyanshuMJ** [LMMS/lmms#5443]
There is an glitch in lmms, when i am listening the song by running the song-editor of saved project file, then in between of the song some type of buzzing sound is coming, I don't know why is this happing but that makes me not to use lmms for making songs.I also have a video of that bug, please help or i will see any other software for making tracks and also i will not recommend lmms to any one.

**Comment by Spekular** [comment]
This looks like a support request to me, and we prefer to answer those elsewhere (for example, Discord). Since you did decide to post here, it would have been nice if you had followed the template for bug reports. I'm closing this until we can confirm that it's a bug, but will gladly try to help you out.

For starters, please post the video you mention so we can tell what kind of issue you're running into.

In addition, it may help to know:
- What version of LMMS are you using, and how did you install it?
- What operating system are you running?
- Which audio backend are you using?

**Comment by DivyanshuMJ** [comment]
1. Lmms 1.2.1
2.Operating system is Window 10 
3.I didn't understand, what is audio backend please tell me
 
Sir, I also have a video clip of that bug, I have sended in the mail

**Comment by Spekular** [comment]
Thank you for the additional information.

>    3.I didn't understand, what is audio backend please tell me

Go to Edit > Settings, then press the speaker icon, fourth from the top on the left hand side. I'd like to know what is selected under "Audio Interface", and what is under "Settings for ___".

> Sir, I also have a video clip of that bug, I have sended in the mail

I'm not sure where you emailed it but it isn't visible here on github. If you could upload the video to Youtube and paste a link, I think that would be the most convenient option.
