### ISSUE TITLE
Muted states not saved when soloed

### ISSUE THREAD

**Issue by gatodev** [LMMS/lmms#5562]
#### Steps to reproduce

Mute some tracks
Solo a track
Save the project
Restart LMMS
Reopen the project
Unsolo the track

#### Expected behavior

All tracks remember their states, or unsoloed before saving.

#### Actual behavior

Some tracks don't remember if they were muted.

#### Affected LMMS versions

1.2.2 (Linux/x86_64, Qt 5.9.7, GCC 5.4.0 20160609)

**Comment by IanCaio** [comment]
The mute state before the solo is stored during runtime in a variable called `Track::m_mutedBeforeSolo`. It's probably not saved on the project file so LMMS doesn't know what the mute state should be after unsoloing. What has to be decided is if we should store this variable on the project file to remember the previous mute state during a solo or make solo a runtime thing and all tracks be loaded with solo off (in this case if solo is toggled it would be turned off before saving).

Personally I tend towards the latter. Mute states are interesting in a project file, but solo states not that much. It's usually used to test things during the production process and rarely something you want to save in the project. But I'm open ears to other opinions.

**Comment by IanCaio** [comment]
I just submitted a PR with a fix for this bug. It's linked above and soon there should be builds available to download. Older project files can't be fixed though, because they didn't store the muted states before the solo, so those files will just set every track to unmuted when you disable the solo. But new project files should now store this information and you'll be able to recover the state after disabling the solo.
