### ISSUE TITLE
Xpressive help dialog maximize behavior

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#5570]
Xpressive's help dialogue does not fill the screen when maximized, which looks awkward and also allows un-maximized window to be placed on top of it.

#### Steps to reproduce

Add an Xpressive instance to the song editor, open it's instrument window, and press the button  labeled "HELP?". Next, press the maximize button belonging to the new window that appears.

#### Expected behavior

(1) Text area makes use of full screen real estate, or (2) the maximize button is not available in the first place.

#### Screenshot

![image](https://user-images.githubusercontent.com/8918426/87050332-6810b200-c1fe-11ea-95cc-a87c2cea4da4.png)

#### Affected LMMS versions

Build of PR PR 5117 via LMMSBot, from 2020-07-09. Since that PR was updated today, build should include everything up to and including commit 5aba3d2a73f91d5c6268b258f2c6f167df1a8e62.

#### Side note

In addition, I find that the writing in the documentation isn't great, but since this isn't the point of the issue I'll just point out some objectively incorrect aspects:
- "Panning is controled by PN1 and PN2." -> Panning is controlled by PN1 and PN2.
- "Gives 0.0 while the key is holded" -> "Gives 0.0 while the key is held"
- "Time after release. While the note is holded, it gives 0.0. Afterwards, it start counting seconds."
  - Once again "holded -> held"
  - "Afterward, it start counting seconds" -> "Afterward, it starts counting seconds"

I'll also note one especially confusing part: "Afterward, it start counting seconds" + "The time it takes to shift from 0.0 to 1.0 after key release is determined by the REL knob". Does `trel` return seconds since key release, or `time since release/release length`? Also "it start counting" -> "it starts counting"

**Comment by Spekular** [comment]
I would prefer if the window didn't have a maximize button which should be a fairly simple fix. There are several windows without maximize buttons already:
- Controller rack
- Mixer
- Instrument windows

**Comment by DomClark** [comment]
In my opinion, this sort of documentation belongs on https://docs.lmms.io/, not in the software itself. Can we just remove the window altogether?

**Comment by Spekular** [comment]
That's a fair point. On the other hand, this dialogue ensures that you have access to the info even if you don't have internet access, and the info within might be something you need to reference more frequently than the instructions for our other synths.

**Comment by russiankumar** [comment]
Working on this.

**Comment by russiankumar** [comment]
Have working versions of both proposals. Your call on which one to be merged.

**Comment by tresf** [comment]
> In my opinion, this sort of documentation belongs on https://docs.lmms.io/, not in the software itself. Can we just remove the window altogether?

To @Spekular's point, offline documentation is valuable.  Whether or not it belongs here is a tricky one.  First, this plugin isn't just buttons and knobs, it's an interpreted language.

... but to @DomClark's point, if we're to have long-winded documentation, it should be stashed somewhere more digestible (such as online and/or a built-in help function).  I vote that we merge #5586 to close the bug and discuss where help belongs as a more holistic change.

**Comment by DomClark** [comment]
> I vote that we [...] discuss where help belongs as a more holistic change.

Issue opened: #5596.

**Comment by gnudles** [comment]
Hello, I am the author of x-pressive plugin. I am glad that finally my plugin got into public release. I am sorry for my not-the-best documentation. It was my first plugin that I wrote, so take it into consideration. May I give a little bit of introduction because I suspect it is not so intuitive. My plugin lets you manage 3 waveforms (W1 W2 W3) that can be used as functions in the output formulas. those waveforms are useless if you do not use the in the output channels O1 and O2. a waveform can be either generated by formula or it can be loaded from file or it can be drawn by hand. it can be smoothen by the knob below. the T axis in the waveforms ranges from 0 to 1 ans it is unitless. then you have two undepended output formula channels. those channels are mixed together according to the PN1 and PN2... means that PN1 is the panning of O1 and PN2 is the panning of O2. you do not have to use both O1 and O2, but you must use one of them to produce sound. the units of the T axis of the output formula is seconds. the value of "f" variable is the frequency of the played note in hz(oscillation per second). all the builtin wave functions like sinew have cycle period of 1, unlike natural sinus that have 2*pi.
so the simple formula sinew(f*t) would produce a pure sine of the played note. but because lmms provides the option to alter the frequency of the played note during the stroke, I added a new function called integrate. each instance of the integrate function has internal counter that multiply the friction of time passed with the given value. so sinew(integrate(f)) will take each frame the current value of f, multiply it by the friction of time that passed in the frame, and add it to the internal sum, and will return the new calculated sum. that's it for now
