### ISSUE TITLE
Outer border for melody clips is drawn one pixel too much to the right and bottom

### ISSUE THREAD

**Issue by claell** [LMMS/lmms#5593]
The melody pattern appears a little bit off (on the right side) compared to the rest.

![image](https://user-images.githubusercontent.com/26451259/87219529-9f579e00-c379-11ea-8a78-c770be37397c.png)

_Originally posted by @russiankumar in https://github.com/LMMS/lmms/pull/5573#issuecomment-657010886_

Creating this issue to keep track of this bug.

**Comment by claell** [comment]
I finally tracked this down now: https://github.com/LMMS/lmms/blob/master/src/tracks/Pattern.cpp#L1126

Apparently each TCO class (instrument, sample track, beat and bassline and automation track) implement their own function for this. There is alot of overlapping functionality, so that should probably be improved in the future.

The current problem could be simply be solved by adjusting the relevant part of the paint function to behave like the one for the rest of the TCOs.

**Comment by Spekular** [comment]
Looks like the original title was correct though, the outer border is drawn too far right rather than the inner border being drawn too far left. Not only that, but it also appears to be drawn to far down on the bottom. Here's the screenshot from the OP cropped further and scaled up without interpolation, for easier viewing.
![image](https://user-images.githubusercontent.com/8918426/88066745-6932cf00-cb6e-11ea-9707-925b352df18f.png)

**Comment by claell** [comment]
Jup, I changed the title based on your comment in the other issue. Now I adjusted it again based on your observations. The scaled screenshot you attached shows that pretty nicely.

See the linked PR I just created. It should fix the problem.

**Comment by russiankumar** [comment]
> There is alot of overlapping functionality, so that should probably be improved in the future.

Again, a suggestion for #5592.

**Comment by russiankumar** [comment]
PR fixing this has been merged, can you close this?
