### ISSUE TITLE
Abbreviate effect module decay knob label

### ISSUE THREAD

**Issue by sound8** [LMMS/lmms#5750]
Effect modules have three knobs
W/D, DECAY, GATE

The "DECAY" label kind of runs into the GATE label, to me it just doesn't look right.
Maybe consider abbreviating the "DECAY" label to "DEC" so the labels are not so close together.

Obviously not a big deal but would clean up the look of things.

**Comment by Spekular** [comment]
The real issue is that the space between decay and gate is shorter than the space between W/D and decay. If this were fixed the labels would be fine as is.
![image](https://user-images.githubusercontent.com/8918426/97625551-f36db780-1a28-11eb-929b-32c71148b149.png)

Measuring pixels in that screenshot, the first margin is 9 pixels and the second is 3.

**Comment by sound8** [comment]
If you are referring to the spacing between the knobs then I would agree.
The only reason I didn't mention this is because I figured I would have a better chance of someone abbreviating a text label, over moving a knob and label a little to the right.
So yeah, two ways to fix this.
1.) Abbreviate "DECAY" label
2.) Move Gate knobw and "GATE" label over to the right.
