### ISSUE TITLE
Effect module names get cut off abrubtly if too long by modules edge

### ISSUE THREAD

**Issue by sound8** [LMMS/lmms#5752]
Effect module names get cut off abrubtly if names are too long.
The names go literally right to the effect modules rectangle vertical edge and stop, does not look good graphically.

When this happens with other labels/names that are too long the suffix "..." is usually added to the end and a little space after so names don't get chopped off by vertical graphical edges.  Effect module names should get this to keep things consistant.

For example type a really long label name in Song Editor track and watch how it adds the "..." and space after.

**Comment by Spekular** [comment]
For demonstrations sake I loaded a VSTi into an effects rack:
![image](https://user-images.githubusercontent.com/8918426/97627220-56f8e480-1a2b-11eb-821e-f0c85cf43666.png)

Sidenote, since effects in the rack can't make use of the additional space (at least not now), we may as well show the scrollbar area all the time, right? Otherwise it looks a bit odd when the space is unused.
