### ISSUE TITLE
Rework waveform plotting

### ISSUE THREAD

**Issue by thmueller64** [LMMS/lmms#5908]
### Enhancement Summary
Plotting the audio waveform is currently done in `SampleBuffer::visualize`. Creating and updating the waveform plot is very unresponsive. You can observe this for example when you load a whole track in the AudioFileProcessor and turn the amplification knob. 
Furthermore, every `n`th sample is currently plotted. In my opinion, this method of "compressing" the information in the actual waveform makes limited sense only. The maximum or RMS of the samples per pixel should be used instead, like in audacity.
#### Justification
This performance issue can be observed especially for longer samples (>2min) in the following situations:
1. Loading a sample: You have to keep the mouse pressed for 15s+ until you can place the sample in the timeline
2. Moving the amplification knob in the AudioFileProcessor

If this feature is wanted I can try to put something together after the refactor.

**Comment by IanCaio** [comment]
That's definitely something worth working in. I'd add that we need to decouple `visualize` from the `SampleBuffer` class (GUI vs Core). I'm not sure which class should it be in though, since it's used on both the AFP and the SampleTCOs. Feels like an overkill to create a `SampleBufferView` class just for that, but because of it being reused it might be the way now.

**Comment by DouglasDGI** [comment]
Issue resolved via #5927.
