### ISSUE TITLE
Fl Studio plugin in Lmms

### ISSUE THREAD

**Issue by techindiesoftgaming** [LMMS/lmms#5917]
**VST PLUGIN**

### Enhancement Summary
        i am not able to use fl studio plugins in lmms though,the plugins have .dll files which is needed to open any vst
        plugin. i would be happy if lmms would support all fl studio plugins. Please a requested feature. Please see to it.                              

#### Justification
         if this feature is added then we can make better music,since fl studio plugins have nice sound quality.

**Comment by RoxasKH** [comment]
This is not an issue caused by LMMS vst host VeSTige. 
As the issue is linked to external plugins, you should have first checked if it was the plugins fault before pointing LMMS.

If you, as i probably suspect, are talking about the dll files that are bundled with FL Studio itself, this is just how it should be, they're not supposed to load up in other DAWS. Image-Line, tho, provide VST version of most of their plugins, you have to buy that if you want it to load in any other DAW which is not FL.

For a clearer explanations, here's what it's said in a KVR post.
![immagine](https://user-images.githubusercontent.com/40141826/108866518-9065e900-75f4-11eb-8760-15f524ca53be.png)

And here's the post
https://www.kvraudio.com/forum/viewtopic.php?t=245274

I'm pretty sure that the vst versions load up in LMMS, as i've seen people doing that.
For example here's a person was able to load Sytrus in LMMS. And we're talking about LMMS 1.0.0 which had a way more terrible vst support than now, ans also on linux through wine which means no support ensured.

https://youtu.be/7BhoLFf7jP0

If i'm wrong and you're talking about an Image-Line plugin in vst version, and not a dll bundled with FL (which i doubt, tho), then there's probably something wrong with your installation i guess.

You can use rewire as suggested in the KVR topic, tho.
