### ISSUE TITLE
Hover Cursor user feedback

### ISSUE THREAD

**Issue by Macawena73** [LMMS/lmms#5993]
Hello,

Every clickable button should change the cursor state to a pointer if it's clickable at that moment.

**Comment by DomClark** [comment]
Is there a particular reason you want this behaviour (e.g., accessibility)? This isn't common in desktop software as far as I'm aware - usually the button itself changes appearance slightly instead.

**Comment by Macawena73** [comment]
It's a rule in design of web applications and games to give feedback of
what is happening to the user. If something is clickable, the cursor should
display what is the interaction type as well as the element should display
a similar behavior. The exemple of buttons ( hover / pressed effects as
well as a pointer cursor or hand, a editable text show a text cursor, a
link show an underlined text as well as a pointer etc. The same for video
games)
The software has some buttons implementing the pointer cursor as well as
hover effect. I simply thing that it should be the design for every
buttons. Think of it as a part of design and comprehension of the
applications.
🙂
I would love to participate to the Dev but I'm a webdevelopper into angular
/ typescript and also an Unreal game dev (For VR apps) and C++ is not
really my thing ...

Le dim. 18 avr. 2021 à 20:58, Dominic Clark ***@***.***> a
écrit :

**Comment by davthedev** [comment]
Hi,

Having the hand finger pointing to the button when hovered is really a web browser thing. Because it originated in times where web pages were mostly showing links that only consisted as underlined words in textual content. It helped disambiguating clickable text from non-interactive underlined words. Nowadays, web apps are full-fledged tools and kept those UX codes because most buttons were implemented as CSS-enhanced links at some moment.

In comparison, desktop software UX codes are different. The pointing hand cursor is less used. Buttons are self-explanatory, aligned in toolbars & tool panels for instance. Hover effects & tooltips help confirming the button trait.
The clickable links, places were the pointing hand cursor is used in desktop apps too, were first seen on my side in the integrated help browsers as far as in the early versions of Windows of 30 years ago. Those help browsers could be seen as grandfathers as today's web browsers.

The line may blur even more as some desktop software releases of those days can be disguised web browsers, using technologies such as Electron.

Your background in web development surely gives you a bias on your perception on how things should work. I can understand that as many people began their development journey using a web browser to render content in the recent years.

**Comment by PhysSong** [comment]
As mentioned above, the UX is common for web-based UIs(ex. Slack, Discord). However, it sounds like very unusual for the desktop world.
I couldn't find any good reason for providing a cursor feedback for every button. As @davthedev pointed out, this is more of the difference in the way giving users some feedback.
> give feedback of what is happening to the user

That's still a good point. If you find some components are not giving proper visual feedback, please let us know by opening a new issue.
