### ISSUE TITLE
wet/dry label is reversed

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6029]
### Bug Summary
wet/dry label is reversed. if you set the value to -1 it is completely dry, as it should be, but the label shows that it now is completely in **wet** position.

#### Steps to reproduce
Look at it..

#### Expected behavior
We simply need to change label D/W

#### Actual behavior
..
#### Screenshot
![image](https://user-images.githubusercontent.com/6662066/119376226-004f4280-bcbc-11eb-89ad-d7535c716f91.png)

#### Affected LMMS versions
All

Easy fix for a good first issue

**Comment by DouglasDGI** [comment]
-1 is not dry, 0 is dry.  -1 mixes both wet and dry.  This is just the Wet/Dry knob, the positions of the labels aren't meant to show the positions of various levels of wetness.  I'll go ahead and close this unless somebody still has concerns.

**Comment by Spekular** [comment]
I'm not opposed, but I don't think this can be called a bug (equalizer bands don't go from "freq" to "ency" either).

Also worth noting that at present, -1 is wet with an inverted signal rather than dry. If we're renaming the knob anyway, we may want to consider "mix" as well.

**Comment by musikBear** [comment]
> -1 is wet with an inverted signal rather than dry.

In that case i think -1 should be called OffWet or negWet because the dial from dry->wet is not correct
Maybe some colour 'stuff' -Like 3 dots a red green blue dot, so user can see that there actually is 3 options in this setting, but Wet should be to the right, and not as it is now to the left -eg D/W
@DouglasDGI since 100% Wet is at pos 1

**Comment by DouglasDGI** [comment]
The label isn't saying the knob goes from wet to dry.  It's just the Wet/Dry knob.  That's its name.  The knob next to it is the "Decay" knob, not the "Minimum Decay/Maximum Decay" knob.  And so on.  It's just the name of the parameter, it is in no way a display of which values go where on the knob.

**Comment by RoxasKH** [comment]
Actually i never saw the label as a possible problems.

Cheking examples, tho, in Ableton the knob is called Dry/Wet, so it could make sense inverting those letters, even if i don't think that one has negative values
![immagine](https://user-images.githubusercontent.com/40141826/119543727-46c2a100-bd91-11eb-8e48-c33dfe8eb5c7.png)

Also in Massive so
![immagine](https://user-images.githubusercontent.com/40141826/119544199-c486ac80-bd91-11eb-88c7-b566588970ee.png)

We can't rename it mix, tho, because that's even less likely to have negative values.

![immagine](https://user-images.githubusercontent.com/40141826/119544030-9f923980-bd91-11eb-9424-dbb46324faa8.png)

It's still called dry/wet also in a lot of other things, so it may have sense at least inverting those. Having it as Wet/Dry, doesn't indicate that there are negative values anyway, so i can't get why it was called wet/dry in first place.

**Comment by Spekular** [comment]
> We can't rename it mix, tho, because that's even less likely to have negative values.

I don't agree. The screenshot you give for mix is only inappropriate for our case because of the DRY and WET labels, and as already established we don't have those in LMMS. A knob that simply says MIX doesn't conflict with negative values any more than one that says DRY/WET, and by musikBears logic the DRY/WET one would actually be more misleading.

**Comment by RoxasKH** [comment]
> 
> 
> > We can't rename it mix, tho, because that's even less likely to have negative values.
> 
> I don't agree. The screenshot you give for mix is only inappropriate for our case because of the DRY and WET labels, and as already established we don't have those in LMMS. A knob that simply says MIX doesn't conflict with negative values any more than one that says DRY/WET, and by musikBears logic the DRY/WET one would actually be more misleading.

The fact is that the mix knob, for definition, state a percentage of mix, usually from 0 to 100%. Although it could actually work if it's a centered knob a guess. Maybe renaming it Mix could be the way at this point.

**Comment by musikBear** [comment]
Someone suggested to just change the label to **Wet**
That works for all situations :)

**Comment by RoxasKH** [comment]
> 
> 
> Someone suggested to just change the label to **Wet**
> That works for all situations :)

Not at all. Wet knobs and sliders are used to indicate the volume of the wet signal, so the affected from the effect one. In a Wet knob, having it set to 0 would result in no volume. Wet sliders are usually used paired with a Dry sliders, so that you can manually choose the amount of the dry and wet sound.

The LMMS knob automatically balance it i think, so when the wet/dry knob is at 0.50, we have 50% dry signal and 50% wet signal.

You usually find those on reverb plugins like Fruity Reeverb 2 or OrilRiver

![immagine](https://user-images.githubusercontent.com/40141826/119790601-5bf41880-bed4-11eb-88f0-e37adb003e67.png)

So no, only Wet can't work at all.
