### ISSUE TITLE
.flac output file is too large.

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#6049]
Is the .flac output file compressed sufficiently?
Here is a view after rendering 8kb .mmpz file into different formats.

![image](https://user-images.githubusercontent.com/5563341/121581056-ac966600-c9ea-11eb-8012-08c437ca1d4d.png)

I apologize for working with the default options.

**Comment by zonkmachine** [comment]
Sounds reasonable. Try different settings and samples. You should be able to get more out of it but that's the price of lossless compression.

**Comment by Sawuare** [comment]
> Sounds reasonable.

Yeah. The screenshot shows a ratio of 67%. Not bad for the default compression, I think.

FLAC usually has 9 compression levels: 0 to 8. The LMMS default is 4, while the default for Audacity and the official utility `flac` is 5. In my experience, higher levels take a bit more time to compress a bit more. The export dialog actually has a combo box for choosing a level, but it *should* be hidden if the `libsndfile` version is less than 1.0.26. I said "should" because it is hidden for me although I have version 1.0.28. Until LMMS lets you choose a level, you could use Audacity, `flac`, or others to do that.

https://www.audacityteam.org/download/
https://xiph.org/flac/download.html
