### ISSUE TITLE
feature request: OPL2 sound emulator

### ISSUE THREAD

**Issue by arcade-legend** [LMMS/lmms#6109]
Hi

I would like to request a new instrument: OPL2/3 sound emulator.
This is used in the Creative Sound Blaster cards and used in many MS-DOS games.

Here is an example music: https://www.youtube.com/watch?v=g8o1NObgsCQ&list=PL2F14F32D6585B064&index=1

**Comment by arcade-legend** [comment]
Here is an example of a library I mean: https://github.com/adplug/adplug

We could use the file types supported by Adplug in LMMS as sort of "samples" for this instrument

**Comment by zonkmachine** [comment]
Havet you tried the plugin OpulenZ?

**Comment by arcade-legend** [comment]
I"m a LMMS beginner and use it on windows.

Where do I find plugins and how to install them?

**Comment by arcade-legend** [comment]
I found it!
It's already in LMMS.
Exactly what I needed!

**Comment by irrenhaus3** [comment]
In future, you might want to consult the user manual at https://docs.lmms.io/user-manual/ before opening github issues. many questions can be answered there without requiring team responses.

**Comment by zonkmachine** [comment]
It is a built in plugin emulating opl2

https://docs.lmms.io/user-manual/3-navigating-lmms/3.5#3-5-2-instrument-plugins

https://docs.lmms.io/user-manual/5-built-in-instruments/5.10-opulenz

I believe this satisfies your need. Closing.

PS. You should really use our discord chat instead of the issue tracker. https://discord.gg/3sc5su7
