### ISSUE TITLE
bug: vestige won't load several VST

### ISSUE THREAD

**Issue by arcade-legend** [LMMS/lmms#6112]
Trying to load these VST here https://transverseaudio.com/posts/best-free-chiptune-vst-synths

I get error message like this but then the VST plugin appears in lmms.

![afbeelding](https://user-images.githubusercontent.com/85412588/126912390-4ccb1446-fe74-4922-bef3-552cf1bd8be1.png)

 Can I ignore these messages or do they mean the VST plugin does NOT work with lmms (or is this a bug)?

![afbeelding](https://user-images.githubusercontent.com/85412588/126912330-c2347990-b5e5-4ace-a626-ff7645a770ae.png)

**Comment by arcade-legend** [comment]
In addition, VST plugins that load correctly and don't give any error message, give very low sound volume compared to the LMMS native plugins.
Is this normal?

**Comment by zonkmachine** [comment]
You need to listen to the advice you have been given before. Our main support site is on Discord. Link has been given. Especially the channel marked `#support` . Please use that site and not the issue tracker which is mainly for development. You will also get much faster response there. I'm closing this to keep the noise down in the issue tracker.

**Comment by arcade-legend** [comment]
If you close REAL bugs here then I'm afraid you are wrong.
This is a real bug I found!

**Comment by qnebra** [comment]
This is not lmms bug. You copy entire unpacked folder to your user VST plugins location, or only dll files?

**Comment by arcade-legend** [comment]
Some archives only contain dll files, some contain other files.
Because i don't find docs on how to do it, I extracted the whold folder to the VST folder I have chosen in lmms settings.
All plugins work, except the one in the screenshot i provided.
it gives several error messages but after those, the plugin is displayed

Thx

**Comment by Iron-Squid** [comment]
> If you close REAL bugs here then I'm afraid you are wrong.
> This is a real bug I found!

Please refrain from posting these sorts of responses on a GitHub development site, of all places.

About your question pertaining to VST installation, every VST is packaged differently and will be installed differently. VeSTige will only open VST2 and VST `.dll`s, it cannot open `vst3` yet as there is not yet any support for it. Use the file browser in VeSTige to search for these `.dll`s, you only need to put the `.dll` for Effects VSTs into the VST directory, so that they show up in the effects search.

In the future, PLEASE use the #support channel on discord for much faster and streamlined assistance. The GitHub page is for development and *true* bugs only. If you find a bug please search for it first so that you don't accidentally create a duplicate issue. The LMMS devs are all volunteers and have a limited amount of time they can donate to LMMS as a project, it would be much appreciated if they could spend less of that time moderating the GitHub and more on actually programming LMMS features and squashing bugs.

For the record, I am not a developer. I just follow LMMS development very closely.

**Comment by arcade-legend** [comment]
to qnebra: if it's not a bug, why do I get the error message?

**Comment by arcade-legend** [comment]
to iron-squid: how can I see which version a VST file is?

**Comment by Iron-Squid** [comment]
Iirc, VST and VST2 will usually install or come with a `.dll`, VST3 uses its own file extension, `.VST3`.

Again, it'd be much appreciated if you could use the support channel on the Discord (it's on https://lmms.io) rather than the GitHub. 😅

**Comment by arcade-legend** [comment]
FUCK OFF MOTHERFUCKERS

I DONT USE THIS SHIT ANYMLRE

NOTHING WORKS

**Comment by Iron-Squid** [comment]
I'm sorry for your loss.

**Comment by JGHFunRun** [comment]
@arcade-legend 
![stop don't come back](https://user-images.githubusercontent.com/52897905/126928977-be20f5c6-e5d1-49bd-8b84-7f46bccc013a.gif)

**Comment by qnebra** [comment]
> to qnebra: if it's not a bug, why do I get the error message?

Because you didn't copy presets folder for plugin I guess. I got no errors using this plugin. 

Download plugin, unpack and copy entire unpacked folder from Downloads to your VST location.
