### ISSUE TITLE
Dragging of tracks up and down by holding track

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6134]
Request for reversion to previous behaviour:
In 1.2.0, one could reorder instrument tracks by dragging them up and down. In 1.3 alpha, this only works by holding the specific area meant for reordering on the left, here:

![image](https://user-images.githubusercontent.com/76674645/129673639-e513108c-ec73-4eb3-9c29-f35b379ea8cf.png)

Holding a track anywhere on a not-knob and dragging doesn't reorder anymore.
This isn't an enhancement as it takes about a second more to carefully ensure the mouse is over the reordering drag area, and then click. It's much faster directly holding on to any part of a track to reorder. I would like to request this feature be brought back.

Video demonstrating expected behaviour in 1.2.0:

https://user-images.githubusercontent.com/76674645/129673831-9a0fbb0b-b44b-444f-9a83-ed3f17b5cdb2.mp4

**Comment by Sawuare** [comment]
I changed the behavior in #3878. Because drag-and-drop of a track has been limited to the handle on the left, and because dragging is also a track movement, I limited dragging to the handle. It seemed more well-defined than being able to drag anywhere even between the little gaps.

> Holding a track anywhere on a not-knob and dragging doesn't reorder anymore.
This isn't an enhancement as it takes about a second more to carefully ensure the mouse is over the reordering drag area, and then click.

I see 2 solutions to this.

1. Add some extra pixels to the width of the drag area to make dragging easier.
2. Do not limit dragging to the handle at all, and leave it (or not) only to indicate track movement.

**Comment by Spekular** [comment]
Dragging must be limited to the handle unless we want to remove or obscure functionality elsewhere in the track label, because clicking is reserved for other actions in other areas.
- Clicking the gear opens a menu
- Clicking mute/solo toggles mute/solo
- Clicking the label opens the instrument
- Clicking the indicator plays the base note
- Dragging pan/volume adjusts pan/volume

There seems to be enough accumulated padding between the handle/gear, gear/led, and led/label that an additional row of dots could be added to the track handle, widening it to 1.5X it's current size.

**Comment by Spekular** [comment]
Addendum: all except the gear and indicator also respond to right click, so moving actions to RMB isn't an option. Double click should be avoided as the sole option to trigger an action, for accessibility purposes.

**Comment by Monospace-V** [comment]
I was wondering if it could be done by clicking and holding the real estate in the instrument name, ie, where I clicked in the demonstrating video.

**Comment by Spekular** [comment]
As mentioned, clicking there opens the instrument. Right clicking there triggers a rename. Click and drag can't be distinguished from a regular click unless you delay the click action, which would slow down the process of opening an instrument.

How long have you been using 1.3? I imagine you would get used to the new behavior after a while as I can't say it's a pain point for me.

**Comment by Monospace-V** [comment]
Primarily use 1.2.0. Makes sense. Thanks!

**Comment by Monospace-V** [comment]
Incidentally, I was watching an introduction to the DAW, and found that this feature of being able to drag by clicking anywhere is used somewhat often in LMMS (at least by the person making the tute). It's worth mentioning that a lot of users will find this new behaviour on LMMS' part.
https://youtu.be/3qfa9hGJzoY?t=277
