### ISSUE TITLE
I can't get SF2 Player or VesTige to work on LMMS

### ISSUE THREAD

**Issue by 2-bithacker** [LMMS/lmms#6168]
I have downloaded stuff from the LMMS sharing platform and the songs requiering SF2 Player or VesTige do not work. I also cannot get them to work otherwise as in I cannot use them in any of my LMMS songs.

**Comment by Monospace-V** [comment]
Yes, the tracks requiring SF2 player and VeSTige does not work due to the nature of how these are based on files from the user's computer rather than in-LMMS presets. As it stands, until an "Export all media" button is implemented that works well with even SF2s and VSTs, SF2s and VSTs will keep breaking.
Unless, of course, your entire song isn't working, not just the SF2 and VST bits. In which case... I believe you're using 1.1.3, and I don't know how to help with that?

**Comment by 2-bithacker** [comment]
Well, I can't get anything newer. Trust me. I've tried everything. But this is raspberry pi os, and I can't install the newest LMMS on this operating system. I don't know why, and if you know, I would love it.

**Comment by Monospace-V** [comment]
Is your entire song not working, or is it just the VST and SF2 tracks?
If it's the latter, then it may be possible to get it to run, albeit with slightly different settings.

**Comment by 2-bithacker** [comment]
Just the VST and SF2 tracks.
     This is kinda off the subject, but I have made some very good covers on LMMS that I would like to post on the LMMS sharing platform, but when I try to create an account, it does not work even when I enter all the information required. Like this:
![2021-09-24-223238_1920x1080_scrot](https://user-images.githubusercontent.com/90713990/134758097-467468f9-dfca-439c-b3c9-cbd8293fe4c6.png)
When I push register like this, It does not work. Like this:
![2021-09-24-223257_1920x1080_scrot](https://user-images.githubusercontent.com/90713990/134758181-171d6f3e-66aa-4a5e-8fa4-9e246c87fca5.png)
I try to sign in, and it says there is a registration failure.

**Comment by Monospace-V** [comment]
#### Regarding the LSP problem:
Yes. I recall getting that on my first time, too. Multiple times. I never understood what finally made it click, but it did end up working eventually. I can only wish you all the best. I do not know where to submit enhancement requests/bug reports for the lmms.io sharing platform, and do not believe there is much maintenance activity going on.


#### Regarding the soundfont/VST usage:

##### VSTs:
Unfortunately, I use a Windows, so I do not know the process of running VSTs on a RasPi (but I believe the Linux process, at least, involves Wine to run VSTs right).

##### SF2s:
First you have to download the required soundfonts to play the track. ie, download the same soundfonts used in the track. If it's a general MIDI soundfont, you should be fine with any GM-compliant soundfont. However, ideally, if a specific soundfont pack has been used: you want to download that from the source. (There is no workaround to this. Only the hard way of locating the source if you even can.)

1. SF2s can be then used by opening the SF2 player instrument controls:
![image](https://user-images.githubusercontent.com/76674645/134765196-8dccede8-c19c-42e3-add7-3b2251e87f47.png)

2. Clicking the folder icon:
![image](https://user-images.githubusercontent.com/76674645/134765208-51b6725a-a147-49e6-8c04-ba93ab9e8371.png)

3. Navigate to the soundfont you want to use

4. Then click the wrench icon:
![image](https://user-images.githubusercontent.com/76674645/134765226-f01c55a2-c901-4ffc-b29d-726ff0098af7.png)

5. Navigate to the bank and patch in use:
![image](https://user-images.githubusercontent.com/76674645/134765242-f8fa2dee-4722-466c-a163-04f51c0e3afc.png)

6. And make sure the settings are the same.

Alternatively, if you're using a .mmp project rather than a .mmpz, then you can save yourself the trouble of navigating to the correct folder and checking the settings and bank and patch, and instead:
1. Open the mmp file in a text / xml editor
2. Find the place in the XML document where the filename points to the file directory the soundfont is placed in
3. Change that directory to the directory YOUR soundfont is placed in.

However, both these methods involve downloading the soundfont from the original source.


#### Regarding the entirety of the thread:
The LMMS github is mainly meant for bug reports (and enhancements). The best place to ask for _help_ would be the [LMMS forums](https://lmms.io/forum/), where you can ask for more details on each instruction, ask the community for how to run VSTs on a RasPi (I'm sure some users might be able to help you, we have a diverse community), and otherwise share any other problems you are facing. We love assisting users; we will be more comprehensive on the forums.

That being said: I believe this issue can be closed.
If you still need help, further explanations, or elaborations, you can visit the forums and ask for help. It may take more time, but it is the best way.

**Comment by 2-bithacker** [comment]
That is just what I needed; Thanks.
