### ISSUE TITLE
Updating themes' styles.css makes the whole css layout crash?

### ISSUE THREAD

**Issue by qantuum** [LMMS/lmms#6329]
found this tutorial about changing the color of the grid lines in piano roll;
found it back in styles.css as indicated,
and now the setup is crashed on LMMS, a lot of items become black, etc.
Even when I undo my changes to the css and save, it stays like that.
What happens? Can't I update the css files? Does the app need to be built again after changing?
How can I turn it back to normal? (edit: OK I just re-installed it)

the tuto I've used: https://infonosity.net/infonosity-english/electronics/lmms-change-theme/

**Comment by Veratil** [comment]
Which version of LMMS are you using?

**Comment by musikBear** [comment]
> Can't I update the css files? Does the app need to be built again after changing?

Yes you can edit CSS-file without any problem at all, but you must use a non-formatting editor! Notepad works fine. Any and all word-processor, like MS-word -Does NOT work.
There is also no reason to re-install, just because you have an issue with a CSS-file. Just get it from us and replace the flawed one.
I also advise you to _always_ make a _backup-file_ for any textfile you try to edit, in _any_ program (modding) then you can roll-back to working condition, with no hazzle

**Comment by zonkmachine** [comment]
Looks like OP fixed it as such:

>  (edit: OK I just re-installed it)
> 

@qantuum Please check out our Discord site where developers and themers hang out if you need help with modding lmms: https://discord.com/invite/3sc5su7
