### ISSUE TITLE
ideas for lmms 1.3 release.

### ISSUE THREAD

**Issue by roshanrules1** [LMMS/lmms#6376]
I am writing this issue to help the devs organise their work and for us users to get lmms 1.3 faster.
i am adding in points i feel we should be getting in 1.3. if i missed out anything, just put a comment and i shall be adding in that. also, if i included something which shouldn't have been included, feel free to point it out too.
tasks

- [ ] add folders to project organisation 
![Capture](https://user-images.githubusercontent.com/74815851/163661555-afc34836-9be8-41a4-a397-f1d335ed6bdc.JPG)     
i hope you guys will get the idea. this is a good idea to clean up the my projects folder. the individual project folders contain the mmpz files, the mmpz.bak backups, exports and also the sample caches (upcoming feature).
      ~sample caching #6363~ (to be moved to a future release) 
- [ ] fix loop marker issues #5505
- [ ] slight changes to default theme (requires discussion)
some bug fixes
 - [ ] #6357 
 - [ ] #6343 
 - [ ] #6335 
 - [ ] #6336 
 - [ ] #6314 
 here are some very old bugs not yet fixed
- [ ] #765
- [ ] #1681
- [ ] #847 
- [ ] take a look at all other older bugs not mentioned and either close it off or fix em.
if you want more issues/bugs to be added, just comment.

the point of this comment is just to organize and speed up the release of lmms 1.3. i included only a few features cause we can move the rest for 1.4. as of now, 1.3 can just be a minor post code refactor release with a few added features. 1.4 can be made a bigger release.

**Comment by Monospace-V** [comment]
First suggestion can already be done manually. There is already the incremental save ability, and project bundles (ie portable project files) has been implemented. All that you are asking for, is to automatically save within a subdirectory, which makes for a good enhancement.

For the rest of them..  This is good for organization, I suppose. There, however, already exists the milestone. LMMS 1.3's alpha is already in the works, with the major file structure changes already implemented.
There exists a milestone called 1.3.0 [that this links to](https://github.com/LMMS/lmms/milestone/4). Most collections of bugs/enhancements, are specific to a certain type of bug/request, to organize all issues of the same type. This is more of an umbrella post. Also see [this](https://github.com/LMMS/lmms/milestone/7)
These are a lot of changes, and there are already many underway, discussions or PRs. Even some of the bugs you have linked to, are being fixed. Also see https://github.com/LMMS/lmms/projects

You have found a few bugs. However, it should be noted that we have about [300](https://github.com/LMMS/lmms/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-asc) open bugs, many of which are old, all of which are given a higher priority over features. And each of which is given a priority. Bugs which break functionality, also, are a higher priority than bugs which mislead or confuse the users. However, bugs which mislead the users can be easier to fix.

You are right in saying it has been very long since an LMMS release. We are running on a few devs. If you know C++, I encourage you to contribute to the codebase, starting with [these](https://github.com/LMMS/lmms/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) (don't forget to look through the codebase first to find the coding standards and conventions!).

The effort taken to find and organize the bugs is appreciated.

**Comment by roshanrules1** [comment]
> This is more of an umbrella post.
yeah exactly. i wrote this umbrella post just for organisation. nothing more.

> There, however, already exists the milestone. 
i didn't see that. btw how about modifying it. since the code refactor took way too long, delaying the release makes little sense (the only reasons being critical bugs). so we can remove the enhancements for now.

> it should be noted that we have about 300 open bugs, many of which are old; and bugs are given a higher priority over enhancements.
again, consolidates the point above

so i think it would be better to cut off most of the enhancements and focusing on easy to do enhancements and bugs and move towards a releasable version asap (tbh im tired of waiting already).

>If you know C++, I encourage you to contribute to the codebase
i want to but unfortunately, i don't know c++. 

anyway thanks for commenting man.

**Comment by Monospace-V** [comment]
If you're tired of waiting, have you considered downloading an LMMS 1.3 alpha binary from the website or from any recently updated PR? Because while the time of release is not definite, if your main worry is _waiting_, that can be mitigated.
https://lmms.io/download#windows https://github.com/LMMS/lmms/pulls
We can keep putting off major things for each next version, but in the end it still has to be done. The code refactor, due to its existence in sight (more or less), is a 1.3 milestone. Nobody likes waiting, but LMMS is an open-source project, and nobody's paid to get things done asap. Rather than easy to do enhancements and bugfixes FOR a release, some of us may believe in maximizing quality, adding functionality.

**Comment by roshanrules1** [comment]
i did consider downloading a binary from a pr but for some reason, thought otherwise. anyway, this time, i might do it but it should not mess with my current 1.2 install. that's what's not allowing me to install it. i get why the development is slow so will wait for now.

**Comment by Monospace-V** [comment]
Can't you just rename the installation folder to something else, in the installer? You will be unable to load themes right, but that's the only thing that breaks in the settings save behaviour.

**Comment by Spekular** [comment]
Closing in favor of the 1.3 milestone.
