### ISSUE TITLE
broken theming of custom themes on 1.3 alpha master

### ISSUE THREAD

**Issue by Rossmaxx** [LMMS/lmms#6391]
### Bug Summary
i am running 1.2 and 1.3 on the same system and have encountered some bugs related to theming.

expected (as seen on 1.2)
![1 2 themed](https://user-images.githubusercontent.com/74815851/166209163-840b7501-df8e-41a2-adb6-d37d3ba1f9fb.JPG)

when i open chameleon theme on 1.3
![chameleon on 1 3](https://user-images.githubusercontent.com/74815851/166209370-7bb79949-159a-4a1b-8c6e-79e39a5f36a2.JPG)

#### Steps to reproduce
Grab any theme from lsp and use it for alpha.

#### Affected LMMS versions
1.2 and 1.3 alpha (build #6390 )

another issue is that whenever i open 1.3 then open 1.2, it reverts back to default. i think that has got something to do with the lmmsrc.xml file.

**Comment by Monospace-V** [comment]
Not sure if this counts as a theming bug.
It seems to me your actual problem isn't theming as of itself, but rather the colour change which happens when loading a new project in an old version. I take this as an indicator that the b/b won't load and play properly. It doesn't make much sense to modify this behaviour to allow new files to be loaded in older versions, due to the nature of compatibility itself.
Features cannot be loaded with unnecessary code just so the loaded colour is correct.
There is no expectation for 1.3 files to open in 1.2 properly, and redundant trying to ensure it does.

Yes, the theme does tend to change and cannot be kept. Keeping a separate settings file has the problem that whenever you update LMMS you need to re-save settings. Using two (well, four, but usually stick to two of them) versions of LMMS myself, and having been unable to use the Cameleon theme and forced to stick with default, I know what you mean. I like to believe the same thing which goes for backward compatibility on themes goes for lmmsrc.xml. The entry name and order itself is changed. However, I think this _might_ be fixable. Not that it makes much sense, but it could be possible.

**Comment by Rossmaxx** [comment]
>It seems to me your actual problem isn't theming as of itself

It is. The 3rd pic is the actual issue.the 2nd one is just an extra point.

> I take this as an indicator that the b/b won't load and play properly.

It does not work. But i do not expect to get it fixed. Just stated it for more points.

> Features cannot be loaded with unnecessary code just so the loaded colour is correct.
There is no expectation for 1.3 files to open in 1.2 properly, and redundant trying to ensure it does.

This is why i left the problem in the 2nd pic to 'no need to be fixed'.

> Yes, the theme does tend to change and cannot be kept. Keeping a separate settings file has the problem that whenever you update LMMS you need to re-save settings.

So its better not to touch lmmsrc.xml either.

But not getting chameleon to work properly (ie the third pic) is a deal breaker for me. I think the original creator of the theme should be fixing it via css.

**Comment by Monospace-V** [comment]
Cameleon was built for 1.2. Trying to "fix it via css" breaks the theme for 1.2 in favour of an unstable alpha version only some of us use. Have you considered manually updating style.css yourself?

(Quick note: I also suggest using the [forums](https://lmms.io/forum/), where we can help you more with any problems or questions, or the LMMS [discord](https://lmms.io/chat/), if you want help from more than 2 people only and are sure you want a response at all, before filing anything on the github. Also, it ensures that "No need to be fixed" items don't take up a large part of a bug report but end up mentioned anyways. And I'd use the discord chat if I could, so that's an endorsement from me.)

I'm willing to, on that note, look at the style.css and see if I can fix the b/b TCO colour for Cameleon for 1.3. If I do, I'll provide you with an updated version.

**Comment by Monospace-V** [comment]
Update: I cannot figure out how to fix the theme for B/B editor.

**Comment by Rossmaxx** [comment]
> Cameleon was built for 1.2. Trying to "fix it via css" breaks the theme for 1.2 in favour of an unstable alpha version only some of us use.

Now i get it. So this issue can be repurposed into support for older themes with 1.3 (because most themes are built for 1.2 and so that the usability with the upcoming 1.3 stable shall not be affected). 

> Have you considered manually updating style.css yourself?

I wanted to but don't know css.

I thought about it and found why the b/b is broken. I think its because the b/b was renamed to patterns and 1.2 mmpz files still use b/b instead of patterns. 

> (Quick note: I also suggest using the forums, where we can help you more with any problems or questions, or the LMMS discord, if you want help from more than 2 people only and are sure you want a response at all, before filing anything on the github.

I did go to discord but after writing this issue. Apparently qnebra has a fixed file. He will send it.

**Comment by Monospace-V** [comment]
I don't know the CSS either. I just mess around.
I managed to fix the black piano roll notes, but can't find how to fix bb. Noticed that it changed to pattern, but still...
Can I get that fixed file if it's not sent here? Thanks

**Comment by allejok96** [comment]
> this issue can be repurposed into support for older themes with 1.3

Good idea. We have backwards compatibility for project files but I don't know if themes have been discussed. Though fixing a broken theme should be pretty straightforward I think.
