### ISSUE TITLE
Add Portamento, Swing Control and Envelope Pitch and Panning

### ISSUE THREAD

**Issue by QuetzalcoutlDev** [LMMS/lmms#6515]
### Enhancement Summary
I think that one of the many things that LMMS lacks, I think that the Portamento, the Swing control and the Pitch and Pan Envelope are one of the most important and necessary things that LMMS needs, I know that we can fix ourselves using the plugins VST but when you need portamento in the LMMS internal plugins you can't as it doesn't have them

#### Justification

I think LMMS badly needs these controls

**Comment by allejok96** [comment]
- #1091
- #1466
- #533

Some plugins like LB302 and Zyn has portamento already. SF2, Vibed and (correct me if I'm wrong) Vestige doesn't support per-note pitch bend at all. The rest of the plugins would benefit from a portamento feature.

**Comment by Monospace-V** [comment]
(Swing control is actually a feature in the works. You can control amount of swing with a slider. I am personally a fan of the change-quantisation-pattern approach for swing, like Reaper does, because I feel it allows you to see exactly what you do- but this is a good way of working.)

Re: portamento, though, there is a handy feature that works on several internal plugins, called pitch bend.
[This](https://youtu.be/Nl4fj0vkQOY) video shows how to use pitch bend in LMMS.
Until (if) portamento is implemented, you can use this. It doesn't work for soundfonts and some other plugins, so I automate pitch. It gives a certain level of control above and beyond portamento.

However, it is worth noting that Portamento usually is found only on monophonic synthesizers, and most LMMS synths are polyphonic. Exception is the LB302, which is monophonic, and it has a portamento option. Unless we add a monophonic mode to normal plugins like the TripleOscillator, portamento could be difficult to do properly unless we're willing to let some slightly funny things happen or patch them up in a way that could sometimes be unwanted.

**Comment by QuetzalcoutlDev** [comment]
> (Swing control is actually a feature in the works. You can control amount of swing with a slider. I am personally a fan of the change-quantisation-pattern approach for swing, like Reaper does, because I feel it allows you to see exactly what you do- but this is a good way of working.)
> 
> Re: portamento, though, there is a handy feature that works on several internal plugins, called pitch bend. [This](https://youtu.be/Nl4fj0vkQOY) video shows how to use pitch bend in LMMS. Until (if) portamento is implemented, you can use this. It doesn't work for soundfonts and some other plugins, so I automate pitch. It gives a certain level of control above and beyond portamento.
> 
> However, it is worth noting that Portamento usually is found only on monophonic synthesizers, and most LMMS synths are polyphonic. Exception is the LB302, which is monophonic, and it has a portamento option. Unless we add a monophonic mode to normal plugins like the TripleOscillator, portamento could be difficult to do properly unless we're willing to let some slightly funny things happen or patch them up in a way that could sometimes be unwanted.

I think another option is to set the LMMS polyphonic plugins to mono mode as I recently saw a video of a professional music producer in FL Studio testing LMMS and mentioning that mono would be a feature he needs 😅

**Comment by Monospace-V** [comment]
Yes, OP, I mentioned the option. I'm a little surprised I haven't seen it suggested anywhere. I'll check tomorrow. It seems a good feature.

**Comment by zonkmachine** [comment]
> > **Unless we add a monophonic mode to normal plugins** like the TripleOscillator, [...]
> 
> I'm a little surprised I haven't seen it suggested anywhere. I'll check tomorrow. It seems a good feature.

:+1: I'd love this!

**Comment by allejok96** [comment]
Closing this due to lot of duplicate requests. Discussion about monophonic portamento continues in #6516. Thanks for bringing up that idea.
