### ISSUE TITLE
request: android version

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#6535]
Hi

I have no idea if it's possible but somebody asked a raspberry pi version.
And then I thought maybe a mobile version of LMMS could be made?
I found there is QT for android.

It's probably difficult but it was just an idea.

**Comment by Rossmaxx** [comment]
LMMS for Android looks like an ok idea. But the no 1 problem i see is what the ui will look like for a device with such small screen sizes. I think we can go for a tweaked version of the single window design once that gets done. But anyway it'll take a long time.

Another major concern is the vst support. As far as i know, there's no vsts on android. Not as major but might break cross compatibility between pc and mobile versions (i think this is why fl mobile has a different file format instead of using the .flp)

If we find solutions to these two, i guess the rest of the minor problems will be easy enough to fix but this is something which **should*

**Comment by rdrpenguin04** [comment]
This will probably be easier after the core-UI split so we can have a dedicated mobile UI; the existing UI has no shot of being usable on a phone. That said, I've been waiting for an Android port too, so I would be all for it once that happens.

**Comment by opensourcefree** [comment]
Here are examples/ideas of how it could look

https://youtu.be/xQC7YWGodeE

https://youtu.be/Xc5AW85ZX5A

I think the VST support can just be disabled, it's not a big problem I think. No VeSTige for Android :)

If the core-UI split is made, will QT6 be used too?
Because I see there is much support here: https://doc-snapshots.qt.io/qt6-dev/android.html

**Comment by allejok96** [comment]
The core/UI split means we are aiming to separate the basic C++ internals from Qt to make it easier to write new frontends to LMMS in the future. This is a long term goal and we will keep the Qt frontend as long as no one has made anything better.

Right now this is not a feasible request and it would probably be faster and easier to code an Android DAW from scratch. If someone wants to create an Android frontend to LMMS in the future, that should probably be treated as a third-party project.

**Comment by zonkmachine** [comment]
Tesla Motors fork of lmms, TRAX, has hacks to integrate with their custom ui for touchscreen. Maybe there's something in there we could snatch back?

**Comment by allejok96** [comment]
We could draw some inspiration from it I guess. It still uses Ubuntu and Qt, though. Looks like they just made a few changes to allow LMMS to run [headless](https://github.com/LMMS/lmms/commit/f3e81bd17c760c6b95da1d1770ede001a0d216a9) with their custom (probably closed source) UI.
