### ISSUE TITLE
Some piano-roll useful features ideas for LMMS ?

### ISSUE THREAD

**Issue by Manerr** [LMMS/lmms#6589]

**Comment by Monospace-V** [comment]
I'll agree, lack of documented shortcuts is a little irritating. LMMS in general uses shortcuts similar to Windows Explorer and other applications, rather than other DAWs which have different shortcuts and no standard mapping, and a lot of people who migrate from other DAWs to LMMS can be surprised by this.
A shortcut mapping editor is planned.

![image](https://user-images.githubusercontent.com/76674645/208297730-554da21b-224d-46cc-add2-ecd4a8bce25e.png)
Select all notes on this key already exists.

There is no option to invert selection, but Ctrl-Shift-Drag selects only all unselected notes and deselects selected notes over a region.
I imagine Ctrl-Shift-A shortcut could be useful, but it already is a shortcut with the same job as Esc: deselect all. (If people often use Esc instead of Ctrl-Shift-A to deselect, then we could use Ctrl-Shift-A to invert selection?)

What do you mean by lock selection? I cannot understand what the feature means in this context. You want to make notes uneditable? But do you want to add notes around them, just not change their volume or pitch or time, but around selection is ok?

Select out of scale notes could be useful. In the meantime I'd suggest using Select All Notes On This Key in combination with Mark Current Scale.

If, by "multi-instrument recording" you mean different parts of MIDI keyboard mapped to different instruments, I recall seeing that planned. I don't recall...
If you mean same melody on multiple instruments, that's planned too.
VST3 support, we hope to have one day. Audio recording support is also in the works.

Your suggestions are useful. I wouldn't have thought of a lot because they don't make sense for my usecase, and I wonder if others would say the same. But they'd be very useful to a lot of users.

**Comment by Manerr** [comment]
> If, by "multi-instrument recording" you mean different parts of MIDI keyboard mapped to different instruments, I recall seeing that planned. I don't recall... If you mean same melody on multiple instruments, that's planned too. VST3 support, we hope to have one day. Audio recording support is also in the works.

There's already something like midi keyboard mapping, since we can choose upper and lower part of a key range for any instrument , so when I was speaking about multi recordings it was more something like a global keyboard recording (instead of just the current selected piano roll) 

> What do you mean by lock selection?  

Something like locking selected notes (not so useful since there's history lol ) .

> Select out of scale notes could be useful. In the meantime I'd suggest using Select All Notes On This Key in combination with Mark Current Scale.

You see it's not really intuitive and it would be better to have a dedicated thing.*

##It'd be great to have something like a mini-scripting thing for adding external things easier (like an api or an integrated scripter) -> I'd immediatly starting writing new feature if so 😄

**Comment by wyldcrd** [comment]
Random melody based on scales -> useful in 1/10000 cases ?

OpenAi made MuseNet which can make a melody based off of preferences although the genres you can base them off are very limited.

**Comment by janEntikan** [comment]
humanization though...

**Comment by wyldcrd** [comment]
Literally just learn music theory bruv

**Comment by Manerr** [comment]
> Literally just learn music theory bruv

Not sure it's the right or best place to speak about
And I understand music theory ,lol ( why will I ask about scale things else ? ) 

I close the thread before it goes too far of the starting purpose

**Comment by dumpster-of-things** [comment]
documentation on where in the code one might give alternating background colors to higher resolutions such as 1/192.  pretty much a required visual aid for those of us who have nothing but a mouse to work with.

**Comment by musikBear** [comment]
> The alternating background colors don't alternate beyond 1/4 resolution. 

wdym, please post a screen shot
![image](https://github.com/LMMS/lmms/assets/6662066/cf115e2e-1854-44b8-8f07-252cc5d7c21e)
The alternating bars in PRoll does not change nomatter what selected note-length 

neither does the shading in SEditor
![image](https://github.com/LMMS/lmms/assets/6662066/3ee4369c-eb68-431c-a68b-f119b684eeff)

are you referring to Q value
Same thing
![image](https://github.com/LMMS/lmms/assets/6662066/519e49bc-ee67-4695-a1d2-bf381e1d5c33)
Only thing different is snap, alternating shading is not changed
Im afraid i do not know what you refer to
