### ISSUE TITLE
Online Projects/Presets/Samples "Collaborato"

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#661]
**Closed due to lack of resources.**

A feature initially developed by @tobydox that never made it to stable but recently resurrected as a topic via mailing list by "oe ai" (2014-04-28) is an enhancement request to have Project/Presets/Samples (et.al) downloadable/uploadable via the LMMS interface.

This bug report is a placeholder for this feature to track feasibility, initial efforts,  major thoughts/concerns.

Note, the LSP rewrite should take special consideration as to accommodate this "Collaborato" feature.

Picture of pre-1.0.0 implementation provided for conceptual purposes only.
![image](https://cloud.githubusercontent.com/assets/6345473/2837233/4628245a-d012-11e3-9d92-0801f0d7b22c.png)

---

**@diizy said on lmms-devel 2015-01-21**

> A reminder: before we add any online features to LMMS, we need to remember that any time something is connected online, it brings with it a whole bunch of new issues to worry about. 
> 
> As long as LMMS is a purely local application, we don't need to worry about such things. The moment we allow LMMS to connect online, we accept a responsibility of handling the user's data over networks, and all the privacy & security concerns that come with it. Simply adding an online
> feature while ignoring those concerns is unacceptable.
> 
> So we really need a cost/benefit analysis here...

**Comment by tresf** [comment]
Cloud comparisons:

> So I'm looking into a proper cloud storage for "collaborato" :) and I've
> come across a few options (please list any/all others).
>
>    - *Google Cloud Storage*
>    - *Amazon S3*
>    - *EMC Atmos*
>
> Feel free to read the details below, but my initial analysis is to use
> Amazon since they offer a "Free Tier" which will cost nothing to startup
> and our bandwidth, storage and file operations will be capped per month.
>
> From an API perspective, REST/SOAP seem to be defacto.  Google provides a
> JSON API although .NET, Java and Python seem to be standard
> implementations.  All APIs use similar terminology
> "DELETE/INSERT/LIST/ETC", and refer to data as "BUCKETS/OBJECTS/ETC"
>
> Here's the pricing details.  EMCs wasn't readily available.
>
> Pricing:
>
>    - Google <https://developers.google.com/storage/pricing>;
>    Storage:  About $.02/GB/Mo (500GB would be $10)
>    Bandwidth:
>       DOWN:  ~$0.10 - $0.20/GB (Varies based on region)
>       UP:  FREE
>    File Operations: $0.01 per 10,000/1,000 (operating depending)
>
>    - Amazon <http://aws.amazon.com/s3/pricing/>;
>    Storage: About $.03/GB/Mo  (500GB would be $15)  *First 5GB Free using
>    "Free Tier"*
>    Bandwidth:
>       DOWN: ~$0.10/GB *First 15GB/Mo Free using "Free Tier"*
>       UP:  FREE
>    File Operations:  $0.005 per 10,000/1,000 (operation depending) *First
>    20,000/2,000 free using "Free Tier"*
>    - EMC <http://www.emc.com/storage/atmos/atmos.htm>;
>    (hides its pricing behind an inquiry screen)
>
> APIs:
>
>    - Google
>       Java/JSON
>    - Amazon
>       REST/SOAP
>    - EMC
>       REST/SOAP
>       Claims to also support NFS/CIFS
>
>
> -Tres
>

**Comment by Wallacoloo** [comment]
I think this is a GREAT opportunity to play around with [IPFS](http://ipfs.io/). It's more-or-less one giant, globally accessible distributed file system that combines a bunch of technologies developed in version control systems and torrent / peer-to-peer communications.

All that would have to be done is on the server side, install the IPFS daemon and mount IPFS to some directory (it behaves as an ordinary file system). Whenever something is uploaded to the LSP, place the public files in the IPFS directory. Then on the user side, they can also mount the IPFS directory to one of the LMMS directories. Then they can browse LSP samples, projects, etc, from within LMMS and we don't have to modify any code within LMMS. Because of the peer-to-peer nature, we shouldn't have any bandwidth issues - the user will cache everything they request and new requests are distributed to everyone else who has downloaded those files, much like torrenting.

**Comment by tresf** [comment]
@Colin,

Cool concept.  The only issue is that currently our LSP is managed by a database, so the filesystem isn't really what most would consider a filesystem since the files are arbitrarily named and receive their actual file name only at download time.

-Tres

**Comment by Wallacoloo** [comment]
@tresf if I were to add IPFS support to the LSP, would it be welcomed? And if so, what would be the preferred way to implement it? I could implement it as a **separate** service which downloads newly uploaded files through the http interface and stores them in an IPFS folder (thus acquiring their correct name in the process), or I could add a hook into the upload process that copies the files to the file system before storing them in the database. The first is probably better since it has fewer dependencies - it could conceivably be modified to run on a different host even.

I have the week after next off, so I could probably implement this at some point. But I'd like to know if the devs would *actually* consider merging a feature like in advance so that I don't end up wasting my free time. I assume this feature would be welcomed, based on the fact that this thread had a lot of discussion, but I've been wrong before so I'm a bit weary.

**Comment by tresf** [comment]
Good question.  I think an LSP rewrite would be a better use of time, personally.  The technology is attractive, but I'm not sure what type of demand we'd have for it.  From an accessibility perspective, I think leveraging a webservice which lists the projects and presets directly in the software is much more robust and a better delivery to the user over a 3rd party plugin, personally.  It's not much different than putting a copy of our files on DropBox or Google Drive, the clients still need to use the 3rd party service to receive them.  The one you posted only helps with the cloud bandwidth problem -- i.e. cost -- which may not even be a problem.

Currently @Lukas-W @Umcaruje and myself maintain the website, so we'd be the ones approving.  I think it's a lot of work that could be better spent improving something more fundamentally broken, personally. :)

**Comment by tresf** [comment]
That said, if you decided to integrate and convert our LSP into a content-management-type front end (perhaps one that tied into our forums logins) that would be a nice win.  Our LSP is in dire need of maintenance.

Also, if you do jump into the LSP database, we have some procedures for setting it up here:

https://github.com/LMMS/lmms.io/wiki/LSP-Installation

**Comment by Umcaruje** [comment]
I agree that this is a really cool idea, but I think that LSP should have a rewrite (something angular,js based maybe?), rather than patching the old php code, since using an existing framework would probably make maintaining a bit easier. That said, I realize there isn't a lot of manpower for that, so maybe patching the php code is the best that can happen atm.

**Comment by tresf** [comment]
@Umcaruje, note that @Lukas-W has converted the majority of the website to use some newer technologies which can greatly simplify the LSP code if we do a rewrite.  He uses a php package manager called "composer" and it does some heavy lifting in terms of using 3rd party APIs, templating, custom URL routing, etc.

Someone with some time to learn these technologies could shrink the LSP code-base to 1/10th of its size and then start adding in features. :)
