### ISSUE TITLE
message printed while doing .ds file preview

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#6633]
Open LMMS from terminal.
Navigate to My Samples > drumsynth.
Click on any .ds file to preview.

Following message appears in the terminal:
```
SampleBuffer::decodeSampleOGGVorbis(): not an Ogg Vorbis file
```

On every click on a .ds file, the message appears.

Call: [SampleBuffer.cpp](https://github.com/LMMS/lmms/blob/master/src/core/SampleBuffer.cpp)

It does not print such message for .ogg, .flac or .wav files but for .ds only. Application performs normally.

**Comment by sakertooth** [comment]
This occurs due to the fact that when loading a ``SampleBuffer`` from an audio file, ``SampleBuffer`` tries to decode it using various decoders until it successfully loads (and if all the decoders it tried still couldn't load it, it bails and creates an empty buffer). This means that it will unnecessarily try to decode ``DrumSynth`` files using its OGG decoders, which would obviously fail. #6610 fixes this issue, as it only decodes the audio file using the ``DrumSynth`` decoder if the filename extension is ``.ds``.
