### ISSUE TITLE
'pCurPreset' is being used without being initialized.

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#6639]
Run-Time Check Failure - The variable 'pCurPreset' is being used without being initialized.

https://github.com/LMMS/lmms/blob/507fa239ddffd2ed1f186d0a51016c85d9c2b5a9/plugins/Sf2Player/PatchesDialog.cpp#L159

How to reproduce:
Open SF player. Choose a soundfont file. Choose wrench icon: "Choose patch".

Debugger stops at this point. After this stoppage, if you restart lmms:
`Cannot load library -\build\Debug\plugins\sf2player.dll: The specified module could not be found.` and the player won't show up in the instrument list next time.

**Comment by michaelgregorius** [comment]
Should be fixed by pull request #6723.

**Comment by michaelgregorius** [comment]
Hi @Veratil,

thanks for the quick review and merge!

I wonder if we can close this issue as well? I am not really sure if the problem with regards to the message "Cannot load library -\build\Debug\plugins\sf2player.dll: The specified module could not be found." is really solved by the fix because as noted the uninitialized variable should not really have caused a problem because it overwritten by the call in the line following it. However, I am not able to test the described problem anyway as I do not have a Windows debug build or the means to debug under Windows.

**Comment by anytizer** [comment]
I am testing for this issue.
I do not have the old copy of Qt 5.12, but on 5.15.

I could NOT recompile to reproduce the bug. Hence I tested with the nightly version only; and that appears to work ok.

---

Further, LMMS was compiled nicely in Qt 5.15, but when I run the exe, I get like:
![image](https://github.com/LMMS/lmms/assets/5563341/23a81438-9cc0-4701-99b7-9ce040a9da2e)
The new error could be due to some other factors.

Meanwhile, the compiling process is in my gist: [Compiling 64bit LMMS under Windows with Visual Studio](https://gist.github.com/anytizer/a674f2d24cd91dd2ffc510963e1a241c).
