### ISSUE TITLE
Freeboy crashes LMMS

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#6649]
Attachment: [freeboy-crash.zip](https://github.com/LMMS/lmms/files/10771605/freeboy-crash.zip)

If a second note plays earlier than first note finishes, freeboy crashes LMMS.

lmms: -/lmms/plugins/FreeBoy/game-music-emu/gme/Gb_Apu.cpp:131: void Gb_Apu::run_until(blip_time_t): Assertion `end_time >= last_time' failed.

**Comment by messmerd** [comment]
I've identified the cause of this and I'm working on a fix.

**Comment by messmerd** [comment]
@zonkmachine No, this bug is different from those

**Comment by messmerd** [comment]
@RiedleroD It affects the GB APU and the audio it produces in a lot of unintended ways.

The APU requires `end_time > last_time` to be true, but due to this bug, it sometimes isn't, and that invalidates a lot of the logic that follows. In addition to the assert statement for debug builds, the person who wrote the library even wrote a comment saying _"end_time must not be before previous time"_, so we are clearly doing things we really should not be doing. However, I cannot know everything that could go wrong without a deeper understanding of how the APU works.

But I do know that by fixing this bug, we will be making FreeBoy behave in the way it was intended to, and we'll likely fix some hard-to-notice audio glitches that would otherwise be nearly impossible to track down.

**Comment by messmerd** [comment]
@RiedleroD I found an example of an audio issue that this bug is causing.

Here's the 1st part of Freeboy_issue.mmpz from #6144 rendered to wav at 96,000 Hz once with the master build and once with the fix in PR #6680:

[Freeboy_issue.zip](https://github.com/LMMS/lmms/files/11095909/Freeboy_issue.zip)

With this bug fixed, you can tell there's much less strange noise in the background when each new note plays.
Note that my PR doesn't fix the high CPU usage described in #6144, but it does fix the failed assertion that was mentioned in the comments.
