### ISSUE TITLE
How to obtain the  Reverb value?

### ISSUE THREAD

**Issue by mhsszm** [LMMS/lmms#6690]
Bug Summary

In the VST plugin DSK saxophones, when modifying the value of Reverb, which function or variable in LMMS can obtain the changed value?

Expected behavior
Get Reverb value in lmms.![image](https://user-images.githubusercontent.com/25781417/232449607-4f2acada-5a02-45a9-b1f9-40844c7ccdc1.png)

**Comment by musikBear** [comment]
> Expected behavior
Get Reverb value in lmms.

Njae.. This issue is 'covered' by the 5-point test.
If a VST does not save all parameters to file, then it is not useable. DSK has a couple of those..
I made a fix for it. It can used in those situations where it is just one of a few parameters that is not preserved in the file, of an absolutely magnificent sounding VST, that just cant be left out of a project.
You can see here how that is done:
https://www.youtube.com/watch?v=ZsgA04tfiwc

**Comment by zonkmachine** [comment]
@mhsszm I see this too. Normally Vestige would have access to the vst parameters by hitting the 'wrench icon' but in the case of DSK Saxophones, nothing shows up.

**Comment by DomClark** [comment]
It looks like this particular plugin doesn't make any parameters available for automation. I'm going to close this issue as "not our bug"; if you can automate the plugin in another DAW, however, please feel free to re-open it.
