### ISSUE TITLE
AudioFileProcessor: Wrong loopback point when reversing sample

### ISSUE THREAD

**Issue by messmerd** [LMMS/lmms#6708]
### Bug Summary
The loopback point in the AudioFileProcessor (AFP) instrument can be set to the wrong value when reversing a sample.

#### Steps to reproduce
- Create a new project
- Add an AFP instrument to the Song-Editor
- Open any audio file in the AFP instrument
- Set the AFP start point to 0.3 (this also sets the loopback point to 0.3)
- Set the AFP loopback point to 0.2 (this also sets the start point to 0.2)
- Notice that both the start point and loopback point should be 0.2 now
- Click the reverse sample button
- Click the reverse sample button again

#### Expected behavior
After clicking the reverse sample button twice, both the start point and loopback point should be back to 0.2 like they were originally.

#### Actual behavior
The start point is 0.2, but the loopback point is 0.4.

Additionally, if the loopback point is then set to any value between 0.2 and 0.4, clicking the reverse sample button twice will set it back to 0.4 regardless of what value it was previously.

#### Affected LMMS versions
master, 1.3.0-alpha, 1.2.2, ...

**Comment by michaelgregorius** [comment]
This seems to be caused by some "chaotic" updates via signals when the points (start, loop, end) change. This can be observed by setting a break point in `AudioFileProcessor::pointChanged` which is triggered by different updates of the points.

If I understand correctly the new points would need to be computed as follows:
```
newStart = 1. - end;
loop = 1. - loop;
newEnd = 1. - start
```
One solution might be to turn off signals during the update, perform the calculation, update the values and then emit one signal at the end.
