### ISSUE TITLE
Comboboxes in SongEditor allow automation but crash

### ISSUE THREAD

**Issue by superpaik** [LMMS/lmms#6711]
### Bug Summary
Comboboxes for zooming and snapping in SongEditor allow automation, but when they are drag to an automation track LMMS crashes.

#### Steps to reproduce
Drag zoom combobox arrow in SongEditor to an automation track

#### Expected behavior
I don't see why those controllers (that are gui controllers) should be automatable, but if they are, they shouldn't cause a crash.
Similar controllers in PianoRoll or AutomationEditor do not cause a crash.

#### Actual behavior
It causes a crash.

#### Screenshot
![DrowDown-Automate-Crash](https://github.com/LMMS/lmms/assets/68785450/e1d99440-1dc8-4b99-af9d-4bb65eb590f2)

#### Affected LMMS versions
1.2.2 and master

Hint:
As far as I found, it happens because in model.cpp we try to get the parentModel()->fullDisplayName(), and those controls' parents do not have that property or something. The string is not null and is not empty, but when accessing to it, it generates an access violation.

**Comment by michaelgregorius** [comment]
This issue seems to be related to #2382 and its associated pull request #2399. If someone wants to fix this please check the discussions in these issue.

**Comment by michaelgregorius** [comment]
I did some investigation and found the reason for the crash. The bug goes away if you change
```
Model* parentModel() const
{
	return static_cast<Model *>( parent() );
}
```
to 
```
Model* parentModel() const
{
	return dynamic_cast<Model *>( parent() );
}
```

This means that the problematic `Model` in question has a parent which is not a `Model`.

Adding these lines to the constructor of `Model`  and setting a break point in the body of the `if` statement yielded no results though:
```
Model * castModel = dynamic_cast<Model *> (_parent);
if (_parent && !castModel)
{
	int i = 0;
}
```

This implies that the problem seems to be introduced later. Therefore let's search for calls to `setParent`. This yields the following two lines in the constructor of `SongEditor`:
```
m_zoomingModel->setParent(this);
m_snappingModel->setParent(this);
```
A `SongEditor` is not a `Model` which explains the crash when we `static_cast` it to one. These two lines have been added by @lukas-w (with commit 24d320de34b) and @Spekular (with commit 1c715bc335b). Pinging them so they can provide some information on why the lines have been added and if they can be removed.

IMHO it's not a good idea to model the parent/child relationships of the LMMS models using the parent/child relationships of Qt because they have different semantics. One is mainly used to model the relationship of graphical objects/widgets while the other is used to model the relationship between some "business" objects of LMMS.

**Comment by lukas-w** [comment]
> Pinging them so they can provide some information on why the lines have been added and if they can be removed.

As the commit message says, this was a memory leak so I used `QObject::setParent` as it's intended to assign ownership. I don't think I was aware that `Model` re-interprets `QObject::parent()` to always point to a model. It looks to me like this is the core of the problem here so using `dynamic_cast` instead would be an appropriate fix. Maybe it's reasonable to add a distinct `parentModel` property to `Model` do properly disambiguate the two semantics? Or maybe we can get rid of this altogether? It's only used in four places in the code and feels like an anti-pattern to me at first glance. I haven't worked with LMMS code for so long though so take this with a grain of salt. I'm not even sure anymore what "models" or parent models represent.

**Comment by Spekular** [comment]
I simply copied and modified the zoom selector code to make the snap selector 😅

**Comment by zonkmachine** [comment]
Fixed in https://github.com/LMMS/lmms/pull/6718
