### ISSUE TITLE
CARLA_EXPORT vs CARLA_API_EXPORT

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#6724]
After submodule updates, I see the following kind of error:
DummyCarla.cpp: CARLA_EXPORT does not name a type; did you mean CARLA_API_EXPORT?

#### Steps to reproduce
On Ubuntu; update submodules. Then, try to compile LMMS.

#### Affected LMMS versions
Latest one (1.3.0-alpha.1.299+)

**Comment by irrenhaus3** [comment]
Introduced in https://github.com/falkTX/Carla/commit/b4cf0412847ae6a55d081553ec1e02ece24d85a3; carla 2.4.2 is the last version without this change.

**Comment by falkTX** [comment]
just check for `CARLA_PLUGIN_EXPORT` presence and use the older macro if not available, like so:

```
#ifdef CARLA_PLUGIN_EXPORT
CARLA_PLUGIN_EXPORT
#else
CARLA_EXPORT
#endif
void my_exported_func() { ... }
```

or put that inside another macro, whatever seems best.

the change was needed in order to have some symbols always exported (plugin export) while others are optional depending on the build type (API export)

**Comment by zonkmachine** [comment]
Closed in https://github.com/LMMS/lmms/pull/6814
