### ISSUE TITLE
Bad UI for instrument-ENV

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6730]
### Bug Summary
Its confusing that there is almost no change in selecting anything but TARGET

#### Steps to reproduce
![image](https://github.com/LMMS/lmms/assets/6662066/d7c1dc5f-b85f-4ac6-a5d2-f9e4ba178d1f)
Easy to see what i mean 
Witch one of the 3 options is selected?

#### Expected behavior
A clear and obvious chane on the UI that shows that a selection took place, and what ENV have focus
#### Actual behavior
Not possible to see what has focus
#### Screenshot
above 
#### Affected LMMS versions
all at least win

#### Mockup
![image](https://github.com/LMMS/lmms/assets/6662066/e7ea5891-3dca-4ca6-b3e0-1979f7603729)
Now its obvious what envelope is focused

**Comment by michaelgregorius** [comment]
I have extended `TabWidget` so that the font color of the selected tab can be set in the style sheet. If the background color of the selected tab is set to the green of the knobs and the text color to full on white it looks as follows:
![6730-TabWidgetChanges](https://github.com/LMMS/lmms/assets/9293269/16ddac65-07c5-4d72-827a-b750f18885ba)

However, I think the designers should also chime in. I don't know if @RebeccaDeField is still active in this project.

**Comment by michaelgregorius** [comment]
Pull request is #6732.

**Comment by michaelgregorius** [comment]
For anyone interested: this [comment](https://github.com/LMMS/lmms/pull/6732#pullrequestreview-1470581456) by @zonkmachine shows a before/after comparison.

**Comment by michaelgregorius** [comment]
I have experimented a bit and set the highlighted text color of the tab to a light green text as proposed by @anytizer. Here's how that looks with the changed dark green background and the unchanged background that the current master uses:

![6730-TabWidgetChanges-GreenTextHighlight](https://github.com/LMMS/lmms/assets/9293269/bff0de1f-1858-44bb-8280-67b109e455e7) ![6730-TabWidgetChanges-GreenTextOldBackground](https://github.com/LMMS/lmms/assets/9293269/d33acf2d-59c5-4732-9491-4ca6aa0d15c7)

The grey background is a bit more neutral and does not bite with any other potential colors in the content area. On the other hand it is not as obvious because it is rather subtle.

**Comment by musikBear** [comment]
> On the other hand it is not as obvious because it is rather subtle.

Agreed 100% !
Image 1 is the better UI 👍

**Comment by Veratil** [comment]
I like the background in the left image, but the `VOLUME` text seems blurry compared to the right image.

**Comment by michaelgregorius** [comment]
The reason for the text looking more blurry in the right image likely is that it's light green text on a dark green background whereas it's light green text on a grey background in the left image.
