### ISSUE TITLE
#6725 breaks Unfa-Spoken and possibly other projects 

### ISSUE THREAD

**Issue by kamkamkamkamkamkamkamkam** [LMMS/lmms#6828]
### Bug Summary
[#6725](https://github.com/LMMS/lmms/pull/6725) breaks Unfa-Spoken and possibly other projects 
#### Steps to reproduce
load Unfa-Spoken in latest nightly
#### Expected behavior
normal playback
#### Actual behavior
multiple elements are pitched up by an octave, because of the base pitch being modified
#### Affected LMMS versions
Nightly

**Comment by michaelgregorius** [comment]
This is fixed with #6832. Builds from version 4ff95072e88 to fc2f6a0b31b did not actually call the upgrade code which adjusts the base notes and as a result most files should open with lots of transposed instruments. This was fixed with commit 0e93f1332b3.

Files that have been saved with the aforementioned versions should not be affected, i.e. projects that have been created with nightlies of these versions should not be affected by the fix and sound the same.

**Comment by michaelgregorius** [comment]
@kamkamkamkamkamkamkamkam, can you please check with a nightly that contains the fix?

**Comment by kamkamkamkamkamkamkamkam** [comment]
unfa-Spoken now sounds perfectly normal 👍

**Comment by michaelgregorius** [comment]
Thanks for testing @kamkamkamkamkamkamkamkam! I will close this issue then.
