### ISSUE TITLE
Increased CPU usage in version of win1.3

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6846]
### Bug Summary
LMMS 1.3.0-a 1pha.1.102+ g89fc6c960 is reported to have increased CPU-load compared to 1.2.2
The CPU can even spike-out and freeze replay, with 'some' audio-samples

#### Steps to reproduce
LMMS 1.3.0-a 1pha.1.102+ g89fc6c960 needs to be installed
Then Audio-Samples need replayed.
This issue is of-cause complicated. There is only one report, and the OPs-HW could be a factor. The behaviour is seen without any other active program, and on a freshly booted PC
I expect to get data on the problematic sound-files soon, but the candidates are large vocal files (not shared).

#### Expected behavior
A version of 1.3 should not result in out-spiking

#### Actual behavior
ya..

#### Screenshot
none

#### Affected LMMS versions
sf. this is reported only for LMMS 1.3.0-a 1pha.1.102+ g89fc6c960

**Comment by musikBear** [comment]
> Were you using VST plugins when you noticed the increase in CPU usage?

Have you the _version in question_, and have you attempted to reproduce ?
There were only used samples
My guess is that a hw issue was the reason. OP diddent share the sample (long vocal)

**Comment by Rossmaxx** [comment]
Long vocal? Then this should be fixed when #6610 gets merged.

**Comment by DomClark** [comment]
I'm not sure what impact #6610 will have on this issue, since it's apparently a regression between 1.2.2 and the alpha.

I think there is far too little detail in this issue for it to be meaningful. "Somebody told me that they find samples to be slower in this two-year-old version than in this three-year-old version" is not something we can sensibly investigate. We need the person in question to communicate directly with us on this issue, not via a proxy, and to test with the nightly version.

**Comment by musikBear** [comment]
> and to test with the nightly version.

That was exactly what i told him to do, but he has chosen to revert to 1.2.2
IMO its a non-reproduceable issue, and one that is most likely HW related, and not LMMS fault.
