### ISSUE TITLE
please add mp3 function and video and more good stuff big thanks

### ISSUE THREAD

**Issue by music-composer-pro** [LMMS/lmms#6911]
# Please search the issue tracker for existing feature requests before submitting your own. Delete this line to confirm no similar request has been posted yet.

**Comment by Spekular** [comment]
- Export to mp3 has been available since 1.2 (#3615).
- We have an existing issue (#2000) and pull request (#6750) for mp3 import.
- Issue #2079 requests a video player.
- Your issue does not follow the template and does not adequately describe what functionality you're requesting
- Issues should only contain one feature request or bug report

**Comment by music-composer-pro** [comment]
and upload mp3 sample ?
