### ISSUE TITLE
Search time regression from #6962 ?

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#6980]
### Bug Summary
Searching takes actual minutes after push #6962 when in previous versions it was instant in the sample folder. No, I wasn't searching under my whole computer, and no, the new hierarchy isn't good or more useful, it's bad confusing and takes up more space. _Thanks for keeping the previous issue open for me to clarify._
#### Steps to reproduce
Try and search in the samples tab, if you even get a change, it'll be after a few minutes
#### Expected behavior
The search works well and doesn't suck, like it did before push #6962
#### Actual behavior
Takes forever and is unusable when it does show up.
I can't use this shit.
#### Screenshot
![image](https://github.com/LMMS/lmms/assets/65266122/cc211c66-b357-4e74-aa6b-4f6b0c287844)
it took minutes for this mess to come up
#### Affected LMMS versions
gc77952173 and other versions after #6962

**Comment by qnebra** [comment]
How many samples and subfolders in Samples location you have?

**Comment by SalutanisOrkonus** [comment]
this is what windows says: 
![image](https://github.com/LMMS/lmms/assets/65266122/375ad29d-83fe-4be8-ac73-715a21645107)
Which, yes, is not a tiny amount, but as I said, it preformed searches basically instantly before

**Comment by sakertooth** [comment]
> Searching takes actual minutes after push https://github.com/LMMS/lmms/pull/6962 when in previous versions it was instant in the sample folder.

It seems like files and directories in the samples folder get loaded on start-up, but the code now does a search across the filesystem every time, which is unnecessary for this directory if everything was loaded to begin with. This is probably why it takes a few minutes for anything to show up in the samples directory compared to it showing up in an instant.

> No, I wasn't searching under my whole computer, and no, the new hierarchy isn't good or more useful, it's bad confusing and takes up more space.

My apologies for assuming you were searching under your whole computer. I find the new hierarchy a bit easier since it mostly resembles how search is done in other DAWs and desktop environments, but I still agree that it is a problem that should be fixed if people aren't okay with it.

However, given your attitude and how you told me my work is utterly useless, I don't think its the right place for me to continue working on the file browser, and you would most likely agree with that. I am once again sorry for this upsetting change, I just don't know if I have it in me to fix the issues you are facing at this point in time.

I just wanted to fix the lag you were facing in #6874, but I failed to realize that such improvements are very delicate and should've been done with more care. I apologize, but I dont know if I can make it up to it as of right now given the state my spirit is in.

> Thanks for keeping the previous issue open for me to clarify.

I reopened the issue for you. It was wrong for me to silence you like that without full clarification of the problem at hand. I'm sorry.

**Comment by Veratil** [comment]
Let's keep the titles relevant to the issue reported please.

**Comment by sakertooth** [comment]
So yes, the search after 6962 is roughly 24x slower than pre-6962. I should've measured this before-hand. Will fix ASAP.

I will also make sure the original hierarchy is shown.

**Comment by SalutanisOrkonus** [comment]
first time (after booting up computer) bootup: 30.94s
consecutive bootup: 5.57s
sample folder search time: 16.73s
**Specs:**
CPU: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz   2.40 GHz
GPU0: Intel(R) UHD Graphics 630
GPU1: NVIDIA GeForce GTX 1650
Installed RAM: 8.00 GB (7.84 GB usable)
System type 64-bit operating system, x64-based processor (Windows 10)
256GB SSD
1tb Extra HDD
Laptop (if that changes anything)

Program is installed on Hard Drive, samples on SSD

**Comment by michaelgregorius** [comment]
> Edit: It would also be nice to know what specs you have. My PC is quite fast, so I couldn't really determine these performance bottlenecks quite accurately.

You can use [KCacheGrind](https://kcachegrind.github.io/html/Home.html) to do some performance analysis, e.g. to identify bottlenecks. It uses [Valgrind](https://valgrind.org/) under the hood.

To be frank, I would expect some profiling to be done for a merge that claims to improve performance.

**Comment by sakertooth** [comment]
> > Edit: It would also be nice to know what specs you have. My PC is quite fast, so I couldn't really determine these performance bottlenecks quite accurately.
> 
> You can use [KCacheGrind](https://kcachegrind.github.io/html/Home.html) to do some performance analysis, e.g. to identify bottlenecks. It uses [Valgrind](https://valgrind.org/) under the hood.
> 
> To be frank, I would expect some profiling to be done for a merge that claims to improve performance.

I already did this in #6985.

**Comment by michaelgregorius** [comment]
> I already did this in #6985.

Oh, sorry. I interpreted the previous quote as that you didn't know how to measure when I fact you do.

**Comment by sakertooth** [comment]
> Oh, sorry. I interpreted the previous quote as that you didn't know how to measure when I fact you do.

Yeah, my previous quote was more about not understanding how slow things were relatively speaking because of the speed of my laptop. What's takes a couple seconds for me might take a couple of minutes for someone else, even if there was still a performance drop on my side.

**Comment by SalutanisOrkonus** [comment]
Well the search is certainly quicker, but also essentially non-functional. The search doesn't just show direct results to your search, but literally everything else in the folders and subfolders even tangentially related.
Here I searched "120" and every single sample in my drumloops folder showed up, instead of just ones labelled 120 or in folders named 120.
![image](https://github.com/LMMS/lmms/assets/65266122/2b4395d4-ede9-4fa5-a71d-7c4af9af6d7a)
also, another example, the entirety of huge sample packs show up cuz I guess there's probably a single file somewhere in there with "120" in the title 
![image](https://github.com/LMMS/lmms/assets/65266122/0ea4b9ef-ea3f-418e-adf9-4006297f2e82)
Also, the organization of root folders is weird, my drumloops folder would usually be at the bottom if other folders had results, but now it's at the top. and there's just no organization on the others where before I'm pretty sure it was just organized by the order of how they are when there's no search

**Comment by sakertooth** [comment]
> Well the search is certainly quicker, but also essentially non-functional. The search doesn't just show direct results to your search, but literally everything else in the folders and subfolders even tangentially related.
Here I searched "120" and every single sample in my drumloops folder showed up, instead of just ones labelled 120 or in folders named 120.

Yeah, there was an issue with the population of directories I didn't fully fix. Everytime you expand or collapse a directory, LMMS will add files/subdirectories automatically, so I had to override that behavior. I actually just fixed it as you mentioned this in the latest commit of #6985.

> Also, the organization of root folders is weird, my drumloops folder would usually be at the bottom if other folders had results, but now it's at the top. and there's just no organization on the others where before I'm pretty sure it was just organized by the order of how they are when there's no search

I didn't add any sorting for the directories as I wanted the most performance, but since the view gets updated in small batches, the performance difference should be minimal. I'll add it in.

I'll update you when I fixed the sorting issue if you would want to test again.

**Comment by sakertooth** [comment]
Okay, forgive the repetition if you can, but the concerns you mentioned should be addressed [now](https://lmms.io/download/pull-request/6985#windows). I will merge a bit later if you don't have any other objections (unless I missed something).

**Comment by sakertooth** [comment]
Another important thing to mention is that because the search results are processed in individual batches, searching the overall search result is not easy.

**Comment by sakertooth** [comment]
Any chance you could do another test with [this build](https://lmms.io/download/pull-request/6985#linux) so I can merge #6985 @SalutanisOrkonus?

**Comment by SalutanisOrkonus** [comment]
To be fully honest, I would rather it just work like it did before that one push, because it just worked better there, but if that's not an option then I guess this works enough. The organization of results is still a little weird but better (seems to be alphabetical, which tbh it's a bit weird that the normal organization isn't, completely.)
