### ISSUE TITLE
Update Linux CI to support Ubuntu 20.04

### ISSUE THREAD

**Issue by messmerd** [LMMS/lmms#6993]
### Enhancement Summary
The Docker image at https://hub.docker.com/r/lmmsci/linux.gcc only offers Ubuntu 18.04 (Bionic) as the latest version, but Ubuntu 20.04 (Focal) is now needed.

Ubuntu 22.04 (Jammy) would also be nice to have, since we will probably need it before long, but it isn't strictly necessary right now.

#### Justification
- Bionic reached the end of its LTS support in May 2023
- The out-of-date `g++` and out-of-date packages of Bionic are starting to impede LMMS development

**Comment by messmerd** [comment]
@lukas-w It looks like you've updated our Docker images in the past. Do you think you could work on this?

**Comment by lukas-w** [comment]
> @lukas-w It looks like you've updated our Docker images in the past. Do you think you could work on this?

I'd love to, but I likely won't find the time until next year. The Dockerfiles are at https://github.com/LMMS/lmms-ci-docker, in theory they should automatically build and push but I don't know it that's still working.

> If you can, maybe you could also invite me to be a member on the `lmmsci` Docker Hub organization

I think we can just change it to use ghcr.io instead which you should already have access to. That simplifies permission management and it could also come with a speed benefit when pulling the images.

Note that this setup predates the use (and existence IIRC) of ghcr.io and GitHub Actions. It was meant as an optimization for installing dependencies on CircleCI because they only offered Docker Layer Caching as a premium feature. That may not be needed on Actions anymore, or it may not be worth it if it hinders our ability to upgrade dependencies. So feel free to replace it if you come up with a better solution. :beers:

**Comment by messmerd** [comment]
What are the steps I'd need to take to build a `lmmsci/linux.gcc:20.04` Docker image manually so that I could upload it to ghcr.io?
