### ISSUE TITLE
(Enhancement) Record pitch/mod wheel WHILE recording keyboard playing

### ISSUE THREAD

**Issue by artao** [LMMS/lmms#702]
I searched with no results, so forgive me if this has been brought up. I also didn't see it on the roadmap.
I'm aware that automation recording has now been implemented and will be in v1.1 .. and that is AWESOME!!
Now I'm wondering two things:
1) As per the thread title. .. I feel this is pretty important, since the pitch/mod wheel are intimately related to the actual at-keyboard performance. I'm talking about recording these along with the keyboard in the piano roll here. The piano roll already records velocity I see, so I'm hoping that adding these two in as well won't be that difficult.

2) Regarding automation recording. Will this be just one knob/slider at a time, or will we be able to record any arbitrary number of knobs/sliders/controls at once? Recording any arbitrary number would be awesome-sauce and ever so useful. .. Take the simple and common following useage: Controlling cutoff and resonance at the same time. Since these two controls are almost always used together, it would be most efficient and useful if both could be simultaneously recorded .. rather than recording one, then going back over the track to record the other (repeat for however many controls the user wants automated for any given instrument) ... that can rapidly become tedious, and thus can cause the performance to lose enthusiasm and coherence.

That's all from me for now.
Thanks for LMMS. I'm really loving it. With a few feature upgrades it can truly be a professional-level tool. =D

**Comment by davetbass2** [comment]
Hi, Sorry if I'm not doing this correctly but, can this be reopened?

Mod wheel movements can not be recorded and played back in Vestige.

Thanks!
Dave

**Comment by tresf** [comment]
@davetbass2 is there a chance there is overlap with https://github.com/LMMS/lmms/issues/1472?

**Comment by davetbass2** [comment]
Hi tresf thanks! I think the mod wheel issue itself might have gotten a little lost, I looked through all the numbers under: 
MIDI modulation wheel, sustain pedal and expression pedal support
the closest one was:
https://github.com/LMMS/lmms/issues/1917
this has been closed.
I couldn't find a separate open issue on recording and playing back Mod Wheel movements for VSTs
If a mod wheel knob was added to the front of Vestige, it could be dragged to the automation track like I do with the pitch bend wheel.
To me this would be one of the most import MIDI enhancements (not just because I suggested it haha) but because it would allow the use of both of the basic synth performance tools.

Right now we can only use pitch bend, exept for the very rare case where the VST has a "mod wheel" knob in the wrench section.

Thanks alot for all your help, this one addition would be a huge leap in usefulness

**Comment by tresf** [comment]
@davetbass2 is the mod wheel movement not part of the missing MIDI messages?  I guess what I'm asking is, is this a standard MIDI feature that works fine on other items but is simply missing from the VST plugin?

**Comment by davetbass2** [comment]
Hi thanks again for quick response! because I don't know enough about MIDI, I'll try to explain what I'm trying to do, and hopefully there is a easy MIDI answer

The mod wheel works when I'm playing the synth, but the mod wheel movements can't be recorded and played back using the automation tracks

The pitch bend can be recorded and played back using the automation tracks, by dragging the pitch knob on the front of Vestige into the automation track, enabling record.

Hope that helps, thanks!

**Comment by tresf** [comment]
@davetbass2 I think that is the problem... the MOD wheel is expected to have a knob in order to be recordable and if the plugin doesn't offer it, we can't automate it.

So it sounds like MOD should be visible regardless of whether or not the plugin offers it, which I think is part of LMMS having better support for capturing all MIDI messages.

@softrabbit do you have any feedback on this conversation?

**Comment by davetbass2** [comment]
Thanks, you have stated the answer clearly when you said:
"MOD should be visible regardless of whether or not the plugin offers it"
That would solve it from my point of view as a player.

Thanks again!

**Comment by tresf** [comment]
@davetbass2 right, I guess I just don't know if the placeholder bug report covers that with the blanket "all midi messages" statement or if perhaps this is important enough to just tackle on its own.  Thanks for the feedback.

**Comment by curlymorphic** [comment]
> "MOD should be visible regardless of whether or not the plugin offers it"

Agreed, and sustain and expresion. 

I am not sure if our internal synths support these features? But this is a must for plugins.

maybe this crosses over with #1965

**Comment by davetbass2** [comment]
Awesome, thanks again guys looking forward to it,

Is there anyway I could help? I'm not a programmer, but I have done some bug reporting and testing in my real job (accounting)

**Comment by tresf** [comment]
Often 50% legwork for a bug can be the research.  If you can get the technical details on the mod wheel stuff and help find a good place in the GUI for it, you might get someone with the technical skills to hack it in.

**Comment by davetbass2** [comment]
Thanks, 
I think this could be modeled on the existing PITCH knob that is in VeSTige

it works for every VSTi and is linked to the Pitch Wheel of my controller, however I have found out that the Pitch Wheel is a dedicated MIDI controller and doesn't have a MIDI CC number

A MOD knob could be added next to the PITCH knob on the GUI and linked to MIDI CC 1?

Sorry, this is probably obvious and not helpful, do we know who created VeSTige?
They probably know already the technical details

Thanks!

**Comment by Wallacoloo** [comment]
> Sorry, this is probably obvious and not helpful, do we know who created VeSTige?

According to the Vestige.cpp [source](https://github.com/LMMS/lmms/blob/fe797cb09fb897ade99bacdb014fc6fb97af6583/plugins/vestige/vestige.cpp#L4), it was Tobias Doerffel (he goes by tobydox on Github).

**Comment by davetbass2** [comment]
Cool thanks! I didn't really that was there, i guess I could buy "Learn C++ in 24 hours" and do it myself haha

**Comment by davetbass2** [comment]
@tobydox, Hi, sorry if this is not the best way to ask you this, but if I understand it you wrote Vestige?

Is the suggested enhancement (adding a Mod Wheel knob to the front of Vestige to enable recording and playback of mod wheel movements for all VSTis) something that would be fairly straightforward, if it was modeled after the way the PITCH knob on Vestige works?

Thanks!
Dave

**Comment by davetbass2** [comment]
Sorry, I might be missing something obvious, but over at the KVR forum the guy who made the PG8X

"Any host which can record MIDI should be able to record the Mod Wheel."

So am I just missing something really obvious? again, all I'm trying to do is play a synth line with pitch and mod wheel movements, and then when the song is played back the pitch and mod wheel movements are still there.

Thanks, sorry if this was a wild goose chase

http://www.kvraudio.com/forum/viewtopic.php?f=1&t=310856&sid=1a1239efadc482d34fa1654cd5c1bf9a&start=1800

**Comment by Sti2nd** [comment]
> "Any host which can record MIDI should be able to record the Mod Wheel."

Does that mean that if you implement MIDI record you automatically achieve functionality to record mod wheel, or is it a statement that he thinks all software should have both...

**Comment by tresf** [comment]
> the Pitch Wheel is a dedicated MIDI controller and doesn't have a MIDI CC number

Right, I think this is the exact issue, better explained in #1159

> "Any host which can record MIDI should be able to record the Mod Wheel."

Well, I think it is obvious by the vast number of bug reports that we have some area to improve here. :+1:   Thanks for taking the time to explain.

Since we have this on our radar including most of the technical details, it is just a matter of getting someone to help code it in.  It's on the list. :+1: 

![image](https://cloud.githubusercontent.com/assets/6345473/7430035/cf00d040-efda-11e4-84ec-d8a28b05f3d1.png)


-Tres

**Comment by davetbass2** [comment]
Sounds good man, again, me and alot of people really appreciate the time you guys put into make this work, and hopefully by bugging you guys I'm doing my part haha!

I noticed MIDI pitch bend support is up there, but as far as recording pitch bend movements, we can do that now by dragging PITCH from vestige into an automation track and enabling record

Could a shot term fix be adding MODWHEEL knob next to PITCH on Vestige, with similar C++ wizardry behind it? (I knew I should have stuck with C in college, 2 semesters ain't enough haha)
