### ISSUE TITLE
Program denies validity of most audio formats in internal browser popup

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#7031]
### Bug Summary
When using the load sample prompt on basically anything, only available audio files are .ds and .aiff. Surprisingly the samples added from sidebar still are fine and even load right.
#### Steps to reproduce
Place audio-using internal plugin (AudioFileProcessor, SlicerT, Ect), click sample load button, grieve,
#### Expected behavior
All usual available sample formats show (and hopefully eventually mp3 too but who knows when that'll work right)
#### Actual behavior
Only shows .ds and .aiff. what even is .ds, who uses that.
#### Screenshot
![image](https://github.com/LMMS/lmms/assets/65266122/2603f8a3-2382-4771-8e7c-9d5e0cfeebb3)

#### Affected LMMS versions
1.3.0-alpha.1.489+g4e63f6065

**Comment by sakertooth** [comment]
> Only shows .ds and .aiff. what even is .ds, who uses that.

`.ds` is for DrumSynth. You can read more about it [here](http://fileformats.archiveteam.org/wiki/DrumSynth_Preset). Our factory samples come with a lot of DrumSynth files.

As for the issue, I think if you are using the builds we provide, the library we are using to load/handle audio files (sndfile) is very outdated on them and so the format list isn't updated to support other formats, even though the library technically does support them. This is partly an assumption, but it is very likely that this is the case.

We might have to maintain our own list with the supported formats, but that comes with its own maintenance problems, since we would have to enable specific ones depending on the version of sndfile used. I don't see any other way though, since sndfile never had a good consistent way to get all the supported formats.

**Comment by messmerd** [comment]
@SalutanisOrkonus Which OS are you on? That will help us know what sndfile version you're using

**Comment by SalutanisOrkonus** [comment]
Windows 10 64-bit

**Comment by musikBear** [comment]
> SlicerT, Ect

 You are using **Nightly**
 That is not bugfree
That 'Open' button is not part of **normal workflow**:
Open side-bar
Select Samples
Browse to a soundfile in that folder
Either drag or rightclick it to load it in AFP
In Sample-track
1.3 correctly shows all supported filetypes
![image](https://github.com/LMMS/lmms/assets/6662066/4a63bbf1-468c-4252-9fe5-d5e52b7f2754)
Nightly should never be used for production!

**Comment by SalutanisOrkonus** [comment]
im aware nightly is not bugfree that's why i'm reporting the bugs
