### ISSUE TITLE
LMMS Project Files Don't Show LMMS Icon

### ISSUE THREAD

**Issue by DarkFlameSquirrel** [LMMS/lmms#706]
This isn't a huge issue or anything, it just bugs me a bit.
I'm running 64-bit Windows 7 Ultimate.
Screenshot below.
![icon problem](https://cloud.githubusercontent.com/assets/7545448/2939184/4d53d68e-d93b-11e3-8244-bdc35f40eb05.png)

**Comment by Umcaruje** [comment]
@DarkFlameSquirrel can you reproduce this issue with a fresh install of LMMS 1.1.3?

**Comment by Wallacoloo** [comment]
Umcaruje: `# make install` does not configure file associations or file
icons for me on Ubuntu 15.04 / Xfce.

However, I am unsure if it's supposed to configure those, or if that's the
job of a .deb file.

**Comment by tresf** [comment]
> Umcaruje: `# make install` does not configure file associations or file icons for me on Ubuntu 15.04 / Xfce.

Yeah, the OP is using Windows, so this bug can't really can't be applied to other platforms or any other installers.

We likely won't ever do registration at `make install` time because `make install` is generally a command only developers (or *nix hobbyists) would run.  We could entertain a helper script, but it will have overlap with our packagers.  Mac, for example, needs a special [`Info.plist`](https://github.com/LMMS/lmms/blob/master/data/lmms.plist.in).  Windows (which we can't build on currently) needs some [`registry settings`](https://github.com/LMMS/lmms/blob/master/CMakeLists.txt#L600) and Linux file association tends to vary between desktop environments.

Since the OP is using Windows, it is most likely a botched install caused this (or more specifically a install over a version that wasn't uninstalled).  Our installer needs some improvements (which myself or Lukas are capable of since we have some [`NSIS experience finally`](https://github.com/qzind/qz-print/blob/1.9/ant/windows/windows-packager.nsi.in)).  It's just a matter of putting in the proper steps for cleanly and sanely uninstalling before reinstalling.

Short story long, we just need a better Windows uninstaller (and possibly Linux too https://github.com/LMMS/lmms/issues/1676). 

For now, purge LMMS and reinstall per https://github.com/LMMS/lmms/issues/2077#issuecomment-106180485.  Reopen if you can reproduce after a purge and we should open a separate ticket for the NSIS stuff. ;)

-Tres

**Comment by Umcaruje** [comment]
:+1:
