### ISSUE TITLE
Ability to see what sample is loaded in SlicerT

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#7060]
### Enhancement Summary
SlicerT, great addition! One problem, though. Occasionally I like going through my projects and writing down what I used in each, SlicerT makes this a bit difficult though, because unless I'm missing something, there's nowhere it tells you what sample the instance has loaded.
#### Justification
It would make working with it a bit easier. Remember a drumloop you used in SlicerT in an old song you wanna use again, but don't remember where it is or what its called? This would make it a LOT easier to find it again.
#### Mockup
I'm no UI designer, so I don't actually know specifically how to go about it. I'd say something like "Click the SlicerT logo in the middle to pull up the sample select popup window", but that doesn't actually work and show you where what's selected is half the time for some reason, so if you wanna do it that way you'd have to fix that problem.

**Comment by zonkmachine** [comment]
I'm also not into UI design but this could need some attention. Maybe the file name of the loaded sample could be shown in the top of the seeker window? @DanielKauss Maybe, when you find some time, you would like to look into this?

**Comment by thismoon** [comment]
for now you can find the paths of all the slicerT instruments in a project using this command
```sh
lmms -d "project.mmpz" | grep '<slicert' | grep -Po 'src="\\K.*?(?=")'
```
(if it starts with `usersample:` that's your default samples folder)

here's a simple UI mockup i made inspired by the sample track:
![mockup 1](https://github.com/LMMS/lmms/assets/107642606/e3fe565c-0002-45a3-92f5-c7ed7d989f9a)
here's another more complex mockup that changes the layout of the plugin by adding a button to select a sample since it's absent too:
![mockup 2](https://github.com/LMMS/lmms/assets/107642606/fc50838c-736d-46c1-b79e-684f5e6ac457)
some other changes that i suggest:
- change the copy midi icon to make its purpose clearer
- set the instrument name to the sample file name when loaded (like audiofileprocessor)

**Comment by RoxasKH** [comment]
I'm sorry i haven't noticed this issue until now.

Actually this was being worked by someone, and i made an UI for it which i posted on Discord 3/4 months ago, which is also reflected in the art resource file i've pushed for this PR on the artwork repo (https://github.com/LMMS/artwork/pull/22).
I'm believing this someone either dropped it or well spaused the work on it for a long time.

Not knowing about an open issue, i didn't mirror post it on github.

Anyways, here it is:

| Before | After |
|---|---|
| ![before](https://cdn.discordapp.com/attachments/332258319228207114/1207823233420754944/slicert2.png?ex=6662e7cb&is=6661964b&hm=86e6908741a148eb2622630c2c0c4e430f4e7718af4126ff2c29d624d2e7ff68&) | ![after](https://cdn.discordapp.com/attachments/332258319228207114/1207823233659707452/slicert3.png?ex=6662e7cb&is=6661964b&hm=392fb017f6ee0aaa2da43f1a90d598ab96cc91bb6e17002c9add4aa0c370ec75&) |

P.S: If anyone needs the discord message link to check the discussion about it here it is (https://discord.com/channels/203559236729438208/332258319228207114/1207823233890386020)
