### ISSUE TITLE
program crash when zooming in on sample in audiofileprocessor

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#7068]
### Bug Summary
the program crashes when you move the points on an audiofileprocessor sample and zoom in
#### Steps to reproduce
move one of the points (start or end, ive been doing end) and then zoom in
#### Expected behavior
it's fine
#### Actual behavior
crash
#### Affected LMMS versions
1.3.0-alpha.1.511+g1e6a902dd

**Comment by michaelgregorius** [comment]
I was able to reproduce this and got the following stack trace:
```
std::accumulate<float const*, float>(const float * __first, const float * __last, float __init) (/usr/include/c++/13.2.1/bits/stl_numeric.h:141)
lmms::gui::SampleWaveform::visualize(lmms::gui::SampleWaveform::Parameters parameters, QPainter & painter, const QRect & rect) (/home/michael/Eigene Dateien/Development/LMMS/lmms-dev-mg/lmms/src/gui/SampleWaveform.cpp:59)
libaudiofileprocessor.so!lmms::gui::AudioFileProcessorWaveView::updateGraph(lmms::gui::AudioFileProcessorWaveView * const this) (/home/michael/Eigene Dateien/Development/LMMS/lmms-dev-mg/lmms/plugins/AudioFileProcessor/AudioFileProcessor.cpp:1018)
libaudiofileprocessor.so!lmms::gui::AudioFileProcessorWaveView::update(lmms::gui::AudioFileProcessorWaveView * const this) (/home/michael/Eigene Dateien/Development/LMMS/lmms-dev-mg/lmms/plugins/AudioFileProcessor/AudioFileProcessor.h:229)
libaudiofileprocessor.so!lmms::gui::AudioFileProcessorWaveView::mouseMoveEvent(lmms::gui::AudioFileProcessorWaveView * const this, QMouseEvent * _me) (/home/michael/Eigene Dateien/Development/LMMS/lmms-dev-mg/lmms/plugins/AudioFileProcessor/AudioFileProcessor.cpp:853)
libQt5Widgets.so.5!QWidget::event(QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QApplicationPrivate::notify_helper(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QApplication::notify(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Core.so.5!QCoreApplication::notifyInternal2(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Widgets.so.5!QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) (Unbekannte Quelle:0)
libQt5Widgets.so.5![Unknown/Just-In-Time compiled code] (Unbekannte Quelle:0)
libQt5Widgets.so.5!QApplicationPrivate::notify_helper(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Core.so.5!QCoreApplication::notifyInternal2(QObject*, QEvent*) (Unbekannte Quelle:0)
libQt5Gui.so.5!QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) (Unbekannte Quelle:0)
libQt5Gui.so.5!QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) (Unbekannte Quelle:0)
libQt5XcbQpa.so.5![Unknown/Just-In-Time compiled code] (Unbekannte Quelle:0)
libglib-2.0.so.0!g_main_context_iteration (Unbekannte Quelle:0)
libQt5Core.so.5!QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (Unbekannte Quelle:0)
libQt5Core.so.5!QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (Unbekannte Quelle:0)
libQt5Core.so.5!QCoreApplication::exec() (Unbekannte Quelle:0)
main(int argc, char ** argv) (/home/michael/Eigene Dateien/Development/LMMS/lmms-dev-mg/lmms/src/core/main.cpp:1018)
```

The crash occurs in the `accumulate` statement in [line 59](https://github.com/LMMS/lmms/blob/1e6a902dd32e9bf4dbf57e17913bdd67acecfaad/src/gui/SampleWaveform.cpp#L59) of `SampleWaveform::visualize`.

**Comment by michaelgregorius** [comment]
Quickest way to reproduce:
1. Add an AFP and open it's view.
2. Drag a sample onto the sample view of the AFP, e.g. `drums/clap01.ogg` from the factory samples.
3. Click with the left mouse button on the sample display and drag to the right until the crash occurs.

**Comment by musikBear** [comment]
> 2\. clap01.

No crash in 
![image](https://github.com/LMMS/lmms/assets/6662066/52a84222-0169-461d-af77-2fb741d707f1)
not even in replay when mouse-dragging.
The issue must be newer
Nb i have _disabled_ "showing play in AFP" in Settings

**Comment by michaelgregorius** [comment]
## Finding the problem
The problem is caused in `AudioFileProcessorWaveView::slide`. It can be best investigated by adding the following private methods:
```
void AudioFileProcessorWaveView::setTo(f_cnt_t to)
{
	assert (to <= m_sample->sampleSize());
	m_to = to;
}

void AudioFileProcessorWaveView::setFrom(f_cnt_t from)
{
	assert (from >= 0);
	m_from = from;
}
```

Then replace direct assignments to `m_to` or `m_from` with calls to these methods. Replace the methods that increment by `step` with:
```
//m_from += step;
setFrom(m_from + step);
//m_to += step;
setTo(m_to + step);
```

You will find that at a certain point a negative step is added to `m_from` with value 0.

## Alleviating the problem
The problem can be alleviated by replacing the `setTo` and `setFrom` implementations with the following ones:
```
void AudioFileProcessorWaveView::setTo(f_cnt_t to)
{
	m_to = std::min(to, static_cast<lmms::f_cnt_t>(m_sample->sampleSize()));
}

void AudioFileProcessorWaveView::setFrom(f_cnt_t from)
{
	m_from = std::max(from, 0);
}
```

I am not really sure if that's the real solution though because the sample view and the controls of the AFP behave very strange if you zoom in.

By the way, is the behavior intended to be a zoom action or something else? I am asking because with the changes described above I cannot zoom out.

## Introduction of a Range object
It might make sense to introduce something like a `Range` object which would have the members `m_from` and `m_to` and that would provide operations on these values like for example safe setters as described above and calculating the range (from - to), etc.

**Comment by michaelgregorius** [comment]
Hi @sakertooth! Should I create a pull request for my changes? They would fix the crashes but also mask some of the problems. However, if you wanted to investigate them you could simply add the two assertions back.

Due to the constraints with regards to the boundaries I think it's much cleaner to have the setters anyway.

**Comment by michaelgregorius** [comment]
In my opinion the setters do not feel temporary at all and already improve the code. This very issue shows that it is not safe to directly write computed values to the members if they have constraints that must be met. So in my opinion the setters should have one of the two forms mentioned in my previous comments:
* Setting the member without any checks but with an assertion or
* making sure that the values are bounded correctly.

The reimplementation can be done independently of these changes. Like I said, if we go with the second implementation you can temporarily add the assertions back to find out whenever one of the computations creates problematic values.
