### ISSUE TITLE
[Suggestion] Per-note Highpass/Lowpass cutoff

### ISSUE THREAD

**Issue by DarkFlameSquirrel** [LMMS/lmms#708]
Sort of like the way velocities is done, except this could control the cutoff amount.

**Comment by Umcaruje** [comment]
@DarkFlameSquirrel can you further explain this request of yours?

**Comment by Spekular** [comment]
I'd imagine the idea is to have the filter cutoff relative to the note so
yoi can cut off the same "part" of each note. Imagine low passing a melody
that spans an octave, your highest notes will sound very filtered whereas
the lowest ones might not be filtered at all.

@DarkFlameSquirrel you probably already know this but at the moment the
best workaround is automating the pitch.

**Comment by michaelgregorius** [comment]
I think what might help @DarkFlameSquirrel the most would be the implementation of a modulation matrix for the internal instruments. This way it would for example be possible to directly map the MIDI velocity to the filter cutoff. An example of this can be seen here:
https://www.youtube.com/watch?v=uA2r0dETsvg

The first mapping that is performed in the video maps the MIDI velocity to the level of the oscillator. This means that notes with a higher velocity will sound louder whereas note with a lower velocity will sound quieter. The cutoff modulation is done towards the end of the video. As you can hear the louder the note is played the more the filter is opened.

Having something like this would add a lot more expressiveness to the instruments because the modulation can be changed on the fly when playing live as opposed to a simple automation which is static in nature.

However, such a feature obviously would not be trivial to implement.

**Comment by Spekular** [comment]
It would be super cool if there was a right click option on appropriate
values like "per note settings" that would add an additional set of sliders
in the piano roll for that setting. Of course a velocity slider that can be
connected to one or more settings is much more reasonable :S

**Comment by Umcaruje** [comment]
No responce from OP in months, closing. Your ideas sound interesting though, so @Spekular @michaelgregorius please open a new proper issue with this idea, if you think this is something that'd benefit LMMS.

**Comment by michaelgregorius** [comment]
@Umcaruje I have added #2467 as a feature request so the idea does not get lost.

**Comment by Umcaruje** [comment]
@Umcaruje I have added #2467 as a feature request so the idea does not get lost.

:+1:
