### ISSUE TITLE
It's becoming increasingly frustrating to zoom in and out

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#7117]
### Enhancement Summary
Recent push makes it so you can't hover over most of the song editor to zoom (ctrl+scrollwheel), hovering over a track at all resizes it instead. **Maybe track resizing should only happen when hovering over the track button itself?**
_(also this is more of a bug but when zooming, zooming out works fine but it feels like zooming in goes wherever it feels)_
#### Justification
Makes zooming in and out with ctrl+scrollwheel bearable again

**Comment by enp2s0** [comment]
Fully agree. Ctrl-scroll is my main way of interacting with the song editor zoom ever since the 100%-200%-400% combobox was replaced with the slider. losing that means the only way to reliably zoom it is to drag the slider with the mouse which is very cumbersome.

Since my workflow is nearly completely midi-based I don't think I've ever used the vertical resize feature of the tracks, but horizontal zoom is absolutely critical. It's something I interact with several times per minute while editing a song.

**Comment by qnebra** [comment]
I think it could be fixed by adding additional modifier key to resize track. Something like:

Ctrl + Mousewheel = Zoom
Ctrl + Alt + Mousewheel = Track resize

**Comment by Spekular** [comment]
I would say #3763 is relevant here as well. If zoom + modifier is going to be used for a vertical zoom, I'd expect it to apply to all tracks rather than just one.

**Comment by michaelgregorius** [comment]
Sorry, I wasn't aware that the handling of the wheel events in the `TrackView` would mask so many other handlers. I also accidentally accepted every event in the `wheelEvent` method and not only the ones that are actually handled.

Pull request #7118 fixes this. It implements the proposal made [here](https://github.com/LMMS/lmms/issues/7117#issuecomment-1953348720) in that the alt key has to be pressed for the track to resize:
* Alt + Control: Resize track height by one pixel.
* Alt + Shift: Resize track height by five pixels.

All other events bubble up, i.e. zooming and scrolling via control and alt now works again.
