### ISSUE TITLE
Equalizer muting output??

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#7131]
### Bug Summary
When using the equalizer after a recent push, it sometimes mutes the output.
#### Steps to reproduce
Not 100%, but so far I've had it happen seemingly connected to bands 7 &/or 8 (high-end) when messing with the equalizer
#### Expected behavior
Sound continues
#### Actual behavior
Equalizer sometimes decides to permanently mute output
#### Screenshot
![image](https://github.com/LMMS/lmms/assets/65266122/dc33d8e1-ceca-49e4-a0b3-b93e06c0880f)

#### Affected LMMS versions
1.3.0-alpha.1.532+gc991a85ee

**Comment by michaelgregorius** [comment]
@SalutanisOrkonus, can you please provide a test file where the Equalizer is set such that the effect can be observed? It might otherwise be hard to reproduce it with the current report.

**Comment by qnebra** [comment]
Strangely enough, it happen to me. Disabling every "band" in EQ did enable sound back, but it isn't point of EQ to had it completly disabled. Also it affects entire EQ, bands 1 - 8

**Comment by michaelgregorius** [comment]
I cannot reproduce the problem. The example file also has two additional plugins that follow the Equalizer that I do not have available on my system.

Can you also reproduce the problem with only the Equalizer in the signal chain? With the current setup it might also be caused by the plugins following the Equalizer, e.g. due to being fed loud input, etc.

For bug reports it's highly desirable to have minimal setups that reproduce the problem so that as many other factors as possible can be ruled out.

**Comment by PhysSong** [comment]
I guess NaNs are generated somewhere, but not sure.

**Comment by SalutanisOrkonus** [comment]
I can't seem to get a consistent isolated project, but I did record it in action

https://github.com/LMMS/lmms/assets/65266122/97dfcea8-934d-4fba-be60-3a382e70f24c

Very infuriating

**Comment by SalutanisOrkonus** [comment]
I'm somewhat assuming related, sometimes activating a "band" will make a very loud extended click-like sound

**Comment by sakertooth** [comment]
I was able to reproduce this issue with this project:

[a_lot_of_notes.mmp.zip](https://github.com/LMMS/lmms/files/14551470/a_lot_of_notes.mmp.zip)

I got this project from @PhysSong a long time ago for some race condition related issue I think, so thanks to him.

Increase the volume a bit for the TripleOscillator, add a EQ to mixer channel 0, hit play, and mess around with the bands (turning them on/off, moving them around etc) until all the audio becomes muted.

For some reason, the spectrum view doesn't show anything on a Debug build for me, but the actual output can still be heard being muted.

So it turns out that this is a inf/nan related issue. Running a debugger across `EqEffect::processAudioBuffer` unfortunately shows one of our filters outputting NaNs. And we know that when this happens, LMMS mutes all the audio within `MixHelpers::sanitize`. I'm not sure how the sanitation would directly make the display go full purple exactly in the code, but I guess the NaNs are having their own effect on the display.

```cpp
if( para4Active )
{
     buf[f][0] = m_para4.update( buf[f][0], 0, periodProgress );
     buf[f][1] = m_para4.update( buf[f][1], 1, periodProgress );
}
```

This was the code in `EqEffect::processAudioBuffer` I caught that was outputting NaNs.

Also got this in the console, which came from `MixHelpers::sanitize`.

```
Bad data, clearing buffer. frame: 0: value -nan
```

![image](https://github.com/LMMS/lmms/assets/20197645/dd1fd7ae-c3d4-4614-a286-c49d40815699)

Digging further, one of the `BiQuad` filters got a NaN in their channels somehow in `BasicFilters::update`, i.e., breaking there, `m_z1[ch]` returned a NaN. This then affected every other calculation using it upwards.

Hopefully someone can take a look and find a proper solution. I'm not sure how a NaN ended up in one of our filters. I would also like for the sanitize functions in `MixHelpers` to be removed as well, but we need to make sure that NaNs don't pop up in our filters anymore first.

**Comment by michaelgregorius** [comment]
I think I might have found the cause. The coefficients of the `BiQuad` have not been initialized either. Pull request #7141 fixes this problem and some other potential divisions by 0 in the Equalizer context.

I will also create another pull request which will deal with potential NaNs that can occur when dbFS values are calculated/displayed for signals that represent silence. I didn't want to include the changes here because they are not really related to this issue but are just other NaN issues that have been found during investigation.

**Comment by sakertooth** [comment]
Great work @michaelgregorius! :+1:
