### ISSUE TITLE
Plugin release frames depend on sample rate

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#7211]
### Bug Summary

First brought up here: https://github.com/LMMS/lmms/pull/6908#issuecomment-1743279684

When a plugin doesn't use the envelope it still has a fixed number of release frames. Example from Bitinvader:
https://github.com/LMMS/lmms/blob/df11a989021d6452d06a9038b3ea0a9dee9b0e66/plugins/BitInvader/BitInvader.h#L88-L91

The problem with a fixed number of frames for release is that the decay time now will vary with the sample rate as shown in the release below in a project exported with three different sample rates.

![samplerate](https://github.com/LMMS/lmms/assets/6368949/9158fe7c-aa8a-4127-af50-d22d8b03edcc)

### Expected Behaviour

The release time should be the same and independent of sample rate.

From @michaelgregorius in the [same thread](https://github.com/LMMS/lmms/pull/6908#issuecomment-1743524379).
 > It looks like the release should be defined in milliseconds which is then converted into a number of samples based on the sample rate.

**Comment by Rossmaxx** [comment]
Would it make sense to `return 64 * (sampleRate ÷ 44100)` ?

**Comment by michaelgregorius** [comment]
I think it makes more sense to solve the problem by changing the method to something like `desiredReleaseTimeMs`. The underlying problem is that the release time is requested in a unit that's independent of the sample rate, so this problem should be fixed.

If you search for `desiredReleaseFrames` you will find that there are already several overrides. If the method `desiredReleaseFrames` was only adjusted and kept then the problem might creep in later again even it all overrides are adjusted as well. Or put differently: the problem should be fixed in one place where the release time in milliseconds is converted into sample frames. Keeping `desiredReleaseFrames` would mean that the problem had to be fixed in several places with the danger of the aforementioned return of the problem, e.g. in new classes.

For the overrides it should also be checked if the number of frames that are used really make sense or if they haven't just been chosen arbitrarily by the implementers. Another potential explanation for the differences in the implementations might be that the implementation in the base class was changed without taking all the overriding implementations into account.

**Comment by michaelgregorius** [comment]
@zonkmachine, can you please check with the changes of pull request #7217?
