### ISSUE TITLE
Update MinGW CI to 20.04

### ISSUE THREAD

**Issue by Rossmaxx** [LMMS/lmms#7256]
More often than not, the MinGW CI being outdated hampers development in the sense of having outdated libraries. A few PRs can't be merged just because of this outdated CI. 

Though we are discussing on discarding MinGW entirely and moving to MSVC builds on windows, it'll still make sense to have updated mingw ci for the time being till we reach a consensus there. 

Also @tobydox the PPA is severely out of date. Mind bumping all the packages to latest versions?

**Comment by Rossmaxx** [comment]
> I don't think the MinGW builds need to target the oldest Ubuntu LTS like the Linux builds do

Didn't know. Then using 24.04 seems good. 

> GitHub build runners + vcpkg or MXE might be our best long term option for MinGW builds

In that case, i vote for vcpkg as i am a bit familiar with it. Don't know about mxe tho, if mxe is better, then better to consider it.

**Comment by tobydox** [comment]
Rebasing/updating all MinGW packages only makes sense for me if really required in the future. If you plan to migrate away from MinGW anyway, please understand that I don't want to invest the time then ;-) Otherwise I'm happy to support you with updating these packages.

**Comment by Rossmaxx** [comment]
> Rebasing/updating all MinGW packages only makes sense for me if really required in the future. 

Makes sense from a maintainer perspective. I didn't really thought of this. 

> you plan to migrate away from MinGW anyway

Tbh, we didn't really reach a consensus. Tresf is against this move when we discussed on discord. Though the votes are actually in favour of removing.

**Comment by DomClark** [comment]
There's no major advantage to updating to an Ubuntu version later than 20.04 - our Linux builds are tied to that version for another year, so any features in newer versions aren't available to us yet anyway. The main advantage would simply be that we can go for longer without needing to upgrade again. I believe the Linux and MinGW Docker images share a common base, so using the same Ubuntu version may be simpler for now.

As for long-term MinGW use, we don't want to migrate away if we don't have to, but it may be a necessary move. The main obstacle to its use is the completeness of the C++ standard library implementation - a lot of threading-related parts are missing. We have a submodule (mingw-std-threads) that implements some of these missing parts, but it's not comprehensive. The choice right now is between sticking with increasingly outdated technology, or dropping support for MinGW, but the hope is that we find a way to avoid both of these options.

**Comment by Rossmaxx** [comment]
Previously, @sakertooth and @messmerd tried introducing some new features into the codebase and they were hindered by the lack of threading support and incomplete features in the MinGW standard library. They know the issue more than i do so let them tell.

**Comment by messmerd** [comment]
@tobydox The MinGW cross-compiler we use does not implement the C++11 standard threading library (`<thread>`, `<mutex>`, `<condition_variable>`, etc.) even though we are using C++17 now. Those features were deliberately left out of MinGW's standard library, but apparently recent versions of MinGW-w64 include support for it via a Win32 port of pthreads. That's something we should look into. Currently we are forced to use [this repo](https://github.com/meganz/mingw-std-threads) for a partial implementation of those standard library features.

**Comment by messmerd** [comment]
@tobydox It looks like you had an Ubuntu 20.04 MinGW PPA already, but it just wasn't being used:
http://ppa.launchpad.net/tobydox/mingw-w64/ubuntu/dists/focal/

So I rebuilt the MinGW Docker image using it and with some small adjustments, was able to get the CI builds working: #7259

**Comment by sakertooth** [comment]
> MinGW-w64 include support for it via a Win32 port of pthreads. That's something we should look into.

I was looking into this, but couldn't confirm that I can compile using only MinGW (without mingw-std-threads) using their pthreads port. If this is in fact possible, then I don't see the need to drop MinGW. Though, I would think the MinGW version we are at right now would already have this port?

**Comment by tresf** [comment]
> I don't think the MinGW builds need to target the oldest Ubuntu LTS like the Linux builds do, so we could probably target Ubuntu 24.04 instead.

Linux won't have to either, once #7252 is merged.  Finally gets away from that lock-in mindset.  We'll be able to choose whichever LTS target we want.  (and no more Intel lock-in either).

**Comment by FyiurAmron** [comment]
> > MinGW-w64 include support for it via a Win32 port of pthreads. That's something we should look into.
> 
> I was looking into this, but couldn't confirm that I can compile using only MinGW (without mingw-std-threads) using their pthreads port.
@sakertooth
I can confirm it, I did it a couple of days ago. Requires adjusting the headers a bit to drop all the ifology for the `#include <mingw.xyz.h>` from the 3rd party pthreads, but IMVHO it compiles and works as a charm. I'm more than happy to do the PR for that change, I already have the code (and it's quite simple as well) - I did it because `mingw-std-threads` breaks MinGW-on-Windows builds due to incompatibilities in `mingw.future.h` implementation vs `future` from C++, so IMVHO dropping `mingw-std-threads` is the way to go (especially taking into account the spamming pragmas in the build process :D). Create a proof-of-concept PR is https://github.com/LMMS/lmms/pull/7283 , it obviously would benefit from additional testing etc.

>If this is in fact possible, then I don't see the need to drop MinGW. Though, I would think the MinGW version we are at right now would already have this port?

MinGW has it for a long time already, if you choose POSIX model (see https://stackoverflow.com/questions/17242516/mingw-w64-threads-posix-vs-win32 for details). The files are provided by https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-libraries/winpthreads/ , and the exposure via C++ header is also kinda ancient. I know for sure that it worked for me out-of-the-box for at least two years now, and probably worked properly well before that.

The LMMS CI docker would have to be updated, though. I'm going through temporary fixes downstream ATM in the GH action to showcase what needs to be done to switch to POSIX model (which IMVHO should be the default in cross-platform build anyway). If you want, I can submit the relevant PR to LMMS CI repo as well as soon as I finish that.

BTW, if you guys are considering dropping first-class MinGW support for any reason, I'm more than happy to help with it. IMVHO maintaining it doesn't really take that much effort vs regular Linux build, and I've been using MinGW to build native (no dedicated MinGW support) Linux and Windows apps for long enough to see the value in it, even if just for myself.

**Comment by FyiurAmron** [comment]
@messmerd 
> I don't think the MinGW builds need to target the oldest Ubuntu LTS like the Linux builds do, so we could probably target Ubuntu 24.04 instead.
I second this. Without going for an update to a recent-ish LTS, it's a dep hell forever, due to having to conform to severely outdated libs. Mind me, even 24.04 has some delay with many of the packages, sometimes a year or two... With 20.04, it's about 5 years of delay vs bleeding edge deps ATM I'd say.

**Comment by messmerd** [comment]
@tobydox Hello again! I was wondering what steps you take to create the MinGW packages. Do you have a script you use, or do you just build and package everything manually from source?

**Comment by tobydox** [comment]
Indeed I update them manually by replacing the source tarballs etc. and bumping the version / adjusting the debian files.

**Comment by messmerd** [comment]
@tobydox Any chance you could send me the script or commands you use for rebuilding the dependencies? At least for Qt?

My goal is to create a repo containing scripts for downloading sources, building, and packaging all the MinGW dependencies, so if you had anything that could help toward that goal, I'd really appreciate it.

**Comment by tobydox** [comment]
Actually there are no scripts. There are source tarballs and diff.gz files (containing all relevant Debian packaging files) at https://launchpad.net/~tobydox/+archive/ubuntu/mingw-w64/+packages which you can simply download and use for rebuilding :-)
