### ISSUE TITLE
Drop 32 bit support from CI. 

### ISSUE THREAD

**Issue by Rossmaxx** [LMMS/lmms#7286]
Moving this here from #6614 to keep the discussion seperate. 

Original discussion here : https://github.com/LMMS/lmms/issues/6614#issuecomment-2122862110

TLDR: Me and @tresf were arguing about removing first class 32 bit support and looks like removing 32 bit support is not really an issue as it's obsolete tech which has started to weigh down the already constrained dev resources.

**Comment by Rossmaxx** [comment]
Would be helpful if @DomClark and @PhysSong drop their tidbits here.

**Comment by DomClark** [comment]
What dev resources is it weighing down? If this is specific to the Qt 6 migration, then we simply only add 64-bit Qt 6 jobs. I'm not sure that we gain anything by removing the existing 32-bit Qt 5 jobs.

**Comment by Rossmaxx** [comment]
This argument seems legit too. We'll keep Qt6 64 bit only and use Qt5 for both 32 and 64 bit builds.

**Comment by FyiurAmron** [comment]
@DomClark

>I'm not sure that we gain anything by removing the existing 32-bit Qt 5 jobs
It has been said, but I'll reiterate: it's basically only about having 64-bit Linux doing a MinGW 32-bit Windows build. Nothing else would be dropped AFAIU/K.

>What dev resources is it weighing down?
Time and effort of anyone wanting to maintain and/or update the CI pipelines or numerous dependencies we don't have up-to-date ATM, for one. LMMS is terribly outdated in many areas right now, and reducing the tech debt would require going through that one way or another.

I'm biased on this one, because in my day job (corporate setting) a lot of my effort goes into maintenance of things that nobody really needs. 32-bit Windows builds of a normal software app are exactly this in my book. 64-bit Windows are available since Windows XP in 2003. We're talking about _more than 20 years ago_. Vendors which didn't stop 32-bit support are doing so right now. Ubuntu stopped AFAIR at 18.04. for Windows it's planned in 2025. Same with drivers and everything else. Of course, you will be still able to run 32-bit apps... but why should we additionally build 32-bit apps for 64-bit systems? I see no point.

Like I said, I already seen build problems for 32-bit MinGW when trying to update. That's the only 32-bit platform that is currently supported as first-class citizen on LMMS. It's also, arguably, the least used.

>If this is specific to the Qt 6 migration, then we simply only add 64-bit Qt 6 jobs.

It's not specific to Qt 6 migration, it's related to it though. However, as a side note, I'd say that having both Qt 5 and Qt 6 in parallel OTOH seems like a great way to make future UI work exceedingly tedious, in all respects (bugfixing, adding new features, you name it).

<sub>
My final 5c on this: many a good OSS project died due to either feature creep or scope bloat. I honestly hope LMMS won't be one of them, because I really like many things about it, and having to maintain yet-another-fork is something I vehemently disdain.
</sub>

**Comment by tresf** [comment]
> What dev resources is it weighing down? If this is specific to the Qt 6 migration, then we simply only add 64-bit Qt 6 jobs. I'm not sure that we gain anything by removing the existing 32-bit Qt 5 jobs.

I agree, it's not weighing us down; I think @Rossmaxx took some generous liberties of inference from this https://github.com/LMMS/lmms/issues/6614#issuecomment-2122862110.

That said, I do think 32-bit support should be removed from the downloads area moving forward.  I do not believe 32-bit builds have a reasonable purpose there.  And over time, I believe ARM64 downloads will be more helpful to users.

**Comment by Rossmaxx** [comment]
I have opened https://github.com/LMMS/lmms.io/pull/389 as a first step.

**Comment by tresf** [comment]
> I have opened [LMMS/lmms.io#389](https://github.com/LMMS/lmms.io/pull/389) as a first step.

The title of this PR is:

> Drop 32 bit support from CI.

However, the proposed solution at https://github.com/LMMS/lmms.io/pull/389 is to remove them from showing. This step seems unnecessary as it'll happen automatically once we stop building them.  I've left the same sentiments over there, since some people may not read both bug trackers.

**Comment by Rossmaxx** [comment]
#7619 is the proper fix. Took a bit long but here I am.

**Comment by tresf** [comment]
Some additional context... If you look at https://api.github.com/repos/lmms/lmms/releases, you can see exactly how often 32-bit Windows downloads vs. 64-bit Windows downloads are being used.  The rates are much higher than I would have expected:

Alpha:

| 32-bit | 64-bit | % (32-bit)  |
|-------|--------|---|
| 110,533 | 246,450 | 44% |

Stable:

| 32-bit | 64-bit | % (32-bit) |
|-------|--------|-----------|
| 787,107 | 2,291,802 | 34% |

... I'm not sure why the increasing rate (due to historical support of 32-bit OSs, I would expect stable releases to have higher 32-bit download rates).

One possible cause is that the alpha releases may be suffering performance or stability issues that users are more likely to try the 32-bit installer to remedy, since -- in 2024 on Windows -- 64-bit OSs can still run 32-bit installers just fine.

This does shed some credibility to @Rossmaxx's recommendation to place a warning on the downloads once removed, which is mentioned here:
* https://github.com/LMMS/lmms.io/pull/389/files

Side-note: @Rossmaxx please rename the above PR to more accurately reflect what it's doing.

**Comment by FyiurAmron** [comment]
> Some additional context... If you look at https://api.github.com/repos/lmms/lmms/releases, you can see exactly how often 32-bit Windows downloads vs. 64-bit Windows downloads are being used. The rates are much higher than I would have expected:

The reason might be dead simple. Many people don't know they can or should use 64-bit one, they just click "32-bit" because it worked for them in the past years... people often just click the first download that's "good enough" for them, and don't think about it later on.

This seems more plausible if you take into account that 32-bit LMMS still works just fine on 64-bit machines AFAIK :)

**Comment by tresf** [comment]
> The reason might be dead simple. Many people don't know they can or should use 64-bit one, they just click "32-bit" because it worked for them in the past years...

Yeah, occam's razor, but the upward trend is still alarming.  I agree, time will tell.

**Comment by Rossmaxx** [comment]
> Side-note: @Rossmaxx please rename the above lmms.io PR to more accurately reflect what it's doing.

I thought i should have done that. Forgot about it. On it.
