### ISSUE TITLE
Beat Baseline Visualization in Song Editor

### ISSUE THREAD

**Issue by OwusuOnyankoponwoho** [LMMS/lmms#7330]
### Enhancement Summary

In Lmms 1.2 You can Make a Drum Pattern without Going to the beat baseline 
but in the 1.3.0 alpha it does not do that anymore

![Old Version](https://github.com/LMMS/lmms/assets/173246292/4d45ee55-b759-4d7b-b9d4-aa218610fa4f)
![New Version](https://github.com/LMMS/lmms/assets/173246292/36569742-9bfe-4bfd-be64-6450c53c4d26)

### Implementation Details / Mockup

That feature help me a lot because It help me Start Making Patterns Easily
Because It Just like Draging You Sample in to the song editor and start making patterns   
So I will be very happy If you Bring That Feature Back Again

And I also think it make Lmms More unique from other DAWs

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Rossmaxx** [comment]
Like me and roxas said on discord, you are among the very few who is asking to add this feature. 

I remember saying a workaround on discord (I did say to someone yesterday and i believe it's you). If not, I'll send it here.

@Spekular is the one who removed it. Any way we can add a settings entry to expose the hidden flag?

**Comment by OwusuOnyankoponwoho** [comment]
> Like me and roxas said on discord, you are among the very few who is asking to add this feature.
> 
> I remember saying a workaround on discord (I did say to someone yesterday and i believe it's you). If not, I'll send it here.
> 
> @Spekular is the one who removed it. Any way we can add a settings entry to expose the hidden flag?

yes it was me

**Comment by Spekular** [comment]
As explained on Discord, setting the `legacysebbeditor` attribute in lmmsrc.xml to `1` re-enables this behavior. 

> Any way we can add a settings entry to expose the hidden flag?

Obviously we could have made a settings entry if desired, but the option is hidden on purpose. This behavior will hopefully be entirely removed in a future version, so aside from avoiding additional clutter in the settings the use of a hidden flag prevents new users from getting used to an obsolete workflow.

As was also mentioned on Discord, the "drums in audio" workflow (in LMMS's case, using sample clips in sanple tracks) is a strictly superior solution if you disregard some of LMMS's current limitations. Right now I would consider sample caching to be the primary blocker, otherwise we get redundant memory use for every duplicated clip; feature-wise we would benefit from per-clip volume adjustment, fade in/outs (PR exists), and pitch shifting. Those limitations aside, sample clips have several important advantages already:
- Much more detailed visualization of what's playing (BB steps don't even represent sample length)
- Ability to adjust timing more finely than 1/16ths, either to offset a whole pattern (preshifted samples) or individual clips. (Note that clips can still be shifted in 1/16th increments or locked into a 1/16th note grid with the song editor's snapping functionality)
- Ability to trim samples in-context (e.g. easily see overlapping samples) and individually per-clip

**Comment by Spekular** [comment]
See also #5988

**Comment by Gabrielxd195** [comment]
> See also #5988

I know this thread is closed, but I think it would be better to add this option in the LMMS settings menu but keep it disabled by default. I understand that it can be activated through lmmsrc.xml but it would be more intuitive to have this option in the settings menu.

In any case, many users were already used to using this function because it was there for a long time and when we discovered it we got a lot of use out of it. Maybe they removed it so that users don't get used to an obsolete workflow, but they removed it prematurely, without giving us a better one than this. 

That's why many of my friends complained when they removed this feature because we were already used to using it, due to 
that LMMS does not have a built-in Drum Sampler. If we had a drum sampler like sitala and better handling of audio clips, perhaps this function would no longer be so necessary, and even with those problems solved this function would still be useful because it is very practical. In my case it is vital because I produce urban and electronic music where many samples are needed.

Please, if you can, add this option to the settings menu. Although it is disabled by default. Greetings

(Google Translate)

**Comment by OwusuOnyankoponwoho** [comment]
where can i find that lmmsrc.xml ?
