### ISSUE TITLE
Add a plugin that complies any file into a DLL. file (as long as its in C++)

### ISSUE THREAD

**Issue by YesImAsh** [LMMS/lmms#7402]
### Enhancement Summary

Since LMMS is a DAW for developers, it would be really cool to make ANY type of vst just by complying a folder into a DLL. file
(as long as the code is in C++)

It can also preview and debug the file without needing to comply it into DLL.

### Implementation Details / Mockup

Step 1: create a folder
Step 2: create assets and scripts using just notes and stuff
step 3: test it in the new plugin
step 4: if it works just the way you like it, you make comply it into a DLL file. If not, you make continue to develop the plugin, as there is a preview feature

it would really be cool

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by sakertooth** [comment]
Either I'm confused by this enhancement, or that just simply isn't how it works.

**Comment by YesImAsh** [comment]
its essentially a DLL. complier

**Comment by zynskeywolf** [comment]
> Since LMMS is a DAW for developers

Other than the fact that it's not, I think this proposal would do the opposite, as in trying to make an IDE for musicians. Even if this could somehow work, logic breaks: if someone wants to write a VST plugin, they will use the proper toolsets already available, and if someone wants to use lmms, they will not want to make VST plugins, especially since VST2 are officially forbidden to make and VST3 is not supported in lmms yet. I just think having a plugin developing tool(?) built into a program that doesn't even handle plugins properly is a pretty useless idea.
`<end of rant>`

**Comment by messmerd** [comment]
A DLL is just Windows' implementation of the concept of shared libraries, and itself has nothing to do with VSTs. A VST2 plugin is simply shipped as a DLL on Windows.

LMMS can use VST plugins (specifically VST2) but has nothing to do with their creation, and I doesn't think it's a good idea for a DAW to have that feature.

If you want, you can use Steinberg's VST SDK and C/C++ to build your own VST2 plugin - or at least you once could, but Steinberg doesn't support VST2 anymore now that VST3 is out.

I would recommend trying Lv2 instead if you want to create plugins usable in LMMS. There are frameworks like JUCE and DISTRHO that would help you with that.

**Comment by musikBear** [comment]
> its essentially a DLL. complier

That is just not possible. You need a complete .NET environment. Also it is highly unwanted that LMMS should compile ao read code in any and all circumstances!
LMMS should never be made to do that!
It would be a HUGE possible exploration possibility!
HUGE **NO**!!

**Comment by YesImAsh** [comment]
...the hell did i do?
