### ISSUE TITLE
Missing Meters in FX GUI

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#75]
If I use the plugin SC4 in Ardour, beside some control sliders I have a few meters that show me for example: the momental input signal level and gain reduction. This is very helpful.
However in LMMS this feedback information provided by plugins is ignored and not exposed to the user. Can we fix that?

**Comment by tresf** [comment]
> in LMMS this feedback information provided by plugins is ignored and not exposed to the user. Can we fix that?

Is the intent to only handle LADSPA plugins, or to make this feature scale to LMMS Native and VST effect plugins as well?

For example, LMMS ships with [15 native plugins](https://cloud.githubusercontent.com/assets/6345473/24025526/53091dd4-0a91-11e7-995a-f5ac374d0c37.png) yet [only the Equilizer plugin offers any visual feedback](https://cloud.githubusercontent.com/assets/6345473/24025633/f30a819c-0a91-11e7-8fd8-d30a5ca359d7.png).

Furthermore, can we have a mock-up of the placement of this so that it will fit into the current GUI?  This should help put definition around it.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
