### ISSUE TITLE
Mixer looks cramped and has decreased usability

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#7505]
### LMMS Version(s)

4803bbb73ad3e7b9e36c39cabdec3aff6f1dafe4

### Bug Summary

With #7502 merged the mixer looks cramped and the usability has decreased because usable whitespace has been removed.

Here's how the mixer looks now:

![7502-CrampedMixer](https://github.com/user-attachments/assets/eaa874fe-3ab3-42a3-ad4a-7561ae4d700e)

And here's how it looked before:

![7502-MixerBefore](https://github.com/user-attachments/assets/31cffae3-3cc6-43fe-859b-63c28484b160)

Before the changes the mixer had valuable white space which separated different elements.

### Expected Behaviour

The mixer should be usable while looking good and professional.

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by sakertooth** [comment]
Please refer to #7502. Lots of people complained that there was too much whitespace ever since #6591 was merged. This is most likely because you have to stretch the mixer window further to fit the same number of channels.

**Comment by michaelgregorius** [comment]
## Proposal for an alternative fix
My proposal would be to fix this by doing something about the tons of whitespace that can be found above the channel number then. That space is only needed in the special case of doing something with the sends. So it's wasted space most of the time.

## Principles of UI/UX design
The solution should not be to simply remove all margins and make the mixer look bad. Sorry for being so blunt, but UI/UX designers would likely either laugh or faint when presented with the first screenshot. And I am not even saying that the previous solution looked that good.

Here's an article on the "Gestalt" principles which also apply to GUI design: https://uxplanet.org/gestalt-principles-in-ux-design-2e0f423bfcb5. You will find that the "Law of Proximity" is about whitespace.

And here's another article about the importance of whitespace in GUI designs: https://uxplanet.org/the-power-of-whitespace-a1a95e45f82b

I do not get the need to make everything as small and cramped as possible only to be able to fix hundreds of elements at once on the screen. Certain information must be presented and this needs space to be usable. If you try to cramp as much information as possible in the smallest space this will drastically reduce usability. From what I have seen in every DAW there's a limit of the number of tracks or channels that can be seen at once. But for some reasons LMMS wants to go to the extreme.

There are tons of problems already with LMMS' GUI, e.g. fixed layouts, inflexible widgets, etc. In my opinion most of them need to be fixed by providing some elements more space not less. If we always listen to very conservative users then LMMS won't have a chance to every really improve.

**Comment by sakertooth** [comment]
> My proposal would be to fix this by doing something about the tons of whitespace that can be found above the channel number then. That space is only needed in the special case of doing something with the sends. So it's wasted space most of the time.

I don't believe it was the vertical space most users were complaining about, but the horizontal space.

Either way, I'm going to try and make another compromise to this. If you are referring to the vertical space, I can see why that may be an issue. I'll restore the spacing there, and I have another PR that makes the send button and receive arrow use the same space, so that should work well vertically. I'm also going to try and provide whitespace horizontally for the peak indicator.

It's all very subjective (what I see as a non/low-profile issue is a real issue for many, which I can't really control), so I will wait for 2 approvals (maybe 3) before the compromise is merged.

**Comment by michaelgregorius** [comment]
I think it would be good to compare the mixer to other DAWs. Do they have different rendering modes for the strips? What information do they provide? How many strips can you fit on the screen with them? I assume that they are more generous with the space.

**Comment by sakertooth** [comment]
> I think it would be good to compare the mixer to other DAWs. Do they have different rendering modes for the strips? What information do they provide? How many strips can you fit on the screen with them? I assume that they are more generous with the space.

Since most professional DAWs have a lot more controls, yes, they are more generous with the space.

Maybe there was a misunderstanding on my end. Are we concerned with the vertical or horizontal space of the mixer channel? I never had issue with how the horizontal space changed in 6591, its just that I thought when users said the mixer channels got massive, I figured they were referring to the horizontal space. But maybe they were referring to the vertical space instead?

**Comment by michaelgregorius** [comment]
The changes in #7507 at least provide a compromise. Here's how the mixer looks with them:

![7502-CompromiseWith3](https://github.com/user-attachments/assets/dcce6c99-d748-418e-8b7c-38bf1ec86fc6)

**Comment by sakertooth** [comment]
The only potential problem I can see is with the peak indicators. They look right justified for some reason, and should probably be shrunk just a tad bit horizontally and centered. I'm trying to fix this now.
