### ISSUE TITLE
FX-Mixer channel routing 

### ISSUE THREAD

**Issue by Rogemcy** [LMMS/lmms#7563]
### Enhancement Summary

Some times need routing survial channels to a single channel, not ONLY FX but the global volume. For examples,  decreasing the volume of all EGuitar channels at the same time or just mute them by one click.

### Implementation Details / Mockup

Turning the "FX-Mixer" to "Mixer", each channel's volume range from -100 to 100,  -100 means mute itself and all routing child channels, 0 means default volume , 100 means highest volume.  As compensation, add a percentage knobs for every FX on the right side of each FX panel.

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Monospace-V** [comment]
This is the current state of the mixer.
![image](https://github.com/user-attachments/assets/eeb96575-7ad4-4b39-9a03-625f188ee0fe)
As you can see, FX-Mixer has already been renamed.

I recommend you change your settings to view in dbFS instead of percentage.
Presently, 0% means no volume, while negative 100% has no meaning whatsoever.
A person more familiar with LMMS might assume, sensibly, that -100 implies a waveform inversion (the audio will sound the exact same independently). This will, however, likely come as a separate button later.
In the default view settings, percentage view is used. If you want negative numbers in your volume knob, percentage is not the way to go, since it is fractional. dbFS as a logarithmic value will be better suited to your needs.
Here is the button:
![image](https://github.com/user-attachments/assets/730cd49f-ff20-4849-9eff-8765e93b38b9)
![image](https://github.com/user-attachments/assets/f921a140-d18d-4964-a466-e638c2fffc50)


Do you want a percentage knob for all FX collectively, or one for every individual FX?
![image](https://github.com/user-attachments/assets/df10fb79-f2d5-4601-a255-5cd84209dd4d)
The latter already exists. I'm not sure if the former is a standard, since typically audio is sent in parallel as dry and wet mixes, but could be useful? You can already control the percentage sent to the master.
![image](https://github.com/user-attachments/assets/19852c06-7db7-4543-82ea-b221fb0e91b8)

**Comment by Rossmaxx** [comment]
Closing as done. Everything you request is on the nightly, and routing, it's been there for a while, just not as obvious.
