### ISSUE TITLE
Multiple minor typos

### ISSUE THREAD

**Issue by Wuzzy2** [LMMS/lmms#7600]
I found small typos in the application:

> The JACK server seems to be **shuted** down.

(in `src/core/midi/MidiJack.cpp`)

> A bundle folder with that name already **eists** on the selected path. Can't overwrite a project bundle. Please select a different name.

(in `src/core/DataFile.cpp`)

> Move recording **curser** using \<Left/Right\> arrows

(in `src/gui/editors/StepRecorderWidget.cpp`)

---

> **Reactvate** them to start the process again, with the last saved state applied to it.

(apparently in Carla, so can probably be ignored)

**Comment by Rossmaxx** [comment]
If you don't mind, can you share more details like the screenshots of the locations where the typos are.

**Comment by michaelgregorius** [comment]
The "shuted" typo can be found here:
https://github.com/LMMS/lmms/blob/95a0518085930c68b38eae67bf7a2608613dd6f8/src/core/midi/MidiJack.cpp#L60

The "Reactvate" one is upstream in Carla and needs to be reported there if it has not been fixed in the meantime and LMMS only uses a version that's "too old":
https://github.com/falkTX/Carla/blob/66afe24a08790732cc17d81d4b846a1e0cfa0118/resources/ui/carla_settings.ui#L3056

**Comment by Wuzzy2** [comment]
Yeah, the Carla one can probably be ignored. I just added 2 more typos to the list.
