### ISSUE TITLE
One keypress - multiple notes while using QWERTY keyboard

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#851]
Everything is shown and explained in this video:
http://youtu.be/l7MrLOnzSVY

In case you can't watch:
Pressing a key on my laptop's keyboard generates not one note but a stream of them, spaced in random time intervals. The problem doesn't exist in any other part of the operating system (like text editors, or XEV) - so I'm sure my keyboard isn't broken. The problem also doesn't occur while using a MIDI keyboard. Looks like all LMMS's instrument plugins are affected (synths and Audio File Player).

Also this image sums it up pretty well:
![lmmsbug](https://cloud.githubusercontent.com/assets/491704/3278388/f86ca100-f3bb-11e3-9149-0fbd5954ed4b.png)

**Comment by rkfg** [comment]
Unfortunately, it's back. Tested with git snapshot and the repo version from Debian Stretch amd64 (1.1.3-1). Stock kernel 4.1.0-2-amd64, X.Org X Server 1.17.2. libqt4-dev 4:4.8.7+dfsg-3

**Comment by tresf** [comment]
No advice here, sorry, but if the conversation suggests a bug with Xorg, perhaps looking around other projects suffering the same problem is a good start.

**Comment by rkfg** [comment]
It's really weird. At work it glitches but at home it works just fine. The only difference I can think of is the keyboard itself, at work it's a USB one and at home it's a quite old PS/2 keyboard. xev behaves the same way producing lots of key presses/releases on key hold but LMMS doesn't interpret them as separate key presses. I tried sunvox at work and it was ok. Though it doesn't use any toolkit for GUI it seems. How can I investigate further? I'm using Awesome WM and the config and .xinitrc are the same (synced with Syncthing across my machines).

**Comment by tresf** [comment]
> at home it's a quite old PS/2 keyboard

:older_man: *"good 'ol ps2"*

> LMMS doesn't interpret them as separate key presses

Yeah, LMMS checks `QKeyEvent.isAutoRepeat()`, so it can depend on how the application is written.

> How can I investigate further? 

In my experience these bugs are very hard to track down as they can be caused by X, the DM or Qt.

Here are some upstream bugs that sound similar, but as described by others, the `QKeyEvent.isAutoRepeat()` check must be failing.

 * [qt/#41146](https://bugreports.qt.io/browse/QTBUG-41146) (Closed, Invalid)
 * [qt/#34542](https://bugreports.qt.io/browse/QTBUG-34542) (Incomplete)
 * [qt/#25795](https://bugreports.qt.io/browse/QTBUG-25795) (Qt5, Fixed)

I'm not sure what your system is, but if updating packages is an option, that may be a good start.

>  The only difference I can think of is the keyboard itself

If hardware is the cause, other applications should encounter the same problem.  Finding another application that allows the holding of a key may be a bit trickier to find, but may provide a baseline for comparison.

**Comment by rkfg** [comment]
Thanks for the info! However, all these bugs are related to Qt5 while LMMS uses Qt4. Both of my systems are fully updated, I'm using Awesome WM on both, no DM. Qt and Xorg versions are identical as well. I'll try to take my home kb to work and check it. The other difference is GPU, NVIDIA @ home and Intel @ work. It's hardly related but weird bugs could crawl from unrelated parts like conflicting IRQs and stuff.

**Comment by tresf** [comment]
> It's hardly related but weird bugs could crawl from unrelated parts like conflicting IRQs and stuff.

Sure, although IRQ conflicts are much more rare than they once were, since OSs and boards generally manage resource conflicts automatically.

Here's an older kernel bug which specifically says the bug won't occur on PS/2... 

https://bugzilla.kernel.org/show_bug.cgi?id=9448

**Comment by tresf** [comment]
Another item worth mentioning is that I often encounter key stuck issues with Remote Desktop, VirtualBox, SplashTop, TeamViewer on various systems.  If a modifier key is getting stuck (CTRL, ALT, etc), this may be the cause and the symptom may be misleading as some of the Qt bug reports state that the modifier key can trigger a premature release event.

**Comment by rkfg** [comment]
>Here's an older kernel bug which specifically says the bug won't occur on PS/2...

Looks familiar, I have such issues on the PS/2 kbd. I open terminal windows with Alt+Enter and sometimes, though quite rarely, it starts opening a huge number of them until I press Enter again. Never happened at work on the USB keyboard.

Well, tomorrow I'll try to trigger the bug with my home keyboard, we'll see what happens.

**Comment by Wallacoloo** [comment]
You can listen in on the raw commands coming from your keyboard (before
they are processed by xorg) through `cat /dev/input/xxx`. I think there's
actually a better command than cat for this, because that will just display
binary data. But with some effort, you should be able to determine if there
are duplicate keypresses at the hardware level through that interface.

If /dev/input looks fine, then you can check for problems at the xorg level
through `xdotool`. For example, configure it to log to a file everytime 'a'
is pressed, and everytime 'a' is released. This could reveal whether xorg
is perhaps sending multiple keydown events between each keyup event (which
would probably explain the symptoms).

**Comment by rkfg** [comment]
A quick check at work. PS/2 keyboard hasn't changed anything so I tried a colleague machine. He uses MATE DE but more important is that he has Xorg 16.4 and there's no issues with LMMS. I suspect this bug was fixed in 16.x and introduced back in 17.x. Though this doesn't explain why I don't have it at home on the same Xorg version (17.2). Really weird.

/dev/input/eventXX shows repeating data on key hold, on all machines. I couldn't find a way to make xdotool log external events so tried to simulate keypresses with it. Seems to work fine (on the affected machine), I send keydown and LMMS reacts with just one note played until it fades out.

**Comment by Umcaruje** [comment]
This issue still affects me. I'm on elementary OS Loki.
```
Xorg -version
X.Org X Server 1.18.4
```

**Comment by lukeoftheaura** [comment]
Still affects me on both my arch Linux installs.

**Comment by tresf** [comment]
For reference, the original bug report doesn't seem to be mentioned, but it's here: https://github.com/LMMS/lmms/issues/110

Upstream bug report here: 
https://bugreports.qt-project.org/browse/QTBUG-21500

**Comment by zonkmachine** [comment]
Workaround in [original bug report...](https://github.com/LMMS/lmms/issues/110#issuecomment-274394366)
