### ISSUE TITLE
AFP behavior of the 'disable loop' button

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#927]
Is that correct?
Wouldent it be more versatile if **that** button _toggles_ loop on/off? That would give the repeat-fwd and the new (great) repeat-bckw, much more sense?
Also it sounds a litte as repeat-bckw dos not contain the entire sound.. some 'garbling' at the point of repeat (not sure -what say you all??)
Il try to investigate more with audasity record..

**Comment by SecondFlight** [comment]
This issue is almost 5 years old. I vote to close.

1. It is very common to have a multi-button selection like this where only one option is active at a time. A great example of this is the TripleOscillator oscillator selector.
2. The odd sounds when looping a sample with loop points not set to 0 and 1, which I can reproduce, is another issue altogether, which should be reported separately. This seems to be simply due to a lack of declicking in the DSP.
3. *It's 5 years old.* Nobody else has commented expressing interest in this specific UX change.

I'll leave this open for a bit in case anyone has objections.
